### ISSUE TITLE
Cannot infer, RuntimeError: mat1 and mat2 must have the same dtype

### ISSUE THREAD

**Issue by litagin02** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1000]
I'm using the latest main branch of RVC (not 7z ver).
When trying to infer in infer-web.py, some error occurred after clicking "Convert".
Below are the full log.
```
(venv) C:\AI\Retrieval-based-Voice-Conversion-WebUI>python infer-web.py
Found GPU NVIDIA GeForce RTX 4070
Use Language: ja_JP
Running on local URL:  http://0.0.0.0:7865
loading weights/XX_e200.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
2023-08-14 09:03:59 | INFO | fairseq.tasks.hubert_pretraining | current directory is C:\AI\Retrieval-based-Voice-Conversion-WebUI
2023-08-14 09:03:59 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-08-14 09:03:59 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
Traceback (most recent call last):
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 211, in vc_single
    audio_opt = vc.pipeline(
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\vc_infer_pipeline.py", line 402, in pipeline
    self.vc(
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\vc_infer_pipeline.py", line 255, in vc
    (net_g.infer(feats, p_len, pitch, pitchf, sid)[0][0, 0])
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\lib\infer_pack\models.py", line 762, in infer
    o = self.dec(z * x_mask, nsff0, g=g)
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\lib\infer_pack\models.py", line 497, in forward
    har_source, noi_source, uv = self.m_source(f0, self.upp)
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\lib\infer_pack\models.py", line 420, in forward
    sine_merge = self.l_tanh(self.l_linear(sine_wavs.to(x)))
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype

Traceback (most recent call last):
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'
```

**Comment by RVC-Boss** [comment]
> I'm using the latest main branch of RVC (not 7z ver). When trying to infer in infer-web.py, some error occurred after clicking "Convert". Below are the full log.
> 
> ```
> (venv) C:\AI\Retrieval-based-Voice-Conversion-WebUI>python infer-web.py
> Found GPU NVIDIA GeForce RTX 4070
> Use Language: ja_JP
> Running on local URL:  http://0.0.0.0:7865
> loading weights/XX_e200.pth
> gin_channels: 256 self.spk_embed_dim: 109
> <All keys matched successfully>
> 2023-08-14 09:03:59 | INFO | fairseq.tasks.hubert_pretraining | current directory is C:\AI\Retrieval-based-Voice-Conversion-WebUI
> 2023-08-14 09:03:59 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
> 2023-08-14 09:03:59 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
> Traceback (most recent call last):
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 211, in vc_single
>     audio_opt = vc.pipeline(
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\vc_infer_pipeline.py", line 402, in pipeline
>     self.vc(
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\vc_infer_pipeline.py", line 255, in vc
>     (net_g.infer(feats, p_len, pitch, pitchf, sid)[0][0, 0])
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\lib\infer_pack\models.py", line 762, in infer
>     o = self.dec(z * x_mask, nsff0, g=g)
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\lib\infer_pack\models.py", line 497, in forward
>     har_source, noi_source, uv = self.m_source(f0, self.upp)
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\lib\infer_pack\models.py", line 420, in forward
>     sine_merge = self.l_tanh(self.l_linear(sine_wavs.to(x)))
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
>     return F.linear(input, self.weight, self.bias)
> RuntimeError: mat1 and mat2 must have the same dtype
> 
> Traceback (most recent call last):
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
>     output = await app.get_blocks().process_api(
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\blocks.py", line 1349, in process_api
>     data = self.postprocess_data(fn_index, result["prediction"], state)
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
>     prediction_value = block.postprocess(prediction_value)
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\components.py", line 2586, in postprocess
>     file_path = self.audio_to_temp_file(
>   File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
>     temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
> AttributeError: 'NoneType' object has no attribute 'tobytes'
> ```

@litagin02   

File "C:\AI\Retrieval-based-Voice-Conversion-WebUI\lib\infer_pack\models.py", line 420, in forward
    sine_merge = self.l_tanh(self.l_linear(sine_wavs.to(x)))

try changing this line to 

sine_merge = self.l_tanh(self.l_linear(sine_wavs.to(self.l_linear.weight.dtype)))

**Comment by litagin02** [comment]
Thanks, fixed!
