### ISSUE TITLE
AMD updated0814v2版本报错，不太了解这个，请问这是什么问题。麻烦有时间的时候告知一下。谢谢。

### ISSUE THREAD

**Issue by qzrsa** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1008]
G:\RVC0813AMD_Intel\gui_v1.py:461: UserWarning: The operator 'aten::linspace.out' is not currently supported on the DML backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\dml\dml_cpu_fallback.cpp:17.)
  self.fade_in_window: torch.Tensor = torch.linspace(
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "G:\RVC0813AMD_Intel\gui_v1.py", line 476, in soundinput
    with sd.Stream(
  File "G:\RVC0813AMD_Intel\runtime\lib\site-packages\sounddevice.py", line 1800, in __init__
    _StreamBase.__init__(self, kind='duplex', wrap_callback='array',
  File "G:\RVC0813AMD_Intel\runtime\lib\site-packages\sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "G:\RVC0813AMD_Intel\runtime\lib\site-packages\sounddevice.py", line 2745, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: Error opening Stream: Unanticipated host error [PaErrorCode -9999]: '无效的参数被传递给一个 系统功能。' [MME error 11]

**Comment by qzrsa** [comment]
> 输出设备和输入设备的协议不一致

多谢了。

**Comment by jieran233** [comment]
- 关掉防病毒软件
  https://stackoverflow.com/a/57086198

- 设置 > 隐私 > 麦克风，禁用再启用麦克风访问权限
  https://stackoverflow.com/a/51098227

关闭防病毒软件为我解决了问题
