### ISSUE TITLE
Not so easy start with RVC

### ISSUE THREAD

**Issue by santosphd** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1010]
I did all the procedure of the Readme and after the installation when I select the "Interference voice" I always got an error:

```
Traceback (most recent call last):
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Pedro\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Pedro\Documents\IA\Retrieval-based-Voice-Conversion-WebUI-main\infer-web.py", line 473, in get_vc
    tgt_sr = cpt["config"][-1]
KeyError: 'config'
```

I'm using Windows 10. Has anyone experienced this problem?

**Comment by timmosaurusrex** [comment]
Yes, i have got the same error.

**Comment by josh0615** [comment]
same here

**Comment by ndxzzy** [comment]
same here :(

**Comment by Mechhead** [comment]
Same Problem. I'm also having a similar problem with the forks, Applio etc.

**Comment by Tristan-2i** [comment]
Did someone find a solution ?
