### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by Thoro1** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1020]
Traceback (most recent call last):
  File "infer-web.py", line 194, in vc_single
    load_hubert()
  File "infer-web.py", line 135, in load_hubert
    models, _, _ = fairseq.checkpoint_utils.load_model_ensemble_and_task(
  File "/home/user/Desktop/Retrieval-based-Voice-Conversion-WebUI-main/myenv/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 423, in load_model_ensemble_and_task
    raise IOError("Model file not found: {}".format(filename))
OSError: Model file not found: hubert_base.pt

Traceback (most recent call last):
  File "/home/user/Desktop/Retrieval-based-Voice-Conversion-WebUI-main/myenv/lib/python3.8/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/home/user/Desktop/Retrieval-based-Voice-Conversion-WebUI-main/myenv/lib/python3.8/site-packages/gradio/blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/user/Desktop/Retrieval-based-Voice-Conversion-WebUI-main/myenv/lib/python3.8/site-packages/gradio/blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/user/Desktop/Retrieval-based-Voice-Conversion-WebUI-main/myenv/lib/python3.8/site-packages/gradio/components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "/home/user/Desktop/Retrieval-based-Voice-Conversion-WebUI-main/myenv/lib/python3.8/site-packages/gradio/processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "/home/user/Desktop/Retrieval-based-Voice-Conversion-WebUI-main/myenv/lib/python3.8/site-packages/gradio/processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

i have no idea whats wrong and how to fix this, the site just says error and thats it, console shows the exception shown above but im unable to figure out what is the issue. can someone help me fix this?

**Comment by truszko1** [comment]
"OSError: Model file not found: hubert_base.pt"

this is your ticket, most likely. [Check the hugginf](https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main) Download the file from here and add it to your project root dir.

**Comment by RVC-Boss** [comment]
↑ is right.
