### ISSUE TITLE
No such file or directory: 'ffmpeg'

### ISSUE THREAD

**Issue by timegoby** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#104]
Traceback (most recent call last):
  File "/home/iot1/zhongzhilai/Retrieval-based-Voice-Conversion-WebUI/trainset_preprocess_pipeline_print.py", line 73, in pipeline
    audio = load_audio(path, self.sr)
  File "/home/iot1/zhongzhilai/Retrieval-based-Voice-Conversion-WebUI/my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [Errno 2] No such file or directory: 'ffmpeg'

/home/iot1/zhongzhilai/so-vits-svc/dataset_raw/speaker0/8_86.wav->Traceback (most recent call last):
  File "/home/iot1/zhongzhilai/Retrieval-based-Voice-Conversion-WebUI/my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "/home/iot1/anaconda3/envs/retrieval/lib/python3.9/site-packages/ffmpeg/_run.py", line 313, in run
    process = run_async(
  File "/home/iot1/anaconda3/envs/retrieval/lib/python3.9/site-packages/ffmpeg/_run.py", line 284, in run_async
    return subprocess.Popen(
  File "/home/iot1/anaconda3/envs/retrieval/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/iot1/anaconda3/envs/retrieval/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

Readme 里的ffmpeg相关的安装没看懂呢？

**Comment by RVC-Boss** [comment]
apt install ffmpeg
看看能否装上。

**Comment by timegoby** [comment]
ffmpeg已经装过了，不知道为什么项目根目录下创建了一个ffmpeg文件夹，把它删掉就行了
Thx
