### ISSUE TITLE
error when converting

### ISSUE THREAD

**Issue by Daxerus** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1042]
Hi! I just trained a test and got this error, am i missing something? thanks! i hope i pasted the enough error code
```
AttributeError: 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "E:\RVC0813Nvidia\RVC0813Nvidia\infer-web.py", line 211, in vc_single
    audio_opt = vc.pipeline(
  File "E:\RVC0813Nvidia\RVC0813Nvidia\vc_infer_pipeline.py", line 366, in pipeline
    self.vc(
  File "E:\RVC0813Nvidia\RVC0813Nvidia\vc_infer_pipeline.py", line 218, in vc
    score, ix = index.search(npy, k=8)
  File "E:\RVC0813Nvidia\RVC0813Nvidia\runtime\lib\site-packages\faiss\__init__.py", line 341, in replacement_search
    assert d == self.d
AssertionError

Traceback (most recent call last):
  File "E:\RVC0813Nvidia\RVC0813Nvidia\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "E:\RVC0813Nvidia\RVC0813Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\RVC0813Nvidia\RVC0813Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "E:\RVC0813Nvidia\RVC0813Nvidia\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "E:\RVC0813Nvidia\RVC0813Nvidia\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "E:\RVC0813Nvidia\RVC0813Nvidia\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```

**Comment by RVC-Boss** [comment]
v1 index with v2 pth or v1 pth with v2 index is not allowed。
