### ISSUE TITLE
TextEncoder768 to 256

### ISSUE THREAD

**Issue by artificialnouveau** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1044]
I'm currently getting this error:

Traceback (most recent call last):
  File "C:\Users\Anaconda3\envs\rvc-eval\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Anaconda3\envs\rvc-eval\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\rvc-eval\rvc_eval\cli.py", line 222, in <module>
    main(args)
  File "C:\Users\rvc-eval\rvc_eval\cli.py", line 120, in main
    net_g, sampling_ratio = load_net_g(args.model, is_half, device, args.rvcversion)
  File "C:\Users\rvc-eval\rvc_eval\model.py", line 58, in load_net_g
    net_g.load_state_dict(cpt["weight"], strict=False)
  File "C:\Users\Anaconda3\envs\rvc-eval\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid_nono:
        size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 768]) from checkpoint, the shape in current model is torch.Size([192, 256]).

The hubert_base.pt has a hidden channels of 768, how does it adapt to the RVC v2 models which has hidden channels set to 256?

**Comment by RVC-Boss** [comment]
by linear or conv1d

**Comment by artificialnouveau** [comment]
I'm still encountered an error when loading weights when I do net_g.load_state_dict(cpt["weight"], strict=False). This only occurs when I load the rvc2 models. Can you propose what to do?
