### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by komando0311** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1049]
Traceback (most recent call last):
  File "C:\Users\Ali\OneDrive\Documents\hi\RVC0813AMD_Intel\infer-web.py", line 211, in vc_single
    audio_opt = vc.pipeline(
  File "C:\Users\Ali\OneDrive\Documents\hi\RVC0813AMD_Intel\vc_infer_pipeline.py", line 359, in pipeline
    pitchf = torch.tensor(pitchf, device=self.device).unsqueeze(0).float()
RuntimeError: The GPU device does not support Double (Float64) operations!

Traceback (most recent call last):
  File "C:\Users\Ali\OneDrive\Documents\hi\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Ali\OneDrive\Documents\hi\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Ali\OneDrive\Documents\hi\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Ali\OneDrive\Documents\hi\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\Ali\OneDrive\Documents\hi\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\Ali\OneDrive\Documents\hi\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'                                            

I read some of the last comments and I still couldn`t figure the problem

**Comment by popopapi** [comment]
I'm having the same error and i tried to install it in different ways and i still get this same problem

**Comment by gigamesh** [comment]
I've tried installing it on 3 different computers (Mac M1, Mac Intel, & PC with recent AMD GPU) and get the same error no matter how I install it.

**Comment by DuckersMcQuack** [comment]
Same issue here. Downloaded the larger preassembled nvidia one.
