### ISSUE TITLE
在使用onnx_dereverb模型时出现报错

### ISSUE THREAD

**Issue by Hello-Moeka** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1051]
Traceback (most recent call last):
  File "C:\Users\Moeka-Desktop\Downloads\Compressed\RVC0813Nvidia\infer-web.py", line 342, in uvr
    pre_fun = MDXNetDereverb(15)
  File "C:\Users\Moeka-Desktop\Downloads\Compressed\RVC0813Nvidia\MDXNet.py", line 253, in __init__
    self.pred = Predictor(self)
  File "C:\Users\Moeka-Desktop\Downloads\Compressed\RVC0813Nvidia\MDXNet.py", line 107, in __init__
    import onnxruntime as ort
ModuleNotFoundError: No module named 'onnxruntime'

在使用onnx_dereverb模型时出现报错

**Comment by Fvduan** [comment]
我也遇到了同样的问题

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/config.py
download it and replace config.py, reload webui, and it will be fixed.
I will update it to the nvidia package.

**Comment by Fvduan** [comment]
> https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/config.py 下载并替换config.py，重新加载webui，即可修复。 我会将其更新到 nvidia 包。

I did so, but still the same result.


----------------------------------------------------------------
Traceback (most recent call last):
  File "C:\RVC0813Nvidia\RVC0813Nvidia\infer-web.py", line 342, in uvr
    pre_fun = MDXNetDereverb(15)
  File "C:\RVC0813Nvidia\RVC0813Nvidia\MDXNet.py", line 253, in __init__
    self.pred = Predictor(self)
  File "C:\RVC0813Nvidia\RVC0813Nvidia\MDXNet.py", line 107, in __init__
    import onnxruntime as ort
ModuleNotFoundError: No module named 'onnxruntime'
