### ISSUE TITLE
TypeError: ForwardRef.__init__() got an unexpected keyword argument 'is_class'

### ISSUE THREAD

**Issue by shadowvvf** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1061]
C:\Users\void\Desktop\Retrieval-based-Voice-Conversion-WebUI-updated0618v2>python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Traceback (most recent call last):
  File "C:\Users\void\Desktop\Retrieval-based-Voice-Conversion-WebUI-updated0618v2\infer-web.py", line 22, in <module>
    import gradio as gr
  File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\components.py", line 35, in <module>
    from gradio.blocks import Block
  File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 33, in <module>
    from gradio import (
  File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\networking.py", line 18, in <module>
    from gradio.routes import App
  File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 43, in <module>
    from gradio.queue import Estimation, Event
  File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queue.py", line 17, in <module>
    class Estimation(BaseModel):
  File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\_internal\_model_construction.py", line 172, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\_internal\_model_construction.py", line 400, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\_internal\_fields.py", line 98, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\_internal\_typing_extra.py", line 212, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
  File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\_internal\_typing_extra.py", line 221, in eval_type_lenient
    value = _make_forward_ref(value, is_argument=False, is_class=True)
TypeError: ForwardRef.__init__() got an unexpected keyword argument 'is_class'

Windows 10, Python 3.10.0, visual studio and all requirements installed

**Comment by mozhong123** [comment]
> C:\Users\void\Desktop\Retrieval-based-Voice-Conversion-WebUI-updated0618v2>python.exe infer-web.py --pycmd runtime\python.exe --port 7897 Traceback (most recent call last): File "C:\Users\void\Desktop\Retrieval-based-Voice-Conversion-WebUI-updated0618v2\infer-web.py", line 22, in import gradio as gr File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio__init__.py", line 3, in import gradio.components as components File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\components.py", line 35, in from gradio.blocks import Block File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 33, in from gradio import ( File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\networking.py", line 18, in from gradio.routes import App File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 43, in from gradio.queue import Estimation, Event File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queue.py", line 17, in class Estimation(BaseModel): File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic_internal_model_construction.py", line 172, in **new** set_model_fields(cls, bases, config_wrapper, types_namespace) File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic_internal_model_construction.py", line 400, in set_model_fields fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map) File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic_internal_fields.py", line 98, in collect_model_fields type_hints = get_cls_type_hints_lenient(cls, types_namespace) File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic_internal_typing_extra.py", line 212, in get_cls_type_hints_lenient hints[name] = eval_type_lenient(value, globalns, localns) File "C:\Users\void\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic_internal_typing_extra.py", line 221, in eval_type_lenient value = _make_forward_ref(value, is_argument=False, is_class=True) TypeError: ForwardRef.**init**() got an unexpected keyword argument 'is_class'
> 
> Windows 10, Python 3.10.0, visual studio and all requirements installed

Simply delete 'is_class=True'.
