### ISSUE TITLE
Have an issue with training the model 

### ISSUE THREAD

**Issue by Ktivin** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1064]
[train.log](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/12389191/train.log)
Here is the train log and that thing from cmd:
INFO:mi-test:Train Epoch: 1 [0%]
INFO:mi-test:[0, 0.0001]
INFO:mi-test:loss_disc=3.949, loss_gen=2.514, loss_fm=15.857,loss_mel=30.657, loss_kl=9.000
DEBUG:matplotlib:matplotlib data path: D:\RVC-beta0717\runtime\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\hohik\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "D:\RVC-beta0717\train_nsf_sim_cache_sid_load_pretrain.py", line 228, in run
    train_and_evaluate(
  File "D:\RVC-beta0717\train_nsf_sim_cache_sid_load_pretrain.py", line 444, in train_and_evaluate
    scaler.step(optim_d)
  File "D:\RVC-beta0717\runtime\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 370, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "D:\RVC-beta0717\runtime\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 290, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "D:\RVC-beta0717\runtime\lib\site-packages\torch\optim\lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "D:\RVC-beta0717\runtime\lib\site-packages\torch\optim\optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "D:\RVC-beta0717\runtime\lib\site-packages\torch\optim\optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "D:\RVC-beta0717\runtime\lib\site-packages\torch\optim\adamw.py", line 171, in step
    adamw(
  File "D:\RVC-beta0717\runtime\lib\site-packages\torch\optim\adamw.py", line 321, in adamw
    func(
  File "D:\RVC-beta0717\runtime\lib\site-packages\torch\optim\adamw.py", line 566, in _multi_tensor_adamw
    denom = torch._foreach_add(exp_avg_sq_sqrt, eps)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 10.00 MiB (GPU 0; 4.00 GiB total capacity; 3.20 GiB already allocated; 0 bytes free; 3.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by zzadryzz** [comment]
you have run out of CUDA memory, most likely other applications use it such as screen recording, etc. Try to close all applications and set a high priority python.exe during training

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/wiki/FAQ-(Frequently-Asked-Questions)#q8cuda-errorcuda-out-of-memory
