### ISSUE TITLE
index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by Jagan-7-Mohan** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1070]
```
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 286, in vc_single
    audio_opt = vc.pipeline(
  File "/content/Retrieval-based-Voice-Conversion-WebUI/vc_infer_pipeline.py", line 564, in pipeline
    self.vc(
  File "/content/Retrieval-based-Voice-Conversion-WebUI/vc_infer_pipeline.py", line 417, in vc
    npy = np.sum(big_npy[ix] * np.expand_dims(weight, axis=2), axis=1)
IndexError: index -1 is out of bounds for axis 0 with size 0

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'
```

Getting this error while trying to clone voice using the trained dataset , but was able to process it via other dataset.
Stuck on this for a while , please let me know of resolution.

**Comment by RVC-Boss** [comment]
You may use the "trained_xxxx.index". You need use "added_xxxx.index".
