### ISSUE TITLE
Poetry metadat-generation-failed

### ISSUE THREAD

**Issue by vincbeaulieu** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1073]
I was trying to import this GitHub repo as a package in a project, but encountered a problem with poetry "pyproject.toml".

`poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package rvc-beta`

The full traceback is below and generated using the command:
`pip install git+https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI.git`

I've never used poetry before, thus this is new to me. Does anyone have any advice on how to resolve this conflict?

```       
Collecting git+https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI.git
  Cloning https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI.git to /private/var/folders/r9/p8m_f27j5w10mlfyx2kwcwc00000gn/T/pip-req-build-0ld5g6in
  Running command git clone --filter=blob:none --quiet https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI.git /private/var/folders/r9/p8m_f27j5w10mlfyx2kwcwc00000gn/T/pip-req-build-0ld5g6in
  Resolved https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI.git to commit 2789b8e8f405bf6d7563e6791fe95baba46c6600
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/Users/vincentbeaulieu/Desktop/AI/bark-with-voice-clone-main/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/vincentbeaulieu/Desktop/AI/bark-with-voice-clone-main/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/vincentbeaulieu/Desktop/AI/bark-with-voice-clone-main/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/r9/p8m_f27j5w10mlfyx2kwcwc00000gn/T/pip-build-env-hgez1xzz/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 42, in prepare_metadata_for_build_wheel
          builder = WheelBuilder(poetry)
        File "/private/var/folders/r9/p8m_f27j5w10mlfyx2kwcwc00000gn/T/pip-build-env-hgez1xzz/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 61, in __init__
          super().__init__(poetry, executable=executable)
        File "/private/var/folders/r9/p8m_f27j5w10mlfyx2kwcwc00000gn/T/pip-build-env-hgez1xzz/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/builder.py", line 85, in __init__
          self._module = Module(
        File "/private/var/folders/r9/p8m_f27j5w10mlfyx2kwcwc00000gn/T/pip-build-env-hgez1xzz/overlay/lib/python3.10/site-packages/poetry/core/masonry/utils/module.py", line 69, in __init__
          raise ModuleOrPackageNotFound(
      poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package rvc-beta
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by xiaoqiang-ok** [comment]
i get the same error in windows11 + nvidia-3080
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/5809864/22633d72-2a58-4f11-b9be-40bc7771fc13)
