### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by cvrk** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1091]
INFO:test2:====> Epoch: 200 [2023-08-26 18:18:25] | (0:00:20.367071)
INFO:test2:Training is done. The program is closed.
INFO:test2:saving final ckpt:Success.
_Traceback (most recent call last):
  File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\infer-web.py", line 1283, in train1key
    big_npy = np.concatenate(npys, 0)
  File "<__array_function__ internals>", line 180, in concatenate_
**ValueError: need at least one array to concatenate**

**Comment by RVC-Boss** [comment]
The real problem is before this traceback, you may need to copy more traceback information before it.

**Comment by midou307** [comment]
I met the same issue, did you solve this problem?

**Comment by midou307** [comment]
I found the solution
in the box "Enter the path of the training folder:"
put the path of the file not the name of files.mp3 or files.wav
only the path of the file Which contains files .mp3 or .wav

**Comment by liu944** [comment]
我解决了，当你运行训练模型的第一个项目时(Process data)，会显示缺失ffmpeg，重新执行获取包ffmpeg即可
