### ISSUE TITLE
how to use /run/infer_convert

### ISSUE THREAD

**Issue by anvanio** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1104]
this function return 500 error and this message {"detail":"Method Not Allowed"}
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/43257940/4bb81f36-e238-4961-bd67-da0953a95567)

**Comment by Kamikadashi** [comment]
I have a problem with /run/infer_convert as well.  /run/infer_refresh_batch seems to be working just fine. 


Traceback (most recent call last):
  File "C:\Users\ALVIBO\Downloads\Compressed\RVC1006Nvidia\infer\modules\vc\pipeline.py", line 347, in pipeline
    inp_f0.append([float(i) for i in line.split(",")])
  File "C:\Users\ALVIBO\Downloads\Compressed\RVC1006Nvidia\infer\modules\vc\pipeline.py", line 347, in <listcomp>
    inp_f0.append([float(i) for i in line.split(",")])
ValueError: could not convert string to float: 'PK\x05\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
2023-10-12 23:17:15 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "C:\Users\ALVIBO\Downloads\Compressed\RVC1006Nvidia\infer\modules\vc\modules.py", line 190, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "C:\Users\ALVIBO\Downloads\Compressed\RVC1006Nvidia\infer\modules\vc\pipeline.py", line 354, in pipeline
    pitch, pitchf = self.get_f0(
  File "C:\Users\ALVIBO\Downloads\Compressed\RVC1006Nvidia\infer\modules\vc\pipeline.py", line 166, in get_f0
    (inp_f0[:, 0].max() - inp_f0[:, 0].min()) * tf0 + 1
TypeError: list indices must be integers or slices, not tuple

Traceback (most recent call last):
  File "C:\Users\ALVIBO\Downloads\Compressed\RVC1006Nvidia\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\ALVIBO\Downloads\Compressed\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\ALVIBO\Downloads\Compressed\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\ALVIBO\Downloads\Compressed\RVC1006Nvidia\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\ALVIBO\Downloads\Compressed\RVC1006Nvidia\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\ALVIBO\Downloads\Compressed\RVC1006Nvidia\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by Kamikadashi** [comment]
I've figured it out. First of all, `http://localhost:7897/run/infer_change_voice` must be called once before making any calls to `/run/infer_convert`. The `/run/infer_convert` requires both the physical path to the file and `{"name":"zip.zip","data":"data:@file/octet-stream;base64,base64_audio_data"}`, where `base64_audio_data` is the data of the same file in the physical path. This request generates a result in `C:\Users\UserName\AppData\Local\Temp`. Other than that, I still haven't figured out how to get the result directly to memory or read the server response in any way (I always get an error).
