### ISSUE TITLE
Issue on 2b Feature Extraction

### ISSUE THREAD

**Issue by BRLTS** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1127]
When i try to feature extraction, it becomes like this, there's no f0ing or something:

loading rmvpe model
2023-08-30 03:41:30 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
f0fail-71-/content/Retrieval-based-Voice-Conversion-WebUI/logs/Raisu/1_16k_wavs/151_3.wav-Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer/modules/train/extract/extract_f0_print.py", line 126, in go
    featur_pit = self.compute_f0(inp_path, f0_method)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer/modules/train/extract/extract_f0_print.py", line 89, in compute_f0
    self.model_rmvpe = RMVPE(
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer/lib/rmvpe.py", line 585, in __init__
    ckpt = torch.load(model_path, map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'assets/rmvpe/rmvpe.pt'

**Comment by Tps-F** [comment]
@BRLTS 
Place rmvpe.pt in 'assets/rmvpe/

**Comment by BRLTS** [comment]
Anyway, I'm using on colab, so i upload it into assets/rmvpe/ folder? @Tps-F

**Comment by knasiotis** [comment]
same issue. where do i find rmvpe.pt?

**Comment by dan198j** [comment]
> same issue. where do i find rmvpe.pt?

Download the required files for the rmvpe vocal pitch extraction algorithm
If you want to use the latest RMVPE vocal pitch extraction algorithm, you need to download the pitch extraction model parameters and place them in assets/rmvpe.

https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/rmvpe.pt

I had the same issue. Found the solution right after reading this thread. Just move that file from huggingface into rmvpe folder. I tested and it worked.
