### ISSUE TITLE
Model Inference broke with `rmvpe`

### ISSUE THREAD

**Issue by NatoBoram** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1128]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/10495562/0937485c-15f2-4656-869b-7b24dbd832bd)

Currently, it works with these:

* [x] `pm`
* [x] `harvest`
* [x] `crepe`
* [ ] `rmvpe`

With `rmvpe`, I get these errors:

```py
Traceback (most recent call last):
  File "/opt/rvc/infer/modules/vc/modules.py", line 134, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "/opt/rvc/infer/modules/vc/pipeline.py", line 355, in pipeline
    pitch, pitchf = self.get_f0(
  File "/opt/rvc/infer/modules/vc/pipeline.py", line 148, in get_f0
    f0 = self.model_rmvpe.infer_from_audio(x, thred=0.03)
AttributeError: 'NoneType' object has no attribute 'infer_from_audio'

Traceback (most recent call last):
  File "/home/nato/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/nato/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/gradio/blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/nato/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/gradio/blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/nato/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/gradio/components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "/home/nato/.asdf/installs/python/3.10.13/lib/python3.10/site-packages/gradio/components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'
```

### System

```yaml
OS: Pop!_OS 22.04 LTS x86_64 (Yes, a real Linux, not WSL)
Host: MS-7D53 1.0 
Kernel: 6.4.6-76060406-generic 
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
GPU: AMD ATI Radeon RX 6700 XT
Memory: 32007MiB 
```

```sh
Python 3.10.13
```

**Comment by RVC-Boss** [comment]
fixed now.
You can update the repo and put 2 rmvpe model files into assets/rmvpe
