### ISSUE TITLE
ERROR WITH RVC GUI..

### ISSUE THREAD

**Issue by Biczu19** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1160]
Traceback (most recent call last):
  File "C:\RVC-GUI-pkg\rvcgui.py", line 150, in vc_single
    sf.write(output_path, audio_opt, tgt_sr, format='WAV')
  File "C:\RVC-GUI-pkg\runtime\lib\site-packages\soundfile.py", line 340, in write
    with SoundFile(file, 'w', samplerate, channels,
  File "C:\RVC-GUI-pkg\runtime\lib\site-packages\soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\RVC-GUI-pkg\runtime\lib\site-packages\soundfile.py", line 1213, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\piekniwaw_RVC_1.wav': System error.

**Comment by absencev** [comment]
Any solution?

**Comment by Biczu19** [comment]
> Any solution?

I didn't solve the problem. Nobody helped me

**Comment by absencev** [comment]
Same. Couldn't find any solution as well
