### ISSUE TITLE
pip install -r requirements.txt error

### ISSUE THREAD

**Issue by skaba04** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1183]
I am getting this error each time i want to install all the requirements in latest release
 Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Tomáš\AppData\Local\Programs\Python\Python311\Lib\site-pa
ckages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <mo
dule>
          main()
        File "C:\Users\Tomáš\AppData\Local\Programs\Python\Python311\Lib\site-pa
ckages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in mai
n
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Tomáš\AppData\Local\Programs\Python\Python311\Lib\site-pa
ckages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get
_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Tomáš\AppData\Local\Temp\pip-build-env-ce_cnxia\overlay\L
ib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_
wheel
          return self._get_build_requires(config_settings, requirements=['wheel'
])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^
        File "C:\Users\Tomáš\AppData\Local\Temp\pip-build-env-ce_cnxia\overlay\L
ib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\Tomáš\AppData\Local\Temp\pip-build-env-ce_cnxia\overlay\L
ib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_scri
pt)
        File "C:\Users\Tomáš\AppData\Local\Temp\pip-build-env-ce_cnxia\overlay\L
ib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 51, in <module>
        File "<string>", line 48, in _guard_py_ver
      RuntimeError: Cannot install on Python version 3.11.5; only versions >=3.7
,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit
h pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1

**Comment by skaba04** [comment]
nevermind i installed reqiurements but i cand process my training file in the training process of data

start preprocess
['trainset_preprocess_pipeline_print.py', 'C:\\1_Anis AI Voice_(Vocals).wav', '40000', '4', 'D:\\AI\\VoiceUI\\RVC0813Nvidia/logs/mi-test', 'False']
Fail. Traceback (most recent call last):
  File "D:\AI\VoiceUI\RVC0813Nvidia\trainset_preprocess_pipeline_print.py", line 111, in pipeline_mp_inp_dir
    for idx, name in enumerate(sorted(list(os.listdir(inp_root))))
NotADirectoryError: [WinError 267] Název adresáře je neplatný: 'C:\\1_Anis AI Voice_(Vocals).wav'

end preprocess
