### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by midou307** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1198]
INFO:test2:====> Epoch: 200 [2023-08-26 18:18:25] | (0:00:20.367071)
INFO:test2:Training is done. The program is closed.
INFO:test2:saving final ckpt:Success.
Traceback (most recent call last):
File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
output = await app.blocks.process_api(
File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
result = await self.call_function(fn_index, inputs, iterator, request)
File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
prediction = await anyio.to_thread.run_sync(
File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\anyio_backends_asyncio.py", line 937, in run_sync_in_worker_thread
return await future
File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\anyio_backends_asyncio.py", line 867, in run
result = context.run(func, *args)
File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
return next(iterator)
File "C:\Users\Catalin\Desktop\RVC0813AMD_Intel\RVC0813AMD_Intel\infer-web.py", line 1283, in train1key
big_npy = np.concatenate(npys, 0)
File "<array_function internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

**Comment by RVC-Boss** [comment]
check that if there is any npy file in 2a_f0 2b_f0nsf  3_feature768 folders

**Comment by kongminh113** [comment]
I encountered the same problem

**Comment by shihaoking** [comment]
> check that if there is any npy file in 2a_f0 2b_f0nsf 3_feature768 folders

Yes, I have the same issue, and I have those files in my logs folder
