### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pipeline'

### ISSUE THREAD

**Issue by ParzivalWolfram** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1267]
During any operation on CPU, I get the following error:
```
2023-09-17 03:00:48 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "/big/work/Retrieval-based-Voice-Conversion-WebUI/infer/modules/vc/modules.py", line 191, in vc_single
    audio_opt = self.pipeline.pipeline(
AttributeError: 'NoneType' object has no attribute 'pipeline'

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

```

**Comment by notnotniche** [comment]
I have the same problem , any fix ?

**Comment by yuygfgg** [comment]
same with you, on macos 14.1, when using model downloaded from internet (https://huggingface.co/WenqiOfficial/RVC-V2-Models/resolve/main/Elysia-V1.7z)

```
2023-10-04 11:14:35 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-10-04 11:14:35 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
2023-10-04 11:14:37 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "/Users/a1/Retrieval-based-Voice-Conversion-WebUI/infer/modules/vc/modules.py", line 191, in vc_single
    audio_opt = self.pipeline.pipeline(
AttributeError: 'NoneType' object has no attribute 'pipeline'

Traceback (most recent call last):
  File "/Users/a1/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.9/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/a1/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.9/site-packages/gradio/blocks.py", line 1392, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/a1/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.9/site-packages/gradio/blocks.py", line 1326, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/Users/a1/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.9/site-packages/gradio/components/audio.py", line 329, in postprocess
    file_path = self.audio_to_temp_file(
  File "/Users/a1/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.9/site-packages/gradio/components/base.py", line 327, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'
```
