### ISSUE TITLE
'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by alih552** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1271]
I am getting this error when trying to convert the audio file.

Traceback (most recent call last):
  File "E:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "E:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "E:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "E:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "E:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by daintyoracle** [comment]
Mine too.

Traceback (most recent call last):
  File "C:\001-RVC0813Nvidia\infer-web.py", line 195, in vc_single
    if_f0 = cpt.get("f0", 1)
AttributeError: 'NoneType' object has no attribute 'get'

and

Traceback (most recent call last):
  File "C:\001-RVC0813Nvidia\infer-web.py", line 276, in vc_multi
    paths = [os.path.join(dir_path, name) for name in os.listdir(dir_path)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\codes\\py39\\test-20230416b\\todo-songs'

and

Traceback (most recent call last):
  File "C:\001-RVC0813Nvidia\infer-web.py", line 276, in vc_multi
    paths = [os.path.join(dir_path, name) for name in os.listdir(dir_path)]
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\atl-instrumeno\\weightless-atl.mp3'

**Comment by VertofChest** [comment]
Anyone find a solution for this yet?

**Comment by alih552** [comment]
It appears that the problem is specific to this particular trained model. I've experimented with other models I've trained, and they function as expected. However, I'm still in the process of pinpointing the exact issue.

**Comment by SocksAndStuff** [comment]
> Anyone find a solution for this yet?

There is none and there will never be one. Tis the way of RVC

**Comment by wilsme** [comment]
ok.. I think i solved it...

two things: 
1) make sure the file you are trying to sound like is saved as a 16bit wav (not 24 bit or 32 bit float etc)
2)end your file name path with .wav  ( i only added it to the name of the path and not renamed in my directory)



this fixed my issues...

**Comment by XTRMsavage** [comment]
> ok.. I think i solved it...
> 
> two things:
> 
> 1. make sure the file you are trying to sound like is saved as a 16bit wav (not 24 bit or 32 bit float etc)
>    2)end your file name path with .wav  ( i only added it to the name of the path and not renamed in my directory)
> 
> this fixed my issues...

Thanks , This fixed my issue as well.

**Comment by GianlucaApollaro** [comment]
Can you explain this wav thing? I'm having this issue, but here's the wheird thing. It only happens if using a gpu, If I use my cpu, everything runs smoothly and I can give it whatever file format I like. Thanks
