### ISSUE TITLE
能训练，但是推理不了

### ISSUE THREAD

**Issue by SZ2528** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1284]
```
Traceback (most recent call last):
  File "C:\RVC\RVC0813AMD_Intel\infer-web.py", line 211, in vc_single
    audio_opt = vc.pipeline(
  File "C:\RVC\RVC0813AMD_Intel\vc_infer_pipeline.py", line 342, in pipeline
    sid = torch.tensor(sid, device=self.device).unsqueeze(0).long()
RuntimeError: device or resource busy: device or resource busy

Traceback (most recent call last):
  File "C:\RVC\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\RVC\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\RVC\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\RVC\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\RVC\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\RVC\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```
核显，Intel(R)HD Graphics 530
我是不是该换独显了

**Comment by SZ2528** [comment]
甚至还有这样的
```
Traceback (most recent call last):
  File "E:\RVC0813AMD_Intel\infer-web.py", line 211, in vc_single
    audio_opt = vc.pipeline(
  File "E:\RVC0813AMD_Intel\vc_infer_pipeline.py", line 359, in pipeline
    pitchf = torch.tensor(pitchf, device=self.device).unsqueeze(0).float()
RuntimeError: The GPU device does not support Double (Float64) operations!

Traceback (most recent call last):
  File "E:\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "E:\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "E:\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "E:\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "E:\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```
我: 😅

**Comment by ZZZ-zero** [comment]
是这样的，直接40系解君愁

**Comment by dvdcjw** [comment]
我3070ti也一样报

**Comment by jzzj-KKBK** [comment]
一样的，4060也是会报这个错误，似乎是音频文件处理的问题

**Comment by jzzj-KKBK** [comment]
我找到问题并修复了，报错点在  D:\AI\voice\RVC1006Nvidia\infer\modules\vc\pipeline.py  第221行，里面应该传入浮点数，但是传进来的却是一个字典，我不知道是哪传来传去产生的问题，但是可以看见里面的结构是重复的：
{'visible': True, 'value': {'visible': True, 'value': {'visible': True, 'value': {'visible': True, 'value': {'visible': True, 'value': {'visible': True, 'value': 0.33, '__type__': 'update'}, '__type__': 'update'}, '__type__': 'update'}, '__type__': 'update'}, '__type__': 'update'}, '__type__': 'update'}
解决方法比较粗糙，直接复制到那行前面（220行）就好了：
            try:
                while True:
                    if "value" in protect:
                        protect=protect["value"]
            except:
                print("程序正常运行")
