### ISSUE TITLE
ModuleNotFoundError: No module named 'pywintypes'

### ISSUE THREAD

**Issue by venometric** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1285]
C:\Users\verno\Desktop\RVC\RVC-TEST\Retrieval-based-Voice-Conversion-WebUI>python infer-web.py

C:\Users\verno\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\verno\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\verno\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
Traceback (most recent call last):
  File "C:\Users\verno\Desktop\RVC\RVC-TEST\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 16, in <module>
    import fairseq
  File "C:\Users\verno\AppData\Local\Programs\Python\Python39\lib\site-packages\fairseq\__init__.py", line 40, in <module>
    import fairseq.scoring  # noqa
  File "C:\Users\verno\AppData\Local\Programs\Python\Python39\lib\site-packages\fairseq\scoring\__init__.py", line 55, in <module>
    importlib.import_module("fairseq.scoring." + module)
  File "C:\Users\verno\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\verno\AppData\Local\Programs\Python\Python39\lib\site-packages\fairseq\scoring\bleu.py", line 14, in <module>
    from fairseq.scoring.tokenizer import EvaluationTokenizer
  File "C:\Users\verno\AppData\Local\Programs\Python\Python39\lib\site-packages\fairseq\scoring\tokenizer.py", line 8, in <module>
    import sacrebleu as sb
  File "C:\Users\verno\AppData\Local\Programs\Python\Python39\lib\site-packages\sacrebleu\__init__.py", line 21, in <module>
    from .utils import smart_open, SACREBLEU_DIR, download_test_set  # noqa: F401
  File "C:\Users\verno\AppData\Local\Programs\Python\Python39\lib\site-packages\sacrebleu\utils.py", line 9, in <module>
    import portalocker
  File "C:\Users\verno\AppData\Local\Programs\Python\Python39\lib\site-packages\portalocker\__init__.py", line 1, in <module>
    from . import __about__, constants, exceptions, portalocker, utils
  File "C:\Users\verno\AppData\Local\Programs\Python\Python39\lib\site-packages\portalocker\portalocker.py", line 15, in <module>
    import pywintypes
ModuleNotFoundError: No module named 'pywintypes'

**Comment by venometric** [comment]
solved.
pip uninstall pywin32
pip install pywin32
