### ISSUE TITLE
打开go-web.bat时失败

### ISSUE THREAD

**Issue by dxj916** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1287]
开发者你好，我在尝试打开go-web.bat时失败了，以下是错误信息

C:\Users\dxj91\Documents\GitHub\RVC0813Nvidia\RVC0813Nvidia>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Traceback (most recent call last):
  File "C:\Users\dxj91\Documents\GitHub\RVC0813Nvidia\RVC0813Nvidia\infer-web.py", line 26, in <module>
    import fairseq
  File "C:\Users\dxj91\Documents\GitHub\RVC0813Nvidia\RVC0813Nvidia\runtime\lib\site-packages\fairseq\__init__.py", line 21, in <module>
    from fairseq.logging import meters, metrics, progress_bar  # noqa
  File "C:\Users\dxj91\Documents\GitHub\RVC0813Nvidia\RVC0813Nvidia\runtime\lib\site-packages\fairseq\logging\progress_bar.py", line 407, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "C:\Users\dxj91\Documents\GitHub\RVC0813Nvidia\RVC0813Nvidia\runtime\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "C:\Users\dxj91\Documents\GitHub\RVC0813Nvidia\RVC0813Nvidia\runtime\lib\site-packages\torch\utils\tensorboard\writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "C:\Users\dxj91\AppData\Roaming\Python\Python39\site-packages\tensorboard\compat\proto\event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "C:\Users\dxj91\AppData\Roaming\Python\Python39\site-packages\tensorboard\compat\proto\summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "C:\Users\dxj91\AppData\Roaming\Python\Python39\site-packages\tensorboard\compat\proto\tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "C:\Users\dxj91\AppData\Roaming\Python\Python39\site-packages\tensorboard\compat\proto\resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "C:\Users\dxj91\AppData\Roaming\Python\Python39\site-packages\tensorboard\compat\proto\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\dxj91\Documents\GitHub\RVC0813Nvidia\RVC0813Nvidia\runtime\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

C:\Users\dxj91\Documents\GitHub\RVC0813Nvidia\RVC0813Nvidia>pause
请按任意键继续. . .

电脑中安装有python3.9.12，求告知如何解决，感谢！

**Comment by mrhan1993** [comment]
在 `C:\Users\dxj91\Documents\GitHub\RVC0813Nvidia\RVC0813Nvidia` 目录下执行 `runtime\python.exe -m pip install protobuf==3.20.0` 然后再试试

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this install issue has already been resolved.  Fairseq is not import now.
