### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [192, 513, 1], expected input[1, 1025, 368] to have 513 channels, but got 1025 channels instead

### ISSUE THREAD

**Issue by hunter2009pf** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#129]
显卡是1050Ti，就按照教学视频跑了一遍，上传了总长约12分钟的音频，wav格式，32kHz和44100Hz采样率都试了试，报下面这个错。

Traceback (most recent call last):
  File "E:\vits\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "E:\vits\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 188, in run
    train_and_evaluate(
  File "E:\vits\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 316, in train_and_evaluate
    ) = net_g(phone, phone_lengths, spec, spec_lengths, sid)
  File "E:\vits\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\vits\RVC-beta\runtime\lib\site-packages\torch\nn\parallel\distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "E:\vits\RVC-beta\runtime\lib\site-packages\torch\nn\parallel\distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "E:\vits\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\vits\RVC-beta\runtime\lib\site-packages\infer_pack\models.py", line 644, in forward
    z, m_q, logs_q, y_mask = self.enc_q(y, y_lengths, g=g)
  File "E:\vits\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\vits\RVC-beta\runtime\lib\site-packages\infer_pack\models.py", line 163, in forward
    x = self.pre(x) * x_mask
  File "E:\vits\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\vits\RVC-beta\runtime\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "E:\vits\RVC-beta\runtime\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [192, 513, 1], expected input[1, 1025, 368] to have 513 channels, but got 1025 channels instead

**Comment by RVC-Boss** [comment]
你的目标采样率是32k吗？

**Comment by RVC-Boss** [comment]
试试是不是只有32k才有这个错，而40k和48k都可以正常训练

**Comment by hunter2009pf** [comment]
> 你的目标采样率是32k吗？

是32k的，我特意用ffmpeg转换了。

**Comment by hunter2009pf** [comment]
> 试试是不是只有32k才有这个错，而40k和48k都可以正常训练

原来它不支持双声道的，我转成单声道，就可以正常训练了。
