### ISSUE TITLE
Process 0 terminated with the following error:

### ISSUE THREAD

**Issue by xxxxsssssx** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#130]
I use RTX3060ti.

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\RVC-beta\RVC-beta\runtime\lib\site-packages\torch\serialization.py", line 441, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "C:\RVC-beta\RVC-beta\runtime\lib\site-packages\torch\serialization.py", line 668, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
RuntimeError: [enforce fail at C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\caffe2\serialize\inline_container.cc:476] . PytorchStreamWriter failed writing file data/2229: file write failed

RuntimeError: [enforce fail at C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\caffe2\serialize\inline_container.cc:337] . unexpected pos 256653056 vs 256652948

I tried several times but all cases made like this error.(like 256653056 vs 256652948,this number is changed by in cace.)

**Comment by maskedhypocrite** [comment]
I am currently facing the same issue. Were you able to solve your problem?
