### ISSUE TITLE
RVC cannot save the result

### ISSUE THREAD

**Issue by volosogriz** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1319]
Hello! I encountered a problem that rvc cannot save the model. Do you know how to solve this problem? Nvidia . System Win32
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/145838585/908dcdde-b715-4bca-8870-c087610fe868)
`Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "C:\rvc\RVC0813Nvidia\train_nsf_sim_cache_sid_load_pretrain.py", line 228, in run
    train_and_evaluate(
  File "C:\rvc\RVC0813Nvidia\train_nsf_sim_cache_sid_load_pretrain.py", line 526, in train_and_evaluate
    utils.save_checkpoint(
  File "C:\rvc\RVC0813Nvidia\lib\train\utils.py", line 148, in save_checkpoint
    torch.save(
  File "C:\rvc\RVC0813Nvidia\runtime\lib\site-packages\torch\serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "C:\rvc\RVC0813Nvidia\runtime\lib\site-packages\torch\serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "C:\rvc\RVC0813Nvidia\runtime\lib\site-packages\torch\serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: File ./logs\артём3\G_5.pth cannot be opened.
`

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/145838585/c445f7ae-6d15-4abf-ad80-46dee7075874)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/145838585/0d18fcf1-5f66-402f-83a4-b026dc91828c)

**Comment by seedlord** [comment]
You have special characters in the folder name logs\артём3
do not use cyrillic characters and it will work i guess

**Comment by ZZZ-zero** [comment]
请尝试使用纯英文目录

**Comment by RVC-Boss** [comment]
↑ is right

special char not supported is in the path 
try to use pure English path
