### ISSUE TITLE
Problems loading voice file for training

### ISSUE THREAD

**Issue by OLAFO1205** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1320]
When processing the file this error appears:
start preprocess
['trainset_preprocess_pipeline_print.py', '/content/drive/MyDrive/dataset', '40000', '2', '/content/Retrieval-based-Voice-Conversion-WebUI/logs/VexModel', 'False']
/content/drive/MyDrive/dataset/OLAF2.zip->Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/my_utils.py", line 134, in load_audio
    ffmpeg.input(file, threads=0)
  File "/usr/local/lib/python3.10/dist-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/trainset_preprocess_pipeline_print.py", line 84, in pipeline
    audio = load_audio(path, self.sr, DoFormant, Quefrency, Timbre)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/my_utils.py", line 141, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

end preprocess

I need help I'm blocked!!! please.

**Comment by ZZZ-zero** [comment]
请尝试重新安装ffmpeg
