### ISSUE TITLE
Getting failed to load audio error

### ISSUE THREAD

**Issue by DhananjayPurohit** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1329]
I am storing the voice like this:-
```
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
353dd9|OK  |   472KiB/s|/content/Retrieval-based-Voice-Conversion-WebUI/dataset/alia.wav
```

On running the cell having commands:-
```
%cd /content/Retrieval-based-Voice-Conversion-WebUI
sudo python3 infer-web.py --colab --pycmd python3

```
the UI is starting up:-
![Screenshot (318)](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/44242169/93af47f4-1fcc-46a6-bf97-0218c25eed54)

I think it's taking the location fine as it can read up the wav file inside the `dataset` folder but still getting the error:-
```
start preprocess
['trainset_preprocess_pipeline_print.py', 'dataset', '40000', '2', '/content/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test', 'False']
dataset/alia.wav->Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "/usr/local/lib/python3.8/dist-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trainset_preprocess_pipeline_print.py", line 75, in pipeline
    audio = load_audio(path, self.sr)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

end preprocess
```

Any suggestions or help will be much appreciated.

Thanks in advance.

**Comment by ZZZ-zero** [comment]
ffmpeg可能是因为它不需要将wav转为wav文件而报错，也可能是由于ffmpeg版本报错，请先尝试重装ffmpeg。

**Comment by DhananjayPurohit** [comment]
I have tried downgrading the ffmpeg version. Can you specify the version I should try with?

**Comment by RVC-Boss** [comment]
try copying the absolute path of dataset?

**Comment by DhananjayPurohit** [comment]
@ZZZ-zero @RVC-Boss

**Comment by PasiKoodaa** [comment]
I had the same error, the fix was

pip install ffmpeg-python
instead of
pip install ffmpeg
