### ISSUE TITLE
gradio and faiss issue

### ISSUE THREAD

**Issue by mukatsuku** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1336]
i have a 7950x 64gb ram and a 4080 in case it matters

2023-09-26 23:41:33 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-09-26 23:41:33 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-09-26 23:41:33 | INFO | faiss.loader | Loading faiss.
2023-09-26 23:41:33 | INFO | faiss.loader | Successfully loaded faiss.
2023-09-26 23:41:35 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 4080
2023-09-26 23:41:35 | INFO | __main__ | Use Language: en_US
Running on local URL:  http://0.0.0.0:7865
Traceback (most recent call last):
  File "D:\anaconda3\envs\rvc\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\anaconda3\envs\rvc\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\anaconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "D:\anaconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\anaconda3\envs\rvc\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\anaconda3\envs\rvc\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\anaconda3\envs\rvc\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\anaconda3\envs\rvc\lib\site-packages\gradio\utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "W:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\modules\vc\modules.py", line 37, in get_vc
    logger.info("Get sid: " + sid)
TypeError: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "D:\anaconda3\envs\rvc\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\anaconda3\envs\rvc\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\anaconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "D:\anaconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\anaconda3\envs\rvc\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\anaconda3\envs\rvc\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\anaconda3\envs\rvc\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\anaconda3\envs\rvc\lib\site-packages\gradio\utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "W:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\modules\vc\modules.py", line 37, in get_vc
    logger.info("Get sid: " + sid)
TypeError: can only concatenate str (not "NoneType") to str

**Comment by mukatsuku** [comment]
forgot to mention
