### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found.

### ISSUE THREAD

**Issue by vorob1** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1353]
I've installed **python-3.10.8-amd64.exe**
Both 
`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`
and
`pip install -r requirements.txt`
applied with only this error:
**DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063**

But when i'm trying to launch web ui, i'm getting this error:

```
(virtual) D:\Voice>python infer-web.py
Traceback (most recent call last):
  File "D:\Voice\infer-web.py", line 16, in <module>
    import fairseq
  File "D:\Voice\virtual\lib\site-packages\fairseq\__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "D:\Voice\virtual\lib\site-packages\fairseq\distributed\__init__.py", line 6, in <module>
    from .distributed_timeout_wrapper import DistributedTimeoutWrapper
  File "D:\Voice\virtual\lib\site-packages\fairseq\distributed\distributed_timeout_wrapper.py", line 11, in <module>
    from torch import nn
  File "D:\Voice\virtual\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "D:\Voice\virtual\lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.
```

**Comment by vorob1** [comment]
Case solved, using virtual environment was a mistake from my side.
