### ISSUE TITLE
Model Inference Error on Transform

### ISSUE THREAD

**Issue by Arslan007** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1358]
I trained the model with rmvpe-gpu through colab without GUI which is linked to my Google Drive. 
I got these files in log folder 
D_2333333.pth (~857 MB)
G_2333333.pth (~435 MB)
trained_IVF2593_Flat_nprobe_1_My-Model_v2.index (~8 MB)
added_IVF2593_Flat_nprobe_1_My-Model_v2.index (~ 320 MB)

So which one I have to use as transform in Model Inference. 

Lastly If I Use GUI to download the Model by connecting to GDrive and try to use Model Inference then I am getting this error 

2023-10-03 01:21:19 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "/content/drive/MyDrive/project-main/infer/modules/vc/modules.py", line 191, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "/content/drive/MyDrive/project-main/infer/modules/vc/pipeline.py", line 410, in pipeline
    self.vc(
  File "/content/drive/MyDrive/project-main/infer/modules/vc/pipeline.py", line 238, in vc
    npy = np.sum(big_npy[ix] * np.expand_dims(weight, axis=2), axis=1)
IndexError: index -1 is out of bounds for axis 0 with size 0

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/audio.py", line 349, in postprocess
    file_path = self.audio_to_temp_file(
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 325, in audio_to_temp_file
    temp_dir = Path(self.DEFAULT_TEMP_DIR) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

**Comment by RVC-Boss** [comment]
weights/xxxx.pth(~60MB)
added_IVF2593_Flat_nprobe_1_My-Model_v2.index (~ 320 MB)
these two files

**Comment by Arslan007** [comment]
Thanks @RVC-Boss 

Appreciate your help and i am able to find training model now. 

I am still getting this issue on conversion interface.


2023-10-03 01:21:19 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
File "/content/drive/MyDrive/project-main/infer/modules/vc/modules.py", line 191, in vc_single
audio_opt = self.pipeline.pipeline(
File "/content/drive/MyDrive/project-main/infer/modules/vc/pipeline.py", line 410, in pipeline
self.vc(
File "/content/drive/MyDrive/project-main/infer/modules/vc/pipeline.py", line 238, in vc
npy = np.sum(big_npy[ix] * np.expand_dims(weight, axis=2), axis=1)
IndexError: index -1 is out of bounds for axis 0 with size 0

Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 388, in call_prediction
output = await route_utils.call_process_api(
File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 219, in call_process_api
output = await app.get_blocks().process_api(
File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1440, in process_api
data = self.postprocess_data(fn_index, result["prediction"], state)
File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1341, in postprocess_data
prediction_value = block.postprocess(prediction_value)
File "/usr/local/lib/python3.10/dist-packages/gradio/components/audio.py", line 349, in postprocess
file_path = self.audio_to_temp_file(
File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 325, in audio_to_temp_file
temp_dir = Path(self.DEFAULT_TEMP_DIR) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

**Comment by anushka0415** [comment]
Facing the same issue. What can be done ?
