### ISSUE TITLE
It does not work because it is overwritten with the latest version of the file.

### ISSUE THREAD

**Issue by eqe1sa1** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1386]
D:\RVC-beta-v2-0618>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Traceback (most recent call last):
  File "D:\RVC-beta-v2-0618\infer-web.py", line 6, in <module>
    from infer.modules.vc.modules import VC
  File "D:\RVC-beta-v2-0618\infer\modules\vc\modules.py", line 11, in <module>
    from infer.lib.audio import load_audio, wav2
  File "D:\RVC-beta-v2-0618\infer\lib\audio.py", line 3, in <module>
    import av
ModuleNotFoundError: No module named 'av'

They said there was no module, so I downloaded the module, but it was still the same.

**Comment by eqe1sa1** [comment]
An error occurred due to overwriting, so it was resolved by completely deleting and reinstalling.
