### ISSUE TITLE
Unable to clean audio

### ISSUE THREAD

**Issue by vorob1** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1392]
I'm getting this error: 

20231007_154555008.wav.reformatted.wav->Traceback (most recent call last):
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'D:\\Voice\\TEMP/20231007_154555008.wav.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Voice\infer\modules\uvr5\modules.py", line 73, in uvr
    pre_fun._path_audio_(
  File "D:\Voice\infer\modules\uvr5\preprocess.py", line 61, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Voice\\TEMP/20231007_154555008.wav.reformatted.wav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'D:\\Voice\\TEMP/20231007_154555008.wav.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Voice\infer\modules\uvr5\modules.py", line 81, in uvr
    pre_fun._path_audio_(
  File "D:\Voice\infer\modules\uvr5\preprocess.py", line 61, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Users\babud\AppData\Local\Programs\Python\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Voice\\TEMP/20231007_154555008.wav.reformatted.wav'

**Comment by RVC-Boss** [comment]
would you mind uploading the audio that you want to get the clean version for us for checking?

**Comment by vorob1** [comment]
[sg10406F.zip](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/12845159/sg10406F.zip)
For example this one, want to clean echo from it.

**Comment by KittoHub** [comment]
@vorob1 @RVC-Boss 

I had the same issue error I have been getting. I found the reason why its not working.

You have to make sure the input file name and input folder name does not have space. I put underscore between the space of the input mp3 file and folder and voila sucess.

Example: 
Current file name: ABC Songs.mp3
Change file name to: ABC_Songs.mp3 (put a underscore or remove spaces)

Do the same with the main input folder if you have just remove it or add underscore then it works.

**Comment by xden2331** [comment]
For those using Mac, try
`brew install ffmpeg fprobe`
Works on M2.
