### ISSUE TITLE
Unable to Train, Results in 

### ISSUE THREAD

**Issue by InquisitorDavid** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1397]
I'm a first-time user and I unpacked the latest NVIDIA package (as of 08-10-2023), ran the training and filled out all the necessary fields. I get this error when training:

`2023-10-08 15:19:01 | INFO | __main__ | Use gpus: 0
2023-10-08 15:19:01 | INFO | __main__ | "runtime\python.exe" infer/modules/train/train.py -e "kinoue" -sr 48k -f0 0 -bs 7 -g 0 -te 200 -se 5 -pg assets/pretrained_v2/f0G48k.pth -pd assets/pretrained_v2/f0D48k.pth -l 1 -c 0 -sw 0 -v v2
INFO:kinoue:{'data': {'filter_length': 2048, 'hop_length': 480, 'max_wav_value': 32768.0, 'mel_fmax': None, 'mel_fmin': 0.0, 'n_mel_channels': 128, 'sampling_rate': 48000, 'win_length': 2048, 'training_files': './logs\\kinoue/filelist.txt'}, 'model': {'filter_channels': 768, 'gin_channels': 256, 'hidden_channels': 192, 'inter_channels': 192, 'kernel_size': 3, 'n_heads': 2, 'n_layers': 6, 'p_dropout': 0, 'resblock': '1', 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'resblock_kernel_sizes': [3, 7, 11], 'spk_embed_dim': 109, 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [24, 20, 4, 4], 'upsample_rates': [12, 10, 2, 2], 'use_spectral_norm': False}, 'train': {'batch_size': 7, 'betas': [0.8, 0.99], 'c_kl': 1.0, 'c_mel': 45, 'epochs': 20000, 'eps': 1e-09, 'fp16_run': True, 'init_lr_ratio': 1, 'learning_rate': 0.0001, 'log_interval': 200, 'lr_decay': 0.999875, 'seed': 1234, 'segment_size': 17280, 'warmup_epochs': 0}, 'model_dir': './logs\\kinoue', 'experiment_dir': './logs\\kinoue', 'save_every_epoch': 5, 'name': 'kinoue', 'total_epoch': 200, 'pretrainG': 'assets/pretrained_v2/f0G48k.pth', 'pretrainD': 'assets/pretrained_v2/f0D48k.pth', 'version': 'v2', 'gpus': '0', 'sample_rate': '48k', 'if_f0': 0, 'if_latest': 1, 'save_every_weights': '0', 'if_cache_data_in_gpu': 0}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "G:\RVC\RVC1006Nvidia\infer\modules\train\train.py", line 174, in run
    net_g = RVC_Model_nof0(
  File "G:\RVC\RVC1006Nvidia\infer\lib\infer_pack\models.py", line 1128, in __init__
    super(self, SynthesizerTrnMs768NSFsid_nono).__init__()
TypeError: super() argument 1 must be type, not SynthesizerTrnMs768NSFsid_nono
`

If I switch to Version v1, I get different errors, and one-click says 'all processes completed' but no output models come out:

`2023-10-08 15:25:20 | INFO | __main__ | Use gpus: 0
2023-10-08 15:25:20 | INFO | __main__ | "runtime\python.exe" infer/modules/train/train.py -e "kinoue" -sr 48k -f0 0 -bs 4 -g 0 -te 20 -se 5 -pg assets/pretrained/f0G48k.pth -pd assets/pretrained/f0D48k.pth -l 0 -c 0 -sw 0 -v v1
INFO:kinoue:{'data': {'filter_length': 2048, 'hop_length': 480, 'max_wav_value': 32768.0, 'mel_fmax': None, 'mel_fmin': 0.0, 'n_mel_channels': 128, 'sampling_rate': 48000, 'win_length': 2048, 'training_files': './logs\\kinoue/filelist.txt'}, 'model': {'filter_channels': 768, 'gin_channels': 256, 'hidden_channels': 192, 'inter_channels': 192, 'kernel_size': 3, 'n_heads': 2, 'n_layers': 6, 'p_dropout': 0, 'resblock': '1', 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'resblock_kernel_sizes': [3, 7, 11], 'spk_embed_dim': 109, 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [24, 20, 4, 4], 'upsample_rates': [12, 10, 2, 2], 'use_spectral_norm': False}, 'train': {'batch_size': 4, 'betas': [0.8, 0.99], 'c_kl': 1.0, 'c_mel': 45, 'epochs': 20000, 'eps': 1e-09, 'fp16_run': True, 'init_lr_ratio': 1, 'learning_rate': 0.0001, 'log_interval': 200, 'lr_decay': 0.999875, 'seed': 1234, 'segment_size': 17280, 'warmup_epochs': 0}, 'model_dir': './logs\\kinoue', 'experiment_dir': './logs\\kinoue', 'save_every_epoch': 5, 'name': 'kinoue', 'total_epoch': 20, 'pretrainG': 'assets/pretrained/f0G48k.pth', 'pretrainD': 'assets/pretrained/f0D48k.pth', 'version': 'v1', 'gpus': '0', 'sample_rate': '48k', 'if_f0': 0, 'if_latest': 0, 'save_every_weights': '0', 'if_cache_data_in_gpu': 0}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
DEBUG:infer.lib.infer_pack.models:gin_channels: 256, self.spk_embed_dim: 109
INFO:kinoue:loaded pretrained assets/pretrained/f0G48k.pth
Process Process-1:
Traceback (most recent call last):
  File "G:\RVC\RVC1006Nvidia\infer\modules\train\train.py", line 210, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "G:\RVC\RVC1006Nvidia\infer\lib\train\utils.py", line 213, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "G:\RVC\RVC1006Nvidia\infer\modules\train\train.py", line 230, in run
    net_g.module.load_state_dict(
  File "G:\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid_nono:
        Unexpected key(s) in state_dict: "enc_p.emb_pitch.weight", "dec.m_source.l_linear.weight", "dec.m_source.l_linear.bias", "dec.noise_convs.0.weight", "dec.noise_convs.0.bias", "dec.noise_convs.1.weight", "dec.noise_convs.1.bias", "dec.noise_convs.2.weight", "dec.noise_convs.2.bias", "dec.noise_convs.3.weight", "dec.noise_convs.3.bias", "dec.noise_convs.4.weight", "dec.noise_convs.4.bias", "dec.ups.4.bias", "dec.ups.4.weight_g", "dec.ups.4.weight_v", "dec.resblocks.12.convs1.0.bias", "dec.resblocks.12.convs1.0.weight_g", "dec.resblocks.12.convs1.0.weight_v", "dec.resblocks.12.convs1.1.bias", "dec.resblocks.12.convs1.1.weight_g", "dec.resblocks.12.convs1.1.weight_v", "dec.resblocks.12.convs1.2.bias", "dec.resblocks.12.convs1.2.weight_g", "dec.resblocks.12.convs1.2.weight_v", "dec.resblocks.12.convs2.0.bias", "dec.resblocks.12.convs2.0.weight_g", "dec.resblocks.12.convs2.0.weight_v", "dec.resblocks.12.convs2.1.bias", "dec.resblocks.12.convs2.1.weight_g", "dec.resblocks.12.convs2.1.weight_v", "dec.resblocks.12.convs2.2.bias", "dec.resblocks.12.convs2.2.weight_g", "dec.resblocks.12.convs2.2.weight_v", "dec.resblocks.13.convs1.0.bias", "dec.resblocks.13.convs1.0.weight_g", "dec.resblocks.13.convs1.0.weight_v", "dec.resblocks.13.convs1.1.bias", "dec.resblocks.13.convs1.1.weight_g", "dec.resblocks.13.convs1.1.weight_v", "dec.resblocks.13.convs1.2.bias", "dec.resblocks.13.convs1.2.weight_g", "dec.resblocks.13.convs1.2.weight_v", "dec.resblocks.13.convs2.0.bias", "dec.resblocks.13.convs2.0.weight_g", "dec.resblocks.13.convs2.0.weight_v", "dec.resblocks.13.convs2.1.bias", "dec.resblocks.13.convs2.1.weight_g", "dec.resblocks.13.convs2.1.weight_v", "dec.resblocks.13.convs2.2.bias", "dec.resblocks.13.convs2.2.weight_g", "dec.resblocks.13.convs2.2.weight_v", "dec.resblocks.14.convs1.0.bias", "dec.resblocks.14.convs1.0.weight_g", "dec.resblocks.14.convs1.0.weight_v", "dec.resblocks.14.convs1.1.bias", "dec.resblocks.14.convs1.1.weight_g", "dec.resblocks.14.convs1.1.weight_v", "dec.resblocks.14.convs1.2.bias", "dec.resblocks.14.convs1.2.weight_g", "dec.resblocks.14.convs1.2.weight_v", "dec.resblocks.14.convs2.0.bias", "dec.resblocks.14.convs2.0.weight_g", "dec.resblocks.14.convs2.0.weight_v", "dec.resblocks.14.convs2.1.bias", "dec.resblocks.14.convs2.1.weight_g", "dec.resblocks.14.convs2.1.weight_v", "dec.resblocks.14.convs2.2.bias", "dec.resblocks.14.convs2.2.weight_g", "dec.resblocks.14.convs2.2.weight_v".
        size mismatch for dec.ups.0.weight_v: copying a param with shape torch.Size([512, 256, 16]) from checkpoint, the shape in current model is torch.Size([512, 256, 24]).
        size mismatch for dec.ups.1.weight_v: copying a param with shape torch.Size([256, 128, 16]) from checkpoint, the shape in current model is torch.Size([256, 128, 20]).
        size mismatch for dec.conv_post.weight: copying a param with shape torch.Size([1, 16, 7]) from checkpoint, the shape in current model is torch.Size([1, 32, 7]).`

**Comment by InquisitorDavid** [comment]
Addendum: I tried doing the same sequence on prior build 0813 and it did not error and actually outputted a functional trained model.

**Comment by JiSiN3000** [comment]
Unfortunately i got pretty much the same error. "IndexError: list index out of range".
The exact same Audiofile worked pretty well on a fork of an older version of RVC.

Here is what i got on cmd:

c:\Temp\RVC>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
2023-10-08 15:25:16 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 3060
is_half:True, device:cuda:0
2023-10-08 15:25:18 | INFO | __main__ | Use Language: en_US
Running on local URL:  http://0.0.0.0:7897
2023-10-08 15:26:16 | INFO | __main__ | "runtime\python.exe" infer/modules/train/preprocess.py "c:\Temp\RVC\datasets\" 40000 22 "c:\Temp\RVC/logs/Halid" False 3.0
['infer/modules/train/preprocess.py', 'c:\\Temp\\RVC\\datasets" 40000 22 c:\\Temp\\RVC/logs/Halid False 3.0']
Traceback (most recent call last):
  File "c:\Temp\RVC\infer\modules\train\preprocess.py", line 11, in <module>
    sr = int(sys.argv[2])
IndexError: list index out of range
2023-10-08 15:26:17 | INFO | __main__ |

**Comment by RVC-Boss** [comment]
super(self, SynthesizerTrnMs768NSFsid_nono).__init__() TypeError: super() argument 1 must be type, not SynthesizerTrnMs768NSFsid_nono 
We have fixed this error. You can update this file and have a try.
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/dev/infer/lib/infer_pack/models.py

**Comment by FlynnHHH** [comment]
> @InquisitorDavid super(self, SynthesizerTrnMs768NSFsid_nono).**init**() TypeError: super() argument 1 must be type, not SynthesizerTrnMs768NSFsid_nono We have fixed this error. You can update this file and have a try. https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/dev/infer/lib/infer_pack/models.py
> 
> RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid_nono: Unexpected key(s) in state_dict: This error: You can update this file and have a try. https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/dev/infer-web.py

I had a similar issue and after I upgraded the two files it does not work. The cmd output is:

2024-06-14 00:00:15 | INFO | __main__ | Use gpus: 0
2024-06-14 00:00:15 | INFO | __main__ | "runtime\python.exe" infer/modules/train/train.py -e "bingtang" -sr 40k -f0 1 -b
s 4 -g 0 -te 10 -se 5 -pg assets/pretrained_v2/f0G40k.pth -pd assets/pretrained_v2/f0D40k.pth -l 0 -c 0 -sw 1 -v v2
INFO:bingtang:{'data': {'filter_length': 2048, 'hop_length': 480, 'max_wav_value': 32768.0, 'mel_fmax': None, 'mel_fmin'
: 0.0, 'n_mel_channels': 128, 'sampling_rate': 48000, 'win_length': 2048, 'training_files': './logs\\bingtang/filelist.t
xt'}, 'model': {'filter_channels': 768, 'gin_channels': 256, 'hidden_channels': 192, 'inter_channels': 192, 'kernel_size
': 3, 'n_heads': 2, 'n_layers': 6, 'p_dropout': 0, 'resblock': '1', 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1
, 3, 5]], 'resblock_kernel_sizes': [3, 7, 11], 'spk_embed_dim': 109, 'upsample_initial_channel': 512, 'upsample_kernel_s
izes': [24, 20, 4, 4], 'upsample_rates': [12, 10, 2, 2], 'use_spectral_norm': False}, 'train': {'batch_size': 4, 'betas'
: [0.8, 0.99], 'c_kl': 1.0, 'c_mel': 45, 'epochs': 20000, 'eps': 1e-09, 'fp16_run': True, 'init_lr_ratio': 1, 'learning_
rate': 0.0001, 'log_interval': 200, 'lr_decay': 0.999875, 'seed': 1234, 'segment_size': 17280, 'warmup_epochs': 0}, 'mod
el_dir': './logs\\bingtang', 'experiment_dir': './logs\\bingtang', 'save_every_epoch': 5, 'name': 'bingtang', 'total_epo
ch': 10, 'pretrainG': 'assets/pretrained_v2/f0G40k.pth', 'pretrainD': 'assets/pretrained_v2/f0D40k.pth', 'version': 'v2'
, 'gpus': '0', 'sample_rate': '40k', 'if_f0': 1, 'if_latest': 0, 'save_every_weights': '1', 'if_cache_data_in_gpu': 0}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 n
odes.
DEBUG:infer.lib.infer_pack.models:gin_channels: 256, self.spk_embed_dim: 109
INFO:bingtang:loaded pretrained assets/pretrained_v2/f0G40k.pth
Process Process-1:
Traceback (most recent call last):
  File "D:\RVC1006Nvidia\RVC1006Nvidia\infer\modules\train\train.py", line 213, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "D:\RVC1006Nvidia\RVC1006Nvidia\infer\lib\train\utils.py", line 213, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "D:\RVC1006Nvidia\RVC1006Nvidia\infer\modules\train\train.py", line 233, in run
    net_g.module.load_state_dict(
  File "D:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_d
ict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs768NSFsid:
        size mismatch for dec.ups.0.weight_v: copying a param with shape torch.Size([512, 256, 16]) from checkpoint, the
 shape in current model is torch.Size([512, 256, 24]).
        size mismatch for dec.ups.1.weight_v: copying a param with shape torch.Size([256, 128, 16]) from checkpoint, the
 shape in current model is torch.Size([256, 128, 20]).
