### ISSUE TITLE
RVC1006v2 realtime error

### ISSUE THREAD

**Issue by mikisayakamitakihara** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1412]
Audio block passed.
Index search FAILED or disabled
Exception ignored from cffi callback <function _StreamBase.__init__.<locals>.callback_ptr at 0x000001E1F4E92790>:
Traceback (most recent call last):
  File "C:\Users\compute1\Downloads\RVC1006Nvidia\runtime\lib\site-packages\sounddevice.py", line 886, in callback_ptr
    return _wrap_callback(
  File "C:\Users\compute1\Downloads\RVC1006Nvidia\runtime\lib\site-packages\sounddevice.py", line 2687, in _wrap_callback
    callback(*args)
  File "C:\Users\compute1\Downloads\RVC1006Nvidia\gui_v1.py", line 725, in audio_callback
    infer_wav = self.rvc.infer(
  File "C:\Users\compute1\Downloads\RVC1006Nvidia\tools\rvc_for_realtime.py", line 414, in infer
    infered_audio = self.net_g.infer(
  File "C:\Users\compute1\Downloads\RVC1006Nvidia\infer\lib\infer_pack\models.py", line 1245, in infer
    nsff0 = nsff0[:, head:]
UnboundLocalError: local variable 'nsff0' referenced before assignment

・RTX 2070
・My RVC model has been working smoothly in versions from August, June, and others.
model detail . 40k v2 nof0model  /　　　I can't get it to work with PM, Harvest, or RMVPE.

**Comment by RVC-Boss** [comment]
Sorry.
Fixed now.
You can updated this file and replace it on local to fix this issue.
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/dev/infer/lib/infer_pack/models.py
