### ISSUE TITLE
1006v2 go-realtime-gui error

### ISSUE THREAD

**Issue by sharesharp** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1437]
使用1006版的go-realtime-gui.bat打开报错如下，请问这个该怎么去解决(0814版本可以正常使用)

I:\AI\RVC1006Nvidia\RVC1006Nvidia>runtime\python.exe gui_v1.py
2023-10-16 07:32:19 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-10-16 07:32:19 | INFO | faiss.loader | Successfully loaded faiss with AVX2 support.
2023-10-16 07:32:20 | INFO | configs.config | Found GPU NVIDIA GeForce GTX 1070 Ti, force to fp32
overwrite preprocess and configs.json
is_half:False, device:cuda:0
Traceback (most recent call last):
  File "I:\AI\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 126, in load
    data["sg_input_device"] = input_devices[sd.default.device[0]]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\AI\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 874, in <module>
    gui = GUI()
  File "I:\AI\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 114, in __init__
    self.launcher()
  File "I:\AI\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 153, in launcher
    data = self.load()
  File "I:\AI\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 134, in load
    "sg_input_device": input_devices[sd.default.device[0]],
IndexError: list index out of range

**Comment by ChengsongLu** [comment]
怎么解决的？
