### ISSUE TITLE
启动不了程序

### ISSUE THREAD

**Issue by idolf** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1446]
第一次训练到一半突然error了，输出太多被clear了，这次是第二次的
在autoDL上买的镜像，v4的
``` sh
Traceback (most recent call last):
  File "infer-web.py", line 26, in <module>
    import fairseq
  File "/root/miniconda3/lib/python3.8/site-packages/fairseq/__init__.py", line 40, in <module>
    import fairseq.scoring  # noqa
  File "/root/miniconda3/lib/python3.8/site-packages/fairseq/scoring/__init__.py", line 55, in <module>
    importlib.import_module("fairseq.scoring." + module)
  File "/root/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/miniconda3/lib/python3.8/site-packages/fairseq/scoring/bleu.py", line 14, in <module>
    from fairseq.scoring.tokenizer import EvaluationTokenizer
  File "/root/miniconda3/lib/python3.8/site-packages/fairseq/scoring/tokenizer.py", line 8, in <module>
    import sacrebleu as sb
  File "/root/miniconda3/lib/python3.8/site-packages/sacrebleu/__init__.py", line 21, in <module>
    from .utils import smart_open, SACREBLEU_DIR, download_test_set  # noqa: F401
  File "/root/miniconda3/lib/python3.8/site-packages/sacrebleu/utils.py", line 9, in <module>
    import portalocker
  File "/root/miniconda3/lib/python3.8/site-packages/portalocker/__init__.py", line 5, in <module>
    from . import utils
  File "/root/miniconda3/lib/python3.8/site-packages/portalocker/utils.py", line 366, in <module>
    class BoundedSemaphore(LockBase):
  File "/root/miniconda3/lib/python3.8/site-packages/portalocker/utils.py", line 388, in BoundedSemaphore
    directory: str = tempfile.gettempdir(),
  File "/root/miniconda3/lib/python3.8/tempfile.py", line 286, in gettempdir
    tempdir = _get_default_tempdir()
  File "/root/miniconda3/lib/python3.8/tempfile.py", line 218, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/root/Retrieval-based-Voice-Conversion-WebUI']
```

**Comment by idolf** [comment]
系统盘还干满了。。。
