### ISSUE TITLE
Vocal Separation error

### ISSUE THREAD

**Issue by SohitKumar** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1450]
hunnysinghm2ccf49e.wav.reformatted.wav->Traceback (most recent call last):
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 1213, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'D:\\Github Software\\RVC1006Nvidia\\TEMP/hunnysinghm2ccf49e.wav.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Github Software\RVC1006Nvidia\infer\modules\uvr5\modules.py", line 74, in uvr
    pre_fun._path_audio_(
  File "D:\Github Software\RVC1006Nvidia\infer\modules\uvr5\vr.py", line 63, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Github Software\\RVC1006Nvidia\\TEMP/hunnysinghm2ccf49e.wav.reformatted.wav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 1213, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'D:\\Github Software\\RVC1006Nvidia\\TEMP/hunnysinghm2ccf49e.wav.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Github Software\RVC1006Nvidia\infer\modules\uvr5\modules.py", line 82, in uvr
    pre_fun._path_audio_(
  File "D:\Github Software\RVC1006Nvidia\infer\modules\uvr5\vr.py", line 63, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "D:\Github Software\RVC1006Nvidia\runtime\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Github Software\\RVC1006Nvidia\\TEMP/hunnysinghm2ccf49e.wav.reformatted.wav'

**Comment by viniciuspinto** [comment]
I had the same error and solved by installing ffmpeg/ffprobe (downloaded the binaries, added the folder path to the PATH variable and restarted the prompt/webUI).

**Comment by Rocdaric** [comment]
> I had the same error and solved by installing ffmpeg/ffprobe (downloaded the binaries, added the folder path to the PATH variable and restarted the prompt/webUI).

Total noob here... Can u explain like i'm 5?

**Comment by viniciuspinto** [comment]
> > I had the same error and solved by installing ffmpeg/ffprobe (downloaded the binaries, added the folder path to the PATH variable and restarted the prompt/webUI).
> 
> Total noob here... Can u explain like i'm 5?

1. Download ffmpeg/ffprobe binaries for Windows: https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z
2. Unzip them somewhere. Copy the path to the unzipped /bin folder;
3. Edit your PATH environment variable (you can search for "variables" on start menu); Add the path you copied previously to the PATH variable;
4. Restart the webUI.
