### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by billy7097** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1454]
AttributeError: 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\infer-web.py", line 203, in vc_single
    audio_opt = vc.pipeline(
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\vc_infer_pipeline.py", line 361, in pipeline
    self.vc(
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\vc_infer_pipeline.py", line 249, in vc
    (net_g.infer(feats, p_len, pitch, pitchf, sid)[0][0, 0])
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\lib\infer_pack\models.py", line 752, in infer
    m_p, logs_p, x_mask = self.enc_p(phone, pitch, phone_lengths)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\lib\infer_pack\models.py", line 104, in forward
    x = self.encoder(x * x_mask, x_mask)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\lib\infer_pack\attentions.py", line 65, in forward
    y = self.attn_layers[i](x, x, attn_mask)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\lib\infer_pack\attentions.py", line 221, in forward
    x, self.attn = self.attention(q, k, v, mask=attn_mask)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\lib\infer_pack\attentions.py", line 265, in attention
    relative_weights = self._absolute_position_to_relative_position(p_attn)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\lib\infer_pack\attentions.py", line 346, in _absolute_position_to_relative_position
    x_flat = F.pad(x_flat, commons.convert_pad_shape([[0, 0], [0, 0], [length, 0]]))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 0; 4.00 GiB total capacity; 1.99 GiB already allocated; 21.89 MiB free; 2.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Traceback (most recent call last):
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by billy7097** [comment]
AttributeError: 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\infer-web.py", line 203, in vc_single
    audio_opt = vc.pipeline(
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\vc_infer_pipeline.py", line 361, in pipeline
    self.vc(
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\vc_infer_pipeline.py", line 249, in vc
    (net_g.infer(feats, p_len, pitch, pitchf, sid)[0][0, 0])
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\lib\infer_pack\models.py", line 752, in infer
    m_p, logs_p, x_mask = self.enc_p(phone, pitch, phone_lengths)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\lib\infer_pack\models.py", line 104, in forward
    x = self.encoder(x * x_mask, x_mask)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\lib\infer_pack\attentions.py", line 65, in forward
    y = self.attn_layers[i](x, x, attn_mask)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\lib\infer_pack\attentions.py", line 221, in forward
    x, self.attn = self.attention(q, k, v, mask=attn_mask)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\lib\infer_pack\attentions.py", line 265, in attention
    relative_weights = self._absolute_position_to_relative_position(p_attn)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\lib\infer_pack\attentions.py", line 346, in _absolute_position_to_relative_position
    x_flat = F.pad(x_flat, commons.convert_pad_shape([[0, 0], [0, 0], [length, 0]]))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 0; 4.00 GiB total capacity; 1.99 GiB already allocated; 21.89 MiB free; 2.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Traceback (most recent call last):
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\rodan\Downloads\RVC\RVC-beta0717\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
