### ISSUE TITLE
ImportError: cannot import name 'inp_root' from 'config' 

### ISSUE THREAD

**Issue by tomas122727** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1455]
C:\Users\tomas_000\Desktop\Retrieval-based-Voice-Conversion-WebUI-main>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Traceback (most recent call last):
  File "C:\Users\tomas_000\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\infer-web.py", line 6, in <module>
    from infer.modules.vc.modules import VC
  File "C:\Users\tomas_000\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\infer.py", line 5, in <module>
    from config import inp_root,opt_root,f0_up_key,person,is_half,device
ImportError: cannot import name 'inp_root' from 'config' (C:\Users\tomas_000\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\config.py)
here is the main issue

**Comment by tomas122727** [comment]
cuda version 12.3
not sure if the current pytorch along with current gpu driver update 
supports cuda 12.3 and my gpu may not support it however this was working before i updated
cuda and my gpu
