### ISSUE TITLE
stopped working. there was an error at startup

### ISSUE THREAD

**Issue by Sinicyn78** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1479]
2023-10-26 10:51:38 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 3060
is_half:True, device:cuda:0
Traceback (most recent call last):
  File "D:\Data\Anton\VoiceCloning\RVC NEW\RVC1006Nvidia\infer-web.py", line 20, in <module>
    import gradio as gr
  File "C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\gradio\components\annotated_image.py", line 14, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\gradio\components\base.py", line 29, in <module>
    from gradio.blocks import Block, BlockContext, Updateable
  File "C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\gradio\blocks.py", line 29, in <module>
    from gradio import (
  File "C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\gradio\networking.py", line 20, in <module>
    from gradio.routes import App
  File "C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\gradio\routes.py", line 49, in <module>
    from gradio import route_utils, utils, wasm_utils
  File "C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\gradio\route_utils.py", line 13, in <module>
    from gradio.helpers import EventData
  File "C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\gradio\helpers.py", line 18, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\matplotlib\pyplot.py", line 66, in <module>
    from matplotlib.figure import Figure, FigureBase, figaspect
  File "C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\matplotlib\figure.py", line 43, in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
  File "C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\matplotlib\projections\__init__.py", line 58, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "D:\Data\Anton\VoiceCloning\RVC NEW\RVC1006Nvidia\runtime\lib\site-packages\mpl_toolkits\mplot3d\__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "D:\Data\Anton\VoiceCloning\RVC NEW\RVC1006Nvidia\runtime\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 45, in <module>
    class Axes3D(Axes):
  File "D:\Data\Anton\VoiceCloning\RVC NEW\RVC1006Nvidia\runtime\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 718, in Axes3D
    set_zticklabels = _axis_method_wrapper(
  File "C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\matplotlib\axes\_base.py", line 56, in __init__
    doc = inspect.getdoc(getattr(maxis.Axis, method_name))
AttributeError: type object 'Axis' has no attribute '_set_ticklabels'

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved.
