### ISSUE TITLE
WSL2 Ubuntu下训练失败，Windows下就没问题。

### ISSUE THREAD

**Issue by hpx502766238** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1482]
想用WSL2 Ubuntu来训练以得到速度的加成。但是WSL2下总是报错Cuda out of memory就终止了，将batchsize调成1都不行；Windows下batchsize调到6都能正常运行。
系统：Windows11 Home 21H2 WSL2 Ubuntu2202
CUDAToolkit版本11.8，torch三件套在windows下和wsl2中都是匹配cu118的相同版本。
显卡：RTX3060 6G
内存：24G
CPU：AMD R7 5800H

WSL2控制台日志：
DEBUG:matplotlib:matplotlib data path: /home/hpx502766238/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/hpx502766238/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hpx502766238/Retrieval-based-Voice-Conversion-WebUI/infer/modules/train/train.py", line 271, in run
    train_and_evaluate(
  File "/home/hpx502766238/Retrieval-based-Voice-Conversion-WebUI/infer/modules/train/train.py", line 499, in train_and_evaluate
    scaler.scale(loss_gen_all).backward()
  File "/home/hpx502766238/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/hpx502766238/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2023-10-28 17:28:21 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-10-28 17:28:22 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-10-28 17:28:22 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-10-28 17:28:22 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK"

**Comment by sunmy2019** [comment]
https://docs.nvidia.com/cuda/wsl-user-guide/index.html#known-limitations-for-linux-cuda-applications
> Pinned system memory (example: System memory that an application makes resident for GPU accesses) availability for applications is limited.
> For example, some deep learning training workloads, depending on the framework, model and dataset size used, can exceed this limit and may not work.

See also https://github.com/microsoft/WSL/issues/8447
