### ISSUE TITLE
Multi GPU not working

### ISSUE THREAD

**Issue by BrianStark** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1507]
A very good evening I am having some problems training my model on 2 graphics cards. 
If I try on each card the program runs fine, only using the cards does not work.

I run the program on:

CPU: AMD Ryzen Threadripper 2990WX 32-Core Processor
RAM: 128 GB
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

I then get the following problem in my console:

```
Process Process-2:
Traceback (most recent call last):
  File "D:\AI\AI-voice-tools\RVC1006Nvidia\infer\modules\train\train.py", line 213, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "D:\AI\AI-voice-tools\RVC1006Nvidia\infer\lib\train\utils.py", line 213, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "D:\AI\AI-voice-tools\RVC1006Nvidia\infer\modules\train\train.py", line 232, in run
    logger.info(
UnboundLocalError: local variable 'logger' referenced before assignment
```

Is there anyone who might have a way to fix this?

**Comment by VincentHu1** [comment]
same problem

**Comment by AZEN-SGG** [comment]
same problem, does anyone have a solution?

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/infer/modules/train/train.py
update this file. Maybe fix now.
