### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by billy7097** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1508]
2023-11-03 16:25:15 | INFO | infer.modules.vc.pipeline | Loading rmvpe model,assets/rmvpe/rmvpe.pt
2023-11-03 16:25:29 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\infer\modules\vc\modules.py", line 185, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\infer\modules\vc\pipeline.py", line 354, in pipeline
    pitch, pitchf = self.get_f0(
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\infer\modules\vc\pipeline.py", line 154, in get_f0
    f0 = self.model_rmvpe.infer_from_audio(x, thred=0.03)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\infer\lib\rmvpe.py", line 603, in infer_from_audio
    hidden = self.mel2hidden(mel)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\infer\lib\rmvpe.py", line 584, in mel2hidden
    hidden = self.model(mel)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\infer\lib\rmvpe.py", line 409, in forward
    x = self.cnn(self.unet(mel)).transpose(1, 2).flatten(-2)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\infer\lib\rmvpe.py", line 369, in forward
    x = self.decoder(x, concat_tensors)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\infer\lib\rmvpe.py", line 338, in forward
    x = layer(x, concat_tensors[-1 - i])
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\infer\lib\rmvpe.py", line 320, in forward
    x = conv2(x)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\infer\lib\rmvpe.py", line 210, in forward
    return self.conv(x) + self.shortcut(x)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\functional.py", line 2450, in batch_norm
    return torch.batch_norm(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 212.00 MiB (GPU 0; 4.00 GiB total capacity; 1.96 GiB already allocated; 139.89 MiB free; 2.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Traceback (most recent call last):
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\rodan\Downloads\RVC\RVC1006Nvidia\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by wilsme** [comment]
Hey bro.. I spent about 2 hours grinding on this and absolutely hated myself and the people who wrote the instructions for this...but here was my issue...
1) make sure the the file you are trying to sound like saved as a 16 bit wav (not 32 bit float, not 24 bit  int)
2) add .wav at the end of your file path/ name to indicate the file type
example
not c:\users\me\music\song
but
c:\users\me\music\song.wav

should run after that

another weird moment... export from spectral layers software created an issue... but file converted with soundforge was recognized... so if the above doesn't work.. then try to"  save as" with a different audio converter

good luck my friend

**Comment by H46K3RL0L** [comment]
It doesnt always have to be wav, for some reason. It seems to sometimes work with other files, but is seemingly random. Used a yt download service to download some data as an mp3, and a second yt download service. Tried to use one, didnt work, other one did work.

**Comment by wilsme** [comment]
I agree with your observation, and I believe that when i first started using this ( a different build) i could convert mp3's. I eventually  read all the preceding lines to the error and the code is trying to get everything to 16 bit wav so I thought rather than have the program code perhaps fail in conversion; to handle it myself...

I am not a programmer or even a python guru... so my advice here is based on observation/trial and error, and voodoo dolls. Need a real captain from here on out lol.
