### ISSUE TITLE
No such file or directory: 'ffprobe'

### ISSUE THREAD

**Issue by jygytfugi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1511]
Traceback (most recent call last):
  File "/home/tinparnus/Desktop/Retrieval-based-Voice-Conversion-WebUI/infer/modules/uvr5/modules.py", line 49, in uvr
    info = ffmpeg.probe(inp_path, cmd="ffprobe")
  File "/home/tinparnus/.local/lib/python3.10/site-packages/ffmpeg/_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'
sh: 1: ffmpeg: not found

**Comment by hopto-dot** [comment]
1. Which version of RVC are you using?
2. Do you have `ffmpeg.exe` and `ffprobe.exe` in the base directory of the RVC folder?

**Comment by ShutaShimazaki** [comment]
If you are Ubuntu/Debean user, 
`sudo apt install ffmpeg`

if you are MacOS user, 
`brew install ffmpeg`

cf: [2. install ffmgeg](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/docs/en/README.en.md)
