### ISSUE TITLE
I've seen some people having similar issue but nothing like mine, if anyone could help ?

### ISSUE THREAD

**Issue by Vlahi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1531]
2023-11-11 16:26:26 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "C:\Users\Filip\RVC1006AMD_Intel\infer\lib\audio.py", line 61, in load_audio
    with open(file, "rb") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Filip\\RVC1006AMD_Intel\\Moj glas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Filip\RVC1006AMD_Intel\infer\modules\vc\modules.py", line 163, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "C:\Users\Filip\RVC1006AMD_Intel\infer\lib\audio.py", line 73, in load_audio
    raise RuntimeError(traceback.format_exc())
RuntimeError: Traceback (most recent call last):
  File "C:\Users\Filip\RVC1006AMD_Intel\infer\lib\audio.py", line 61, in load_audio
    with open(file, "rb") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Filip\\RVC1006AMD_Intel\\Moj glas'

Traceback (most recent call last):
  File "C:\Users\Filip\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Filip\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Filip\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Filip\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\Filip\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\Filip\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

tried, reruning it multiple times, changing from Harvest to crape to pm nothing changed. 

GPU: RX 6900 XT ( if this means something ) 
CPU: Ryzen 5 3600

**Comment by Mojobones** [comment]
It seems like a permissions issue potentially. Try moving it to a different folder such as your desktop, or into your Downloads folder. Then try to rerun it there, just as an easy way to check it.

**Comment by Vlahi** [comment]
i'll give it a try in a bit and give you what the results are

**Comment by Vlahi** [comment]
New comments from console: 

Traceback (most recent call last):
  File "C:\Users\Filip\RVC1006AMD_Intel\infer\modules\vc\modules.py", line 163, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "C:\Users\Filip\RVC1006AMD_Intel\infer\lib\audio.py", line 73, in load_audio
    raise RuntimeError(traceback.format_exc())
RuntimeError: Traceback (most recent call last):
  File "C:\Users\Filip\RVC1006AMD_Intel\infer\lib\audio.py", line 61, in load_audio
    with open(file, "rb") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Filip\\Downloads\\Moj glas'


Traceback (most recent call last):
  File "C:\Users\Filip\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Filip\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Filip\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Filip\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\Filip\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\Filip\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by JD-2006** [comment]
Try using paths with no spaces 'C:\Users\Filip\Downloads\Moj glas' -> 'C:\Users\Filip\Downloads\Mojglas'
Also in the training tab/ location you can use locations with quotations like - "C:\Users\Filip\Downloads\Mojglas\traing"

**Comment by Vlahi** [comment]
tried multiple times, still the same error happens, i have backup file of training model on desktop, can that make issues ?

**Comment by JD-2006** [comment]
It should not if it is not in any of your paths.
And you have ffmpeg.exe and ffprobe.exe in your Retrieval-based-Voice-Conversion-WebUI base folder?

**Comment by JD-2006** [comment]
Or this https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1271#issuecomment-1729497613

**Comment by LordMilutin** [comment]
Eh moj Filipe, probaj drugu particiju. :D

**Comment by RVC-Boss** [comment]
Because you wrote a wrong file path.
You can update the code to the latest `main` branch. You can now drag and drop audio files into the frontend instead of entering their file paths manually.
