### ISSUE TITLE
关于不用WebUI的问题

### ISSUE THREAD

**Issue by Yaodada12** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#155]
在Windows上和Linux上运行都是各种各样的报错，以下为linux报错。大佬，能不能给个不用webui的推理代码和训练代码？

```
Traceback (most recent call last):
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 359, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/resource_sharer.py", line 77, in register
    self._start()
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/resource_sharer.py", line 130, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long

```

**Comment by RVC-Boss** [comment]
https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/myinfer.py

**Comment by Yaodada12** [comment]
> https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/myinfer.py

好的，多谢大佬。

**Comment by hxpGit512** [comment]
> https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/myinfer.py

这个脚本在新版本下似乎不可用了，大佬您能不能更新一下呢

**Comment by w4l6** [comment]
训练只能是ui界面吧

**Comment by hxpGit512** [comment]
已收件
