### ISSUE TITLE
Use Model Error M2 Mac

### ISSUE THREAD

**Issue by vysecurity** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1552]
I am getting the following error when trying to use a model I've trained over night:

```
WARNING:infer.modules.vc.modules:Traceback (most recent call last):
  File "/Users/xxxx/Downloads/Retrieval-based-Voice-Conversion-WebUI/infer/modules/vc/modules.py", line 186, in vc_single
    audio_opt = self.pipeline.pipeline(
                ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pipeline'

Traceback (most recent call last):
  File "/Users/xxxx/Downloads/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.11/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/Downloads/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.11/site-packages/gradio/blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/Downloads/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.11/site-packages/gradio/blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/Downloads/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.11/site-packages/gradio/components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/Downloads/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.11/site-packages/gradio/components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
                                           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'tobytes'
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'date', b'Thu, 16 Nov 2023 09:10:24 GMT'), (b'server', b'uvicorn'), (b'content-length', b'14'), (b'content-type', b'application/json')])
```

**Comment by Tps-F** [comment]
Have you loaded the model?
If you can send me all the logs I can help

**Comment by vysecurity** [comment]
There's a few bugs but eventually messing with the settings it worked out!

**Comment by iamzhangyunlu** [comment]
@vysecurity hi, i met this problem too, can you tell me how to solve this, please?
