### ISSUE TITLE
HTTP/1.1 500 Internal Server Error

### ISSUE THREAD

**Issue by Cryptofan83** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1555]
2023-11-16 18:09:04 | INFO | httpx | HTTP Request: POST http://localhost:7897/api/predict "HTTP/1.1 200 OK"
2023-11-16 18:09:04 | INFO | __main__ | "python.exe" infer/modules/train/preprocess.py "e:\kabare-hangom\kohalmi\" 40000 8 "C:\ai\RVC\Retrieval-based-Voice-Conversion-WebUI/logs/k" False 3.0
['infer/modules/train/preprocess.py', 'e:\\kabare-hangom\\kohalmi" 40000 8 C:\\ai\\RVC\\Retrieval-based-Voice-Conversion-WebUI/logs/k False 3.0']
Traceback (most recent call last):
  File "C:\ai\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\modules\train\preprocess.py", line 11, in <module>
    sr = int(sys.argv[2])
IndexError: list index out of range
2023-11-16 18:09:05 | INFO | __main__ |
2023-11-16 18:09:05 | INFO | httpx | HTTP Request: POST http://localhost:7897/api/predict "HTTP/1.1 200 OK"
2023-11-16 18:09:05 | INFO | __main__ | "python.exe" infer/modules/train/extract/extract_f0_rmvpe.py 2 0 0 "C:\ai\RVC\Retrieval-based-Voice-Conversion-WebUI/logs/k" True
2023-11-16 18:09:05 | INFO | __main__ | "python.exe" infer/modules/train/extract/extract_f0_rmvpe.py 2 1 0 "C:\ai\RVC\Retrieval-based-Voice-Conversion-WebUI/logs/k" True
['infer/modules/train/extract/extract_f0_rmvpe.py', '2', '0', '0', 'C:\\ai\\RVC\\Retrieval-based-Voice-Conversion-WebUI/logs/k', 'True']
['infer/modules/train/extract/extract_f0_rmvpe.py', '2', '1', '0', 'C:\\ai\\RVC\\Retrieval-based-Voice-Conversion-WebUI/logs/k', 'True']
Traceback (most recent call last):
  File "C:\ai\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\modules\train\extract\extract_f0_rmvpe.py", line 118, in <module>
Traceback (most recent call last):
    for name in sorted(list(os.listdir(inp_root))):
  File "C:\ai\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\modules\train\extract\extract_f0_rmvpe.py", line 118, in <module>
FileNotFoundError: [WinError 3] A rendszer nem találja a megadott elérési utat: 'C:\\ai\\RVC\\Retrieval-based-Voice-Conversion-WebUI/logs/k/1_16k_wavs'
    for name in sorted(list(os.listdir(inp_root))):
FileNotFoundError: [WinError 3] A rendszer nem találja a megadott elérési utat: 'C:\\ai\\RVC\\Retrieval-based-Voice-Conversion-WebUI/logs/k/1_16k_wavs'
2023-11-16 18:09:07 | INFO | __main__ | ['infer/modules/train/extract/extract_f0_rmvpe.py', '2', '0', '0', 'C:\\ai\\RVC\\Retrieval-based-Voice-Conversion-WebUI/logs/k', 'True']
['infer/modules/train/extract/extract_f0_rmvpe.py', '2', '1', '0', 'C:\\ai\\RVC\\Retrieval-based-Voice-Conversion-WebUI/logs/k', 'True']

2023-11-16 18:09:07 | INFO | __main__ | "python.exe" infer/modules/train/extract_feature_print.py cuda:0 1 0 0 "C:\ai\RVC\Retrieval-based-Voice-Conversion-WebUI/logs/k" v2
['infer/modules/train/extract_feature_print.py', 'cuda:0', '1', '0', '0', 'C:\\ai\\RVC\\Retrieval-based-Voice-Conversion-WebUI/logs/k', 'v2']
C:\ai\RVC\Retrieval-based-Voice-Conversion-WebUI/logs/k
load model(s) from assets/hubert/hubert_base.pt
2023-11-16 18:09:09 | INFO | fairseq.tasks.hubert_pretraining | current directory is C:\ai\RVC\Retrieval-based-Voice-Conversion-WebUI
2023-11-16 18:09:09 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-11-16 18:09:09 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
C:\Users\vanko\anaconda3\envs\rvc-webui\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
move model to cuda
Traceback (most recent call last):
  File "C:\ai\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\modules\train\extract_feature_print.py", line 98, in <module>
    todo = sorted(list(os.listdir(wavPath)))[i_part::n_part]
FileNotFoundError: [WinError 3] A rendszer nem találja a megadott elérési utat: 'C:\\ai\\RVC\\Retrieval-based-Voice-Conversion-WebUI/logs/k/1_16k_wavs'
2023-11-16 18:09:11 | INFO | __main__ | ['infer/modules/train/extract/extract_f0_rmvpe.py', '2', '0', '0', 'C:\\ai\\RVC\\Retrieval-based-Voice-Conversion-WebUI/logs/k', 'True']
['infer/modules/train/extract/extract_f0_rmvpe.py', '2', '1', '0', 'C:\\ai\\RVC\\Retrieval-based-Voice-Conversion-WebUI/logs/k', 'True']
['infer/modules/train/extract_feature_print.py', 'cuda:0', '1', '0', '0', 'C:\\ai\\RVC\\Retrieval-based-Voice-Conversion-WebUI/logs/k', 'v2']
C:\ai\RVC\Retrieval-based-Voice-Conversion-WebUI/logs/k
load model(s) from assets/hubert/hubert_base.pt
move model to cuda

2023-11-16 18:09:11 | INFO | httpx | HTTP Request: POST http://localhost:7897/api/predict "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "C:\Users\vanko\anaconda3\envs\rvc-webui\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\vanko\anaconda3\envs\rvc-webui\lib\site-packages\gradio\blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "C:\Users\vanko\anaconda3\envs\rvc-webui\lib\site-packages\gradio\blocks.py", line 1090, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\vanko\anaconda3\envs\rvc-webui\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\vanko\anaconda3\envs\rvc-webui\lib\site-packages\gradio\utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\vanko\anaconda3\envs\rvc-webui\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\vanko\anaconda3\envs\rvc-webui\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "C:\Users\vanko\anaconda3\envs\rvc-webui\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "C:\Users\vanko\anaconda3\envs\rvc-webui\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "C:\ai\RVC\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 721, in train1key
    click_train(
  File "C:\ai\RVC\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 477, in click_train
    set([name.split(".")[0] for name in os.listdir(gt_wavs_dir)])
FileNotFoundError: [WinError 3] A rendszer nem találja a megadott elérési utat: 'C:\\ai\\RVC\\Retrieval-based-Voice-Conversion-WebUI/logs/k/0_gt_wavs'
2023-11-16 18:09:11 | INFO | httpx | HTTP Request: POST http://localhost:7897/api/predict "HTTP/1.1 500 Internal Server Error"
2023-11-16 18:09:11 | INFO | httpx | HTTP Request: POST http://localhost:7897/reset "HTTP/1.1 200 OK"

I've been encountering this error since yesterday and I don't know what the solution would be, I updated the program,
the pc: win11
gpu 4060 Ti 16 gb

**Comment by Cryptofan83** [comment]
I found out what's wrong, it's not enough to just specify the directory for the path, you need the file.
