### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by MohammedAlkhatib1011** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1561]
Traceback (most recent call last):
  File "C:\Users\goodm\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\goodm\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\goodm\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 180, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "C:\Users\goodm\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "C:\Users\goodm\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\goodm\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\goodm\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\goodm\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\goodm\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\goodm\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
i tried million thing to fix this issue but nothing worked, i even trying other pc with diff OS.

**Comment by rgwan1314** [comment]
I have the same issue as you

**Comment by dvdcjw** [comment]
SAME
