### ISSUE TITLE
Vocals/Accompaniment Separation Issue

### ISSUE THREAD

**Issue by xxrraa** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1563]
Hi there thanks to all involved for this amazing release!  Originally was using the version of this code from July, downloaded the new code (Today) in order to use the most updated version and getting some issues with Vocals/Accompaniment Separation that I wasn't getting w the old version.  I get no output whatsoever and it seems like it's something related to the TEMP files but I could be wrong.  I am on Ubuntu 20.04.6 LTS.  I am using conda with python 3.9.7, I installed to my conda env - torch, torch audio, torchvision with pip as directed from the "started locally" url, then the requirements using pip.  Someone else in the last 1-2 months posted the same issue with no response I'm assuming because they didn't provide enough info, and I couldn't find anyone else with the same issue, if my searching skills were lacklustre and there is a posted solution I apologize

**Here is the output from terminal**
Also, i checked conda list and ffmpeg is installed as listed in the requirements.txt

`Traceback (most recent call last):
  File "/home/andrew/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/infer/modules/uvr5/modules.py", line 49, in uvr
    info = ffmpeg.probe(inp_path, cmd="ffprobe")
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/ffmpeg/_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'
sh: 1: ffmpeg: not found
`

**Here is output from the "output information" on the webUI**

```
k1.wav.reformatted.wav->Traceback (most recent call last):
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/librosa/core/audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening '/home/andrew/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/TEMP/k1.wav.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrew/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/infer/modules/uvr5/modules.py", line 74, in uvr
    pre_fun._path_audio_(
  File "/home/andrew/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/infer/modules/uvr5/vr.py", line 63, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/librosa/util/decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/librosa/core/audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/librosa/core/audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/audioread/__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/audioread/rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/andrew/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/TEMP/k1.wav.reformatted.wav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/librosa/core/audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening '/home/andrew/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/TEMP/k1.wav.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrew/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/infer/modules/uvr5/modules.py", line 82, in uvr
    pre_fun._path_audio_(
  File "/home/andrew/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/infer/modules/uvr5/vr.py", line 63, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/librosa/util/decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/librosa/core/audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/librosa/core/audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/audioread/__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "/home/andrew/anaconda3/envs/rvcv7/lib/python3.9/site-packages/audioread/rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/andrew/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/TEMP/k1.wav.reformatted.wav'
```

Thank you in advance

**Comment by xxrraa** [comment]
Solved the issue after lots of troubleshooting
It was an issue with the ffmpeg-python from pip, I had to use the ffmpeg-python from conda
`conda install -c conda-forge ffmpeg-python`

**Comment by xxrraa** [comment]
Solved the issue after lots of troubleshooting
It was an issue with the ffmpeg-python from pip, I had to use the ffmpeg-python from conda
`conda install -c conda-forge ffmpeg-python`
