### ISSUE TITLE
"torch.distributed.DistNetworkError: Unknown error" when attempting training

### ISSUE THREAD

**Issue by T0biasCZe** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1564]
I inserted the path of my data, set target sample to 40k, disabled pitch, and processed data and extracted features.
But, when i then start training, it throws pytorch error "Unknown error"        
whole log:        
```
start preprocess
['infer/modules/train/preprocess.py', 'C:\\Users\\user\\Documents\\HisVOICE\\in', '40000', '10', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'False', '3.0']
2023-11-20 02:09:55 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
['D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main\\infer\\modules\\train\\preprocess.py', 'C:\\Users\\user\\Documents\\HisVOICE\\in', '40000', '10', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'False', '3.0']
['D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main\\infer\\modules\\train\\preprocess.py', 'C:\\Users\\user\\Documents\\HisVOICE\\in', '40000', '10', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'False', '3.0']
['D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main\\infer\\modules\\train\\preprocess.py', 'C:\\Users\\user\\Documents\\HisVOICE\\in', '40000', '10', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'False', '3.0']
['D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main\\infer\\modules\\train\\preprocess.py', 'C:\\Users\\user\\Documents\\HisVOICE\\in', '40000', '10', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'False', '3.0']
['D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main\\infer\\modules\\train\\preprocess.py', 'C:\\Users\\user\\Documents\\HisVOICE\\in', '40000', '10', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'False', '3.0']
['D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main\\infer\\modules\\train\\preprocess.py', 'C:\\Users\\user\\Documents\\HisVOICE\\in', '40000', '10', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'False', '3.0']
['D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main\\infer\\modules\\train\\preprocess.py', 'C:\\Users\\user\\Documents\\HisVOICE\\in', '40000', '10', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'False', '3.0']
['D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main\\infer\\modules\\train\\preprocess.py', 'C:\\Users\\user\\Documents\\HisVOICE\\in', '40000', '10', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'False', '3.0']
['D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main\\infer\\modules\\train\\preprocess.py', 'C:\\Users\\user\\Documents\\HisVOICE\\in', '40000', '10', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'False', '3.0']
['D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main\\infer\\modules\\train\\preprocess.py', 'C:\\Users\\user\\Documents\\HisVOICE\\in', '40000', '10', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'False', '3.0']
2023-11-20 02:09:56 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:09:57 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:09:58 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:09:59 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:10:00 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
C:\Users\user\Documents\HisVOICE\in/Mimoradne hlaseni zastavka u brna.mp3->Suc.
2023-11-20 02:10:01 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
C:\Users\user\Documents\HisVOICE\in/hlaseni karlstejn.mp3->Suc.
C:\Users\user\Documents\HisVOICE\in/hlaseni his nezamyslice os 3728.mp3->Suc.
2023-11-20 02:10:02 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:10:03 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
C:\Users\user\Documents\HisVOICE\in/hlaseni hvezdonice HIS prijel.mp3->Suc.
C:\Users\user\Documents\HisVOICE\in/LocoMania hlaseni.mp3->Suc.
2023-11-20 02:10:04 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
C:\Users\user\Documents\HisVOICE\in/hlaseni lysa nad labem VISL.mp3->Suc.
2023-11-20 02:10:05 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:10:06 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
C:\Users\user\Documents\HisVOICE\in/hlaseni roudnice nad labem VISL.mp3->Suc.
end preprocess
2023-11-20 02:10:07 | INFO | __main__ | start preprocess
['infer/modules/train/preprocess.py', 'C:\\Users\\user\\Documents\\HisVOICE\\in', '40000', '10', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'False', '3.0']
C:\Users\user\Documents\HisVOICE\in/Mimoradne hlaseni zastavka u brna.mp3->Suc.
C:\Users\user\Documents\HisVOICE\in/hlaseni karlstejn.mp3->Suc.
C:\Users\user\Documents\HisVOICE\in/hlaseni his nezamyslice os 3728.mp3->Suc.
C:\Users\user\Documents\HisVOICE\in/hlaseni hvezdonice HIS prijel.mp3->Suc.
C:\Users\user\Documents\HisVOICE\in/LocoMania hlaseni.mp3->Suc.
C:\Users\user\Documents\HisVOICE\in/hlaseni lysa nad labem VISL.mp3->Suc.
C:\Users\user\Documents\HisVOICE\in/hlaseni roudnice nad labem VISL.mp3->Suc.
end preprocess

2023-11-20 02:10:07 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:10:07 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:10:07 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK"
2023-11-20 02:10:26 | INFO | __main__ | "C:\Python310\python.exe" infer/modules/train/extract_feature_print.py cuda:0 1 0 0 "D:\Oculus\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice" v2
2023-11-20 02:10:26 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:10:27 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:10:28 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:10:29 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:10:30 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
['infer/modules/train/extract_feature_print.py', 'cuda:0', '1', '0', '0', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'v2']
D:\Oculus\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice
load model(s) from assets/hubert/hubert_base.pt
2023-11-20 02:10:30 | INFO | fairseq.tasks.hubert_pretraining | current directory is D:\Oculus\Retrieval-based-Voice-Conversion-WebUI-main
2023-11-20 02:10:30 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-11-20 02:10:30 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
C:\Python310\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
2023-11-20 02:10:31 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:10:32 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
move model to cuda
all-feature-205
all-feature-done
2023-11-20 02:10:33 | INFO | __main__ | ['infer/modules/train/extract_feature_print.py', 'cuda:0', '1', '0', '0', 'D:\\Oculus\\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice', 'v2']
D:\Oculus\Retrieval-based-Voice-Conversion-WebUI-main/logs/vaclavknop_hisvoice
load model(s) from assets/hubert/hubert_base.pt
move model to cuda
all-feature-205
all-feature-done

2023-11-20 02:10:33 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:10:33 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-20 02:10:33 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK"
2023-11-20 02:11:35 | INFO | __main__ | Use gpus: 0
2023-11-20 02:11:35 | INFO | __main__ | "C:\Python310\python.exe" infer/modules/train/train.py -e "vaclavknop_hisvoice" -sr 40k -f0 0 -bs 6 -g 0 -te 20 -se 5 -pg assets/pretrained_v2/G40k.pth -pd assets/pretrained_v2/D40k.pth -l 0 -c 1 -sw 0 -v v2
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
INFO:vaclavknop_hisvoice:{'data': {'filter_length': 2048, 'hop_length': 400, 'max_wav_value': 32768.0, 'mel_fmax': None, 'mel_fmin': 0.0, 'n_mel_channels': 125, 'sampling_rate': 40000, 'win_length': 2048, 'training_files': './logs\\vaclavknop_hisvoice/filelist.txt'}, 'model': {'filter_channels': 768, 'gin_channels': 256, 'hidden_channels': 192, 'inter_channels': 192, 'kernel_size': 3, 'n_heads': 2, 'n_layers': 6, 'p_dropout': 0, 'resblock': '1', 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'resblock_kernel_sizes': [3, 7, 11], 'spk_embed_dim': 109, 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'upsample_rates': [10, 10, 2, 2], 'use_spectral_norm': False}, 'train': {'batch_size': 6, 'betas': [0.8, 0.99], 'c_kl': 1.0, 'c_mel': 45, 'epochs': 20000, 'eps': 1e-09, 'fp16_run': True, 'init_lr_ratio': 1, 'learning_rate': 0.0001, 'log_interval': 200, 'lr_decay': 0.999875, 'seed': 1234, 'segment_size': 12800, 'warmup_epochs': 0}, 'model_dir': './logs\\vaclavknop_hisvoice', 'experiment_dir': './logs\\vaclavknop_hisvoice', 'save_every_epoch': 5, 'name': 'vaclavknop_hisvoice', 'total_epoch': 20, 'pretrainG': 'assets/pretrained_v2/G40k.pth', 'pretrainD': 'assets/pretrained_v2/D40k.pth', 'version': 'v2', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 0, 'if_latest': 0, 'save_every_weights': '0', 'if_cache_data_in_gpu': 1}
Process Process-1:
Traceback (most recent call last):
  File "C:\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Oculus\Retrieval-based-Voice-Conversion-WebUI-main\infer\modules\train\train.py", line 132, in run
    dist.init_process_group(
  File "C:\Python310\lib\site-packages\torch\distributed\c10d_logger.py", line 86, in wrapper
    func_return = func(*args, **kwargs)
  File "C:\Python310\lib\site-packages\torch\distributed\distributed_c10d.py", line 1176, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "C:\Python310\lib\site-packages\torch\distributed\rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "C:\Python310\lib\site-packages\torch\distributed\rendezvous.py", line 174, in _create_c10d_store
    return TCPStore(
torch.distributed.DistNetworkError: Unknown error
```
system: windows 10 64bit     
RVC version: latest (commit ff093ad)        
GPU: Nvidia RTX 3060 12GB

**Comment by JD-2006** [comment]
If you are using only one gpu check/change all 3 spots that reference which gpu to use and put only 0.
I even change to use rvmpe instead of rvmpe-gpu.

**Comment by T0biasCZe** [comment]
I already have "0" inside all the columns for which GPU use...

**Comment by PedroSophiaaa** [comment]
> I already have "0" inside all the columns for which GPU use...

Hello T0bias, did to found a solution?

**Comment by T0biasCZe** [comment]
no :(

**Comment by PedroSophiaaa** [comment]
> no :(

Hey T0bias, I also wrote an issue (basically I copied yours but with my log), I received an answer that worked for me, they suggested I use an AI browser called Pinokio, it might work for you.
[Check my post.](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1622)

**Comment by Noctropolitan** [comment]
I'm having the same issue, I tried reinstalling everything and nothing works.
Also the Pinokio version is severely limited, you can't train models in rmvpe for some reason.

**Comment by dillfrescott** [comment]
Same issue on dev branch sadly, everything is a fresh install too...

**Comment by dillfrescott** [comment]
Figured it out. Version Pytorch version `2.2.0` introduces a breaking change, and RVC hasnt addressed the change yet. So just use a slightly older version of pytorch for now. A list can be found [here](https://pytorch.org/get-started/previous-versions/). I recommend version `2.1.2` as this is working and only one version behind 2.2.0.

**Comment by Mantinum** [comment]
Hello, I am experiencing the same issue on Windows with Pinokio. I saw that it is necessary to change the Pytorch version, but is it possible with Pinokio?
Thx.

**Comment by trivikramak** [comment]
@Mantinum Did you find any solution for Pinokio?

**Comment by Fenrirdub** [comment]
> Figured it out. Pytorch version `2.2.0` introduces a breaking change, and RVC hasnt addressed the change yet. So just use a slightly older version of pytorch for now. A list can be found [here](https://pytorch.org/get-started/previous-versions/). I recommend version `2.1.2` as this is working and only one version behind 2.2.0.

Work for me !! thanks bro ! 💯

**Comment by Mantinum** [comment]
> @MantinumAvez-vous trouvé une solution pour Pinokio ?

No, for RVC, now I use the 'compact'. https://github.com/WadRex/RVCompact
