### ISSUE TITLE
AttributeError: 'RVC' object has no attribute 'tgt_sr'

### ISSUE THREAD

**Issue by Blueqvq** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1568]
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\RVC-beta0717\RVC-beta0717\gui_v1.py", line 502, in <module>
    gui = GUI()
  File "D:\BaiduNetdiskDownload\RVC-beta0717\RVC-beta0717\gui_v1.py", line 74, in __init__
    self.launcher()
  File "D:\BaiduNetdiskDownload\RVC-beta0717\RVC-beta0717\gui_v1.py", line 260, in launcher
    self.event_handler()
  File "D:\BaiduNetdiskDownload\RVC-beta0717\RVC-beta0717\gui_v1.py", line 271, in event_handler
    self.start_vc()
  File "D:\BaiduNetdiskDownload\RVC-beta0717\RVC-beta0717\gui_v1.py", line 330, in start_vc
    self.config.samplerate=self.rvc.tgt_sr
AttributeError: 'RVC' object has no attribute 'tgt_sr'

**Comment by THE-SINDOL** [comment]
please don't use beta release, there are new one here : 
For Nvidia GPU users:
https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006Nvidia.7z

For AMD/Intel GPU users:
https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006AMD_Intel.7z

for start UI : go-web.bat
