### ISSUE TITLE
RuntimeError: could not create a primitive descriptor for a matmul primitive in docker

### ISSUE THREAD

**Issue by hkhking** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1571]
2023-11-23 02:48:34 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "/var/www/Retrieval-based-Voice-Conversion-WebUI/infer/modules/vc/modules.py", line 186, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "/var/www/Retrieval-based-Voice-Conversion-WebUI/infer/modules/vc/pipeline.py", line 375, in pipeline
    self.vc(
  File "/var/www/Retrieval-based-Voice-Conversion-WebUI/infer/modules/vc/pipeline.py", line 271, in vc
    audio1 = (net_g.infer(*arg)[0][0, 0]).data.cpu().float().numpy()
  File "/var/www/Retrieval-based-Voice-Conversion-WebUI/infer/lib/infer_pack/models.py", line 955, in infer
    o = self.dec(z * x_mask, nsff0, g=g)
  File "/var/www/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/var/www/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/var/www/Retrieval-based-Voice-Conversion-WebUI/infer/lib/infer_pack/models.py", line 572, in forward
    har_source, noi_source, uv = self.m_source(f0, self.upp)
  File "/var/www/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/var/www/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/var/www/Retrieval-based-Voice-Conversion-WebUI/infer/lib/infer_pack/models.py", line 493, in forward
    sine_merge = self.l_tanh(self.l_linear(sine_wavs))
  File "/var/www/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/var/www/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/var/www/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: could not create a primitive descriptor for a matmul primitive

I try to docker run infer, get this error. plz help

**Comment by benthompson29** [comment]
Just ran into the same problem. This portion of the output is the same for me:

File "/var/www/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/var/www/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "/var/www/Retrieval-based-Voice-Conversion-WebUI/.venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
return F.linear(input, self.weight, self.bias)
RuntimeError: could not create a primitive descriptor for a matmul primitive
