### ISSUE TITLE
Anyone got a clue on how to fix this? AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by billy7097** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1580]
File "C:\Users\rodan\Downloads\RVC\RVC1006AMD_Intel\infer\modules\vc\modules.py", line 185, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "C:\Users\rodan\Downloads\RVC\RVC1006AMD_Intel\infer\modules\vc\pipeline.py", line 375, in pipeline
    self.vc(
  File "C:\Users\rodan\Downloads\RVC\RVC1006AMD_Intel\infer\modules\vc\pipeline.py", line 221, in vc
    if protect < 0.5 and pitch is not None and pitchf is not None:
TypeError: '<' not supported between instances of 'dict' and 'float'

Traceback (most recent call last):
  File "C:\Users\rodan\Downloads\RVC\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\rodan\Downloads\RVC\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\rodan\Downloads\RVC\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\rodan\Downloads\RVC\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\rodan\Downloads\RVC\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\rodan\Downloads\RVC\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by luwen666666** [comment]
我是用的1006AMD，如果推理超过十几秒的话也会报错，和上面一样，只能推理几十秒短的音频，不知道有没有知道的个解释一下。
