### ISSUE TITLE
RuntimeError: You input a wrong audio path that does not exists, please fix it!

### ISSUE THREAD

**Issue by wrl1224** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1603]
2023-12-09 18:31:49 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "D:\Retrieval-based-Voice-Conversion-WebUI-main\infer\modules\vc\modules.py", line 163, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "D:\Retrieval-based-Voice-Conversion-WebUI-main\infer\lib\audio.py", line 57, in load_audio
    raise RuntimeError(
RuntimeError: You input a wrong audio path that does not exists, please fix it!

Traceback (most recent call last):
  File "D:\anaconda3\envs\RVC\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\anaconda3\envs\RVC\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\anaconda3\envs\RVC\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\anaconda3\envs\RVC\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "D:\anaconda3\envs\RVC\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

路径我检查过了没问题，也按照代码要求上传了16000采样率的wav，不知道什么问题请求一下帮助。

**Comment by wrl1224** [comment]
目前我正在操作WebUi界面的推理功能

**Comment by SnowTung999** [comment]
i am same also not work

**Comment by Chen-Ed** [comment]
我无论是单次推理还是批量推理（使用完整包自带的模型）也遇到同样的情况。我使用过很多次不同路径（包括在硬盘根目录）都是出现说路径报错

- Windows环境下，使用git上下载的完整包版本RVC1006AMD_Intel.zip

以下是错误：
F:\RVC1006AMD_Intel>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897 --dml
2023-12-24 13:02:05 | INFO | configs.config | No supported Nvidia GPU found
overwrite preprocess and configs.json
2023-12-24 13:02:05 | INFO | configs.config | Use DirectML instead
is_half:False, device:privateuseone:0
2023-12-24 13:02:12 | INFO | __main__ | Use Language: zh_CN
Running on local URL:  http://0.0.0.0:7897
2023-12-24 13:02:54 | INFO | infer.modules.vc.modules | Get sid: youzhanv2-xi.pth
2023-12-24 13:02:54 | INFO | infer.modules.vc.modules | Loading: assets/weights/youzhanv2-xi.pth
2023-12-24 13:02:54 | INFO | infer.modules.vc.modules | Select index:
2023-12-24 13:03:20 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "F:\RVC1006AMD_Intel\infer\modules\vc\modules.py", line 163, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "F:\RVC1006AMD_Intel\infer\lib\audio.py", line 57, in load_audio
    raise RuntimeError(
RuntimeError: You input a wrong audio path that does not exists, please fix it!

Traceback (most recent call last):
  File "F:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "F:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "F:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "F:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "F:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by Chen-Ed** [comment]
> 我无论是单次推理还是批量推理（使用完整包自带的模型）也遇到同样的情况。我使用过很多次不同路径（包括在硬盘根目录）都是出现说路径报错
> 
> * Windows环境下，使用git上下载的完整包版本RVC1006AMD_Intel.zip
> 
> 以下是错误： F:\RVC1006AMD_Intel>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897 --dml 2023-12-24 13:02:05 | INFO | configs.config | No supported Nvidia GPU found overwrite preprocess and configs.json 2023-12-24 13:02:05 | INFO | configs.config | Use DirectML instead is_half:False, device:privateuseone:0 2023-12-24 13:02:12 | INFO | **main** | Use Language: zh_CN Running on local URL: http://0.0.0.0:7897 2023-12-24 13:02:54 | INFO | infer.modules.vc.modules | Get sid: youzhanv2-xi.pth 2023-12-24 13:02:54 | INFO | infer.modules.vc.modules | Loading: assets/weights/youzhanv2-xi.pth 2023-12-24 13:02:54 | INFO | infer.modules.vc.modules | Select index: 2023-12-24 13:03:20 | WARNING | infer.modules.vc.modules | Traceback (most recent call last): File "F:\RVC1006AMD_Intel\infer\modules\vc\modules.py", line 163, in vc_single audio = load_audio(input_audio_path, 16000) File "F:\RVC1006AMD_Intel\infer\lib\audio.py", line 57, in load_audio raise RuntimeError( RuntimeError: You input a wrong audio path that does not exists, please fix it!
> 
> Traceback (most recent call last): File "F:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict output = await app.blocks.process_api( File "F:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api data = self.postprocess_data(fn_index, result["prediction"], state) File "F:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data prediction_value = block.postprocess(prediction_value) File "F:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess processing_utils.audio_to_file(sample_rate, data, file.name) File "F:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file data = convert_to_16_bit_wav(data) File "F:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav if data.dtype in [np.float64, np.float32, np.float16]: AttributeError: 'NoneType' object has no attribute 'dtype'

我在ling另一个issue（https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/529）找到了答案，似乎是字符串处理的问题或者说webUI的提示不够完善。
正确做法是需要在路径上 添加双引号
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/53363383/7cc4d473-cc16-4394-926c-72bf4ed92800)

**Comment by RVC-Boss** [comment]
你填错路径了。不过现在不用填了，更新到最新的main分支，直接把音频拖到前端就行。
