### ISSUE TITLE
OSError: AF_UNIX path too long

### ISSUE THREAD

**Issue by Yaodada12** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#165]
老是报这个错，不管是用webui跑，还是把各个模块剥离到本地python文件去跑，都报这个错。。
```
INFO:O:{'train': {'log_interval': 200, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 12800, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 40000, 'filter_length': 2048, 'hop_length': 400, 'win_length': 2048, 'n_mel_channels': 125, 'mel_fmin': 0.0, 'mel_fmax': None, 'training_files': './logs/O/filelist.txt'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 10, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'use_spectral_norm': False, 'gin_channels': 256, 'spk_embed_dim': 109}, 'model_dir': './logs/O', 'experiment_dir': './logs/O', 'save_every_epoch': 5, 'name': 'O', 'total_epoch': 20, 'pretrainG': 'pretrained/f0G40k.pth', 'pretrainD': 'pretrained/f0D40k.pth', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 1, 'if_latest': 0, 'if_cache_data_in_gpu': 1}
WARNING:O:/home/user/Desktop/yao/projects/VC/Retrieval-based-Voice-Conversion-WebUI/train is not a git repository, therefore hash value comparison will be ignored.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
gin_channels: 256 self.spk_embed_dim: 109
Traceback (most recent call last):
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 359, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/resource_sharer.py", line 77, in register
    self._start()
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/resource_sharer.py", line 130, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/user/Software/Anaconda/envs/dl_vc/lib/python3.8/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
```

**Comment by RVC-Boss** [comment]
看看你的path是啥？

**Comment by Yaodada12** [comment]
> 看看你的path是啥？

哪个path。。

**Comment by Yaodada12** [comment]
> 看看你的path是啥？

我把文件https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/train_nsf_sim_cache_sid_load_pretrain.py中的两行代码删掉，如下图。再改代码里for epoch in range(epoch_str, hps.train.epochs + 1)的hps.train.epochs为hps.total_epoch + 1就可以了。

**Comment by Uio96** [comment]
> > 看看你的path是啥？
> 
> 我把文件[https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/train_nsf_sim_cache_sid_load_pretrain.py中的两行代码删掉，如下图。再改代码里for](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/train_nsf_sim_cache_sid_load_pretrain.py%E4%B8%AD%E7%9A%84%E4%B8%A4%E8%A1%8C%E4%BB%A3%E7%A0%81%E5%88%A0%E6%8E%89%EF%BC%8C%E5%A6%82%E4%B8%8B%E5%9B%BE%E3%80%82%E5%86%8D%E6%94%B9%E4%BB%A3%E7%A0%81%E9%87%8Cfor) epoch in range(epoch_str, hps.train.epochs + 1)的hps.train.epochs为hps.total_epoch + 1就可以了。 ![2023-04-27 10-44-59屏幕截图](https://user-images.githubusercontent.com/107554614/234747447-f9c1db99-9406-45bf-bbce-9e8f0469a4bf.png)

It does not work for me. I have to move the folder somewhere else, which shortens the length of the path.

**Comment by titusfx** [comment]
Hi guys I had the same error, and I fix it:
Just add this in the second line of  infer/modules/train/train.py file

os.environ["TMPDIR"] = "/tmp"


you file will be something like this now:

import os
os.environ["TMPDIR"] = "/tmp"
import sys
import logging

logger = logging.getLogger(__name__)

now_dir = os.getcwd()
sys.path.append(os.path.join(now_dir))

import datetime




################ The explanation of the problem
## OSError: AF_UNIX path too long when using multiprocessing

### Description

When running the script using multiprocessing, I encounter the following error:

OSError: AF_UNIX path too long



### Details

The error traceback indicates that the path for a Unix domain socket exceeds the system's maximum allowable length, causing the `OSError`. This issue seems to occur during the initialization of the multiprocessing environment.

### Steps to Reproduce

1. Run the provided script with multiprocessing enabled.
2. Ensure that the working directory or any related paths are sufficiently long to trigger the error.

### Environment

- **Python Version:** 3.10
- **Libraries Involved:** `torch`, `multiprocessing`, `intel_extension_for_pytorch` (if applicable)
- **Operating System:** [Your Operating System Here]

### Relevant Code

Here is a snippet of the code where the error occurs:

```python
import os
os.environ["TMPDIR"] = "/tmp"  # Attempt to resolve the issue with a shorter path
import sys
import logging

logger = logging.getLogger(__name__)

now_dir = os.getcwd()
sys.path.append(os.path.join(now_dir))

import datetime

from infer.lib.train import utils

hps = utils.get_hparams()
os.environ["CUDA_VISIBLE_DEVICES"] = hps.gpus.replace("-", ",")
n_gpus = len(hps.gpus.split("-"))
from random import randint, shuffle

import torch
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import DataLoader

Proposed Solution
Setting the TMPDIR environment variable to a shorter path (e.g., /tmp) appears to mitigate the issue for temporary files and sockets. However, if other parts of the script or dependencies create long paths, further adjustments might be needed.

Request for Assistance
I'm looking for guidance on:

Ensuring the TMPDIR environment variable is respected by all parts of the script and its dependencies.
Identifying any additional configurations or settings within the script or libraries that could help resolve the issue.
Any help or pointers on this issue would be greatly appreciated!
