### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by rutvik106** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1666]
Happens when I click on "Train Model" Button on my MacBook M1 Pro (MacOS: Sonoma 14.1.2 (23B92))

Following are the LOGS

2023-12-30 00:36:15 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/Users/rutvikmehta/PycharmProjects/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/rutvikmehta/PycharmProjects/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "/Users/rutvikmehta/PycharmProjects/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1090, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/rutvikmehta/PycharmProjects/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "/Users/rutvikmehta/PycharmProjects/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/rutvikmehta/PycharmProjects/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/rutvikmehta/PycharmProjects/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/Users/rutvikmehta/PycharmProjects/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/Users/rutvikmehta/PycharmProjects/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "/Users/rutvikmehta/PycharmProjects/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 721, in train1key
    click_train(
  File "/Users/rutvikmehta/PycharmProjects/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 479, in click_train
    & set([name.split(".")[0] for name in os.listdir(f0_dir)])
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rutvikmehta/PycharmProjects/Retrieval-based-Voice-Conversion-WebUI/logs/wiz/2a_f0'
2023-12-30 00:36:15 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 500 Internal Server Error"
2023-12-30 00:36:15 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK"

**Comment by ADR3-N** [comment]
I had this same issue earlier, but in Colab. It only resolved after a careful reinstall, doing each step in order, one at the time. Hopefully this is not the same case for you, but when in doubt, try it.

**Comment by rutvik106** [comment]
> I had this same issue earlier, but in Colab. It only resolved after a careful reinstall, doing each step in order, one at the time. Hopefully this is not the same case for you, but when in doubt, try it.

Yeah thanks I forgot to run "brew install ffmpeg"

one more thing I was running the app via "python infer-web.py" but now when I ran it using "sh ./run.sh" it works.

Thanks.

**Comment by iamzhangyunlu** [comment]
@rutvik106 hi there, same issue happens here. I already run "brew install ffmpeg" and problem not solved, and I ran with "python infer-web.py" too.

I don't understand use "sh ./run.sh" will work,     "sh ./run.sh"  will let me download those trained models but not start the project and downloading models here will always timeout

what should I do, please?
