### ISSUE TITLE
Incompatible with python 3.11

### ISSUE THREAD

**Issue by TheYellowArchitect** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1672]
```
Collecting numba==0.56.4 (from -r requirements.txt (line 2))
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_i7d1l_k/numba_345449b5e3294882a76589690cdf3a88/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-_i7d1l_k/numba_345449b5e3294882a76589690cdf3a88/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.6; only versions >=3.7,<3.11 are supported.
      [end of output]
Collecting numba==0.56.4 (from -r requirements.txt (line 2))
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_i7d1l_k/numba_345449b5e3294882a76589690cdf3a88/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-_i7d1l_k/numba_345449b5e3294882a76589690cdf3a88/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.6; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
This problem also exists with faiss-gpu. My suggestion is to make it simply compatible, or exit early with an error message. Here is even a better suggestion https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1461

**Comment by ms903x1** [comment]
Due to some requirements packages requiring Python<3.11, Python versions 3.10 and above are currently not supported.

**Comment by TheYellowArchitect** [comment]
Sad, but understandable.
