### ISSUE TITLE
python download_models.py can't work 

### ISSUE THREAD

**Issue by somewheve** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1674]
try  to download model. 
```
python download_models.py 
```

but got output 
```
Downloading hubert_base.pt...
Traceback (most recent call last):
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000297CD9D0130>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /lj1995/VoiceConversionWebUI/resolve/main/hubert_base.pt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000297CD9D0130>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\somew\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\tools\download_models.py", line 21, in <module>
    dl_model(RVC_DOWNLOAD_LINK, "hubert_base.pt", BASE_DIR / "assets/hubert")
  File "C:\Users\somew\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\tools\download_models.py", line 11, in dl_model
    with requests.get(f"{link}{model_name}") as r:
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\somew\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /lj1995/VoiceConversionWebUI/resolve/main/hubert_base.pt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000297CD9D0130>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
```

and [https://huggingface.co/](https://huggingface.co/) can't be visited，

**Comment by THE-SINDOL** [comment]
Tested on python 3.10.6 and venv on windows 10 pro, and works fine : 

git clone https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI.git
cd Retrieval-based-Voice-Conversion-WebUI
python -m venv venv
venv\Scripts\activate.bat
pip install -r requirements.txt
cd tools
(venv) H:\RVC-SVC-NEWS-2024\Retrieval-based-Voice-Conversion-WebUI\tools>python download_models.py

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/144182156/b2da9531-be01-45b3-abc0-e8ab7228a89b)

**Comment by DaBaiTuu** [comment]
确实，抱脸上不去，有替代方案么

**Comment by somewheve** [comment]
it works now.
