### ISSUE TITLE
Apple M1 issue in training model

### ISSUE THREAD

**Issue by orbenda83** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1701]
Hi,

I am running  on macos with M1 processor.
The "train feature index" does nothing and then the training fail.

When I run "One-click training" I get the following error.

Traceback (most recent call last):
  File "/Users/xxx/miniconda3/envs/rvcenv/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/xxx/miniconda3/envs/rvcenv/lib/python3.10/site-packages/gradio/blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "/Users/xxx/miniconda3/envs/rvcenv/lib/python3.10/site-packages/gradio/blocks.py", line 1090, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/xxx/miniconda3/envs/rvcenv/lib/python3.10/site-packages/gradio/utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "/Users/xxx/miniconda3/envs/rvcenv/lib/python3.10/site-packages/gradio/utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/xxx/miniconda3/envs/rvcenv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/xxx/miniconda3/envs/rvcenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/Users/xxx/miniconda3/envs/rvcenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/Users/xxx/miniconda3/envs/rvcenv/lib/python3.10/site-packages/gradio/utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "/Users/xxx/Documents/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 721, in train1key
    click_train(
  File "/Users/xxx/Documents/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 479, in click_train
    & set([name.split(".")[0] for name in os.listdir(f0_dir)])

Please assist.

**Comment by arbaz686** [comment]
The traceback indicates an issue with file operations, particularly related to directory paths and file lists. The error appears to occur here:

`& set([name.split(".")[0] for name in os.listdir(f0_dir)])`
