### ISSUE TITLE
使用window训练报错：torch.distributed.DistNetworkError: Unknown error

### ISSUE THREAD

**Issue by qihengzhw** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1728]
windows10系统，显卡nvidia rtx 2060 with max-q design
conda 4.5.11
cuda 11.7
torch                     2.3.0.dev20240109+cu118
torchaudio                2.2.0.dev20240110+cu118
torchvision               0.18.0.dev20240110+cu118
tornado                   6.4

执行torch.cuda.is_available()，返回true
执行torch.cuda.device_count()，返回为1
（说明有1个gpu可用）

按照教程 https://github.com/netease-youdao/EmotiVoice/tree/main/data/DataBaker 操作，一切顺利，可以进行正常推理

**执行微调模型命令**：
torchrun \
--nproc_per_node=1 \
--master_port 8008 \
train_am_vocoder_joint.py \
--config_folder exp/DataBaker/config \
--load_pretrained_model True

**出现如下报错**：

(EmotiVoice) F:\07_demo\EmotiVoice-train>torchrun --nproc_per_node=1 --master_port 8080 train_am_vocoder_joint.py --config_folder exp/DataBaker/config --load_pretrained_model True
[2024-01-16 09:39:47,305] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
[W socket.cpp:697] [c10d] The client socket has failed to connect to [LAPTOP-985BOILA]:8080 (system error: 10049 - 在其 上下文中，该请求的地址无效。).
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\site-packages\torch\distributed\run.py", line 812, in main
    run(args)
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\site-packages\torch\distributed\run.py", line 803, in run
    elastic_launch(
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\site-packages\torch\distributed\launcher\api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\site-packages\torch\distributed\launcher\api.py", line 259, in launch_agent
    result = agent.run()
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 727, in run
    result = self._invoke_run(role)
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 862, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 699, in _initialize_workers
    self._rendezvous(worker_group)
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 542, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "d:\ProgramData\Anaconda3\envs\EmotiVoice\lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
torch.distributed.DistNetworkError: Unknown error

请大佬们帮忙看下这个问题，感谢

**Comment by fumiama** [comment]
和本仓库无关。
