### ISSUE TITLE
After restart ubuntu, i can`t run anymore infer-web.py, why?

### ISSUE THREAD

**Issue by CGAlei** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1735]
Traceback (most recent call last):
  File "/home/nullsky/ai_enviroments/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 8, in <module>
    from infer.modules.vc.modules import VC
  File "/home/nullsky/ai_enviroments/Retrieval-based-Voice-Conversion-WebUI/infer/modules/vc/modules.py", line 7, in <module>
    import soundfile as sf
ModuleNotFoundError: No module named 'soundfile'
(base)

**Comment by rekvizitt** [comment]
You probably forgot to connect the virtual environment.
