### ISSUE TITLE
HELP \ AttributeError: 'NoneType' object has no attribute 'dtype' Error while converting in Model Inference

### ISSUE THREAD

**Issue by micspears** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1739]
I'm very new to RVC and wanted to experiment with making AI music covers of my favorite artists. I recently trained my first model (which I believe went well) so I tried testing it using model inference but with no success. Here's what I got:

C:\Users\marci\Downloads\RVC0813AMD_Intel\RVC0813AMD_Intel>runtime\python.exe` infer-web.py --pycmd runtime\python.exe --port 7897 --dml

No supported Nvidia GPU found
use DirectML instead
Use Language: en_US
loading weights/britneyglory_2_e200_s200.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
Traceback (most recent call last):
  File "C:\Users\marci\Downloads\RVC0813AMD_Intel\RVC0813AMD_Intel\infer-web.py", line 211, in vc_single
    audio_opt = vc.pipeline(
  File "C:\Users\marci\Downloads\RVC0813AMD_Intel\RVC0813AMD_Intel\vc_infer_pipeline.py", line 342, in pipeline
    sid = torch.tensor(sid, device=self.device).unsqueeze(0).long()
RuntimeError

Traceback (most recent call last):
  File "C:\Users\marci\Downloads\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\marci\Downloads\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\marci\Downloads\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\marci\Downloads\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\marci\Downloads\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\marci\Downloads\RVC0813AMD_Intel\RVC0813AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute `'dtype'

The issue is probably not related to my model since I tested it using another model on the Internet and got the same issue. The path of the audio file to be processed was correct. (C:\Users\marci\OneDrive\Documentos\Audio\DontSpeak.wav if anybody is curious). I was very excited to see the results so I appreciate any help!

**Comment by zhou20120904** [comment]
same
