### ISSUE TITLE
12.28补丁打开卡住，无法运行

### ISSUE THREAD

**Issue by ferretgeek** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1742]
在1006版本中运行正常，但是打上12.28补丁之后，无论如何都是出现以下报错，webUI又能正常打开
已按要求安装好所有requirements

PS F:\RVC1006Nvidia> python .\gui_v1.py
2024-01-19 10:14:41 | INFO | faiss.loader | Loading faiss with AVX2 support.
2024-01-19 10:14:41 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2024-01-19 10:14:41 | INFO | faiss.loader | Loading faiss.
2024-01-19 10:14:41 | INFO | faiss.loader | Successfully loaded faiss.
2024-01-19 10:14:41 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 3070 Ti
is_half:True, device:cuda:0
Traceback (most recent call last):
  File "F:\RVC1006Nvidia\gui_v1.py", line 148, in load
    data = json.load(j)
  File "C:\Users\Magic\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Magic\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Magic\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Magic\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\RVC1006Nvidia\gui_v1.py", line 956, in <module>
    gui = GUI()
  File "F:\RVC1006Nvidia\gui_v1.py", line 143, in __init__
    self.launcher()
  File "F:\RVC1006Nvidia\gui_v1.py", line 190, in launcher
    data = self.load()
  File "F:\RVC1006Nvidia\gui_v1.py", line 165, in load
    "sg_input_device": self.input_devices[self.input_devices_indices.index(sd.default.device[0])],
ValueError: -1 is not in list

**Comment by ferretgeek** [comment]
> 检查一下系统是否有录音设备，或者类似voicemeeter之类的虚拟设备有没有正确安装

好的谢谢，没想到最新版本添加了这个检查机制

**Comment by cooper1x** [comment]
不是1226补丁嘛，哪里来的1228呢
