### ISSUE TITLE
Version 2: TypeError: super() argument 1 must be type, not SynthesizerTrnMs768NSFsid_nono

### ISSUE THREAD

**Issue by Ko4ka** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1762]
I am test v2, the Training wont start due to this error

I am using a local gradio interface

```2024-01-24 23:59:57 | INFO | infer-web | Use gpus: 0
2024-01-24 23:59:57 | INFO | infer-web | "C:\Users\Alex\AppData\Local\Programs\Python\Python39\python.exe" infer/modules/train/train.py -e "mi-test" -sr 48k -f0 0 -bs 12 -g 0 -te 500 -se 10 -pg assets/pretrained_v2/f0G48k.pth -pd assets/pretrained_v2/f0D48k.pth -l 0 -c 0 -sw 1 -v v2
INFO:mi-test:{'data': {'filter_length': 2048, 'hop_length': 480, 'max_wav_value': 32768.0, 'mel_fmax': None, 'mel_fmin': 0.0, 'n_mel_channels': 128, 'sampling_rate': 48000, 'win_length': 2048, 'training_files': './logs\\mi-test/filelist.txt'}, 'model': {'filter_channels': 768, 'gin_channels': 256, 'hidden_channels': 192, 'inter_channels': 192, 'kernel_size': 3, 'n_heads': 2, 'n_layers': 6, 'p_dropout': 0, 'resblock': '1', 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'resblock_kernel_sizes': [3, 7, 11], 'spk_embed_dim': 109, 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [24, 20, 4, 4], 'upsample_rates': [12, 10, 2, 2], 'use_spectral_norm': False}, 'train': {'batch_size': 12, 'betas': [0.8, 0.99], 'c_kl': 1.0, 'c_mel': 45, 'epochs': 20000, 'eps': 1e-09, 'fp16_run': False, 'init_lr_ratio': 1, 'learning_rate': 0.0001, 'log_interval': 200, 'lr_decay': 0.999875, 'seed': 1234, 'segment_size': 17280, 'warmup_epochs': 0}, 'model_dir': './logs\\mi-test', 'experiment_dir': './logs\\mi-test', 'save_every_epoch': 10, 'name': 'mi-test', 'total_epoch': 500, 'pretrainG': 'assets/pretrained_v2/f0G48k.pth', 'pretrainD': 'assets/pretrained_v2/f0D48k.pth', 'version': 'v2', 'gpus': '0', 'sample_rate': '48k', 'if_f0': 0, 'if_latest': 0, 'save_every_weights': '1', 'if_cache_data_in_gpu': 0}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "H:\Retrieval-based-Voice-Conversion-WebUI-updated1006v2\infer\modules\train\train.py", line 176, in run
    net_g = RVC_Model_nof0(
  File "H:\Retrieval-based-Voice-Conversion-WebUI-updated1006v2\infer\lib\infer_pack\models.py", line 1128, in __init__
    super(self, SynthesizerTrnMs768NSFsid_nono).__init__()
TypeError: super() argument 1 must be type, not SynthesizerTrnMs768NSFsid_nono```

**Comment by RVC-Boss** [comment]
Fixed now. You need clone the latest codes.
