### ISSUE TITLE
运行整合包的go-realtime-gui后，开始音频转换后出现了报错

### ISSUE THREAD

**Issue by guoyaoyang0522** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1777]
E:\mycode\RVC1006Nvidia>runtime\python.exe gui_v1.py
2024-01-30 05:25:43 | INFO | faiss.loader | Loading faiss with AVX2 support.
2024-01-30 05:25:43 | INFO | faiss.loader | Successfully loaded faiss with AVX2 support.
2024-01-30 05:25:43 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 3070 Ti
is_half:True, device:cuda:0
Input device: 2:麦克风 (Yeti X) (MME)
Output device: 7:VoiceMeeter Input (VB-Audio Voi (MME)
cuda_is_available: True
Index search enabled
Audio block passed.
Audio block passed.
Exception ignored from cffi callback <function _StreamBase.__init__.<locals>.callback_ptr at 0x000001C2FFFA4430>:
Traceback (most recent call last):
  File "E:\mycode\RVC1006Nvidia\runtime\lib\site-packages\sounddevice.py", line 889, in callback_ptr
    return _wrap_callback(
  File "E:\mycode\RVC1006Nvidia\runtime\lib\site-packages\sounddevice.py", line 2690, in _wrap_callback
    callback(*args)
  File "E:\mycode\RVC1006Nvidia\gui_v1.py", line 726, in audio_callback
    infer_wav = self.rvc.infer(
TypeError: infer() takes 6 positional arguments but 7 were given
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
一直重复

**Comment by THE-SINDOL** [comment]
Hi, delete config.config and try it
