### ISSUE TITLE
Macbook Pro M2 Pro issues with webUI Errors 

### ISSUE THREAD

**Issue by InochiPM** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1782]
Okay so i know this might be a long shot but when trying to launch the webui from [sh run.sh] i get this error 
```
Traceback (most recent call last):
  File "infer-web.py", line 26, in <module>
    from fairseq import checkpoint_utils
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/__init__.py", line 40, in <module>
    import fairseq.scoring  # noqa
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/scoring/__init__.py", line 55, in <module>
    importlib.import_module("fairseq.scoring." + module)
  File "/opt/homebrew/Cellar/python@3.8/3.8.18_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/scoring/bleu.py", line 14, in <module>
    from fairseq.scoring.tokenizer import EvaluationTokenizer
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/scoring/tokenizer.py", line 8, in <module>
    import sacrebleu as sb
  File "/opt/homebrew/lib/python3.8/site-packages/sacrebleu/__init__.py", line 21, in <module>
    from .utils import smart_open, SACREBLEU_DIR, download_test_set  # noqa: F401
  File "/opt/homebrew/lib/python3.8/site-packages/sacrebleu/utils.py", line 597, in <module>
    from .dataset import DATASETS, SUBSETS, DOMAINS, COUNTRIES
  File "/opt/homebrew/lib/python3.8/site-packages/sacrebleu/dataset/__init__.py", line 73, in <module>
    from .wmt_xml import WMTXMLDataset
  File "/opt/homebrew/lib/python3.8/site-packages/sacrebleu/dataset/wmt_xml.py", line 3, in <module>
    import lxml.etree as ET
ImportError: dlopen(/opt/homebrew/lib/python3.8/site-packages/lxml/etree.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_exsltDateXpathCtxtRegister'
```

when using my Intel macbook pro it throws this error when trying to use inference. 
```
 UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
and when the ui works [mangio RVC] for instance 
i get this error, 
```
NotImplementedError: The operator 'aten::upsample_linear1d.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```
Mind you i can get the actual UI to work on my intel macbook but i cant get it to launch on my m2 pro macbook at all. 
Any ideas on how to fix these issues???

**Comment by THE-SINDOL** [comment]
IS mangio rvc ?

**Comment by InochiPM** [comment]
> IS mangio rvc ? Or rvc project you download ?

Its this one, RVC Project.

**Comment by iamzhangyunlu** [comment]
@InochiPM @InochiPM execute "export PYTORCH_ENABLE_MPS_FALLBACK=1" first then run "python infer-web.py" when you're using Macbook M series chips

**Comment by jathoo** [comment]
Hi @inochiPM thanks for the answer, how did you fix the issue on M2 mac ? 

I can’t even get the UI working, 

I am getting this error when trying to answer 

Traceback (most recent call last):
  File "infer-web.py", line 26, in <module>
    from fairseq import checkpoint_utils
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/__init__.py", line 40, in <module>
    import fairseq.scoring  # noqa
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/scoring/__init__.py", line 55, in <module>
    importlib.import_module("fairseq.scoring." + module)
  File "/opt/homebrew/Cellar/python@3.8/3.8.18_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/scoring/bleu.py", line 14, in <module>
    from fairseq.scoring.tokenizer import EvaluationTokenizer
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/scoring/tokenizer.py", line 8, in <module>
    import sacrebleu as sb
  File "/opt/homebrew/lib/python3.8/site-packages/sacrebleu/__init__.py", line 21, in <module>
    from .utils import smart_open, SACREBLEU_DIR, download_test_set  # noqa: F401
  File "/opt/homebrew/lib/python3.8/site-packages/sacrebleu/utils.py", line 597, in <module>
    from .dataset import DATASETS, SUBSETS, DOMAINS, COUNTRIES
  File "/opt/homebrew/lib/python3.8/site-packages/sacrebleu/dataset/__init__.py", line 73, in <module>
    from .wmt_xml import WMTXMLDataset
  File "/opt/homebrew/lib/python3.8/site-packages/sacrebleu/dataset/wmt_xml.py", line 3, in <module>
    import lxml.etree as ET
ImportError: dlopen(/opt/homebrew/lib/python3.8/site-packages/lxml/etree.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_exsltDateXpathCtxtRegister'

**Comment by R3D347HR4Y** [comment]
@jathoo 
Had this issue, fixed it by doing this:
brew install libxml2
brew install libxslt
pip install lxml==4.9.2

And when you try to run don't use run.sh, do this:
python infer-web.py

**Comment by jathoo** [comment]
Thanks , I did try all this steps , I can only run this command with pip3 , I guess i don’t have previous python version locally , but i am stuck with the same error. 

‘’’ pip install lxml==4.9.2’’’ 

will it only work with pip not pip3 ?

**Comment by jathoo** [comment]
thanks, now I am getting this, `No module named 'numpy'` 

I am new to Python and i wonder if there are issues with my path or something. 
would be helpful if someone could make a shell file to run these commands  that works please

**Comment by hoonlight** [comment]
Same issue here

**Comment by sxsx-G** [comment]
@jathoo, you need activate env first:   ''. .venv/bin/activate''
then doing "pip install lxml==4.9.2" and ''python infer-web.py''
