### ISSUE TITLE
在colab使用cpu推断报错

### ISSUE THREAD

**Issue by TinaChen95** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#179]
相同的模型在GPU上推断没问题，但是在CPU上遇到如下报错：

Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 141, in vc_single
    if_f0 = cpt.get("f0", 1)
NameError: name 'cpt' is not defined

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1305, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1239, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 2542, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 160, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 174, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 141, in vc_single
    if_f0 = cpt.get("f0", 1)
NameError: name 'cpt' is not defined

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1305, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1239, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 2542, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 160, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 174, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 141, in vc_single
    if_f0 = cpt.get("f0", 1)
NameError: name 'cpt' is not defined

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1305, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1239, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 2542, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 160, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 174, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 141, in vc_single
    if_f0 = cpt.get("f0", 1)
NameError: name 'cpt' is not defined

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1305, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1239, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 2542, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 160, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "/usr/local/lib/python3.9/dist-packages/gradio/processing_utils.py", line 174, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by RVC-Boss** [comment]
选了音色吗

**Comment by TinaChen95** [comment]
选了的，CPU 上操作过程跟GPU上一样的。
使用的是colab的环境

**Comment by ctykwz** [comment]
@RVC-Boss 是的 一样的问题


2023-06-10 11:23:37 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
Traceback (most recent call last):
  File "D:\code\python\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 169, in vc_single
    if_f0 = cpt.get("f0", 1)
NameError: name 'cpt' is not defined
Traceback (most recent call last):
  File "D:\code\python\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\code\python\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\code\python\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\code\python\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "D:\code\python\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

**Comment by harryhuang2015** [comment]
> 左右

我在Apple M1上也遇到这个问题，weights下的模型只有55M，这个需要怎么解决？
