### ISSUE TITLE
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation'

### ISSUE THREAD

**Issue by GUUser91** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1798]
>>python infer-web.py
2024-02-07 19:11:18 | INFO | configs.config | Found GPU AMD Radeon RX 7900 XTX
is_half:True, device:cuda:0
Traceback (most recent call last):
  File "/home/user/RVC/infer-web.py", line 21, in <module>
    import gradio as gr
  File "/home/user/RVC/venv/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/user/RVC/venv/lib/python3.10/site-packages/gradio/components.py", line 37, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (/home/user/RVC/venv/lib/python3.10/site-packages/gradio_client/documentation.py)

**Comment by GUUser91** [comment]
I was able to fix the problem by following these guides.
https://www.reddit.com/r/StableDiffusion/comments/1akriw5/error_in_kohya_ss_script/
https://github.com/gitmylo/audio-webui/issues/212#issuecomment-1933031971
Type in this command
>>pip install gradio_client==0.8.1
