### ISSUE TITLE
Error when trying to run RVC

### ISSUE THREAD

**Issue by ffirenn** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1804]
> 2024-02-08 23:19:10 | INFO | configs.config | No supported Nvidia GPU found
overwrite preprocess and configs.json
2024-02-08 23:19:10 | INFO | configs.config | Use cpu instead
is_half:False, device:cpu
Traceback (most recent call last):
  File "C:\Users\pc\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\infer-web.py", line 21, in <module>
    import gradio as gr
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\components.py", line 37, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio_client\documentation.py)

is there a solution?

**Comment by ffirenn** [comment]
Resolved.
I just uninstalled and reinstalled gradio and it worked.

> pip uninstall gradio

> pip install gradio

**Comment by chnisar515** [comment]
I tried what you said but the issue still not solve.
