### ISSUE TITLE
Script to train .pth and .index without the UI

### ISSUE THREAD

**Issue by ffd000** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1821]
Can we use a script for finetuning instead of the UI?

There are some scripts in tools/infer/ but I don't understand how to give it the wav files for training and whisper.json

**Comment by ffd000** [comment]
I put this function at the end of infer-web.py (deleting the gradio stuff

```def main1():
    trainset_dir4 = '....'
    exp_dir1 = 'voice-test'
    sr2 = '40k'
    np7=int(np.ceil(config.n_cpu / 1.5))
    gpus16 = gpus
    f0method8 = 'rmvpe_gpu'
    if_f0_3 = False
    version19 = 'v2'
    gpus_rmvpe = "%s-%s" % (gpus, gpus)
    save_epoch10 = 10
    total_epoch11 = 200
    batch_size12 = 4
    if_save_latest13 = "0"
    pretrained_G14 = "assets/pretrained_v2/f0G40k.pth"
    pretrained_D15 = "assets/pretrained_v2/f0D40k.pth"
    if_cache_gpu17 = "0"
    if_save_every_weights18="0"
    spk_id5 = 0
    
    infos = []
    def get_info_str(strr):
        infos.append(strr)
        return "\n".join(infos)
    yield get_info_str(i18n("step1:正在处理数据"))
    [get_info_str(_) for _ in preprocess_dataset(trainset_dir4, exp_dir1, sr2, np7)]

    yield get_info_str(i18n("step2:正在提取音高&正在提取特征"))
    [
        get_info_str(_)
        for _ in extract_f0_feature(
            gpus16, np7, f0method8, if_f0_3, exp_dir1, version19, gpus_rmvpe
        )
    ]

    yield get_info_str(i18n("step3a:正在训练模型"))
    click_train(
        exp_dir1,
        sr2,
        if_f0_3,
        spk_id5,
        save_epoch10,
        total_epoch11,
        batch_size12,
        if_save_latest13,
        pretrained_G14,
        pretrained_D15,
        gpus16,
        if_cache_gpu17,
        if_save_every_weights18,
        version19,
    )
    yield get_info_str(
        i18n("训练结束, 您可查看控制台训练日志或实验文件夹下的train.log")
    )

    [get_info_str(_) for _ in train_index(exp_dir1, version19)]
    yield get_info_str(i18n("全流程结束！"))

[print(_) for _ in main1()]
```

Error:
```
INFO:voice-test:loaded pretrained assets/pretrained_v2/f0G40k.pth
Process Process-1:
Traceback (most recent call last):
  File "/content/joe/infer/modules/train/train.py", line 210, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "/content/joe/infer/lib/train/utils.py", line 213, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/joe/infer/modules/train/train.py", line 230, in run
    net_g.module.load_state_dict(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs768NSFsid_nono:
	Unexpected key(s) in state_dict: "enc_p.emb_pitch.weight", "dec.m_source.l_linear.weight", "dec.m_source.l_linear.bias", "dec.noise_convs.0.weight", "dec.noise_convs.0.bias", "dec.noise_convs.1.weight", "dec.noise_convs.1.bias", "dec.noise_convs.2.weight", "dec.noise_convs.2.bias", "dec.noise_convs.3.weight", "dec.noise_convs.3.bias". 
```

pretrained models downloaded from huggingface
Tried the SynthesizerTrnMs768NSFsid_nono constructor fix mentioned in another issue, didn't work
