### ISSUE TITLE
AttributeError: module 'huggingface_hub.constants' has no attribute 'HF_HUB_CACHE'

### ISSUE THREAD

**Issue by Ninja34234** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1832]
I am getting this error while generating public URL for RVC v2, how to fix this?

Im using this link: https://colab.research.google.com/drive/1Gj6UTf2gicndUW_tVheVhTXIIYpFTYc7?usp=sharing

/content

-------------------------------
RVC v2 Easy GUI (Colab Edition)
-------------------------------

-------------------------------
File /content/Retrieval-based-Voice-Conversion-WebUI/hubert_base.pt already exists. No need to download.
2024-02-21 17:18:34.705829: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-21 17:18:34.705892: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-21 17:18:34.707201: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-21 17:18:34.714274: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-21 17:18:35.796014: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/EasierGUI.py", line 221, in <module>
    from fairseq import checkpoint_utils
  File "/usr/local/lib/python3.10/dist-packages/fairseq/__init__.py", line 33, in <module>
    import fairseq.criterions  # noqa
  File "/usr/local/lib/python3.10/dist-packages/fairseq/criterions/__init__.py", line 36, in <module>
    importlib.import_module("fairseq.criterions." + file_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/fairseq/criterions/ctc.py", line 19, in <module>
    from fairseq.tasks import FairseqTask
  File "/usr/local/lib/python3.10/dist-packages/fairseq/tasks/__init__.py", line 136, in <module>
    import_tasks(tasks_dir, "fairseq.tasks")
  File "/usr/local/lib/python3.10/dist-packages/fairseq/tasks/__init__.py", line 117, in import_tasks
    importlib.import_module(namespace + "." + task_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/fairseq/tasks/online_backtranslation.py", line 34, in <module>
    from fairseq.sequence_generator import SequenceGenerator
  File "/usr/local/lib/python3.10/dist-packages/fairseq/sequence_generator.py", line 16, in <module>
    from fairseq.models import FairseqIncrementalDecoder
  File "/usr/local/lib/python3.10/dist-packages/fairseq/models/__init__.py", line 235, in <module>
    import_models(models_dir, "fairseq.models")
  File "/usr/local/lib/python3.10/dist-packages/fairseq/models/__init__.py", line 217, in import_models
    importlib.import_module(namespace + "." + model_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/fairseq/models/transformer_from_pretrained_xlm.py", line 12, in <module>
    from fairseq.models.transformer import (
  File "/usr/local/lib/python3.10/dist-packages/fairseq/models/transformer/__init__.py", line 13, in <module>
    from .transformer_decoder import TransformerDecoder, TransformerDecoderBase, Linear
  File "/usr/local/lib/python3.10/dist-packages/fairseq/models/transformer/transformer_decoder.py", line 16, in <module>
    from fairseq.modules import (
  File "/usr/local/lib/python3.10/dist-packages/fairseq/modules/__init__.py", line 34, in <module>
    from .positional_embedding import PositionalEmbedding
  File "/usr/local/lib/python3.10/dist-packages/fairseq/modules/positional_embedding.py", line 9, in <module>
    from .sinusoidal_positional_embedding import SinusoidalPositionalEmbedding
  File "/usr/local/lib/python3.10/dist-packages/fairseq/modules/sinusoidal_positional_embedding.py", line 10, in <module>
    import torch.onnx.operators
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/__init__.py", line 46, in <module>
    from ._internal.exporter import (  # usort:skip. needs to be last to avoid circular import
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/exporter.py", line 42, in <module>
    from torch.onnx._internal.fx import (
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/__init__.py", line 1, in <module>
    from .patcher import ONNXTorchPatcher
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/fx/patcher.py", line 11, in <module>
    import transformers  # type: ignore[import]
  File "/usr/local/lib/python3.10/dist-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.10/dist-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/__init__.py", line 62, in <module>
    from .hub import (
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 96, in <module>
    PYTORCH_PRETRAINED_BERT_CACHE = os.getenv("PYTORCH_PRETRAINED_BERT_CACHE", constants.HF_HUB_CACHE)
AttributeError: module 'huggingface_hub.constants' has no attribute 'HF_HUB_CACHE'

**Comment by atmerka** [comment]
Also just started getting this error after months if it working smoothly - following

**Comment by Ninja34234** [comment]
I think nobody is interested in solving this issue. Not sure when they will fix it! I see many Tickets have been unanswered for months! I genuinely request if anyone has a fix for this please help us as soon as possible.
