### ISSUE TITLE
Apple m1 issue in running gui_v1.py (realtime WebUI)

### ISSUE THREAD

**Issue by breadjuice** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1841]
System: MacbookPro M1
Error: may about sounddevice package
I am not a dev, the following error feedback is too hard for me to solve.
**This happens after** I select the input and output device and **click the 'start audio conversion'.**

(base) jacob@jacobdeMBP Retrieval-based-Voice-Conversion-WebUI-main % python gui_v1.py
2024-02-25 16:46:22 | INFO | faiss.loader | Loading faiss.
2024-02-25 16:46:22 | INFO | faiss.loader | Successfully loaded faiss.
2024-02-25 16:46:22 | INFO | configs.config | No supported Nvidia GPU found
overwrite preprocess and configs.json
2024-02-25 16:46:22 | INFO | configs.config | Use mps instead
is_half:False, device:mps
Input device: 3:MacBook Pro Microphone (Core Audio)
Output device: 1:soundcore AeroFit Pro (Core Audio)
cuda_is_available: False
2024-02-25 16:46:40 | INFO | fairseq.tasks.hubert_pretraining | current directory is /Users/jacob/Downloads/Retrieval-based-Voice-Conversion-WebUI-main
2024-02-25 16:46:40 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2024-02-25 16:46:40 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
/Users/jacob/miniconda3/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:25: UserWarning: The operator 'aten::_weight_norm_interface' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  return _weight_norm(v, g, self.dim)
Index search FAILED or disabled
Loading fcpe model
  [INFO]: device is not None, use mps
  [INFO]    > call by:torchfcpe.tools.spawn_infer_cf_naive_mel_pe_from_pt
  [WARN] args.model.use_harmonic_emb is None; use default False
  [WARN]    > call by:torchfcpe.tools.spawn_cf_naive_mel_pe
/Users/jacob/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/infer/lib/infer_pack/attentions.py:334: UserWarning: MPS: The constant padding of more than 3 dimensions is not currently supported natively. It uses View Ops default implementation to run. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Pad.mm:393.)
  x = F.pad(
Spent time: fea = 0.526s, index = 0.000s, f0 = 0.809s, model = 0.623s
Exception ignored from cffi callback <function _StreamBase.__init__.<locals>.callback_ptr at 0x15065dcf0>:
Traceback (most recent call last):
  File "/Users/jacob/miniconda3/lib/python3.10/site-packages/sounddevice.py", line 886, in callback_ptr
    return _wrap_callback(
  File "/Users/jacob/miniconda3/lib/python3.10/site-packages/sounddevice.py", line 2687, in _wrap_callback
    callback(*args)
  File "/Users/jacob/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/gui_v1.py", line 889, in audio_callback
    _, sola_offset = torch.max(cor_nom[0, 0] / cor_den[0, 0])
  File "/Users/jacob/miniconda3/lib/python3.10/site-packages/torch/_tensor.py", line 930, in __iter__
    raise TypeError("iteration over a 0-d tensor")
TypeError: iteration over a 0-d tensor

**Comment by breadjuice** [comment]
Well, I fix it myself.
<img width="683" alt="image" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/30001126/ca90070e-3b11-437d-b205-2ef0c26fe298">
