### ISSUE TITLE
pth转onnx失败

### ISSUE THREAD

**Issue by obitodaitu** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1913]
你好，我想把pth模型转成onnx（用的kikiV1.pth），但是转不了，会报错，报错内容如下：
```shell
Traceback (most recent call last):
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\RVC1006Nvidia\infer-web.py", line 171, in export_onnx
    eo(ModelPath, ExportedPath)
  File "D:\RVC1006Nvidia\infer\modules\onnx\export.py", line 29, in export_onnx
    torch.onnx.export(
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\onnx\utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\onnx\utils.py", line 989, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\onnx\utils.py", line 893, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\jit\_trace.py", line 1268, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "D:\RVC1006Nvidia\infer\lib\infer_pack\models_onnx.py", line 650, in forward
    z = self.flow(z_p, x_mask, g=g, reverse=True)
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "D:\RVC1006Nvidia\infer\lib\infer_pack\models_onnx.py", line 152, in forward
    x = flow(x, x_mask, g=g, reverse=reverse)
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "D:\RVC1006Nvidia\infer\lib\infer_pack\modules.py", line 519, in forward
    x0, x1 = torch.split(x, [self.half_channels] * 2, 1)
  File "D:\RVC1006Nvidia\runtime\lib\site-packages\torch\functional.py", line 189, in split
    return tensor.split(split_size_or_sections, dim)
AttributeError: 'tuple' object has no attribute 'split'
```

请问是什么原因呢？

**Comment by yc930401** [comment]
请问是怎么解决的？
