### ISSUE TITLE
关于使用时在audio。py

### ISSUE THREAD

**Issue by WuYuZh17** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1916]

**Comment by WuYuZh17** [comment]
文件路径中没有中文，现在想知道是不是av库版本更新导致的？

**Comment by fumiama** [comment]
请尝试使用dev版本。

**Comment by DaLongmao2** [comment]
你们解决了吗，怎么解决的。感谢

**Comment by Koji-Huang** [comment]
我用 Pycharm 追踪了半天，解决了

**Comment by Koji-Huang** [comment]
方法很简单: av.open(i, "r") 里面加一个 metadata_encoding='utf-8' 来指定编码格式就可以解决编码问题
还有并不是每一个 open 里的 rb 都要改为 r , 最下面的那个 with open(file, "rb") as f: 里的 rb 是不用改动的
av 不允许使用 rb 和 wb

**Comment by DaLongmao2** [comment]
> 方法很简单: av.open(i, "r") 里面加一个metadata_encoding='utf-8' 来指定编码格式就可以解决编码问题 还有不是每一个开放里的 rb 到底要 r , 最下面的那个 with open(file, "rb") as f: 里的 rb 是不用右边的 av 不允许使用 rb 和 wb

OK感谢，我试一下

**Comment by wangtiance** [comment]
> 方法很简单: av.open(i, "r") 里面加一个 metadata_encoding='utf-8' 来指定编码格式就可以解决编码问题 还有并不是每一个 open 里的 rb 都要改为 r , 最下面的那个 with open(file, "rb") as f: 里的 rb 是不用改动的 av 不允许使用 rb 和 wb

是这样吗？inp = av.open(i, "rb", metadata_encoding='utf-8')
我改了之后还是报一样的错误：
2024-06-20 15:25:12 | WARNING | libav.wav | Discarding ID3 tags because more suitable tags were found.
2024-06-20 15:25:12 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "D:\git\Voice_conversion\RVC1006Nvidia\infer\lib\audio.py", line 65, in load_audio
    audio2(f, out, "f32le", sr)
  File "D:\git\Voice_conversion\RVC1006Nvidia\infer\lib\audio.py", line 36, in audio2
    inp = av.open(i, "rb", metadata_encoding='utf-8')
  File "av\container\core.pyx", line 401, in av.container.core.open
  File "av\container\input.pyx", line 86, in av.container.input.InputContainer.__cinit__
  File "av\utils.pyx", line 26, in av.utils.avdict_to_dict
  File "av\utils.pyx", line 14, in av.utils._decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 26: invalid start byte

**Comment by wangtiance** [comment]
先换成librosa.load绕开这个问题了

**Comment by Koji-Huang** [comment]
我的那个方法针对的是没打补丁的版本, 你这个应该是打了补丁之后的? (对比了一下报错信息和源码, 是差不多的)
如果想折腾可以试试设置Windows10的默认编码为 UTF-8 或者这篇帖子 https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1776

> 先换成librosa.load绕开这个问题了

**Comment by cancaglar** [comment]
I tried your suggestions, and the error disappeared, but after resolving the error, I encountered this issue:
`2025-01-24 21:44:23 | INFO | configs.config | No supported Nvidia GPU found
overwrite preprocess and configs.json
2025-01-24 21:44:23 | INFO | configs.config | Use cpu instead
is_half:False, device:cpu
C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio_client\documentation.py:106: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f\"Could not get documentation group for {cls}: {exc}\")
C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio_client\documentation.py:106: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f\"Could not get documentation group for {cls}: {exc}\")
2025-01-24 21:44:24 | INFO | __main__ | Use Language: en_US
Running on local URL:  http://0.0.0.0:7865
2025-01-24 21:44:45 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict \"HTTP/1.1 200 OK\"
2025-01-24 21:44:45 | INFO | __main__ | \"C:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python310\\python.exe\" infer/modules/train/preprocess.py \"C:\\Users\\pc\\Desktop\\testses\" 40000 8 \"C:\\Users\\pc\\Desktop\\r\\rvc/logs/test343\" False 3.7
['infer/modules/train/preprocess.py', 'C:\\\\Users\\\\pc\\\\Desktop\\\\testses', '40000', '8', 'C:\\\\Users\\\\pc\\\\Desktop\\\\r\\\\rvc/logs/test343', 'False', '3.7']
start preprocess
['infer/modules/train/preprocess.py', 'C:\\\\Users\\\\pc\\\\Desktop\\\\testses', '40000', '8', 'C:\\\\Users\\\\pc\\\\Desktop\\\\r\\\\rvc/logs/test343', 'False', '3.7']
C:\\Users\\pc\\Desktop\\testses/tahatest.wav->Suc.
end preprocess
2025-01-24 21:45:07 | INFO | __main__ | start preprocess
['infer/modules/train/preprocess.py', 'C:\\\\Users\\\\pc\\\\Desktop\\\\testses', '40000', '8', 'C:\\\\Users\\\\pc\\\\Desktop\\\\r\\\\rvc/logs/test343', 'False', '3.7']
C:\\Users\\pc\\Desktop\\testses/tahatest.wav->Suc.
end preprocess`

There doesn't seem to be an error, but right after "preprocess start," it quickly ends with "end preprocess," and the program remains idle, doing nothing further.

I also reviewed other issues and tried different versions of the AV package, as well as running it on two different PCs. However, I couldn't resolve the issue. I have even created an issue for this problem. Please help me!
this is my issue page
#2455 
@Koji-Huang @fumiama @wangtiance @DaLongmao2

**Comment by cancaglar** [comment]
I solved.
#2455 
here is the steps that I made.
https://docs.google.com/document/d/12Oytu9m9zCnKZjJphpeq4najOUlRxz5tJCUPGoHYYeg/edit?usp=sharing

**Comment by fumiama** [comment]
@cancaglar Thanks for your effort. This repo is no longer active due to #2109 . The problems you mentioned are mainly solved in my fork https://github.com/fumiama/Retrieval-based-Voice-Conversion-WebUI . Feel free to use it.

**Comment by RVC-Boss** [comment]
更新到最新main分支可解决该问题。av库问题和编码问题已修复。
