### ISSUE TITLE
 vocal accompaniment separation not working

### ISSUE THREAD

**Issue by Dannny0117** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1929]
So i downloaded https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006Nvidia.7z ran the web ui and when i select the file , specify the output and select the model and click convert the progress shows up and then throws all of this at me. 

when i check the TEMP folder on the RVC folder theres nothing however it creates a copy of the original file at \AppData\Local\Temp but thats about it. 

i changed nothing just downloaded, used 7z to extract and ran go-web.bat

any ideas on how i can get it to work?

10 Get Over It Demo Versionrw0zc47e.mp3.reformatted.wav->Traceback (most recent call last):
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 1213, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'E:\\RVC1006Nvidia\\TEMP/10 Get Over It Demo Versionrw0zc47e.mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\RVC1006Nvidia\infer\modules\uvr5\modules.py", line 74, in uvr
    pre_fun._path_audio_(
  File "E:\RVC1006Nvidia\infer\modules\uvr5\vr.py", line 63, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\RVC1006Nvidia\\TEMP/10 Get Over It Demo Versionrw0zc47e.mp3.reformatted.wav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 1213, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'E:\\RVC1006Nvidia\\TEMP/10 Get Over It Demo Versionrw0zc47e.mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\RVC1006Nvidia\infer\modules\uvr5\modules.py", line 82, in uvr
    pre_fun._path_audio_(
  File "E:\RVC1006Nvidia\infer\modules\uvr5\vr.py", line 63, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "E:\RVC1006Nvidia\runtime\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\RVC1006Nvidia\\TEMP/10 Get Over It Demo Versionrw0zc47e.mp3.reformatted.wav'

**Comment by ic1149** [comment]
Make sure you installed ffmpeg and ffprobe in the root directory of rvc as mentioned in readme

**Comment by iwoolf** [comment]
Separation doesn't work for me on linux, either. Whereas voice training and conversion work really well.
