### ISSUE TITLE
Vocal Separation error

### ISSUE THREAD

**Issue by Reviem0** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1936]
Same error every time

b.wav.reformatted.wav->Traceback (most recent call last):
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\modules\uvr5\modules.py", line 74, in uvr
    pre_fun._path_audio_(
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\modules\uvr5\vr.py", line 119, in _path_audio_
    wav_instrument = spec_utils.cmb_spectrogram_to_wave(
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\lib\uvr5_pack\lib_v5\spec_utils.py", line 397, in cmb_spectrogram_to_wave
    spectrogram_to_wave(
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\lib\uvr5_pack\lib_v5\spec_utils.py", line 295, in spectrogram_to_wave
    wave_left = librosa.istft(spec_left, hop_length=hop_length)
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\env\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\env\lib\site-packages\librosa\core\spectrum.py", line 394, in istft
    dtype = util.dtype_c2r(stft_matrix.dtype)
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\env\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\env\lib\site-packages\librosa\util\utils.py", line 2185, in dtype_c2r
    np.dtype(complex): np.dtype(np.float).type,
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\env\lib\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\modules\uvr5\modules.py", line 82, in uvr
    pre_fun._path_audio_(
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\modules\uvr5\vr.py", line 119, in _path_audio_
    wav_instrument = spec_utils.cmb_spectrogram_to_wave(
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\lib\uvr5_pack\lib_v5\spec_utils.py", line 397, in cmb_spectrogram_to_wave
    spectrogram_to_wave(
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\lib\uvr5_pack\lib_v5\spec_utils.py", line 295, in spectrogram_to_wave
    wave_left = librosa.istft(spec_left, hop_length=hop_length)
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\env\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\env\lib\site-packages\librosa\core\spectrum.py", line 394, in istft
    dtype = util.dtype_c2r(stft_matrix.dtype)
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\env\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\env\lib\site-packages\librosa\util\utils.py", line 2185, in dtype_c2r
    np.dtype(complex): np.dtype(np.float).type,
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\env\lib\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?

**Comment by Madriix** [comment]
I just posted the same thing here https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1938 I hadn't seen

**Comment by Reviem0** [comment]
Found a fix for this.
You have to downgrade numpy to 1.23.5
You can open your venv and run this
```
pip install --upgrade numpy==1.23.5
```

**Comment by Reviem0** [comment]
downgrade numpy using:
```
pip install --upgrade numpy==1.23.5
```
