### ISSUE TITLE
go-realtime-gui not starting

### ISSUE THREAD

**Issue by NeoLoger** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1941]
When I try to start the `go-realtime-gui.bat` I get the following error.
The `go-web.bat` seems to work fine and I can train and change voices.

```
2024-03-30 15:44:30 | INFO | faiss.loader | Loading faiss with AVX2 support.
2024-03-30 15:44:30 | INFO | faiss.loader | Successfully loaded faiss with AVX2 support.
2024-03-30 15:44:30 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 3060 Ti
2024-03-30 15:44:30 | INFO | configs.config | Half-precision floating-point: True, device: cuda:0
Traceback (most recent call last):
  File "C:\tools\AI\RVC\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 154, in load
    data = json.load(j)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\tools\AI\RVC\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 1049, in <module>
    gui = GUI()
  File "C:\tools\AI\RVC\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 147, in __init__
    self.launcher()
  File "C:\tools\AI\RVC\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 220, in launcher
    data = self.load()
  File "C:\tools\AI\RVC\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 192, in load
    self.input_devices_indices.index(sd.default.device[0])
ValueError: -1 is not in list
```

Is something missing? 
Any suggestions?

**Comment by NeoLoger** [comment]
Ok never mind, found the issue myself.
I'm using a remote server to run this and there was no input device.
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/23522883/c86c3ada-7c27-4a1d-a488-6d2a8e56392e)

For future reference make sure you have a microphone recognized on your system before running the `go-realtime-gui.bat`
