### ISSUE TITLE
error rvc

### ISSUE THREAD

**Issue by hijxmmy** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1957]
Traceback (most recent call last):
  File "C:\Users\Utilizador\Desktop\RVC-GUI-pkg-20220525-mp3fix\RVC-GUI-pkg\rvcgui.py", line 129, in vc_single
    audio_opt = vc.pipeline(
  File "C:\Users\Utilizador\Desktop\RVC-GUI-pkg-20220525-mp3fix\RVC-GUI-pkg\vc_infer_pipeline.py", line 326, in pipeline
    sid = torch.tensor(sid, device=self.device).unsqueeze(0).long()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by arbaz686** [comment]
Set the environment variable `CUDA_LAUNCH_BLOCKING=1` before running your application. This makes CUDA API calls synchronous, providing more accurate error messages and stack traces.

`export CUDA_LAUNCH_BLOCKING=1`
