### ISSUE TITLE
人声伴奏分离时报错：TypeError: load() takes 1 positional argument but 3 positional arguments (and 2 keyword-only arguments) were given

### ISSUE THREAD

**Issue by liangcaodba** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1961]
Traceback (most recent call last):
  File "/Users/tal/Documents/Retrieval-based-Voice-Conversion-WebUI/infer/modules/uvr5/modules.py", line 55, in uvr
    pre_fun._path_audio_(
  File "/Users/tal/Documents/Retrieval-based-Voice-Conversion-WebUI/infer/modules/uvr5/vr.py", line 63, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
TypeError: load() takes 1 positional argument but 3 positional arguments (and 2 keyword-only arguments) were given
ffmpeg version 7.0 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.1.0.2.5)

**Comment by arbaz686** [comment]
There is a mismatch between the arguments provided to the `librosa.core.load` function and what the function expects. This is likely due to an update in the `librosa` library that has changed the function's signature.

Check the arguments of `librosa.load` -
(If `librosa` has been updated, the expected arguments might have changed.)

1. `path` 
2. `sr`
3. `mono`

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this librosa version issue has already been resolved.
