### ISSUE TITLE
Error when starting RVC on Windows

### ISSUE THREAD

**Issue by last-fisherman** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1969]
The installation of the program was successful, however when I tried to run this, I got the following error: 
Traceback (most recent call last):                                                                                        File "C:\Users\pyspil\AppData\Roaming\Python\Python311\site-packages\fairseq\__init__.py", line 20, in <module>           from fairseq.distributed import utils as distributed_utils                                                            File "C:\Users\pyspil\AppData\Roaming\Python\Python311\site-packages\fairseq\distributed\__init__.py", line 7, in <module>                                                                                                                        from .fully_sharded_data_parallel import (                                                                            File "C:\Users\pyspil\AppData\Roaming\Python\Python311\site-packages\fairseq\distributed\fully_sharded_data_parallel.py", line 10, in <module>                                                                                                    from fairseq.dataclass.configs import DistributedTrainingConfig                                                       File "C:\Users\pyspil\AppData\Roaming\Python\Python311\site-packages\fairseq\dataclass\__init__.py", line 6, in <module>                                                                                                                          @dataclass                                                                                                            File "C:\Program Files\Python311\Lib\dataclasses.py", line 1220, in dataclass                                             return wrap(cls)                                                                                                      File "C:\Program Files\Python311\Lib\dataclasses.py", line 1210, in wrap                                                  return _process_class(cls, init, repr, eq, order, unsafe_hash,                                                        File "C:\Program Files\Python311\Lib\dataclasses.py", line 958, in _process_class                                     ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory                                                                                                               
How I can fix it?

**Comment by ic1149** [comment]
Can you tell me which file did you attempt to run? Is it infer-web.py or go-web.bat or sth else?

**Comment by last-fisherman** [comment]
This error occurs when running all startup files such as infer-web.py or go-web.bat

**Comment by ic1149** [comment]
As suggested in the file paths, you are using python 3.11? Maybe try using python 3.9

**Comment by sv3nk** [comment]
This error occures due to Python 3.11 and the fairseq package.
Fairseq does work up until python 3.10. So just go for 3.9 or 3.10 and it should work.

**Comment by zac-market** [comment]
`pip install git+https://github.com/One-sixth/fairseq.git`
