### ISSUE TITLE
启动报错了

### ISSUE THREAD

**Issue by EricKong1985** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1973]
2024-04-17 08:17:22 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 4050 Laptop GPU
2024-04-17 08:17:22 | INFO | configs.config | Half-precision floating-point: True, device: cuda:0
2024-04-17 08:17:23 | INFO | httpx | HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "F:\codes\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 21, in <module>
    import gradio as gr
  File "F:\codes\Retrieval-based-Voice-Conversion-WebUI\py310\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "F:\codes\Retrieval-based-Voice-Conversion-WebUI\py310\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "F:\codes\Retrieval-based-Voice-Conversion-WebUI\py310\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "F:\codes\Retrieval-based-Voice-Conversion-WebUI\py310\lib\site-packages\gradio\components\__init__.py", line 40, in <module>
    from gradio.components.multimodal_textbox import MultimodalTextbox
  File "F:\codes\Retrieval-based-Voice-Conversion-WebUI\py310\lib\site-packages\gradio\components\multimodal_textbox.py", line 34, in <module>
    class MultimodalTextbox(FormComponent):
  File "F:\codes\Retrieval-based-Voice-Conversion-WebUI\py310\lib\site-packages\gradio\component_meta.py", line 198, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "F:\codes\Retrieval-based-Voice-Conversion-WebUI\py310\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi
    source_code = source_file.read_text()
  File "C:\Python310\lib\pathlib.py", line 1133, in read_text
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 2074: illegal multibyte sequence

**Comment by Ando-Lin** [comment]
try to upgrade gradio. I solved this problem by command "pip install gradio==4.24.0 --upgrade"
