### ISSUE TITLE
Check Models Error, Not able to start WebUI

### ISSUE THREAD

**Issue by hirowa** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1992]
Hi, I'm getting this error when opening "go-web.bat", I've already did a fresh install without success, hope someone can help me :)

```
C:\Retrieval-based-Voice-Conversion-WebUI>CALL env\Scripts\activate
2024-04-20 22:29:58 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 4090
2024-04-20 22:29:58 | INFO | configs.config | Half-precision floating-point: True, device: cuda:0
2024-04-20 22:29:59 | INFO | httpx | HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
2024-04-20 22:30:00 | INFO | infer.lib.rvcmd | checking hubret & rmvpe...
Traceback (most recent call last):
  File "infer-web.py", line 59, in <module>
    if not check_all_assets():
  File "C:\Retrieval-based-Voice-Conversion-WebUI\infer\lib\rvcmd.py", line 43, in check_all_assets
    if not check_model(
  File "C:\Retrieval-based-Voice-Conversion-WebUI\infer\lib\rvcmd.py", line 22, in check_model
    relname = relname[relname.rindex("assets/") :]
ValueError: substring not found
Press any key to continue . . .
```

**Comment by hirowa** [comment]
Missing "--nocheck" flag, added it and everything worked!
