### ISSUE TITLE
Can`t start training (It was working before)

### ISSUE THREAD

**Issue by Defflorstor** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1998]
Hello, sorry for bothering you, but like a half a year ago RVC was working perfectly, but for now when I press "One-Clock training" console showing me this: 

Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\train_nsf_sim_cache_sid_load_pretrain.py", line 108, in run
    train_dataset = TextAudioLoaderMultiNSFsid(hps.data.training_files, hps.data)
  File "C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\train\data_utils.py", line 18, in __init__
    self.audiopaths_and_text = load_filepaths_and_text(audiopaths_and_text)
  File "C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\train\utils.py", line 275, in load_filepaths_and_text
    filepaths_and_text = [line.strip().split(split) for line in f]
  File "C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\train\utils.py", line 275, in <listcomp>
    filepaths_and_text = [line.strip().split(split) for line in f]
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 28: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\infer-web.py", line 1217, in train1key
    faiss.write_index(
  File "C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\runtime\lib\site-packages\faiss\swigfaiss.py", line 8255, in write_index
    return _swigfaiss.write_index(*args)
RuntimeError: Error in __cdecl faiss::FileIOWriter::FileIOWriter(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:98: Error: 'f' failed: could not open C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)/logs/Goga/trained_IVF479_Flat_nprobe_1_Goga_v2.index for writing: No such file or directory

----------------------------------------------------------
And also output information at launched programm:
----------------------------------------------------------

Step 1: Processing data
runtime\python.exe trainset_preprocess_pipeline_print.py C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)\Sources 40000 16 C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)/logs/Goga False
step2a:正在提取音高
runtime\python.exe extract_f0_print.py C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)/logs/Goga 16 harvest
Step 2b: Extracting features
runtime\python.exe extract_feature_print.py cuda:0 1 0 0 C:\Users\Hyesos\Desktop\ИИ\RVC_(Training)/logs/Goga v2
Step 3a: Model training started
write filelist done
runtime\python.exe train_nsf_sim_cache_sid_load_pretrain.py -e Goga -sr 40k -f0 1 -bs 18 -g 0 -te 500 -se 5 -pg pretrained_v2/f0G40k.pth -pd pretrained_v2/f0D40k.pth -l 1 -c 0 -sw 1 -v v2
Training complete. You can check the training logs in the console or the 'train.log' file under the experiment folder.
(18698, 768),479
training index

-------------------------------------
And screenshot of all my settings:
-------------------------------------

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/67242805/b77b8177-888c-4e75-913a-389b3ef2df9d)

Maybe some libraries are missing or I should delete some files (because I was trying to reinstall it several times).
I really like this programm, can you help me, my Chinese brother?(

**Comment by Defflorstor** [comment]
Bro no fckng way it was russian "ИИ". So happy bro
