### ISSUE TITLE
選擇推理音色時，推理部分出現紅色Error字樣

### ISSUE THREAD

**Issue by pony1229** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2018]
大家好，我的問題代碼如下：
2024-04-26 01:12:10 | INFO | infer.modules.vc.modules | Get sid: G_90650.pth
2024-04-26 01:12:10 | INFO | infer.modules.vc.modules | Loading: assets/weights/G_90650.pth
Traceback (most recent call last):
```
  File "C:\Users\User\Desktop\rvc\RVC1006Nvidia\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\User\Desktop\rvc\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\User\Desktop\rvc\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\User\Desktop\rvc\RVC1006Nvidia\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\User\Desktop\rvc\RVC1006Nvidia\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\User\Desktop\rvc\RVC1006Nvidia\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\User\Desktop\rvc\RVC1006Nvidia\infer\modules\vc\modules.py", line 104, in get_vc
    self.tgt_sr = self.cpt["config"][-1]
KeyError: 'config'
```

選擇G_90650.pth和D_90650.pth都會顯示一樣的內容：
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/102134689/c5a7b9dc-c68b-41ac-8076-4e082bc9649f)

強行按下轉換的話，會出現：
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\rvc\RVC1006Nvidia\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\User\Desktop\rvc\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\User\Desktop\rvc\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\User\Desktop\rvc\RVC1006Nvidia\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\User\Desktop\rvc\RVC1006Nvidia\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\User\Desktop\rvc\RVC1006Nvidia\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/102134689/633a4eb1-2163-4581-a4e4-7e379e453350)

想請教各位大佬，謝謝。

**Comment by fumiama** [comment]
G和D都不是推理时需要的模型。应该会同时生成一个小模型以供推理之用。
