### ISSUE TITLE
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "C:\Users\Toby\Desktop\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by SephDavis** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2019]
Whenever I run go-realtime-gui I get this error:

C:\Users\Toby\Desktop\RVC\RVC1006Nvidia>runtime\python.exe guiv1.py
Traceback (most recent call last):
  File "C:\Users\Toby\Desktop\RVC\RVC1006Nvidia\gui_v1.py", line 59, in <module>
    import torch
  File "C:\Users\Toby\Desktop\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch_init.py", line 122, in <module>
    raise err
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "C:\Users\Toby\Desktop\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.

I have CUDA 11.8 installed with Pytorch 2.3.0. I've added environmental variables for CUDA bin and libnvvp. I've also tried reinstalling my drivers, Python and Cuda.

**Comment by Tps-F** [comment]
Can you tell me the environment of your device, it sometimes happen if the CPU is too old

**Comment by hypercat420** [comment]
it was working just fine for me yesterday before all of a sudden, torch died.
