### ISSUE TITLE
[WinError 10054]

### ISSUE THREAD

**Issue by adastmin1** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2026]
2024-04-29 21:07:34 | ERROR | root | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

**Comment by Tps-F** [comment]
This occurs when the internet is interrupted.
