### ISSUE TITLE
This error comes when process data is given

### ISSUE THREAD

**Issue by TharindaMarasingha** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2048]
**This error comes when process data is given**

```
**start preprocess
['infer/modules/train/preprocess.py', '/workspace/RVC1006Nvidia/data', '40000', '24', '/workspace/RVC1006Nvidia/logs/nirdoshagency', 'False', '3.0']
/workspace/RVC1006Nvidia/data/.ipynb_checkpoints->Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 61, in load_audio
    with open(file, "rb") as f:
IsADirectoryError: [Errno 21] Is a directory: '/workspace/RVC1006Nvidia/data/.ipynb_checkpoints'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/modules/train/preprocess.py", line 87, in pipeline
    audio = load_audio(path, self.sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 73, in load_audio
    raise RuntimeError(traceback.format_exc())
RuntimeError: Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 61, in load_audio
    with open(file, "rb") as f:
IsADirectoryError: [Errno 21] Is a directory: '/workspace/RVC1006Nvidia/data/.ipynb_checkpoints'


/workspace/RVC1006Nvidia/data/1.wav->Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 63, in load_audio
    audio2(f, out, "f32le", sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 34, in audio2
    inp = av.open(i, "rb")
  File "av/container/core.pyx", line 398, in av.container.core.open
ValueError: mode must be 'r', 'w', or None, got: rb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/modules/train/preprocess.py", line 87, in pipeline
    audio = load_audio(path, self.sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 73, in load_audio
    raise RuntimeError(traceback.format_exc())
RuntimeError: Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 63, in load_audio
    audio2(f, out, "f32le", sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 34, in audio2
    inp = av.open(i, "rb")
  File "av/container/core.pyx", line 398, in av.container.core.open
ValueError: mode must be 'r', 'w', or None, got: rb


/workspace/RVC1006Nvidia/data/2.wav->Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 63, in load_audio
    audio2(f, out, "f32le", sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 34, in audio2
    inp = av.open(i, "rb")
  File "av/container/core.pyx", line 398, in av.container.core.open
ValueError: mode must be 'r', 'w', or None, got: rb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/modules/train/preprocess.py", line 87, in pipeline
    audio = load_audio(path, self.sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 73, in load_audio
    raise RuntimeError(traceback.format_exc())
RuntimeError: Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 63, in load_audio
    audio2(f, out, "f32le", sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 34, in audio2
    inp = av.open(i, "rb")
  File "av/container/core.pyx", line 398, in av.container.core.open
ValueError: mode must be 'r', 'w', or None, got: rb


/workspace/RVC1006Nvidia/data/3.wav->Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 63, in load_audio
    audio2(f, out, "f32le", sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 34, in audio2
    inp = av.open(i, "rb")
  File "av/container/core.pyx", line 398, in av.container.core.open
ValueError: mode must be 'r', 'w', or None, got: rb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/modules/train/preprocess.py", line 87, in pipeline
    audio = load_audio(path, self.sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 73, in load_audio
    raise RuntimeError(traceback.format_exc())
RuntimeError: Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 63, in load_audio
    audio2(f, out, "f32le", sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 34, in audio2
    inp = av.open(i, "rb")
  File "av/container/core.pyx", line 398, in av.container.core.open
ValueError: mode must be 'r', 'w', or None, got: rb


/workspace/RVC1006Nvidia/data/4.wav->Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 63, in load_audio
    audio2(f, out, "f32le", sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 34, in audio2
    inp = av.open(i, "rb")
  File "av/container/core.pyx", line 398, in av.container.core.open
ValueError: mode must be 'r', 'w', or None, got: rb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/modules/train/preprocess.py", line 87, in pipeline
    audio = load_audio(path, self.sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 73, in load_audio
    raise RuntimeError(traceback.format_exc())
RuntimeError: Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 63, in load_audio
    audio2(f, out, "f32le", sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 34, in audio2
    inp = av.open(i, "rb")
  File "av/container/core.pyx", line 398, in av.container.core.open
ValueError: mode must be 'r', 'w', or None, got: rb


/workspace/RVC1006Nvidia/data/5.wav->Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 63, in load_audio
    audio2(f, out, "f32le", sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 34, in audio2
    inp = av.open(i, "rb")
  File "av/container/core.pyx", line 398, in av.container.core.open
ValueError: mode must be 'r', 'w', or None, got: rb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/modules/train/preprocess.py", line 87, in pipeline
    audio = load_audio(path, self.sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 73, in load_audio
    raise RuntimeError(traceback.format_exc())
RuntimeError: Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 63, in load_audio
    audio2(f, out, "f32le", sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 34, in audio2
    inp = av.open(i, "rb")
  File "av/container/core.pyx", line 398, in av.container.core.open
ValueError: mode must be 'r', 'w', or None, got: rb


/workspace/RVC1006Nvidia/data/6.wav->Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 63, in load_audio
    audio2(f, out, "f32le", sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 34, in audio2
    inp = av.open(i, "rb")
  File "av/container/core.pyx", line 398, in av.container.core.open
ValueError: mode must be 'r', 'w', or None, got: rb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/modules/train/preprocess.py", line 87, in pipeline
    audio = load_audio(path, self.sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 73, in load_audio
    raise RuntimeError(traceback.format_exc())
RuntimeError: Traceback (most recent call last):
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 63, in load_audio
    audio2(f, out, "f32le", sr)
  File "/workspace/RVC1006Nvidia/infer/lib/audio.py", line 34, in audio2
    inp = av.open(i, "rb")
  File "av/container/core.pyx", line 398, in av.container.core.open
ValueError: mode must be 'r', 'w', or None, got: rb


end preprocess**
```

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/126756637/04a9fc5c-6834-4f82-ae8f-a7a8722ac499)

**Can you tell me how to fix this?** Thanks

**Comment by AleksisVorobjovs** [comment]
Downgrading av helped me

pip install --force-reinstall -v "av==11.0.0"

**Comment by N3K00OO** [comment]
> Downgrading av helped me
> 
> pip install --force-reinstall -v "av==11.0.0"

you are a live saver :DDd
