### ISSUE TITLE
AttributeError: module 'wandb.proto.wandb_internal_pb2' has no attribute 'Result'

### ISSUE THREAD

**Issue by z2000y** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2062]
D:\RVC1006Nvidia\RVC1006Nvidia>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Traceback (most recent call last):
  File "D:\RVC1006Nvidia\RVC1006Nvidia\infer-web.py", line 8, in <module>
    from infer.modules.vc.modules import VC
  File "D:\RVC1006Nvidia\RVC1006Nvidia\infer\modules\vc\modules.py", line 19, in <module>
    from infer.modules.vc.utils import *
  File "D:\RVC1006Nvidia\RVC1006Nvidia\infer\modules\vc\utils.py", line 3, in <module>
    from fairseq import checkpoint_utils
  File "D:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\fairseq\__init__.py", line 21, in <module>
    from fairseq.logging import meters, metrics, progress_bar  # noqa
  File "D:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\fairseq\logging\progress_bar.py", line 479, in <module>
    import wandb
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\__init__.py", line 5, in <module>
    from .wandb_artifacts import Artifact  # noqa: F401
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\wandb_artifacts.py", line 33, in <module>
    from wandb.apis import InternalApi, PublicApi
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\wandb\apis\__init__.py", line 42, in <module>
    from .internal import Api as InternalApi  # noqa
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\wandb\apis\internal.py", line 1, in <module>
    from wandb.sdk.internal.internal_api import Api as InternalApi
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\internal\internal_api.py", line 38, in <module>
    from wandb.apis.normalize import normalize_exceptions
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\wandb\apis\normalize.py", line 13, in <module>
    from wandb.sdk.lib.mailbox import ContextCancelledError
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\lib\mailbox.py", line 102, in <module>
    class _MailboxSlot:
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\wandb\sdk\lib\mailbox.py", line 103, in _MailboxSlot
    _result: Optional[pb.Result]
AttributeError: module 'wandb.proto.wandb_internal_pb2' has no attribute 'Result'

D:\RVC1006Nvidia\RVC1006Nvidia>pause

**Comment by ClayShoaf** [comment]
This solved this problem for me: https://github.com/wandb/wandb/issues/7406#issuecomment-2082231447

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved. Fairseq is not import now.
