### ISSUE TITLE
No index/ .index file creation?

### ISSUE THREAD

**Issue by zaneburko** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2067]
I did everything properly. Let my model train, but I can't find the .index file. Anyone know a fix?

_______________________________________________________________________________________________________________

2024-05-19 14:12:25 | INFO | __main__ | Use Language: en_US
Running on local URL:  http://0.0.0.0:7865
IMPORTANT: You are using gradio version 4.23.0, however version 4.29.0 is available, please upgrade.
--------
2024-05-19 14:12:44 | WARNING | __main__ | assets/pretrained_v2/f0G48k.pth not exist, will not use pretrained model
2024-05-19 14:12:44 | WARNING | __main__ | assets/pretrained_v2/f0D48k.pth not exist, will not use pretrained model
2024-05-19 14:12:45 | WARNING | __main__ | assets/pretrained_v2/G48k.pth not exist, will not use pretrained model
2024-05-19 14:12:45 | WARNING | __main__ | assets/pretrained_v2/D48k.pth not exist, will not use pretrained model
2024-05-19 14:14:33 | INFO | __main__ | Execute: "D:\Users\zaneb\miniconda3\envs\rvc-env\python.exe" infer/modules/train/preprocess.py "C:\Users\zaneb\Downloads\Archive" 48000 3 "C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI/logs/zane" False 3.0
C:\Users\zaneb\Downloads\Archive 48000 3 C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI/logs/zane False 3.0
start preprocess
C:\Users\zaneb\Downloads\Archive 48000 3 C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI/logs/zane False 3.0
C:\Users\zaneb\Downloads\Archive 48000 3 C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI/logs/zane False 3.0
C:\Users\zaneb\Downloads\Archive 48000 3 C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI/logs/zane False 3.0
C:\Users\zaneb\Downloads\Archive/1_UNBOXING NIKE LOWCOAST DUNKS! _ Akashoe Unboxing _ Zane Burko_(Vocals).mp3   -> Traceback (most recent call last):
  File "C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI\infer\lib\audio.py", line 37, in load_audio
    ffmpeg.input(file, threads=0)
  File "D:\Users\zaneb\miniconda3\envs\rvc-env\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "D:\Users\zaneb\miniconda3\envs\rvc-env\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "D:\Users\zaneb\miniconda3\envs\rvc-env\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Users\zaneb\miniconda3\envs\rvc-env\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI\infer\modules\train\preprocess.py", line 83, in pipeline
    audio = load_audio(path, self.sr)
  File "C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI\infer\lib\audio.py", line 42, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 2] The system cannot find the file specified
C:\Users\zaneb\Downloads\Archive/3_UNBOXING BAPESTA MIST GREY_ROYAL PURPLE COURTSTAS! _ Fashoes Unboxing _ Zane Burko_(Vocals).mp3      -> Traceback (most recent call last):
  File "C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI\infer\lib\audio.py", line 37, in load_audio
    ffmpeg.input(file, threads=0)
  File "D:\Users\zaneb\miniconda3\envs\rvc-env\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "D:\Users\zaneb\miniconda3\envs\rvc-env\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "D:\Users\zaneb\miniconda3\envs\rvc-env\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Users\zaneb\miniconda3\envs\rvc-env\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI\infer\modules\train\preprocess.py", line 83, in pipeline
    audio = load_audio(path, self.sr)
  File "C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI\infer\lib\audio.py", line 42, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 2] The system cannot find the file specified

2024-05-19 14:19:22 | INFO | __main__ | Execute: "D:\Users\zaneb\miniconda3\envs\rvc-env\python.exe" infer/modules/train/extract_feature_print.py cpu 1 0 0 "C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI/logs/zane" v2 False
infer/modules/train/extract_feature_print.py cpu 1 0 0 C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI/logs/zane v2 False
exp_dir: C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI/logs/zane
load model(s) from assets/hubert/hubert_base.pt
2024-05-19 14:19:25 | INFO | fairseq.tasks.hubert_pretraining | current directory is C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI
2024-05-19 14:19:25 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2024-05-19 14:19:25 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
D:\Users\zaneb\miniconda3\envs\rvc-env\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
move model to cpu
no-feature-todo
2024-05-19 14:19:27 | INFO | __main__ | infer/modules/train/extract/extract_f0_print.py C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI/logs/zane 3 dio
no-f0-todo
no-f0-todo
no-f0-todo
infer/modules/train/extract_feature_print.py cpu 1 0 0 C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI/logs/zane v2 False
exp_dir: C:\Users\zaneb\Retrieval-based-Voice-Conversion-WebUI/logs/zane
load model(s) from assets/hubert/hubert_base.pt
move model to cpu
no-feature-todo

2024-05-19 14:19:56 | INFO | __main__ | Use gpus:
2024-05-19 14:19:56 | INFO | __main__ | No pretrained Generator
2024-05-19 14:19:56 | INFO | __main__ | No pretrained Discriminator
2024-05-19 14:19:56 | INFO | __main__ | Execute: "D:\Users\zaneb\miniconda3\envs\rvc-env\python.exe" infer/modules/train/train.py -e "zane" -sr 48k -f0 1 -bs 4 -te 350 -se 25   -l 1 -c 0 -sw 0 -v v2
NO GPU DETECTED: falling back to CPU - this may take a while
INFO:zane:{'data': {'filter_length': 2048, 'hop_length': 480, 'max_wav_value': 32768.0, 'mel_fmax': None, 'mel_fmin': 0.0, 'n_mel_channels': 128, 'sampling_rate': 48000, 'win_length': 2048, 'training_files': './logs\\zane/filelist.txt'}, 'model': {'filter_channels': 768, 'gin_channels': 256, 'hidden_channels': 192, 'inter_channels': 192, 'kernel_size': 3, 'n_heads': 2, 'n_layers': 6, 'p_dropout': 0, 'resblock': '1', 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'resblock_kernel_sizes': [3, 7, 11], 'spk_embed_dim': 109, 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [24, 20, 4, 4], 'upsample_rates': [12, 10, 2, 2], 'use_spectral_norm': False}, 'train': {'batch_size': 4, 'betas': [0.8, 0.99], 'c_kl': 1.0, 'c_mel': 45, 'epochs': 20000, 'eps': 1e-09, 'fp16_run': False, 'init_lr_ratio': 1, 'learning_rate': 0.0001, 'log_interval': 200, 'lr_decay': 0.999875, 'seed': 1234, 'segment_size': 17280, 'warmup_epochs': 0}, 'model_dir': './logs\\zane', 'experiment_dir': './logs\\zane', 'save_every_epoch': 25, 'name': 'zane', 'total_epoch': 350, 'pretrainG': '', 'pretrainD': '', 'version': 'v2', 'gpus': '0', 'sample_rate': '48k', 'if_f0': 1, 'if_latest': 1, 'save_every_weights': '0', 'if_cache_data_in_gpu': 0}
D:\Users\zaneb\miniconda3\envs\rvc-env\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
DEBUG:infer.lib.infer_pack.models:gin_channels: 256, self.spk_embed_dim: 109
D:\Users\zaneb\miniconda3\envs\rvc-env\lib\site-packages\torch\autograd\graph.py:744: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [64, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [64, 1, 4], strides() = [4, 4, 1] (Triggered internally at ..\torch\csrc\distributed\c10d\reducer.cpp:339.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:zane:Train Epoch: 1 [0%]
INFO:zane:[0, 0.0001]
INFO:zane:loss_disc=8.836, loss_gen=7.659, loss_fm=0.130,loss_mel=75.000, loss_kl=9.000
DEBUG:matplotlib:matplotlib data path: D:\Users\zaneb\miniconda3\envs\rvc-env\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\zaneb\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:root:Saving model and optimizer state at epoch 350 to ./logs\zane\G_2333333.pth
INFO:root:Saving model and optimizer state at epoch 350 to ./logs\zane\D_2333333.pth
INFO:zane:====> Epoch: 350 [2024-05-19 15:04:02] | (0:00:08.492908)
INFO:zane:Training is done. The program is closed.
INFO:zane:saving final ckpt:Success.

**Comment by fumiama** [comment]
> ... assets/pretrained_v2/f0G48k.pth not exist ...
> FileNotFoundError: [WinError 2] The system cannot find the file specified

Please read the README carefully. You said that you `did everything properly`, but it's clear that you missed to download the pre-models, which is mentioned in README.
