### ISSUE TITLE
维度错误

### ISSUE THREAD

**Issue by Linzsd** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#207]
INFO:wuhaiyuan:Train Epoch: 1 [0%]
INFO:wuhaiyuan:[0, 0.0001]
INFO:wuhaiyuan:loss_disc=3.236, loss_gen=2.090, loss_fm=7.873,loss_mel=29.727, loss_kl=5.000
DEBUG:matplotlib:matplotlib data path: D:\AI_tools\AI_voice\RVC-beta\runtime\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\armstrong\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
max value is  tensor(1.0557)
max value is  tensor(1.0731)
min value is  tensor(-1.0961)
max value is  tensor(1.0621)
min value is  tensor(-1.1016)
max value is  tensor(1.0267)
max value is  tensor(1.1027)
min value is  tensor(-1.0728)
max value is  tensor(1.0153)
max value is  tensor(1.0287)
max value is  tensor(1.0392)
max value is  tensor(1.0548)
INFO:wuhaiyuan:Train Epoch: 1 [46%]
INFO:wuhaiyuan:[200, 0.0001]
INFO:wuhaiyuan:loss_disc=3.257, loss_gen=2.212, loss_fm=9.587,loss_mel=25.851, loss_kl=2.643
Traceback (most recent call last):
  File "D:\AI_tools\AI_voice\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 534, in <module>
    main()
  File "D:\AI_tools\AI_voice\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 50, in main
    mp.spawn(
  File "D:\AI_tools\AI_voice\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\AI_tools\AI_voice\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "D:\AI_tools\AI_voice\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\AI_tools\AI_voice\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "D:\AI_tools\AI_voice\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 188, in run
    train_and_evaluate(
  File "D:\AI_tools\AI_voice\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 356, in train_and_evaluate
    ) = net_g(phone, phone_lengths, pitch, pitchf, spec, spec_lengths, sid)
  File "D:\AI_tools\AI_voice\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AI_tools\AI_voice\RVC-beta\runtime\lib\site-packages\torch\nn\parallel\distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "D:\AI_tools\AI_voice\RVC-beta\runtime\lib\site-packages\torch\nn\parallel\distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "D:\AI_tools\AI_voice\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AI_tools\AI_voice\RVC-beta\runtime\lib\site-packages\infer_pack\models.py", line 541, in forward
    z_slice, ids_slice = commons.rand_slice_segments(
  File "D:\AI_tools\AI_voice\RVC-beta\runtime\lib\site-packages\infer_pack\commons.py", line 66, in rand_slice_segments
    ret = slice_segments(x, ids_str, segment_size)
  File "D:\AI_tools\AI_voice\RVC-beta\runtime\lib\site-packages\infer_pack\commons.py", line 49, in slice_segments
    ret[i] = x[i, :, idx_str:idx_end]
RuntimeError: The expanded size of the tensor (32) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [192, 32].  Tensor sizes: [192, 0]
这是什么情况？？batchsize设为2

**Comment by RVC-Boss** [comment]
看看你的logs/实验名/0_wavs_gt文件夹下面，是否存在文件大小极小的文件？

**Comment by Linzsd** [comment]
> 

最大的是2_5.spec.pt文件，1586kb
最小的0_284.wav文件，24kb

**Comment by Linzsd** [comment]
我之前使用的音频文件是b站下载的直播音频，现在我也是从b站下载5个音乐视频，发现可以正常训练模型了，每个wav文件4-5分钟，大约40-50mb。可能是之前有一个17秒的音频，太小了
