### ISSUE TITLE
slow_conv2d_cpu not implemented for 'Half'

### ISSUE THREAD

**Issue by Mangio621** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#210]
Hey all!
I decided to clone the repo onto my windows machine. After installing, I ran infer-web.py and launched the GUI on localhost. After doing so, I selected my model and my source audio with "pm". After pressing convert, i get the following error:

```
Running on local URL:  http://0.0.0.0:3000
loading weights/kanye2333333.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
2023-05-01 21:17:01 | INFO | fairseq.tasks.hubert_pretraining | current directory is G:\Documents\01AI\Voice2VoiceAI\clones\Retrieval-based-Voice-Conversion-WebUI
2023-05-01 21:17:01 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-05-01 21:17:01 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
Traceback (most recent call last):
  File "G:\Documents\01AI\Voice2VoiceAI\clones\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 158, in vc_single
    audio_opt = vc.pipeline(
  File "G:\Documents\01AI\Voice2VoiceAI\clones\Retrieval-based-Voice-Conversion-WebUI\vc_infer_pipeline.py", line 289, in pipeline
    self.vc(
  File "G:\Documents\01AI\Voice2VoiceAI\clones\Retrieval-based-Voice-Conversion-WebUI\vc_infer_pipeline.py", line 119, in vc
    logits = model.extract_features(**inputs)
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\fairseq\models\hubert\hubert.py", line 535, in extract_features
    res = self.forward(
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\fairseq\models\hubert\hubert.py", line 437, in forward
    features = self.forward_features(source)
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\fairseq\models\hubert\hubert.py", line 392, in forward_features
    features = self.feature_extractor(source)
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\fairseq\models\wav2vec\wav2vec2.py", line 895, in forward
    x = conv(x)
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

Traceback (most recent call last):
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1236, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\components.py", line 2536, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\processing_utils.py", line 160, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\Cole Mangio\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\processing_utils.py", line 174, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```

I suspect this is an issue with my CPU? I'm not too sure. I didn't have this problem when using a linux machine however. Some people were getting similar runtime errors with whisper however, by changing fp16=false? I'm not too sure what to do at this point...

**Comment by Mangio621** [comment]
I found a solution! For anyone trying to run infer_web.py on their windows system, it seems that the property "is_half" is being set to True for some reason. Simply inserting below line 82 (config = Config()) in infer_web.py, insert `config.is_half=False` below it to use the g.float instead of g.half on the get_vc function.

**Enhancement Proposal**
Perhaps we could add a very small enhancement to infer_web.py by adding another flag to force the value of is_half if need be. Potentially something like --use_half or --use_float. Especially for anyone that has windows systems and are inferring locally...

**Comment by Mangio621** [comment]
Better yet, instead of modifying the infer-web.py script, modifiy the config.py script and simply set self.is_half=True to self.is_half=False.

**Comment by Mangio621** [comment]
Better yet, instead of modifying the infer-web.py script, modifiy the config.py script and simply set self.is_half=True to self.is_half=False.
