### ISSUE TITLE
Can't launch RVC

### ISSUE THREAD

**Issue by Shoctopus1** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2112]
## Whenever I try to launch RVC, I get this error message. Do you have any beginner-friendly tips on how to resolve this? I'll probably need to add some paths to the infer-web.py code but idk where to start or what to do. 

Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

 warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Retrieval-based-Voice-Conversion-WebUI-main\infer-web.py", line 8, in <module>
    from infer.modules.vc.modules import VC
  File "C:\Program Files (x86)\Retrieval-based-Voice-Conversion-WebUI-main\infer\modules\vc\modules.py", line 19, in <module>
    from infer.modules.vc.utils import *
  File "C:\Program Files (x86)\Retrieval-based-Voice-Conversion-WebUI-main\infer\modules\vc\utils.py", line 3, in <module>
    from fairseq import checkpoint_utils
  File "C:\Users\X\AppData\Roaming\Python\Python312\site-packages\fairseq\__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "C:\Users\X\AppData\Roaming\Python\Python312\site-packages\fairseq\distributed\__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "C:\Users\X\AppData\Roaming\Python\Python312\site-packages\fairseq\distributed\fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "C:\Users\X\AppData\Roaming\Python\Python312\site-packages\fairseq\dataclass\__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "C:\Users\X\AppData\Roaming\Python\Python312\site-packages\fairseq\dataclass\configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Program Files\Python312\Lib\dataclasses.py", line 1275, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Program Files\Python312\Lib\dataclasses.py", line 1265, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\dataclasses.py", line 994, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\dataclasses.py", line 852, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

**Comment by Husky110** [comment]
USe Python 3.10.x - Python 3.12 is not supported, since there are issues with it.

**Comment by Shoctopus1** [comment]
> USe Python 3.10.x - Python 3.12 is not supported, since there are issues with it.

### I downgraded again, but got a new error saying I'm missing "chardet" 

  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

### then the whole thing falls apart

**Comment by Shoctopus1** [comment]
> USe Python 3.10.x - Python 3.12 is not supported, since there are issues with it.

> USe Python 3.10.x - Python 3.12 is not supported, since there are issues with it.

### I downgraded again, but got a new error saying I'm missing "chardet" 

  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

### then the whole thing falls apart. Guess the python installation didn't get chardet when I asked for the "precompiled library". Either that or I forgot to check the box. 

### Thanks, it works again. cant believe a random failure of torch spiraled so far out of control
