### ISSUE TITLE
AttributeError: module 'infer.lib.infer_pack.modules' has no attribute 'LayerNorm'

### ISSUE THREAD

**Issue by AlgorithmicKing** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2123]
Hi guys, I am having a hard time solving this error:
Traceback (most recent call last):
  File "G:\AI\Voice-Cloning\infer-web.py", line 8, in <module>
    from infer.modules.vc.modules import VC
  File "G:\AI\Voice-Cloning\infer\modules\vc\modules.py", line 12, in <module>
    from infer.lib.infer_pack.models import (
  File "G:\AI\Voice-Cloning\infer\lib\infer_pack\models.py", line 13, in <module>
    from infer.lib.infer_pack import attentions, commons, modules
  File "G:\AI\Voice-Cloning\infer\lib\infer_pack\attentions.py", line 11, in <module>
    from infer.lib.infer_pack.modules import LayerNorm
ImportError: cannot import name 'LayerNorm' from 'infer.lib.infer_pack.modules' (G:\AI\Voice-Cloning\infer\lib\infer_pack\modules\__init__.py)

**Comment by RVC-Boss** [comment]
Did you clone the main branch?

**Comment by AlgorithmicKing** [comment]
i think so but ill check anyways

**Comment by AlgorithmicKing** [comment]
> Did you clone the main branch?

How do i know what version am i using?

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved.
