### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dragonmastercale** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2127]
When clicking on Train or one Click Train, I'm getting the following error, any help would be greatly appreciated!

Process Process-2:
Traceback (most recent call last):
  File "F:\RVC\RVC1006Nvidia\infer\modules\train\train.py", line 213, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "F:\RVC\RVC1006Nvidia\infer\lib\train\utils.py", line 213, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "F:\RVC\RVC1006Nvidia\infer\modules\train\train.py", line 232, in run
    logger.info(
UnboundLocalError: local variable 'logger' referenced before assignment
INFO:JimiHendrixV2:<All keys matched successfully>
INFO:JimiHendrixV2:loaded pretrained assets/pretrained_v2/f0D40k.pth
INFO:JimiHendrixV2:<All keys matched successfully>
F:\RVC\RVC1006Nvidia\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]

**Comment by FlynnHHH** [comment]
I got the same error.

**Comment by wenluqi** [comment]
im the I have the same problem

**Comment by Z3r0shin** [comment]
Has no one helped?
I am having a similar issue :

> 2025-02-06 14:12:43 | INFO | __main__ | Execute: "python.exe" infer/modules/train/preprocess.py "d:\bark\bark-with-voice-clone\Retrieval-based-Voice-Conversion-WebUI\CustomTrainedModels\Guillaume\" 48000 11 "D:\bark\bark-with-voice-clone\Retrieval-based-Voice-Conversion-WebUI/logs/mi-test" False 3.0
> d:\bark\bark-with-voice-clone\Retrieval-based-Voice-Conversion-WebUI\CustomTrainedModels\Guillaume" 48000 11 D:\bark\bark-with-voice-clone\Retrieval-based-Voice-Conversion-WebUI/logs/mi-test False 3.0
> Traceback (most recent call last):
>   File "D:\bark\bark-with-voice-clone\Retrieval-based-Voice-Conversion-WebUI\infer\modules\train\preprocess.py", line 11, in <module>
>     sr = int(sys.argv[2])
> IndexError: list index out of range

**Comment by DUMBCAT1986** [comment]
Also same issue. Installing RVC and re-editing all these scripts and downgrading/upgrading all dependencies all day has me thinking that shit is just broken lol

```
Traceback (most recent call last):
  File "\Retrieval-based-Voice-Conversion-WebUI\infer\modules\train\train.py", line 211, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "\Retrieval-based-Voice-Conversion-WebUI\infer\lib\train\utils.py", line 213, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range
```

Inside the utils.py at line 211-213, I find this: 
```
  f_list = glob.glob(os.path.join(dir_path, regex))
    f_list.sort(key=lambda f: int("".join(filter(str.isdigit, f))))
    x = f_list[-1]

```

**Comment by Dotinkasra** [comment]
@DUMBCAT1986 
I experienced the same issue

<img width="1296" height="404" alt="Image" src="https://github.com/user-attachments/assets/3cfa210b-eca7-41e8-b9d1-9caac5c5c9fe" />

but was able to resolve it using the following steps:

### Method

1. **Redownload the models**  
   - Navigate to the directories:  
     ```
     assets/pretrained
     assets/pretrained_v2
     ```  
   - Delete all models inside these two directories.  
   - Redownload the correct models from the following link and place them in the corresponding directories:  
     👉 [Hugging Face – lj1995/VoiceConversionWebUI](https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main)

2. **Reinstall `matplotlib` with a specific version**  
   ```bash
   pip install matplotlib==3.9.4

This worked for me.
However, an “Error” message still appears in the WebUI, but I can confirm that everything functions correctly when running from the command line.

<img width="2207" height="538" alt="Image" src="https://github.com/user-attachments/assets/14048992-b8b5-417c-899f-a05e8dce54c4" />

**Comment by RVC-Boss** [comment]
Fixed now.
