### ISSUE TITLE
No audio input device error: ValueError: -1 is not in list.

### ISSUE THREAD

**Issue by Amazon90** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2129]
```
2024-06-13 16:20:28 | INFO | faiss.loader | Loading faiss with AVX2 support.
2024-06-13 16:20:28 | INFO | faiss.loader | Successfully loaded faiss with AVX2 support.
2024-06-13 16:20:28 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 4070 Ti
2024-06-13 16:20:28 | INFO | configs.config | Half-precision floating-point: True, device: cuda:0
Traceback (most recent call last):
  File "D:\Git\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 157, in load
    data = json.load(j)
  File "C:\Users\28622\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\28622\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\28622\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\28622\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Git\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 1070, in <module>
    gui = GUI()
  File "D:\Git\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 150, in __init__
    self.launcher()
  File "D:\Git\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 224, in launcher
    data = self.load()
  File "D:\Git\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 195, in load
    self.input_devices_indices.index(sd.default.device[0])
ValueError: -1 is not in list
請按任意鍵繼續 . . .
```
How can I adjust the code to skip the check and allow the program to continue running?

**Comment by yxlllc** [comment]
Now you can't start the real-time voice changing gui without a recording device.If you don't have a physical recording device, you can install at least one virtual device, such as using voicemeeter software
