### ISSUE TITLE
Spontaneous error when separating vocal/accompaniment.

### ISSUE THREAD

**Issue by PMykhailo** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2131]
This error happens to me spontaneously both on Windows and Linux. On Windows I managed to do separation, training and inference before this error occurred. After it did I wasn't able to get fix it. I decided to switch to Linux - separation worked once but now I see the same result.
 Here error text:

```
audio.mp3.reformatted.wav->Traceback (most recent call last):
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 176, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 209, in __soundfile_load
    context = sf.SoundFile(path)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening '/workspace/Retrieval-based-Voice-Conversion-WebUI/TEMP/audio.mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/infer/modules/uvr5/modules.py", line 74, in uvr
    pre_fun._path_audio_(
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/infer/modules/uvr5/vr.py", line 63, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 184, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/librosa/util/decorators.py", line 59, in __wrapper
    return func(*args, **kwargs)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 240, in __audioread_load
    reader = audioread.audio_open(path)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/audioread/__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/audioread/rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/Retrieval-based-Voice-Conversion-WebUI/TEMP/audio.mp3.reformatted.wav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 176, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 209, in __soundfile_load
    context = sf.SoundFile(path)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening '/workspace/Retrieval-based-Voice-Conversion-WebUI/TEMP/audio.mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/infer/modules/uvr5/modules.py", line 82, in uvr
    pre_fun._path_audio_(
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/infer/modules/uvr5/vr.py", line 63, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 184, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/librosa/util/decorators.py", line 59, in __wrapper
    return func(*args, **kwargs)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 240, in __audioread_load
    reader = audioread.audio_open(path)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/audioread/__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/audioread/rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/Retrieval-based-Voice-Conversion-WebUI/TEMP/audio.mp3.reformatted.wav'
```

**Comment by PMykhailo** [comment]
Reinstated ffmpeg. Now it works but only when I upload music as file, but not when I specify folder path
