### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by keegang6705** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2134]
2024-06-16 20:55:29 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "C:\RVC\RVC1006Nvidia\infer\modules\vc\modules.py", line 185, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "C:\RVC\RVC1006Nvidia\infer\modules\vc\pipeline.py", line 410, in pipeline
    self.vc(
  File "C:\RVC\RVC1006Nvidia\infer\modules\vc\pipeline.py", line 235, in vc
    score, ix = index.search(npy, k=8)
  File "C:\RVC\RVC1006Nvidia\runtime\lib\site-packages\faiss\__init__.py", line 341, in replacement_search
    assert d == self.d
AssertionError

Traceback (most recent call last):
  File "C:\RVC\RVC1006Nvidia\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\RVC\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\RVC\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\RVC\RVC1006Nvidia\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\RVC\RVC1006Nvidia\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\RVC\RVC1006Nvidia\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by danielrzad** [comment]
I've got the same issue.

**Comment by RitterKW** [comment]
pip install gradio==3.48.0
