### ISSUE TITLE
Docker build results in non-working container due to incompatible version of numpy (2.x instead of 1.x)

### ISSUE THREAD

**Issue by CoolSpot** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2136]
### Steps to reproduce:
1) git clone git@github.com:RVC-Project/Retrieval-based-Voice-Conversion-WebUI.git
2) cd Retrieval-based-Voice-Conversion-WebUI
3) docker compose build
4) docker compose up

### Output
```> docker compose up
WARN[0000] /home/user/Documents/code/Retrieval-based-Voice-Conversion-WebUI/docker-compose.yml: `version` is obsolete 
[+] Running 1/0
 ✔ Container rvc  Created                                                                                                                                                       0.0s 
Attaching to rvc
rvc  | 
rvc  | ==========
rvc  | == CUDA ==
rvc  | ==========
rvc  | 
rvc  | CUDA Version 11.6.2
rvc  | 
rvc  | Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
rvc  | 
rvc  | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
rvc  | By pulling and using the container, you accept the terms and conditions of this license:
rvc  | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
rvc  | 
rvc  | A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
rvc  | 
rvc  | 
rvc  | A module that was compiled using NumPy 1.x cannot be run in
rvc  | NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
rvc  | versions of NumPy, modules must be compiled with NumPy 2.0.
rvc  | Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
rvc  | 
rvc  | If you are a user of the module, the easiest solution will be to
rvc  | downgrade to 'numpy<2' or try to upgrade the affected module.
rvc  | We expect that some modules will need time to support NumPy 2.
rvc  | 
rvc  | Traceback (most recent call last):  File "/app/infer-web.py", line 8, in <module>
rvc  |     from infer.modules.vc.modules import VC
rvc  |   File "/app/infer/modules/vc/modules.py", line 18, in <module>
rvc  |     from infer.modules.vc.pipeline import Pipeline
rvc  |   File "/app/infer/modules/vc/pipeline.py", line 11, in <module>
rvc  |     import faiss
rvc  |   File "/usr/local/lib/python3.9/dist-packages/faiss/__init__.py", line 16, in <module>
rvc  |     from .loader import *
rvc  |   File "/usr/local/lib/python3.9/dist-packages/faiss/loader.py", line 87, in <module>
rvc  |     from .swigfaiss_avx2 import *
rvc  |   File "/usr/local/lib/python3.9/dist-packages/faiss/swigfaiss_avx2.py", line 10, in <module>
rvc  |     from . import _swigfaiss_avx2
rvc  | AttributeError: _ARRAY_API not found
rvc  | 
rvc  | A module that was compiled using NumPy 1.x cannot be run in
rvc  | NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
rvc  | versions of NumPy, modules must be compiled with NumPy 2.0.
rvc  | Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
rvc  | 
rvc  | If you are a user of the module, the easiest solution will be to
rvc  | downgrade to 'numpy<2' or try to upgrade the affected module.
rvc  | We expect that some modules will need time to support NumPy 2.
rvc  | 
rvc  | Traceback (most recent call last):  File "/app/infer-web.py", line 8, in <module>
rvc  |     from infer.modules.vc.modules import VC
rvc  |   File "/app/infer/modules/vc/modules.py", line 18, in <module>
rvc  |     from infer.modules.vc.pipeline import Pipeline
rvc  |   File "/app/infer/modules/vc/pipeline.py", line 11, in <module>
rvc  |     import faiss
rvc  |   File "/usr/local/lib/python3.9/dist-packages/faiss/__init__.py", line 16, in <module>
rvc  |     from .loader import *
rvc  |   File "/usr/local/lib/python3.9/dist-packages/faiss/loader.py", line 98, in <module>
rvc  |     from .swigfaiss import *
rvc  |   File "/usr/local/lib/python3.9/dist-packages/faiss/swigfaiss.py", line 10, in <module>
rvc  |     from . import _swigfaiss
rvc  | AttributeError: _ARRAY_API not found
rvc  | Traceback (most recent call last):
rvc  |   File "/app/infer-web.py", line 8, in <module>
rvc  |     from infer.modules.vc.modules import VC
rvc  |   File "/app/infer/modules/vc/modules.py", line 18, in <module>
rvc  |     from infer.modules.vc.pipeline import Pipeline
rvc  |   File "/app/infer/modules/vc/pipeline.py", line 11, in <module>
rvc  |     import faiss
rvc  |   File "/usr/local/lib/python3.9/dist-packages/faiss/__init__.py", line 16, in <module>
rvc  |     from .loader import *
rvc  |   File "/usr/local/lib/python3.9/dist-packages/faiss/loader.py", line 98, in <module>
rvc  |     from .swigfaiss import *
rvc  |   File "/usr/local/lib/python3.9/dist-packages/faiss/swigfaiss.py", line 10, in <module>
rvc  |     from . import _swigfaiss
rvc  | ImportError: numpy.core.multiarray failed to import
rvc exited with code 1
```

### Cause
As explained on [numpy website](https://numpy.org/devdocs/user/troubleshooting-importerror.html), it is caused by using numpy 2.x when numpy 1.x is expected:

> If you see a message such as:
>
> A module that was compiled using NumPy 1.x cannot be run in
> NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
> versions of NumPy, modules must be compiled with NumPy 2.0.
> Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
>
> 
> Either as an ImportError or with:
> 
> AttributeError: _ARRAY_API not found
> 
> Then you are using NumPy 2 together with a module that was build with NumPy 1. NumPy 2 made some changes that require rebuilding such modules to avoid possibly incorrect results or crashes.
> 
> As the error message suggests, the easiest solution is likely to downgrade NumPy to numpy<2. Alternatively, you can search the traceback (from the back) to find the first line that isn’t inside NumPy to see which module needs to be updated.
> 
> NumPy 2 was released in the first half of 2024 and especially smaller modules downstream are expected need time to adapt and publish a new version.

### Fix
In requirements.txt replace line
`numpy`
with
`numpy==1.26.4`

**Comment by alexanderjacuna** [comment]
This doesn't seem to be a workaround now. Tried this workaround just now and it errors out during the 'docker compose build'

```
0.871 Ignoring onnxruntime: markers 'sys_platform == "darwin"' don't match your environment                                                                                                                                       
1.244 Collecting aria2 (from -r requirements.txt (line 1))                                                                                                                                                                        
1.643   Downloading aria2-0.0.1b0-py3-none-manylinux_2_17_x86_64.whl.metadata (28 kB)                                                                                                                                             
1.812 Collecting joblib>=1.1.0 (from -r requirements.txt (line 2))                                                                                                                                                                
1.909   Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
2.218 Collecting numba==0.56.4 (from -r requirements.txt (line 3))
2.274   Downloading numba-0.56.4-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.8 kB)
2.697 Collecting numpy==1.26.4 (from -r requirements.txt (line 4))
2.789   Downloading numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
2.824      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.4 MB/s eta 0:00:00
3.139 Collecting scipy (from -r requirements.txt (line 5))
3.210   Downloading scipy-1.13.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
3.236      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.3 MB/s eta 0:00:00
3.352 Collecting librosa==0.9.1 (from -r requirements.txt (line 6))
3.435   Downloading librosa-0.9.1-py3-none-any.whl.metadata (6.9 kB)
3.619 Collecting llvmlite==0.39.0 (from -r requirements.txt (line 7))
3.749   Downloading llvmlite-0.39.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.7 kB)
3.818 Collecting fairseq==0.12.2 (from -r requirements.txt (line 8))
3.958   Downloading fairseq-0.12.2.tar.gz (9.6 MB)
6.578      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 3.7 MB/s eta 0:00:00
7.148   Installing build dependencies: started
12.52   Installing build dependencies: finished with status 'done'
12.52   Getting requirements to build wheel: started
12.70   Getting requirements to build wheel: finished with status 'done'
12.71   Installing backend dependencies: started
19.72   Installing backend dependencies: finished with status 'done'
19.73   Preparing metadata (pyproject.toml): started
20.06   Preparing metadata (pyproject.toml): finished with status 'done'
20.19 Collecting faiss-cpu==1.7.3 (from -r requirements.txt (line 9))
20.26   Downloading faiss_cpu-1.7.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.3 kB)
20.52 Collecting gradio==3.34.0 (from -r requirements.txt (line 10))
20.61   Downloading gradio-3.34.0-py3-none-any.whl.metadata (15 kB)
21.08 Collecting Cython (from -r requirements.txt (line 11))
21.18   Downloading Cython-3.0.11-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
21.26 Collecting pydub>=0.25.1 (from -r requirements.txt (line 12))
21.41   Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
21.52 Collecting soundfile>=0.12.1 (from -r requirements.txt (line 13))
21.59   Downloading soundfile-0.13.1-py2.py3-none-manylinux_2_28_x86_64.whl.metadata (16 kB)
21.73 Collecting ffmpeg-python>=0.2.0 (from -r requirements.txt (line 14))
21.79   Downloading ffmpeg_python-0.2.0-py3-none-any.whl.metadata (1.7 kB)
21.88 Collecting tensorboardX (from -r requirements.txt (line 15))
21.94   Downloading tensorboardX-2.6.2.2-py2.py3-none-any.whl.metadata (5.8 kB)
22.05 Collecting Jinja2>=3.1.2 (from -r requirements.txt (line 16))
22.10   Downloading jinja2-3.1.5-py3-none-any.whl.metadata (2.6 kB)
22.21 Collecting json5 (from -r requirements.txt (line 17))
22.29   Downloading json5-0.10.0-py3-none-any.whl.metadata (34 kB)
22.39 Collecting Markdown (from -r requirements.txt (line 18))
22.45   Downloading Markdown-3.7-py3-none-any.whl.metadata (7.0 kB)
22.74 Collecting matplotlib>=3.7.0 (from -r requirements.txt (line 19))
22.85   Downloading matplotlib-3.9.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
22.93 Collecting matplotlib-inline>=0.1.3 (from -r requirements.txt (line 20))
23.00   Downloading matplotlib_inline-0.1.7-py3-none-any.whl.metadata (3.9 kB)
23.17 Collecting praat-parselmouth>=0.4.2 (from -r requirements.txt (line 21))
23.25   Downloading praat_parselmouth-0.4.5-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (2.9 kB)
23.61 Collecting Pillow>=9.1.1 (from -r requirements.txt (line 22))
23.68   Downloading pillow-11.1.0-cp39-cp39-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
23.75 Collecting resampy>=0.4.2 (from -r requirements.txt (line 23))
23.80   Downloading resampy-0.4.3-py3-none-any.whl.metadata (3.0 kB)
24.09 Collecting scikit-learn (from -r requirements.txt (line 24))
24.15   Downloading scikit_learn-1.6.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
24.28 Collecting tensorboard (from -r requirements.txt (line 25))
24.35   Downloading tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
24.51 Collecting tqdm>=4.63.1 (from -r requirements.txt (line 26))
24.59   Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
24.60      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 54.7 MB/s eta 0:00:00
24.78 Collecting tornado>=6.1 (from -r requirements.txt (line 27))
24.84   Downloading tornado-6.4.2-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
24.96 Collecting Werkzeug>=2.2.3 (from -r requirements.txt (line 28))
25.03   Downloading werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
25.11 Collecting uc-micro-py>=1.0.1 (from -r requirements.txt (line 29))
25.17   Downloading uc_micro_py-1.0.3-py3-none-any.whl.metadata (2.0 kB)
25.27 Collecting sympy>=1.11.1 (from -r requirements.txt (line 30))
25.36   Downloading sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
25.46 Collecting tabulate>=0.8.10 (from -r requirements.txt (line 31))
25.59   Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
25.76 Collecting PyYAML>=6.0 (from -r requirements.txt (line 32))
25.81   Downloading PyYAML-6.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
25.95 Collecting pyasn1>=0.4.8 (from -r requirements.txt (line 33))
26.03   Downloading pyasn1-0.6.1-py3-none-any.whl.metadata (8.4 kB)
26.16 Collecting pyasn1-modules>=0.2.8 (from -r requirements.txt (line 34))
26.25   Downloading pyasn1_modules-0.4.1-py3-none-any.whl.metadata (3.5 kB)
26.37 Collecting fsspec>=2022.11.0 (from -r requirements.txt (line 35))
26.43   Downloading fsspec-2025.2.0-py3-none-any.whl.metadata (11 kB)
26.52 Collecting absl-py>=1.2.0 (from -r requirements.txt (line 36))
26.58   Downloading absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
26.67 Collecting audioread (from -r requirements.txt (line 37))
26.75   Downloading audioread-3.0.1-py3-none-any.whl.metadata (8.4 kB)
26.91 Collecting uvicorn>=0.21.1 (from -r requirements.txt (line 38))
27.03   Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
27.12 Collecting colorama>=0.4.5 (from -r requirements.txt (line 39))
27.18   Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
27.28 Collecting pyworld==0.3.2 (from -r requirements.txt (line 40))
27.37   Downloading pyworld-0.3.2.tar.gz (214 kB)
27.40      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.4/214.4 kB 9.5 MB/s eta 0:00:00
27.46   Installing build dependencies: started
32.60   Installing build dependencies: finished with status 'done'
32.61   Getting requirements to build wheel: started
32.89   Getting requirements to build wheel: finished with status 'done'
32.90   Preparing metadata (pyproject.toml): started
33.19   Preparing metadata (pyproject.toml): finished with status 'done'
33.30 Collecting httpx (from -r requirements.txt (line 41))
33.37   Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
33.45 Collecting onnxruntime-gpu (from -r requirements.txt (line 43))
33.50   Downloading onnxruntime_gpu-1.19.2-cp39-cp39-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.5 kB)
33.60 Collecting torchcrepe==0.0.20 (from -r requirements.txt (line 44))
33.67   Downloading torchcrepe-0.0.20-py3-none-any.whl.metadata (7.8 kB)
33.88 Collecting fastapi==0.88 (from -r requirements.txt (line 45))
33.95   Downloading fastapi-0.88.0-py3-none-any.whl.metadata (24 kB)
34.06 Collecting torchfcpe (from -r requirements.txt (line 46))
34.13   Downloading torchfcpe-0.0.4-py3-none-any.whl.metadata (2.0 kB)
34.20 Collecting ffmpy==0.3.1 (from -r requirements.txt (line 47))
34.26   Downloading ffmpy-0.3.1.tar.gz (5.5 kB)
34.28   Preparing metadata (setup.py): started
34.45   Preparing metadata (setup.py): finished with status 'done'
34.56 Collecting python-dotenv>=1.0.0 (from -r requirements.txt (line 48))
34.62   Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
34.81 Collecting av (from -r requirements.txt (line 49))
34.87   Downloading av-14.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.7 kB)
34.88 INFO: pip is looking at multiple versions of numba to determine which version is compatible with other requirements. This could take a while.
34.88 ERROR: Cannot install -r requirements.txt (line 3) and numpy==1.26.4 because these package versions have conflicting dependencies.
34.88 
34.88 The conflict is caused by:
34.88     The user requested numpy==1.26.4
34.88     numba 0.56.4 depends on numpy<1.24 and >=1.18
34.88 
34.88 To fix this you could try to:
34.88 1. loosen the range of package versions you've specified
34.88 2. remove package versions to allow pip attempt to solve the dependency conflict
34.88 
34.88 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
35.32 
35.32 [notice] A new release of pip is available: 24.0 -> 25.0
35.32 [notice] To update, run: python3 -m pip install --upgrade pip
------
failed to solve: process "/bin/sh -c python3 -m pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
```

**Comment by CoolSpot** [comment]
@alexanderjacuna , try `numpy==1.*` instead
