### ISSUE TITLE
WinError 3 Error

### ISSUE THREAD

**Issue by JustCann** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2176]
I don't undertstand why I am receiving this error, any help would be greatly appreciated!

Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\train_nsf_sim_cache_sid_load_pretrain.py", line 108, in run
    train_dataset = TextAudioLoaderMultiNSFsid(hps.data.training_files, hps.data)
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\train\data_utils.py", line 27, in __init__
    self._filter()
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\train\data_utils.py", line 41, in _filter
    lengths.append(os.path.getsize(audiopath) // (3 * self.hop_length))
  File "genericpath.py", line 50, in getsize
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\alexi\\Retrieval-based-Voice-Conversion-WebUI-main/logs/mute/0_gt_wavs/mute48k.wav'

**Comment by JustCann** [comment]
I decided to manually add that folder to the specified directory and wav (because not sure why this is happening suddenly) and received the following

Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\train_nsf_sim_cache_sid_load_pretrain.py", line 223, in run
    train_and_evaluate(
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\train_nsf_sim_cache_sid_load_pretrain.py", line 275, in train_and_evaluate
    for batch_idx, info in enumerate(train_loader):
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\runtime\lib\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\runtime\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\runtime\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\runtime\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\runtime\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\runtime\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\runtime\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\train\data_utils.py", line 136, in __getitem__
    return self.get_audio_text_pair(self.audiopaths_and_text[index])
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\train\data_utils.py", line 57, in get_audio_text_pair
    phone, pitch, pitchf = self.get_labels(phone, pitch, pitchf)
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\train\data_utils.py", line 79, in get_labels
    phone = np.load(phone)
  File "C:\Users\alexi\Retrieval-based-Voice-Conversion-WebUI-main\runtime\lib\site-packages\numpy\lib\npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\alexi\\Retrieval-based-Voice-Conversion-WebUI-main/logs/mute/3_feature768/mute.npy'
