### ISSUE TITLE
Can't Use - Vocal/Accompaniment Separation & Reverberation Removal

### ISSUE THREAD

**Issue by Mani05gh008** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2178]
when it do all the process, It gives me this error instead of "Success".

~~~~~~~~~~~~~
Moneywox_ljly.mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 374, in uvr
    pre_fun._path_audio_(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 120, in _path_audio_
    wav_instrument = spec_utils.cmb_spectrogram_to_wave(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\lib\uvr5_pack\lib_v5\spec_utils.py", line 392, in cmb_spectrogram_to_wave
    wave = librosa.resample(
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 576, in resample
    util.valid_audio(y, mono=False)
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Python310\lib\site-packages\librosa\util\utils.py", line 294, in valid_audio
    raise ParameterError("Audio buffer is not finite everywhere")
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere
~~~~~~~~~~~~~
![image_2024-07-04_193338795](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/174731649/343b0b7a-1a16-4159-ae4a-1f0e2d5fbfe6)
~ScreenShot~

I don't have any idea what to do, Please some one give a solution... 
~Thanks ;)

**Comment by Mani05gh008** [comment]
And of course it doesn't gives me any files at the "opt" folder
