### ISSUE TITLE
RuntimeError: The expanded size of the tensor (17280) must match the existing size (16080) at non-singleton dimension 1.  

### ISSUE THREAD

**Issue by ParkSoran** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2186]
训练过程报错并中断：
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "E:\BaiduNetdiskDownload\RVC0813Nvidia\train_nsf_sim_cache_sid_load_pretrain.py", line 228, in run
    train_and_evaluate(
  File "E:\BaiduNetdiskDownload\RVC0813Nvidia\train_nsf_sim_cache_sid_load_pretrain.py", line 430, in train_and_evaluate
    wave = commons.slice_segments(
  File "E:\BaiduNetdiskDownload\RVC0813Nvidia\lib\infer_pack\commons.py", line 49, in slice_segments
    ret[i] = x[i, :, idx_str:idx_end]
RuntimeError: The expanded size of the tensor (17280) must match the existing size (16080) at non-singleton dimension 1.  Target sizes: [1, 17280].  Tensor sizes: [16080]

**Comment by heartgold512** [comment]
same problem. Managed to fix it? RuntimeError: The expanded size of the tensor (12800) must match the existing size (12400) at non-singleton dimension 1.  Target sizes: [1, 12800].  Tensor sizes: [12400]

**Comment by heartgold512** [comment]
alright alright so turns out if you increase number of epoches and frequency it will work? i also only left one file in..it could of also been that idk

**Comment by heartgold512** [comment]
2024-07-23 01:05:48 | INFO | __main__ | Use gpus: 0
2024-07-23 01:05:48 | INFO | __main__ | Execute: "C:\Users\Bradley\Desktop\RVC normal\Retrieval-based-Voice-Conversion-WebUI\env\Scripts\python.exe" infer/modules/train/train.py -e "Kurisu4" -sr 40k -f0 1 -bs 12 -g 0 -te 250 -se 50 -pg assets/pretrained_v2/f0G40k.pth -pd assets/pretrained_v2/f0D40k.pth -l 0 -c 0 -sw 1 -v v2
INFO:Kurisu4:{'data': {'filter_length': 2048, 'hop_length': 400, 'max_wav_value': 32768.0, 'mel_fmax': None, 'mel_fmin': 0.0, 'n_mel_channels': 125, 'sampling_rate': 40000, 'win_length': 2048, 'training_files': './logs\\Kurisu4/filelist.txt'}, 'model': {'filter_channels': 768, 'gin_channels': 256, 'hidden_channels': 192, 'inter_channels': 192, 'kernel_size': 3, 'n_heads': 2, 'n_layers': 6, 'p_dropout': 0, 'resblock': '1', 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'resblock_kernel_sizes': [3, 7, 11], 'spk_embed_dim': 109, 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'upsample_rates': [10, 10, 2, 2], 'use_spectral_norm': False}, 'train': {'batch_size': 12, 'betas': [0.8, 0.99], 'c_kl': 1.0, 'c_mel': 45, 'epochs': 20000, 'eps': 1e-09, 'fp16_run': False, 'init_lr_ratio': 1, 'learning_rate': 0.0001, 'log_interval': 200, 'lr_decay': 0.999875, 'seed': 1234, 'segment_size': 12800, 'warmup_epochs': 0}, 'model_dir': './logs\\Kurisu4', 'experiment_dir': './logs\\Kurisu4', 'save_every_epoch': 50, 'name': 'Kurisu4', 'total_epoch': 250, 'pretrainG': 'assets/pretrained_v2/f0G40k.pth', 'pretrainD': 'assets/pretrained_v2/f0D40k.pth', 'version': 'v2', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 1, 'if_latest': 0, 'save_every_weights': '1', 'if_cache_data_in_gpu': 0}
C:\Users\Bradley\Desktop\RVC normal\Retrieval-based-Voice-Conversion-WebUI\env\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
DEBUG:infer.lib.infer_pack.models:gin_channels: 256, self.spk_embed_dim: 109
INFO:Kurisu4:loaded pretrained assets/pretrained_v2/f0G40k.pth
INFO:Kurisu4:<All keys matched successfully>
INFO:Kurisu4:loaded pretrained assets/pretrained_v2/f0D40k.pth
INFO:Kurisu4:<All keys matched successfully>
C:\Users\Bradley\Desktop\RVC normal\Retrieval-based-Voice-Conversion-WebUI\env\lib\site-packages\torch\autograd\graph.py:744: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [64, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [64, 1, 4], strides() = [4, 4, 1] (Triggered internally at ..\torch\csrc\distributed\c10d\reducer.cpp:339.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:Kurisu4:Train Epoch: 1 [0%]
INFO:Kurisu4:[0, 0.0001]
INFO:Kurisu4:loss_disc=4.232, loss_gen=3.885, loss_fm=11.284,loss_mel=30.124, loss_kl=9.000
DEBUG:matplotlib:matplotlib data path: C:\Users\Bradley\Desktop\RVC normal\Retrieval-based-Voice-Conversion-WebUI\env\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\Bradley\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:Kurisu4:====> Epoch: 1 [2024-07-23 01:06:15] | (0:00:14.055517)
INFO:Kurisu4:====> Epoch: 2 [2024-07-23 01:06:18] | (0:00:03.216181)
INFO:Kurisu4:====> Epoch: 3 [2024-07-23 01:06:21] | (0:00:03.075652)
INFO:Kurisu4:====> Epoch: 4 [2024-07-23 01:06:24] | (0:00:02.695316)
INFO:Kurisu4:====> Epoch: 5 [2024-07-23 01:06:27] | (0:00:02.855017) etc i did this to 250

**Comment by weaponmasterjax** [comment]
> alright alright so turns out if you increase number of epoches and frequency it will work? i also only left one file in..it could of also been that idk

Same problem here, tho i dropped several files in and added some more later. Maybe that is causing the issue?
