### ISSUE TITLE
AttributeError: 'RVC' object has no attribute 'tgt_sr' 

### ISSUE THREAD

**Issue by fegerhagat** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2191]
**Program just freezes and this comes up on CMD**

```
C:\Users\Casper\Desktop\RVC1006AMD_Intel1>runtime\python.exe gui_v1.py --pycmd runtime\python.exe --dml
2024-07-14 23:31:54 | INFO | faiss.loader | Loading faiss.
2024-07-14 23:31:54 | INFO | faiss.loader | Successfully loaded faiss.
2024-07-14 23:31:55 | INFO | configs.config | No supported Nvidia GPU found
overwrite preprocess and configs.json
2024-07-14 23:31:56 | INFO | configs.config | Use DirectML instead
is_half:False, device:privateuseone:0
Input device: 4:VoiceMeeter Output (VB-Audio Vo (MME)
Output device: 19:Hoparlör (Realtek High Definition Audio) (Windows DirectSound)
cuda_is_available: False
Traceback (most recent call last):
  File "C:\Users\Casper\Desktop\RVC1006AMD_Intel1\tools\rvc_for_realtime.py", line 102, in __init__
    hubert_model = hubert_model.to(self.device)
  File "C:\Users\Casper\Desktop\RVC1006AMD_Intel1\runtime\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\Casper\Desktop\RVC1006AMD_Intel1\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Casper\Desktop\RVC1006AMD_Intel1\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Casper\Desktop\RVC1006AMD_Intel1\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "C:\Users\Casper\Desktop\RVC1006AMD_Intel1\runtime\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\Casper\Desktop\RVC1006AMD_Intel1\runtime\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError

Traceback (most recent call last):
  File "C:\Users\Casper\Desktop\RVC1006AMD_Intel1\gui_v1.py", line 954, in <module>
    gui = GUI()
  File "C:\Users\Casper\Desktop\RVC1006AMD_Intel1\gui_v1.py", line 134, in __init__
    self.launcher()
  File "C:\Users\Casper\Desktop\RVC1006AMD_Intel1\gui_v1.py", line 459, in launcher
    self.event_handler()
  File "C:\Users\Casper\Desktop\RVC1006AMD_Intel1\gui_v1.py", line 490, in event_handler
    self.start_vc()
  File "C:\Users\Casper\Desktop\RVC1006AMD_Intel1\gui_v1.py", line 636, in start_vc
    self.gui_config.samplerate = self.rvc.tgt_sr if self.gui_config.sr_type == "sr_model" else self.get_device_samplerate()
AttributeError: 'RVC' object has no attribute 'tgt_sr'
```

**Comment by danielrzad** [comment]
I've got the same issue.

**Comment by timwillhack** [comment]
you probably need to make sure hubert_base.pt is in the assets\hubert\ folder
