### ISSUE TITLE
模型推理时报错 Model inference error

### ISSUE THREAD

**Issue by nocookies111** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2206]
模型推理突然就不能用开始报错了，半小时前还好好的，之前也有人出过同样的问题，似乎并没有一个统一的解决方法
系统: Windows 10
CPU: AMD Ryzen 5 5500
内存: 32GB
显卡: NVIDIA GeForce RTX 4060
Model inference suddenly stopped working and started reporting errors. It was fine half an hour ago. Someone has had the same problem before, and there doesn't seem to be a unified solution.
OS: Windows 10
CPU: AMD Ryzen 5 5500
Memory: 32GB
GPU: NVIDIA GeForce RTX 4060
![{60286460-081B-4414-8B87-960454E20ED8}](https://github.com/user-attachments/assets/9a8e2f3a-0a7b-400f-b920-d76cab4e295e)
```python
2024-07-20 16:13:43 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "E:\RVC20240604Nvidia\infer\lib\audio.py", line 38, in load_audio
    ffmpeg.input(file, threads=0)
  File "E:\RVC20240604Nvidia\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\RVC20240604Nvidia\infer\modules\vc\modules.py", line 165, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "E:\RVC20240604Nvidia\infer\lib\audio.py", line 43, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "E:\RVC20240604Nvidia\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "E:\RVC20240604Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\RVC20240604Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "E:\RVC20240604Nvidia\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "E:\RVC20240604Nvidia\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "E:\RVC20240604Nvidia\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by nocookies111** [comment]
解决了，原来是输入音频文件路径时不能直接复制粘贴，要手动输入，一复制粘贴就会报错

**Comment by RVC-Boss** [comment]
这个问题在于你输入了错误的文件路径。现交互已改为拖拽音频解决。该问题不会再出现。
