### ISSUE TITLE
[BUG]AttributeError: 'RVC' object has no attribute 'tgt_sr'

### ISSUE THREAD

**Issue by DvoDan** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#222]
在使用gui.py並按下開始轉換音訊後閃退並回報以下錯誤
Traceback (most recent call last):
  File "C:\Users\Dian\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\gui.py", line 562, in <module>
    gui = GUI()
  File "C:\Users\Dian\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\gui.py", line 195, in __init__
    self.launcher()
  File "C:\Users\Dian\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\gui.py", line 340, in launcher
    self.event_handler()
  File "C:\Users\Dian\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\gui.py", line 352, in event_handler
    self.start_vc()
  File "C:\Users\Dian\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\gui.py", line 409, in start_vc
    orig_freq=self.rvc.tgt_sr,
AttributeError: 'RVC' object has no attribute 'tgt_sr'

**Comment by RVC-Boss** [comment]
模型选择错误，要选weights文件夹的60多MB的模型

**Comment by Siren124** [comment]
File "D:\RVC-beta-v2-0528\gui.py", line 611, in <module>
    gui = GUI()
  File "D:\RVC-beta-v2-0528\gui.py", line 246, in __init__
    self.launcher()
  File "D:\RVC-beta-v2-0528\gui.py", line 389, in launcher
    self.event_handler()
  File "D:\RVC-beta-v2-0528\gui.py", line 401, in event_handler
    self.start_vc()
  File "D:\RVC-beta-v2-0528\gui.py", line 458, in start_vc
    orig_freq=self.rvc.tgt_sr,
AttributeError: 'RVC' object has no attribute 'tgt_sr'
