### ISSUE TITLE
MacBook error

### ISSUE THREAD

**Issue by RhythyKim** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2226]
I’m trying to perform voice modulation after running ./run.sh on my MacBook, but I’m encountering the following error. What should I do?

Traceback (most recent call last):
  File "/Users/rhythy/Documents/AI/RVC-beta0717/my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ffmpeg/_run.py", line 313, in run
    process = run_async(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ffmpeg/_run.py", line 284, in run_async
    return subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infer-web.py", line 180, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "/Users/rhythy/Documents/AI/RVC-beta0717/my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [Errno 2] No such file or directory: 'ffmpeg'

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by duanxiaosheng** [comment]
我也是这个问题 ，没有找到解决方法

**Comment by AwesomeDevin** [comment]
+1
