### ISSUE TITLE
Operation in an environment where the GPU does not work

### ISSUE THREAD

**Issue by kagekiyo7** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#223]
associated with #210

CPU: Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz   2.00 GHz 
GPU: Intel(R) HD Graphics 520
displayed card info: 很遗憾您这没有能用的显卡来支持您训练
config.py: `device = "cpu"`
Ran the file: go-web.bat
Version: 20230428

Step 2b Error:
```Traceback (most recent call last):
  File "C:\RVC-beta\extract_feature_print.py", line 92, in <module>
    logits = model.extract_features(**inputs)
  File "C:\RVC-beta\runtime\lib\site-packages\fairseq\models\hubert\hubert.py", line 535, in extract_features
    res = self.forward(
  File "C:\RVC-beta\runtime\lib\site-packages\fairseq\models\hubert\hubert.py", line 437, in forward
    features = self.forward_features(source)
  File "C:\RVC-beta\runtime\lib\site-packages\fairseq\models\hubert\hubert.py", line 392, in forward_features
    features = self.feature_extractor(source)
  File "C:\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\RVC-beta\runtime\lib\site-packages\fairseq\models\wav2vec\wav2vec2.py", line 895, in forward
    x = conv(x)
  File "C:\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\RVC-beta\runtime\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\RVC-beta\runtime\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\RVC-beta\runtime\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
```
[full extract_f0_feature.log](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/11400296/extract_f0_feature.log)

**Comment by fumiama** [comment]
Only Nvidia CUDA is supported in training now.
