### ISSUE TITLE
Feature Extraction Log File Not Found... (in Step #2b)

### ISSUE THREAD

**Issue by kalbright3275** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2236]
Suddenly, when I attempted to extract the _F0-pitch_ feature during model training, I received the following error message in the running command console as displayed below.

_**Example:**_
```
runtime\python.exe extract_f0_print.py C:\Resources\RVC-Project\RVC Online Interface\Local\RVC-beta0717/logs/Kiki 3 harvest
Traceback (most recent call last):
  File "C:\Resources\RVC-Project\RVC Online Interface\Local\RVC-beta0717\extract_f0_print.py", line 22, in <module>
    n_p = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'Online'

runtime\python.exe extract_feature_print.py cpu 1 0  C:\Resources\RVC-Project\RVC Online Interface\Local\RVC-beta0717/logs/Kiki v2
Traceback (most recent call last):
  File "C:\Resources\RVC-Project\RVC Online Interface\Local\RVC-beta0717\extract_feature_print.py", line 29, in <module>    f = open("%s/extract_f0_feature.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'Online/extract_f0_feature.log'
```

Is there anything needed to be resolved in order that the program can find and recognize this "missing" file or something in particular?

**Comment by kalbright3275** [comment]
...Wait! I see the problem. Spaces were added in the subdirectory, **RVC Online Interface**.
(I'm so sorry...)
