### ISSUE TITLE
运行gui出错

### ISSUE THREAD

**Issue by M1saka10010** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#224]
```
(RVC) D:\RVC>python gui.py
2023-05-05 02:40:12 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2023-05-05 02:40:13 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-05 02:40:13 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-05 02:40:13 | INFO | faiss.loader | Loading faiss.
2023-05-05 02:40:13 | INFO | faiss.loader | Successfully loaded faiss.
Use Language: zh_CN
Traceback (most recent call last):
  File "D:\RVC\gui.py", line 562, in <module>
    gui = GUI()
  File "D:\RVC\gui.py", line 195, in __init__
    self.launcher()
  File "D:\RVC\gui.py", line 240, in launcher
    default_value=input_devices[sd.default.device[0]],
IndexError: list index out of range
```

**Comment by RVC-Boss** [comment]
@EntropyRiser 大佬看看
