### ISSUE TITLE
 warnings.warn('resource_tracker: There appear to be %d '

### ISSUE THREAD

**Issue by Serdcoff** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2262]
Hello dear all. I had an error. 
System: Ubuntu 24.04
GPU: 2x3090
Ram: 128Gb

Can you please help me, where I'm wrong?
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/saif/saif/Retrieval-based-Voice-Conversion-WebUI/infer/modules/train/train.py", line 282, in run
    train_and_evaluate(
  File "/home/saif/saif/Retrieval-based-Voice-Conversion-WebUI/infer/modules/train/train.py", line 496, in train_and_evaluate
    scaler.scale(loss_gen_all).backward()
  File "/home/saif/saif/venv/env398rvc/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/saif/saif/venv/env398rvc/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:589] Read error [127.0.1.1]:20909: Connection reset by peer
/usr/local/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 20 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by meisa233** [comment]
Same here

**Comment by simaek** [comment]
I solved this problem by installing faiss and all its dependencies via conda. BTW, my machine is a Macbook, which can be used as a reference.
