### ISSUE TITLE
RuntimeError: mat1 and mat2 must have the same dtype

### ISSUE THREAD

**Issue by Zufiinos** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2273]
`-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\Downloads\RVC\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "D:\Downloads\RVC\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 189, in run
    train_and_evaluate(
  File "D:\Downloads\RVC\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 357, in train_and_evaluate
    ) = net_g(phone, phone_lengths, pitch, pitchf, spec, spec_lengths, sid)
  File "D:\Downloads\RVC\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Downloads\RVC\RVC-beta\runtime\lib\site-packages\torch\nn\parallel\distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "D:\Downloads\RVC\RVC-beta\runtime\lib\site-packages\torch\nn\parallel\distributed.py", line 1113, in _run_ddp_forward
    return module_to_run(*inputs, **kwargs)
  File "D:\Downloads\RVC\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Downloads\RVC\RVC-beta\infer_pack\models.py", line 629, in forward
    o = self.dec(z_slice, pitchf, g=g)
  File "D:\Downloads\RVC\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Downloads\RVC\RVC-beta\infer_pack\models.py", line 493, in forward
    har_source, noi_source, uv = self.m_source(f0, self.upp)
  File "D:\Downloads\RVC\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Downloads\RVC\RVC-beta\infer_pack\models.py", line 416, in forward
    sine_merge = self.l_tanh(self.l_linear(sine_wavs))
  File "D:\Downloads\RVC\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Downloads\RVC\RVC-beta\runtime\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype`

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved.
