### ISSUE TITLE
sounddevice.PortAudioError: Error opening Stream: Invalid number of channels [PaErrorCode -9998]

### ISSUE THREAD

**Issue by 2NoobPlayer** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2286]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "E:\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 653, in soundinput
    with sd.Stream(
  File "E:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\sounddevice.py", line 1800, in __init__
    _StreamBase.__init__(self, kind='duplex', wrap_callback='array',
  File "E:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "E:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening Stream: Invalid number of channels [PaErrorCode -9998]

PLEASE HELP!!

**Comment by 2NoobPlayer** [comment]
Input Output device pairing fault. Found and  rectified the issue.
