### ISSUE TITLE
Getting corruption error when processing a file for training, but file is fine

### ISSUE THREAD

**Issue by StevieJ123** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2287]
Hello,
I have installed the software under Windows, and have verified installation of all parts including 

I am getting this error when clicking Process Data in the Training tab:

start preprocess
F:\Training\SRC/New MP3.mp3	-> Traceback (most recent call last):
  File "D:\Apps\Python\Retrieval-based-Voice-Conversion-WebUI-main\infer\lib\audio.py", line 43, in load_audio
    ffmpeg.input(file, threads=0)
  File "D:\Apps\Python310\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "D:\Apps\Python310\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "D:\Apps\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Apps\Python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 1392] The file or directory is corrupted and unreadable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Apps\Python\Retrieval-based-Voice-Conversion-WebUI-main\infer\modules\train\preprocess.py", line 83, in pipeline
    audio = load_audio(path, self.sr)
  File "D:\Apps\Python\Retrieval-based-Voice-Conversion-WebUI-main\infer\lib\audio.py", line 49, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 1392] The file or directory is corrupted and unreadable

end preprocess

I have tried proving the file in different formats, reconverting it etc. It plays just fine, so I can't see that being the issue. I've also tried other files.

I've also tried putting forward slashes to the file path etc., but it doesn't seem to help.
Your help would be much appreciated!

Thanks in advance,
Steve

**Comment by antT800** [comment]
I got the exact same issue. The versions of FFMPEG linked to on the install page are corrupted. I replaced it with my own downloaded version and it worked.
