### ISSUE TITLE
go-web.bat运行出错

### ISSUE THREAD

**Issue by ldcivan** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#229]
以下是报错内容
<pre>
runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Use Language: zh_CN
Traceback (most recent call last):
  File "C:\Users\ldciv\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\RVC-beta\infer-web.py", line 1238, in <module>
    choices=[i18n("是"), i18n("否")],
  File "C:\Users\ldciv\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\RVC-beta\i18n.py", line 25, in __call__
    return self.language_map[key]
KeyError: '是'
</pre>

感谢！

**Comment by ldcivan** [comment]
已解决，在./i18n/{对应语言代码}.json中，末尾添加：
<pre>
{
    ......,
    "是": "是",
    "否": "否",
    "每张显卡的batch_size":"每张显卡的batch_size"
}
</pre>
即可

**Comment by ldcivan** [comment]
将i18n.py中的内容更改为以下内容可以彻底解决因language map中查找不到内容而抛出错误：
<pre>
import locale
import json
import os


def load_language_list(language):
    with open(f"./i18n/{language}.json", "r", encoding="utf-8") as f:
        language_list = json.load(f)
    return language_list


class I18nAuto:
    def __init__(self, language=None):
        if language in ["Auto", None]:
            language = locale.getdefaultlocale()[
                0
            ]  # getlocale can't identify the system's language ((None, None))
        if not os.path.exists(f"./i18n/{language}.json"):
            language = "en_US"
        self.language = language
        print("Use Language:", language)
        self.language_map = load_language_list(language)

    def __call__(self, key):
        try:
            return self.language_map[key]
        except:
            return key

</pre>
