### ISSUE TITLE
D Model load error

### ISSUE THREAD

**Issue by Userccx** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2296]
我尝试进行训练但是返回了下面的错误，训练无法开始
Process Process-1:
Traceback (most recent call last):
  File "/root/rvc/RVC_train/infer/modules/train/train.py", line 210, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "/root/rvc/RVC_train/infer/lib/train/utils.py", line 213, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/wangfei/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/wangfei/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/rvc/RVC_train/infer/modules/train/train.py", line 230, in run
    net_g.module.load_state_dict(
  File "/root/anaconda3/envs/wangfei/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs768NSFsid:
        Missing key(s) in state_dict: "dec.m_source.l_linear.weight", "dec.m_source.l_linear.bias", "dec.noise_convs.0.weight", "dec.noise_convs.0.bias", "dec.noise_convs.1.weight", "dec.noise_convs.1.bias", "dec.noise_convs.2.weight", "dec.noise_convs.2.bias", "dec.noise_convs.3.weight", "dec.noise_convs.3.bias", "enc_p.emb_pitch.weight".

**Comment by pbanuru** [comment]
I'm getting this too
