### ISSUE TITLE
Error when using Rmvpe algorythm after installing with pinokio

### ISSUE THREAD

**Issue by phenix60** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2318]
i installed rvc using pinokio, everything seem to worked fine but when i tried to convert i was getting this error:

2024-09-21 13:15:51 | INFO | infer.modules.vc.pipeline | Loading rmvpe model,assets/rmvpe/rmvpe.pt
2024-09-21 13:15:51 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "D:\pinokio\api\rvc.pinokio.git\app\infer\modules\vc\modules.py", line 188, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "D:\pinokio\api\rvc.pinokio.git\app\infer\modules\vc\pipeline.py", line 354, in pipeline
    pitch, pitchf = self.get_f0(
  File "D:\pinokio\api\rvc.pinokio.git\app\infer\modules\vc\pipeline.py", line 149, in get_f0
    self.model_rmvpe = RMVPE(
  File "D:\pinokio\api\rvc.pinokio.git\app\infer\lib\rmvpe.py", line 563, in __init__
    self.model = get_default_model()
  File "D:\pinokio\api\rvc.pinokio.git\app\infer\lib\rmvpe.py", line 544, in get_default_model
    ckpt = torch.load(model_path, map_location="cpu")
  File "D:\pinokio\api\rvc.pinokio.git\app\env\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\pinokio\api\rvc.pinokio.git\app\env\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\pinokio\api\rvc.pinokio.git\app\env\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'assets/rmvpe/rmvpe.pt'

Traceback (most recent call last):
  File "D:\pinokio\api\rvc.pinokio.git\app\env\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\pinokio\api\rvc.pinokio.git\app\env\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\pinokio\api\rvc.pinokio.git\app\env\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\pinokio\api\rvc.pinokio.git\app\env\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "D:\pinokio\api\rvc.pinokio.git\app\env\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

i think it's just he doesn't found the rmvpe.pt, but i'm not sure how to correct this, other alogorythm seem to work but not this one. 
Here what i have in the assets/rmvpe directory folder
![image](https://github.com/user-attachments/assets/8e9b89a2-27f1-4b26-bb8b-9d8e19ca357d)
i hope u could help me solve this

**Comment by phenix60** [comment]
Sry i should've have look better on the main page of the project, found the rmvpe.pt add it to the folder requested now it work

**Comment by hackman1973** [comment]
Where did you get the file rmvpe.pt
