### ISSUE TITLE
Voice separation fails.

### ISSUE THREAD

**Issue by Gitgoodnowplease** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2324]
After 5.6/5.6 of separation processing got done this message was in the output information window. 

50 min audiofile to have music removed.wav.reformatted.wav->Traceback (most recent call last):
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 1213, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'E:\\Voice apps\\RVC1006Nvidia\\TEMP/50 min audiofile to have music removed.wav.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Voice apps\RVC1006Nvidia\infer\modules\uvr5\modules.py", line 74, in uvr
    pre_fun._path_audio_(
  File "E:\Voice apps\RVC1006Nvidia\infer\modules\uvr5\vr.py", line 63, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Voice apps\\RVC1006Nvidia\\TEMP/50 min audiofile to have music removed.wav.reformatted.wav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 1213, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'E:\\Voice apps\\RVC1006Nvidia\\TEMP/50 min audiofile to have music removed.wav.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Voice apps\RVC1006Nvidia\infer\modules\uvr5\modules.py", line 82, in uvr
    pre_fun._path_audio_(
  File "E:\Voice apps\RVC1006Nvidia\infer\modules\uvr5\vr.py", line 63, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "E:\Voice apps\RVC1006Nvidia\runtime\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Voice apps\\RVC1006Nvidia\\TEMP/50 min audiofile to have music removed.wav.reformatted.wav'

**Comment by akshaypai9091** [comment]
@Gitgoodnowplease Try this workaround. Worked for me.

Create a folder 'src' in extracted location, say E:\Voice apps\RVC1006Nvidia\src
paste the audio file in that.
Next edit the go-web.bat in notepad.
add below lines to switch to directory before the existing command. once modified that batch file should look like this.



-------------------
e:
E:\Voice apps\RVC1006Nvidia\
runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
pause
-----------------------------

save and close.
now right click on the go-web.bat and run ad admin.

Thats all , it should run all function without errors.
Ensure you create your working folders inside "E:\Voice apps\RVC1006Nvidia\" at all times.

Worked great for me.
Hope this helps.
