### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by mortistortoise** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2345]
I am on Ubuntu Linux with an NVIDIA Gpu. I've tried three installs, and consistently get the same exact error. RVC continuously fails at launch with said error. I have and have troubleshooted all the necessary files mentioned in previous issues (.env, infer-web.py, pyproject.toml, complete /logs/ directory, ffmpeg.exe (all at root)). yet the error persists.
The only thing I haven't tried is a full on python reinstall, which I'd prefer to save as a last resort.
Below is the full log:

`~/Documents/RVC1006Nvidia$ python3 infer-web.py
2024-10-10 16:58:22 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 4050 Laptop GPU`
`is_half:True, device:cuda:0`
`2024-10-10 16:58:23 | INFO | __main__ | Use Language: en_US`
`Traceback (most recent call last):`
 ` File "/home/tony/Documents/RVC1006Nvidia/infer-web.py", line 153, in <module>`
   ` lookup_indices(index_root)`
  `File "/home/tony/Documents/RVC1006Nvidia/infer-web.py", line 147, in lookup_indices`
  `  for root, dirs, files in os.walk(index_root, topdown=False):`
  `File "/usr/lib/python3.10/os.py", line 343, in walk
    return _walk(fspath(top), topdown, onerror, followlinks)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

Please let me know if you need any more information and I'll happily provide it. Thank you.

**Comment by mortistortoise** [comment]
I was able to fix this error and get it to successfully run. It is directly related to the `.env` file. Infer-web.py and run.sh won't recognize the `.env` file unless it is hidden (indicated by the dot at the beginning of the file in Unix OSes). In Linux, this is an easy fix by simply renaming the file with a period at the beginning.
I am not familiar with how to configure files to be hidden on other OSes, so you'd have to do independent research for that. But you can easily toubleshoot whether the file is hidden or not by clicking the option to reveal hidden files in your respective file explorer.
