### ISSUE TITLE
pip install error, aria2 issue on Mac Sonoma (silicon)

### ISSUE THREAD

**Issue by maxiedaniels** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2381]
Has anyone seen this error? I can't find it mentioned anywhere!!

```
Building wheels for collected packages: aria2
  Building wheel for aria2 (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/myuser/miniconda3/envs/rvc/bin/python /Users/myuser/miniconda3/envs/rvc/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/05/bzkf04vj585f_nw3nqbzhy0m0000gn/T/tmpwsfm8m4h
       cwd: /private/var/folders/05/bzkf04vj585f_nw3nqbzhy0m0000gn/T/pip-install-19xb4r5e/aria2_d580b6660b1e4523abeaf34feef311ac
  Complete output (19 lines):
  Traceback (most recent call last):
    File "/Users/myuser/miniconda3/envs/rvc/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/myuser/miniconda3/envs/rvc/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/myuser/miniconda3/envs/rvc/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/05/bzkf04vj585f_nw3nqbzhy0m0000gn/T/pip-build-env-380vsm6m/overlay/lib/python3.10/site-packages/hatchling/build.py", line 58, in build_wheel
      return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
    File "/private/var/folders/05/bzkf04vj585f_nw3nqbzhy0m0000gn/T/pip-build-env-380vsm6m/overlay/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 147, in build
      build_hook.initialize(version, build_data)
    File "/private/var/folders/05/bzkf04vj585f_nw3nqbzhy0m0000gn/T/pip-install-19xb4r5e/aria2_d580b6660b1e4523abeaf34feef311ac/hatch_build.py", line 132, in initialize
      aria2_tag = get_tag_4_build()
    File "/private/var/folders/05/bzkf04vj585f_nw3nqbzhy0m0000gn/T/pip-install-19xb4r5e/aria2_d580b6660b1e4523abeaf34feef311ac/hatch_build.py", line 110, in get_tag_4_build
      raise RuntimeError(msg)
  RuntimeError: Can't find tag for build.
  Please set 'WHL_PLATFORM' env var or run this building on supported platform.
      supported platform: manylinux_2_17_x86_64, musllinux_1_1_x86_64, manylinux_2_17_aarch64, musllinux_1_1_aarch64, win_amd64, win32

  ----------------------------------------
  ERROR: Failed building wheel for aria2
Failed to build aria2
ERROR: Could not build wheels for aria2 which use PEP 517 and cannot be installed directly
```

**Comment by GitHubbeginerTuring** [comment]
brew install aria2

**Comment by GitHubbeginerTuring** [comment]
貌似是因为aria2不兼容macos所以,要通过docker 模拟兼容的liunx版本来安装依赖再执行项目
