### ISSUE TITLE
Error to convert

### ISSUE THREAD

**Issue by elmathzen** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2410]
Hello, 

I have trained a model and try to convert a wav file. any model or wav file give me this issue. 

Any help please?

    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/.conda/envs/test/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/home/.conda/envs/test/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 420, in _upgrade_state_dict
    state["args"].task = "translation"
AttributeError: 'NoneType' object has no attribute 'task'

Traceback (most recent call last):
  File "/home/.conda/envs/test/lib/python3.8/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/.conda/envs/test/lib/python3.8/site-packages/gradio/blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/.conda/envs/test/lib/python3.8/site-packages/gradio/blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/.conda/envs/test/lib/python3.8/site-packages/gradio/components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "/home/.conda/envs/test/lib/python3.8/site-packages/gradio/components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

**Comment by aigc4o** [comment]
hey, have you solved this issue? I'm also struggling about it.

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue may have already been resolved. Fairseq is not need now.
