### ISSUE TITLE
伴奏人声分离报错RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by Caqlatufi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#242]
此外显卡3070没有认出来，是还不支持30系吗

启动日志：
```
F:\Retrieval-based-Voice-Conversion-WebUI>python.exe infer-web.py --pycmd python.exe --port 7897
Use Language: zh_CN
没有发现支持的N卡, 使用CPU进行推理
Running on local URL:  http://0.0.0.0:7897
```

报错详情：
```
out.m4a.reformatted.wav->Traceback (most recent call last):
  File "F:\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 287, in uvr
    pre_fun._path_audio_(inp_path, save_root_ins, save_root_vocal)
  File "F:\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 120, in _path_audio_
    pred, X_mag, X_phase = inference(
  File "F:\Retrieval-based-Voice-Conversion-WebUI\uvr5_pack\utils.py", line 78, in inference
    pred = _execute(
  File "F:\Retrieval-based-Voice-Conversion-WebUI\uvr5_pack\utils.py", line 49, in _execute
    pred = model.predict(X_mag_window, aggressiveness)
  File "F:\Retrieval-based-Voice-Conversion-WebUI\uvr5_pack\lib_v5\nets_61968KB.py", line 116, in predict
    h = self.forward(x_mag, aggressiveness)
  File "F:\Retrieval-based-Voice-Conversion-WebUI\uvr5_pack\lib_v5\nets_61968KB.py", line 69, in forward
    self.stg1_low_band_net(x[:, :, :bandw]),
  File "F:\Retrieval-based-Voice-Conversion-WebUI\uvr5_pack\lib_v5\nets_61968KB.py", line 24, in __call__
    h, e1 = self.enc1(x)
  File "F:\Retrieval-based-Voice-Conversion-WebUI\uvr5_pack\lib_v5\layers_123821KB.py", line 59, in __call__
    skip = self.conv1(x)
  File "F:\Retrieval-based-Voice-Conversion-WebUI\uvr5_pack\lib_v5\layers_123821KB.py", line 26, in __call__
    return self.conv(x)
  File "C:\Users\Caqlatufi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Caqlatufi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Users\Caqlatufi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Caqlatufi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\Caqlatufi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
```

**Comment by fumiama** [comment]
你可以先检查一下你的torch是否是支持cuda的版本
```
python
>>> import torch
>>> torch.cuda.is_available()
```
应当输出`True`

**Comment by Caqlatufi** [comment]
thanks，是torch和相关依赖的问题，已解决
