### ISSUE TITLE
训练失败，The server socket has failed to bind to [kodachi]:51545 (system error: 10013

### ISSUE THREAD

**Issue by KodachiGitHub** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#246]
启动web页面后，只改了实验名和训练文件夹路径，然后点击一键训练。后面报错提示端口占用，已经查过了，并没有程序占用51545端口。
系统是windows11，kodachi是我电脑名字
下面是log

INFO:qi:{'train': {'log_interval': 200, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 3, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 12800, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 40000, 'filter_length': 2048, 'hop_length': 400, 'win_length': 2048, 'n_mel_channels': 125, 'mel_fmin': 0.0, 'mel_fmax': None, 'training_files': './logs\\qi/filelist.txt'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 10, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'use_spectral_norm': False, 'gin_channels': 256, 'spk_embed_dim': 109}, 'model_dir': './logs\\qi', 'experiment_dir': './logs\\qi', 'save_every_epoch': 5, 'name': 'qi', 'total_epoch': 20, 'pretrainG': 'pretrained/f0G40k.pth', 'pretrainD': 'pretrained/f0D40k.pth', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 1, 'if_latest': 0, 'if_cache_data_in_gpu': 0}
WARNING:qi:G:\rvc\RVC-beta\train is not a git repository, therefore hash value comparison will be ignored.
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:426] [c10d] The server socket has failed to bind to [kodachi]:51545 (system error: 10013 - 以一种访问权限不允许的方式做了一个访问套接 字的尝试。).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:426] [c10d] The server socket has failed to bind to kodachi:51545 (system error: 10013 - 以一种访问权限不允许的方式做了一个访问套接字 的尝试。).
[E C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "G:\rvc\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 534, in <module>
    main()
  File "G:\rvc\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 50, in main
    mp.spawn(
  File "G:\rvc\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "G:\rvc\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "G:\rvc\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "G:\rvc\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "G:\rvc\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 69, in run
    dist.init_process_group(
  File "G:\rvc\RVC-beta\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 888, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "G:\rvc\RVC-beta\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 245, in _env_rendezvous_handler    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "G:\rvc\RVC-beta\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
RuntimeError

**Comment by megascans** [comment]
Getting the same issue here. Running on win10 in a virtual env, cuda pytorch

**Comment by denganliang** [comment]
你解决了没，我也遇到了

**Comment by ErtyHackward** [comment]
Just change port number in file `train_nsf_sim_cache_sid_load_pretrain.py` at line 71 to other value like  `os.environ["MASTER_PORT"] = "21545"`. That helped me
