### ISSUE TITLE
Error when converting PyTorch Model to ONNX

### ISSUE THREAD

**Issue by kodxana** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#251]
中文：
错误：将PyTorch模型转换为ONNX时出错
跟踪回溯信息显示以下错误：

跟踪回溯信息：
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 960, in export_onnx
    cpt["config"][-3] = cpt["weight"]["emb_g.weight"].shape[0]  # n_spk
KeyError: 'weight'
```
请问，这个问题的解决方案是什么？

英文：
Issue: Error when converting PyTorch Model to ONNX
While trying to convert PyTorch model to ONNX, the following error message appeared:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/workspace/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 960, in export_onnx
    cpt["config"][-3] = cpt["weight"]["emb_g.weight"].shape[0]  # n_spk
KeyError: 'weight'
```

What is the solution to this issue?

**Comment by RVC-Boss** [comment]
@NaruseMioShirakana 看看

**Comment by oreo-lp** [comment]
导入：assets/pretrained/D32k.pth这个模型进行onnx模型的转换报错，加载预训练模型不行呀，那需要加载哪个模型路径？
