### ISSUE TITLE
无法创建索引

### ISSUE THREAD

**Issue by koaqiu** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#256]
`ValueError: need at least one array to concatenate`

```
/root/miniconda3/envs/rvc/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:138: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Traceback (most recent call last):
  File "/root/miniconda3/envs/rvc/lib/python3.10/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/rvc/lib/python3.10/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/rvc/lib/python3.10/site-packages/gradio/blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/rvc/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/rvc/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/rvc/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/rvc/lib/python3.10/site-packages/gradio/utils.py", line 490, in async_iteration
    return next(iterator)
  File "/root/autodl-tmp/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 898, in train1key
    big_npy = np.concatenate(npys, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate
```

**Comment by RVC-Boss** [comment]
你看看3_feature256文件夹下有没有东西（或者有没有这个文件夹）

**Comment by koaqiu** [comment]
@RVC-Boss 有目录，空的

**Comment by RVC-Boss** [comment]
step2提特征有报错要截图我看下

**Comment by koaqiu** [comment]
> step2提特征有报错要截图我看下

我本地 windows下cpu跑 也是一样的错误，要不要我本地跑的数据

**Comment by marktiwnzhao** [comment]
I met the same problem. So, Is there a solution?

**Comment by coder-huo** [comment]
3060Ti，一样的问题。有什么解决办法吗？

**Comment by Chaoriticle** [comment]
一样的问题，使用的是autodl的3080，一键训练后webui显示error，单独点“索引”UI没有任何显示，控制台报错。实测weight文件夹生成了.py文件，但log文件夹中找不到index文件，控制台同样报错ValueError: need at least one array to concatenate 3_feature768文件夹下无任何内容，但是文件夹本身存在。

**Comment by Chaoriticle** [comment]
> 一样的问题，使用的是autodl的3080，一键训练后webui显示error，单独点“索引”UI没有任何显示，控制台报错。实测weight文件夹生成了.py文件，但log文件夹中找不到index文件，控制台同样报错ValueError: need at least one array to concatenate 3_feature768文件夹下无任何内容，但是文件夹本身存在。

已解决，因为第一次训练没有在文件路径前加上/root/导致后面一系列报错，换一台机子记得把/root/加上就好。

**Comment by Chaoriticle** [comment]
> 3060Ti，一样的问题。有什么解决办法吗？

已解决，因为第一次训练没有在文件路径前加上/root/导致后面一系列报错，换一台机子记得把/root/加上就好。

**Comment by stickbrime** [comment]
> > 3060Ti，一样的问题。有什么解决办法吗？
> 
> 已解决，因为第一次训练没有在文件路径前加上/root/导致后面一系列报错，换一台机子记得把/root/加上就好。

no idea where to put the "/root/".could you please post a screenshot at least?
