### ISSUE TITLE
求助.找不到_swigfaiss

### ISSUE THREAD

**Issue by s084088** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#257]
PS E:\project\voice\Retrieval-based-Voice-Conversion-WebUI> python infer-web.py
Traceback (most recent call last):
  File "E:\project\voice\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 7, in <module>
    import faiss
  File "C:\Users\Nemo\AppData\Roaming\Python\Python39\site-packages\faiss\__init__.py", line 51, in <module>
    from .loader import *
  File "C:\Users\Nemo\AppData\Roaming\Python\Python39\site-packages\faiss\loader.py", line 65, in <module>
    from .swigfaiss import *
  File "C:\Users\Nemo\AppData\Roaming\Python\Python39\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed while importing _swigfaiss: 找不到指定的模块。

**Comment by s084088** [comment]
如果直接运行 go-web.bat会出现以下错误

E:\project\voice\RVC-beta>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Traceback (most recent call last):
  File "E:\project\voice\RVC-beta\infer-web.py", line 2, in <module>
    import threading, pdb, librosa
  File "C:\Users\Nemo\AppData\Roaming\Python\Python39\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "C:\Users\Nemo\AppData\Roaming\Python\Python39\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\Nemo\AppData\Roaming\Python\Python39\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Users\Nemo\AppData\Roaming\Python\Python39\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\Nemo\AppData\Roaming\Python\Python39\site-packages\librosa\util\__init__.py", line 78, in <module>
    from .files import *  # pylint: disable=wildcard-import
  File "C:\Users\Nemo\AppData\Roaming\Python\Python39\site-packages\librosa\util\files.py", line 11, in <module>
    import pooch
  File "C:\Users\Nemo\AppData\Roaming\Python\Python39\site-packages\pooch\__init__.py", line 10, in <module>
    from .core import Pooch, create, retrieve
  File "C:\Users\Nemo\AppData\Roaming\Python\Python39\site-packages\pooch\core.py", line 21, in <module>
    from .utils import (
  File "C:\Users\Nemo\AppData\Roaming\Python\Python39\site-packages\pooch\utils.py", line 19, in <module>
    import platformdirs
ModuleNotFoundError: No module named 'platformdirs'

**Comment by Tps-F** [comment]
https://github.com/kyamagu/faiss-wheels/issues/38
Try this one

**Comment by s084088** [comment]
谢谢
使用 
pip uninstall faiss-cpu
conda uninstall faiss
conda install faiss-cpu -c pytorch

再重新安装环境问题解决了
