### ISSUE TITLE
Error during training, FileNotFound

### ISSUE THREAD

**Issue by ThrowawayAccount01** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#258]
When trying to train using the One-click training, I get the following error:

```
C:\Users\LXC PC\Desktop\RVC\venv\Scripts>activate

(venv) C:\Users\LXC PC\Desktop\RVC\venv\Scripts>cd C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta

(venv) C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta>go-web.bat

(venv) C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Use Language: en_US
Running on local URL:  http://0.0.0.0:7897
Traceback (most recent call last):
  File "C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta\trainset_preprocess_pipeline_print.py", line 8, in <module>
    sr = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'PC\\Desktop\\RVC\\venv\\Scripts\\RVC-beta\\RVCRawDataset\\nyuraw'

Traceback (most recent call last):
  File "C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta\extract_f0_print.py", line 11, in <module>
    f = open("%s/extract_f0_feature.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\LXC/extract_f0_feature.log'

Traceback (most recent call last):
  File "C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta\extract_feature_print.py", line 21, in <module>
    f = open("%s/extract_f0_feature.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\LXC/extract_f0_feature.log'

Traceback (most recent call last):
  File "C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "C:\Users\LXC PC\Desktop\RVC\venv\Scripts\RVC-beta\infer-web.py", line 800, in train1key
    set([name.split(".")[0] for name in os.listdir(gt_wavs_dir)])
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\LXC PC\\Desktop\\RVC\\venv\\Scripts\\RVC-beta/logs/nyu/0_gt_wavs'
```

I suspect it may be caused by the space between the username `LXC PC`

**Comment by RVC-Boss** [comment]
no space

**Comment by ThrowawayAccount01** [comment]
The username of this PC upon creation already has a space: `C:\Users\LXC PC` Is there no workaround to this?

**Comment by Gitterman69** [comment]
This needs a fix... sometimes you will have a space in the filepath....

**Comment by Gitterman69** [comment]
> no space

is there a workaround to allow space in filepath???

**Comment by LatusPL** [comment]
Got same problem and also have lot of space on my drive.
