### ISSUE TITLE
InvalidURL: Invalid port [Ubuntu]

### ISSUE THREAD

**Issue by Chilluminati91** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#287]
```
Ubuntu 22.04 LTS
NVIDIA GTX 1060
32GB DDR4
```

```
python3 infer-web.py
Use Language: en_US
Traceback (most recent call last):
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/httpx/_urlparse.py", line 339, in normalize_port
    port_as_int = int(port)
ValueError: invalid literal for int() with base 10: ':1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 76, in <module>
    import gradio as gr
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/components.py", line 55, in <module>
    from gradio import processing_utils, utils
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/utils.py", line 517, in <module>
    class AsyncRequest:
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/utils.py", line 536, in AsyncRequest
    client = httpx.AsyncClient()
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/httpx/_client.py", line 1408, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[AsyncBaseTransport]] = {
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/httpx/_client.py", line 1409, in <dictcomp>
    URLPattern(key): None
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/httpx/_utils.py", line 397, in __init__
    url = URL(pattern)
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/httpx/_urls.py", line 113, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/httpx/_urlparse.py", line 246, in urlparse
    parsed_port: typing.Optional[int] = normalize_port(port, scheme)
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/httpx/_urlparse.py", line 341, in normalize_port
    raise InvalidURL("Invalid port")
httpx.InvalidURL: Invalid port
```

Since commit: 77ff5b08b6da75ddbf30862933a64095864e3931

**Comment by RVC-Boss** [comment]
try
pip install httpx==0.23.0

**Comment by Chilluminati91** [comment]
> try pip install httpx==0.23.0

Works, thanks!
