### ISSUE TITLE
运行实时变声报错了，不闪退也不推理

### ISSUE THREAD

**Issue by daycold1000** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#289]
以下是报错日志，从启动推理到停止推理的全部日志

input device:1:麦克风 (Realtek(R) Audio) (MME)
output device:8:扬声器 (Realtek(R) Audio) (MME)
{'hubert_path': 'hubert_base.pt', 'pth_path': 'C:/RVC-beta/weights/nahida.pth', 'index_path': 'C:/RVC-beta/logs/nahida/trained_IVF742_Flat_nprobe_1_v2.index', 'npy_path': "你不需要填写这个You don't need write this.", 'pitch': 12.0, 'samplerate': 44100, 'block_time': 1.0, 'buffer_num': 1, 'threhold': -30.0, 'crossfade_time': 0.08, 'extra_time': 0.05, 'I_noise_reduce': False, 'O_noise_reduce': False, 'index_rate': 0.5}
using_cuda:True
index search enabled
load model(s) from hubert_base.pt
gin_channels: 256 self.spk_embed_dim: 109
Traceback (most recent call last):
  File "C:\RVC-beta\gui.py", line 64, in __init__
    print(self.net_g.load_state_dict(cpt["weight"], strict=False))
  File "C:\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid:
        size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 768]) from checkpoint, the shape in current model is torch.Size([192, 256]).

input_wav:(50362,)
Audio block passed.
Exception ignored from cffi callback <function _StreamBase.__init__.<locals>.callback_ptr at 0x0000017A5B5E33A0>:
Traceback (most recent call last):
  File "C:\RVC-beta\runtime\lib\site-packages\sounddevice.py", line 886, in callback_ptr
    return _wrap_callback(
  File "C:\RVC-beta\runtime\lib\site-packages\sounddevice.py", line 2687, in _wrap_callback
    callback(*args)
  File "C:\RVC-beta\gui.py", line 467, in audio_callback
    self.rvc.infer(self.resampler1(torch.from_numpy(self.input_wav)))
  File "C:\RVC-beta\gui.py", line 133, in infer
    score, ix = self.index.search(npy, k=8)
  File "C:\RVC-beta\runtime\lib\site-packages\faiss\__init__.py", line 341, in replacement_search
    assert d == self.d
AssertionError:
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
Audio block passed.
ENDing VC

**Comment by RVC-Boss** [comment]
现在gui还没有支持v2模型

**Comment by Lingchen218** [comment]
> 现在gui还没有支持v2模型

我用的v1 好像也会卡住

**Comment by Lingchen218** [comment]
is_half:True, device:cuda:0
Input device: 37:麦克风阵列 (Realtek HD Audio Mic input) (Windows WDM-KS)
Output device: 17:扬声器 (Realtek(R) Audio) (Windows WASAPI)
cuda_is_available: True
Process Harvest-3:
Process Harvest-7:
Process Harvest-2:
Process Harvest-5:
Process Harvest-8:
Process Harvest-4:
Process Harvest-9:
Process Harvest-6:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
Traceback (most recent call last):
  File "H:\Downloads\Compressed\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 36, in run
    idx, x, res_f0, n_cpu, ts = self.inp_q.get()
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "H:\Downloads\Compressed\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 36, in run
    idx, x, res_f0, n_cpu, ts = self.inp_q.get()
  File "multiprocessing\queues.py", line 102, in get
  File "multiprocessing\queues.py", line 103, in get
  File "multiprocessing\synchronize.py", line 95, in __enter__
  File "multiprocessing\connection.py", line 221, in recv_bytes
KeyboardInterrupt
  File "multiprocessing\connection.py", line 310, in _recv_bytes
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 315, in _bootstrap
Traceback (most recent call last):
  File "H:\Downloads\Compressed\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 36, in run
    idx, x, res_f0, n_cpu, ts = self.inp_q.get()
  File "H:\Downloads\Compressed\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 36, in run
    idx, x, res_f0, n_cpu, ts = self.inp_q.get()
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
  File "multiprocessing\queues.py", line 102, in get
  File "multiprocessing\queues.py", line 102, in get
  File "H:\Downloads\Compressed\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 36, in run
    idx, x, res_f0, n_cpu, ts = self.inp_q.get()
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\synchronize.py", line 95, in __enter__
  File "multiprocessing\synchronize.py", line 95, in __enter__
KeyboardInterrupt
  File "H:\Downloads\Compressed\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 36, in run
    idx, x, res_f0, n_cpu, ts = self.inp_q.get()
  File "H:\Downloads\Compressed\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 36, in run
    idx, x, res_f0, n_cpu, ts = self.inp_q.get()
  File "H:\Downloads\Compressed\RVC1006Nvidia\RVC1006Nvidia\gui_v1.py", line 36, in run
    idx, x, res_f0, n_cpu, ts = self.inp_q.get()
  File "multiprocessing\queues.py", line 102, in get
KeyboardInterrupt
  File "multiprocessing\queues.py", line 102, in get
  File "multiprocessing\synchronize.py", line 95, in __enter__
  File "multiprocessing\queues.py", line 102, in get
  File "multiprocessing\queues.py", line 102, in get
  File "multiprocessing\synchronize.py", line 95, in __enter__
KeyboardInterrupt
  File "multiprocessing\synchronize.py", line 95, in __enter__
  File "multiprocessing\synchronize.py", line 95, in __enter__
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
^C终止批处理操作吗(Y/N)? y

**Comment by Lingchen218** [comment]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/48959004/7850d63f-111c-42ea-9dc8-c043e5360c13)
点击 开始音频转换 后会断到这里，
