### ISSUE TITLE
[Dockerfile] OSError: Port 7865 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all()

### ISSUE THREAD

**Issue by paul2048** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#291]
I downloaded the `Dockerfile`, and ran the image in Docker GUI on my Windows 11. But I get this error after I run `python infer-web.py` in the terminal:

```
Use Language: en_US
没有发现支持的N卡, 使用CPU进行推理
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/networking.py", line 118, in start_server
    s.bind((LOCALHOST_NAME, server_port))
OSError: [Errno 98] Address already in use

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/infer-web.py", line 1639, in <module>
    app.queue(concurrency_count=511, max_size=1022).launch(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1740, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "/usr/local/lib/python3.10/site-packages/gradio/networking.py", line 121, in start_server
    raise OSError(
OSError: Port 7865 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().
```

I tried to see what runs on that port:
```
# netstat -ltnp | grep :7865
tcp        0      0 0.0.0.0:7865            0.0.0.0:*               LISTEN      1/python3
```
and then I tried to close that with `kill -9 1`, but the process is still there.

I also tried running `python infer-web.py --port 8000`, and the output was:
```
Use Language: en_US
没有发现支持的N卡, 使用CPU进行推理
Running on local URL:  http://0.0.0.0:8000
```
but:
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/23298862/09d26a38-4829-42ab-acac-44a2c50ee895)

**Comment by Mangio621** [comment]
Try running ur shell with full admin access. And try --port 3000.

**Comment by paul2048** [comment]
thanks, but it still doesn't work

**Comment by wyz9616** [comment]
have anyone solved it, i have the same problem

**Comment by progmars** [comment]
In my case, the port was occupied by a Native Instruments background service. Had to stop it.
