### ISSUE TITLE
error when training in colab

### ISSUE THREAD

**Issue by loboere** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#295]
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/extract_feature_print.py", line 13, in <module>
    version = sys.argv[6]
IndexError: list index out of range
['extract_f0_print.py', '/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora', '2', 'harvest']
todo-f0-41
f0ing,now-0,all-41,-/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora/1_16k_wavs/0_0.wav
todo-f0-41
f0ing,now-0,all-41,-/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora/1_16k_wavs/0_2.wav
f0ing,now-8,all-41,-/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora/1_16k_wavs/11_6.wav
f0ing,now-8,all-41,-/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora/1_16k_wavs/11_5.wav
f0ing,now-16,all-41,-/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora/1_16k_wavs/14_1.wav
f0ing,now-16,all-41,-/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora/1_16k_wavs/13_8.wav
f0ing,now-24,all-41,-/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora/1_16k_wavs/3_1.wav
f0ing,now-24,all-41,-/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora/1_16k_wavs/2_8.wav
f0ing,now-32,all-41,-/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora/1_16k_wavs/6_4.wav
f0ing,now-32,all-41,-/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora/1_16k_wavs/6_2.wav
f0ing,now-40,all-41,-/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora/1_16k_wavs/9_6.wav
f0ing,now-40,all-41,-/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora/1_16k_wavs/9_4.wav

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1320, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1064, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 956, in train1key
    & set([name.split(".")[0] for name in os.listdir(co256_dir)])
FileNotFoundError: [Errno 2] No such file or directory: '/content/Retrieval-based-Voice-Conversion-WebUI/logs/gema_lausurpadora/3_feature256'

**Comment by nicokim** [comment]
@fumiama the same error is happening to me when I'm using a pretrained v2 model :thinking:

**Comment by fumiama** [comment]
Well, there may be something wrong on your dataset😂
