### ISSUE TITLE
Trouble running infer-web.py no matter what

### ISSUE THREAD

**Issue by yoyoinneverland** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#301]
I followed the instructions to a T, twice, for two different installations, but alas, I got the same error in the end.
Here it is:
```
D:\VOICE\Retrieval-based-Voice-Conversion-WebUI>python infer-web.py --pycmd python --port 7897
Use Language: en_US
Traceback (most recent call last):
  File "D:\VOICE\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 1664, in <module>
    but6.click(
  File "C:\Users\Yoyo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\events.py", line 132, in __call__    dep, dep_index = self.trigger.set_event_trigger(
  File "C:\Users\Yoyo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 267, in set_event_trigger
    "inputs": [block._id for block in inputs],
  File "C:\Users\Yoyo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 267, in <listcomp>
    "inputs": [block._id for block in inputs],
AttributeError: 'int' object has no attribute '_id'
```
I had to change runtime/python.exe to python because I have no idea how it's ran that way, since otherwise it would say file not found.

Any help will be much appreciated.

Edit:
The last release worked without much issue (only issue is that aria2 doesn't seem to work well with it) but it managed to launch the ui unlike with the latest git clone.

Last infer-web.py (doesn't work [for me])
```
but6.click(
                    merge,
                    [
                        ckpt_a,
                        ckpt_b,
                        alpha_a,
                        sr_,
                        1 if if_f0_ == i18n("是") else 0,
                        info__,
                        name_to_save0,
                        version_2,
                    ],
                    info4,
                ) 
```

infer-web.py from release archive (working)
```
                but6.click(
                    merge,
                    [ckpt_a, ckpt_b, alpha_a, sr_, if_f0_, info__, name_to_save0],
                    info4,
                ) 
```

**Comment by yoyoinneverland** [comment]
Fixed by rolling back from these changes 
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/commit/da0b599fa74d9094fdd0dd6c965a3df363b47ce8

**Comment by yoyoinneverland** [comment]
I'll leave this open so more people see it, since they might get the same issue.

**Comment by yoyoinneverland** [comment]
I'll leave this open so more people see it, since they might get the same issue.

**Comment by justinjohn0306** [comment]
same issue
