### ISSUE TITLE
运行实时变声报错了，无法启动

### ISSUE THREAD

**Issue by 493Arceus** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#306]
日志如下

2023-05-18 13:50:10 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-18 13:50:10 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-18 13:50:10 | INFO | faiss.loader | Loading faiss.
2023-05-18 13:50:10 | INFO | faiss.loader | Successfully loaded faiss.
Use Language: zh_CN
Traceback (most recent call last):
  File "H:\AI\RVC-beta\gui.py", line 570, in <module>
    gui = GUI()
  File "H:\AI\RVC-beta\gui.py", line 205, in __init__
    self.launcher()
  File "H:\AI\RVC-beta\gui.py", line 209, in launcher
    input_devices, output_devices, _, _ = self.get_devices()
  File "H:\AI\RVC-beta\gui.py", line 541, in get_devices
    input_devices_indices = [
  File "H:\AI\RVC-beta\gui.py", line 542, in <listcomp>
    d["index"] for d in devices if d["max_input_channels"] > 0
KeyError: 'index'

**Comment by mgxy921** [comment]
gui.py 586行以后修改为:
input_devices_indices = [
    d["name"] for d in devices if d["max_input_channels"] > 0
]
output_devices_indices = [
    d["name"] for d in devices if d["max_output_channels"] > 0
]

**Comment by 493Arceus** [comment]
完美解决，感谢！ :)👍
