### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Cieven** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#342]
2023-05-24 07:44:09 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-24 07:44:09 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-24 07:44:09 | INFO | faiss.loader | Loading faiss.
2023-05-24 07:44:09 | INFO | faiss.loader | Successfully loaded faiss.
Use Language: zh_CN
Traceback (most recent call last):
  File "C:\Users\******\Downloads\RVC-beta\gui.py", line 570, in <module>
    gui = GUI()
  File "C:\Users\******\Downloads\RVC-beta\gui.py", line 205, in __init__
    self.launcher()
  File "C:\Users\******\Downloads\RVC-beta\gui.py", line 209, in launcher
    input_devices, output_devices, _, _ = self.get_devices()
  File "C:\Users\******\Downloads\RVC-beta\gui.py", line 526, in get_devices
    devices = sd.query_devices()
  File "C:\Users\******\Downloads\RVC-beta\runtime\lib\site-packages\sounddevice.py", line 564, in query_devices
    return DeviceList(query_devices(i)
  File "C:\Users\******\Downloads\RVC-beta\runtime\lib\site-packages\sounddevice.py", line 564, in <genexpr>
    return DeviceList(query_devices(i)
  File "C:\Users\******\Downloads\RVC-beta\runtime\lib\site-packages\sounddevice.py", line 578, in query_devices
    name = name_bytes.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte

**Comment by aliyun2587722529** [comment]
Same problem:
G:\AI\RVC-beta>runtime\python.exe gui.py
2023-05-27 00:20:49 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-27 00:20:49 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-27 00:20:49 | INFO | faiss.loader | Loading faiss.
2023-05-27 00:20:49 | INFO | faiss.loader | Successfully loaded faiss.
Use Language: zh_CN
Traceback (most recent call last):
  File "G:\AI\RVC-beta\gui.py", line 570, in <module>
    gui = GUI()
  File "G:\AI\RVC-beta\gui.py", line 205, in __init__
    self.launcher()
  File "G:\AI\RVC-beta\gui.py", line 209, in launcher
    input_devices, output_devices, _, _ = self.get_devices()
  File "G:\AI\RVC-beta\gui.py", line 526, in get_devices
    devices = sd.query_devices()
  File "G:\AI\RVC-beta\runtime\lib\site-packages\sounddevice.py", line 564, in query_devices
    return DeviceList(query_devices(i)
  File "G:\AI\RVC-beta\runtime\lib\site-packages\sounddevice.py", line 564, in <genexpr>
    return DeviceList(query_devices(i)
  File "G:\AI\RVC-beta\runtime\lib\site-packages\sounddevice.py", line 578, in query_devices
    name = name_bytes.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte

G:\AI\RVC-beta>pause

**Comment by aliyun2587722529** [comment]
In newer version (

**Comment by aliyun2587722529** [comment]
In newer version (updated0528v2), the same bug appears.

G:\AI\RVC-beta-v2-0528>runtime\python.exe gui.py
2023-06-02 18:17:06 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-06-02 18:17:06 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-06-02 18:17:06 | INFO | faiss.loader | Loading faiss.
2023-06-02 18:17:06 | INFO | faiss.loader | Successfully loaded faiss.
Traceback (most recent call last):
  File "G:\AI\RVC-beta-v2-0528\gui.py", line 615, in <module>
    gui = GUI()
  File "G:\AI\RVC-beta-v2-0528\gui.py", line 250, in __init__
    self.launcher()
  File "G:\AI\RVC-beta-v2-0528\gui.py", line 254, in launcher
    input_devices, output_devices, _, _ = self.get_devices()
  File "G:\AI\RVC-beta-v2-0528\gui.py", line 571, in get_devices
    devices = sd.query_devices()
  File "G:\AI\RVC-beta-v2-0528\runtime\lib\site-packages\sounddevice.py", line 564, in query_devices
    return DeviceList(query_devices(i)
  File "G:\AI\RVC-beta-v2-0528\runtime\lib\site-packages\sounddevice.py", line 564, in <genexpr>
    return DeviceList(query_devices(i)
  File "G:\AI\RVC-beta-v2-0528\runtime\lib\site-packages\sounddevice.py", line 578, in query_devices
    name = name_bytes.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte

G:\AI\RVC-beta-v2-0528>pause

**Comment by aliyun2587722529** [comment]
My problem is solved, I reinstall the whole system. I may delete some system files accidentally when I use Disk Cleanup.

**Comment by JiayunLi-3E8** [comment]
The reason of this problem was found.

In the Sounddevice lib of Python,
![Screenshot 2023-06-21 085329](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/61492105/643bc042-b68d-4026-a47d-ac091832cb7c)
it only process the exception of `decode('utf-8')` of DirectSound and MME. So, if there is name of sound device which can not decode with utf-8 and is not DirectSound and MME, it will report same yours error.

To solve this problem temporarily, you can do following patch.
![Screenshot 2023-06-21 091226](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/61492105/31aaddc3-ff5a-4ad0-9ad5-799cde4cd732)

Good luck!😉
