### ISSUE TITLE
step3训练时报错

### ISSUE THREAD

**Issue by odyy345-ui** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#347]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/lib/python3.10/site-packages/gradio/blocks.py", line 1320, in process_api
    result = await self.call_function(
  File "/usr/lib/python3.10/site-packages/gradio/blocks.py", line 1048, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/odyy345/RVC-beta/RVC-beta/infer-web.py", line 607, in click_train
    & set([name.split(".")[0] for name in os.listdir(feature_dir)])
FileNotFoundError: [Errno 2] No such file or directory: '/home/odyy345/RVC-beta/RVC-beta/logs/xyh/3_feature768'

**Comment by RVC-Boss** [comment]
There may be other issues when executing step1 or step2.
