### ISSUE TITLE
no English documentation on how to use Model Fusion feature 

### ISSUE THREAD

**Issue by jfrankdev** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#364]
When you go the ckpt processing tab it is unclear how to use this feature. I can't find any English documentation on it and I have not been able to make it work just trying stuff. I get this error:

  File "C:\Users\user\Desktop\rvc-beta\train\process_ckpt.py", line 212, in merge
    cfg = ckpt1["config"]
KeyError: 'config'

**Comment by harukaxxxx** [comment]
use pth in weight folder, and remeber write down model name.
here is a sample in chinese gui.
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/5777085/1edcb933-6148-43cb-bf1a-4908fdfcc5de)

**Comment by jfrankdev** [comment]
I still receive the same error when I click "Fusion.":

```
Traceback (most recent call last):
  File "C:\Users\conta\Desktop\rvc-beta\train\process_ckpt.py", line 212, in merge
    cfg = ckpt1["config"]
KeyError: 'config'
```

**Comment by jfrankdev** [comment]
With your suggestions I still receive this error when I click "Fusion.":

```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\rvc-beta\train\process_ckpt.py", line 212, in merge
    cfg = ckpt1["config"]
KeyError: 'config'
```

**Comment by dhstsw** [comment]
I manage to get a fusion with 2 models, BUY:

-1- no index file.
-2- When i load the new file created for inference i always get this error:

```
loading weights/mix1.pth
gin_channels: 256 self.spk_embed_dim: 109
Traceback (most recent call last):
  File "J:\RVC-beta\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "J:\RVC-beta\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "J:\RVC-beta\runtime\lib\site-packages\gradio\blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "J:\RVC-beta\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "J:\RVC-beta\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "J:\RVC-beta\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "J:\RVC-beta\infer-web.py", line 420, in get_vc
    print(net_g.load_state_dict(cpt["weight"], strict=False))
  File "J:\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs768NSFsid_nono:
        size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 256]) from checkpoint, the shape in current model is torch.Size([192, 768]).
```
