### ISSUE TITLE
ubuntu用`python infer-web.py`启动报错alueError: invalid literal for int() with base 10: ':1'   httpx.InvalidURL: Invalid port

### ISSUE THREAD

**Issue by denganliang** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#386]
RVC-beta/RVC-beta-v2-0528> python infer-web.py  
Use Language: en_US
2023-05-30 02:11:13 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
Traceback (most recent call last):
  File "/home/pai/lib/python3.9/site-packages/httpx/_urlparse.py", line 339, in normalize_port
    port_as_int = int(port)
ValueError: invalid literal for int() with base 10: ':1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/workspace/new_voice/RVC-beta/RVC-beta-v2-0528/infer-web.py", line 82, in <module>
    import gradio as gr
  File "/home/pai/lib/python3.9/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/pai/lib/python3.9/site-packages/gradio/components.py", line 55, in <module>
    from gradio import processing_utils, utils
  File "/home/pai/lib/python3.9/site-packages/gradio/utils.py", line 497, in <module>
    class AsyncRequest:
  File "/home/pai/lib/python3.9/site-packages/gradio/utils.py", line 516, in AsyncRequest
    client = httpx.AsyncClient()
  File "/home/pai/lib/python3.9/site-packages/httpx/_client.py", line 1408, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[AsyncBaseTransport]] = {
  File "/home/pai/lib/python3.9/site-packages/httpx/_client.py", line 1409, in <dictcomp>
    URLPattern(key): None
  File "/home/pai/lib/python3.9/site-packages/httpx/_utils.py", line 397, in __init__
    url = URL(pattern)
  File "/home/pai/lib/python3.9/site-packages/httpx/_urls.py", line 113, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "/home/pai/lib/python3.9/site-packages/httpx/_urlparse.py", line 246, in urlparse
    parsed_port: typing.Optional[int] = normalize_port(port, scheme)
  File "/home/pai/lib/python3.9/site-packages/httpx/_urlparse.py", line 341, in normalize_port
    raise InvalidURL("Invalid port")
httpx.InvalidURL: Invalid port

**Comment by RVC-Boss** [comment]
pip install httpx==0.23.0

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved.
