### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by sourudev** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#387]
``` Traceback (most recent call last):
  File "D:\Lab\aivoice\RVC-beta-v2-0528\infer-web.py", line 184, in vc_single
    audio_opt = vc.pipeline(
  File "D:\Lab\aivoice\RVC-beta-v2-0528\vc_infer_pipeline.py", line 347, in pipeline
    self.vc(
  File "D:\Lab\aivoice\RVC-beta-v2-0528\vc_infer_pipeline.py", line 201, in vc
    score, ix = index.search(npy, k=8)
  File "D:\Lab\aivoice\RVC-beta-v2-0528\runtime\lib\site-packages\faiss\__init__.py", line 341, in replacement_search
    assert d == self.d
AssertionError

Traceback (most recent call last):
  File "D:\Lab\aivoice\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\Lab\aivoice\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\Lab\aivoice\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\Lab\aivoice\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "D:\Lab\aivoice\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "D:\Lab\aivoice\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype' ```

OS: Window 11
GPU: NVIDIA RTX 3060

**Comment by sourudev** [comment]
New One

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/79008840/41237e0c-394f-4ada-b78e-8029cbcff48b)

**Comment by RVC-Boss** [comment]
1、模型和索引的v1v2混用了
2、pip install torchcrepe==0.0.19再试试，不行就0.0.18，用runtime\Scipts\pip.exe装

**Comment by sourudev** [comment]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/79008840/b26f9a3e-5926-44de-9f45-cbcf7fa1ea69)
Again

**Comment by ArianaStar** [comment]
I'm having this same error message when trying to generate an output, whenever I put "Protect the artifact of voiceless consonant and breath. 0.5: don' use it. The number smaller, the stronger protection." on 0.5 the error goes away.

**Comment by ravenobsidian** [comment]
@RVC-Boss Same error. I am only using v1 model. Also working after moving "Protect the artifact of voiceless consonant and breath. 0.5: don' use it. The number smaller, the stronger protection." to 0.5.

**Comment by sourudev** [comment]
I re-trained again and it fixed

**Comment by ravenobsidian** [comment]
@sourudev do you have pitch guidance on or off?

**Comment by ravenobsidian** [comment]
Cleaned virtualenv and reinstalled requirements.txt with  torchcrepe==0.0.18 and librosa==0.9.1. 
Retrained. 
Same error.

```
loading weights/abc.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
Traceback (most recent call last):
  File "C:\Users\rubyc\Documents\GitHub\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 184, in vc_single
    audio_opt = vc.pipeline(
  File "C:\Users\rubyc\Documents\GitHub\Retrieval-based-Voice-Conversion-WebUI\vc_infer_pipeline.py", line 401, in pipeline
    self.vc(
  File "C:\Users\rubyc\Documents\GitHub\Retrieval-based-Voice-Conversion-WebUI\vc_infer_pipeline.py", line 227, in vc
    pitchff = pitchf.clone()
AttributeError: 'NoneType' object has no attribute 'clone'

Traceback (most recent call last):
  File "C:\Users\rubyc\anaconda3\envs\rvc\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\rubyc\anaconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\rubyc\anaconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 1257, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\rubyc\anaconda3\envs\rvc\lib\site-packages\gradio\components.py", line 2531, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\rubyc\anaconda3\envs\rvc\lib\site-packages\gradio\processing_utils.py", line 163, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\rubyc\anaconda3\envs\rvc\lib\site-packages\gradio\processing_utils.py", line 177, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```

**Comment by AiQuantPro** [comment]
how to fix it?
Traceback (most recent call last):
  File "/home/yyds/anaconda3/envs/rvc/lib/python3.9/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/yyds/anaconda3/envs/rvc/lib/python3.9/site-packages/gradio/blocks.py", line 1323, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/yyds/anaconda3/envs/rvc/lib/python3.9/site-packages/gradio/blocks.py", line 1257, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/yyds/anaconda3/envs/rvc/lib/python3.9/site-packages/gradio/components.py", line 2531, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "/home/yyds/anaconda3/envs/rvc/lib/python3.9/site-packages/gradio/processing_utils.py", line 163, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "/home/yyds/anaconda3/envs/rvc/lib/python3.9/site-packages/gradio/processing_utils.py", line 177, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by ravenobsidian** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/a02019e4284daa7b8ed253ff450fdc7d534fa735/vc_infer_pipeline.py#L227

The reason that setting to 0.5 fixed the issue is because `pitchf` is `None` and if `protect` is `0.5`, the code is skipped
0.5可以修复这个问题的原因是因为出错的时候`pitchf`为`None`，然后如果`protect`设为`0.5`，就不会跑出错的代码

What caused `pitchf` to be `None`?
@RVC-Boss 请问大佬，`pitchf`在什么情况下会是`None`？

**Comment by Namarimizu** [comment]
> https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/a02019e4284daa7b8ed253ff450fdc7d534fa735/vc_infer_pipeline.py#L227
> 
> The reason that setting to 0.5 fixed the issue is because `pitchf` is `None` and if `protect` is `0.5`, the code is skipped 0.5 可以修復這個問題的原因是因為出錯的時候 `pitchf` 為 `None`，然後如果 `protect` 設為 `0.5`，就不會跑出錯的代碼
> 
> What caused `pitchf` to be `None`? @RVC-Boss 請問大佬，`pitchf` 在什麼情況下會是 `None`？

一样的问题，torchcrepe也装了0.0.18版

**Comment by Namarimizu** [comment]
> https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/a02019e4284daa7b8ed253ff450fdc7d534fa735/vc_infer_pipeline.py#L227
> 
> The reason that setting to 0.5 fixed the issue is because `pitchf` is `None` and if `protect` is `0.5`, the code is skipped 0.5 可以修復這個問題的原因是因為出錯的時候 `pitchf` 為 `None`，然後如果 `protect` 設為 `0.5`，就不會跑出錯的代碼
> 
> What caused `pitchf` to be `None`? @RVC-Boss 請問大佬，`pitchf` 在什麼情況下會是 `None`？

噢，我这边的问题是训练时不带音高指导的话，就没法用那个功能；重新训练一个带音高指导的就ok了

**Comment by Wuxlol** [comment]
> > https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/a02019e4284daa7b8ed253ff450fdc7d534fa735/vc_infer_pipeline.py#L227
> > 
> > 设置为 0.5 解决问题的原因是因为`pitchf`is`None`和 if `protect`is `0.5`，代码被跳过 0.5 可以修改这个问题的原因是因为出错的时候`pitchf`为`None`，然后如果`protect`设置为`0.5`，就不会跑出错误的代码
> > 是什么造成`pitchf`的`None`？@RVC-Boss请问大佬，`pitchf`在什么情况下会是`None`？
> 
> 哦，我总结的问题是训练时不带音高指导的话，就没法用那个功能；重新训练一个带音高指导的就ok了

我带了高音特征提取了，感觉大家出错的都一样啊

**Comment by leaper-max** [comment]
> I re-trained again and it fixed

What train settings did you use? with or without pitch v1 or v2?

**Comment by MojoPriest42** [comment]
If the Nonetype error shows up on Windows when doing inference with a trained model, it may be caused by file replacement. The pth file of a model should be located directly in the Weights folder inside RVC, since this folder seemingly does not handle any subfolders.

A YouTube video "RVC Tutorial: The Easiest Vocal A.i. to date (Windows/Linux)" by P3tro has more on this subject. I won't insert a direct link to avoid any forum policy violations.

**Comment by fssyy** [comment]
用自己训练的模型转换时报错：AttributeError: 'NoneType' object has no attribute 'clone'，有大佬知道怎么解决吗
