### ISSUE TITLE
[help wanted]ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

### ISSUE THREAD

**Issue by YukiWorks432** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#388]
What do these errors represent, stderr is of no help.
How can I solve this?

OS: Windows 10
CPU: AMD Ryzen7 3700X
Memory: 32GB
GPU: NVIDIA GeForce RTX 2060

```
Traceback (most recent call last):
  File "F:\RVC-beta-v2-0528\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "F:\RVC-beta-v2-0528\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\RVC-beta-v2-0528\infer-web.py", line 161, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "F:\RVC-beta-v2-0528\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "F:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "F:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "F:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "F:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "F:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```

**Comment by VioletChaolan** [comment]
i get this exact issue and my path to the audio to convert is C:\Users\lucky\Desktop\Audio so it doesnt seem to be a path issue? exact same error message

**Comment by VioletChaolan** [comment]
after getting the stderr i get this in an admin terminal i literally cant give it more permission than it has. even in the security tab i gave full control and modify to the folder 



`C:\Users\lucky\Desktop\RVC-beta-v2-0528>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Use Language: en_US
Running on local URL:  http://0.0.0.0:7897
loading weights/CSGOSAS_e10.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
stdout:
stderr: ffmpeg version n4.3.2-160-gfbb9368226 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9.3-win32 (GCC) 20200320
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-zlib --enable-libxml2 --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-opencl --enable-libvmaf --disable-vulkan --enable-libvorbis --enable-amf --enable-libaom --disable-avisynth --enable-libdav1d --disable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --disable-libglslang --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --disable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --disable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libtwolame --disable-libvidstab --disable-libx264 --disable-libx265 --disable-libxavs2 --disable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
C:\Audio: Permission denied

Traceback (most recent call last):
  File "C:\Users\lucky\Desktop\RVC-beta-v2-0528\infer-web.py", line 161, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "C:\Users\lucky\Desktop\RVC-beta-v2-0528\my_utils.py", line 22, in load_audio
    raise e
  File "C:\Users\lucky\Desktop\RVC-beta-v2-0528\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\lucky\Desktop\RVC-beta-v2-0528\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "C:\Users\lucky\Desktop\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\lucky\Desktop\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\lucky\Desktop\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\lucky\Desktop\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\lucky\Desktop\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\lucky\Desktop\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'`

**Comment by VioletChaolan** [comment]
alright gotta apoloigze it seems the actual issue is i gave it the file path without acctualy supplying the filename.
i did this C:\Audio
wheen it shouldve been  C:\Audio\bucklemyshoe.wav

**Comment by YukiWorks432** [comment]
> alright gotta apoloigze it seems the actual issue is i gave it the file path without acctualy supplying the filename. i did this C:\Audio wheen it shouldve been C:\Audio\bucklemyshoe.wav

I tried but could not solve the problem. Is there anything else you have changed?

**Comment by VioletChaolan** [comment]
Start the webui with an admin console I guess?

**Comment by YukiWorks432** [comment]
I will add the details of the error.

This occurred when converting an audio file.
In "Inferencing voice" I specified the pth file I downloaded and in "Enter the path of the audio file to be processed" I entered "F:\output.wav".
Then I specified the wav file and clicked "Convert", and it took about 5 seconds before an error message appeared.

**Comment by reflectt6** [comment]
I had the same problem, but it worked fine for me before. I don't know what happened to cause the error

**Comment by reflectt6** [comment]
I printed the err and the key information is as follows:

Codec AVOption threads (set the number of threads) specified for input file # 0 (F: AI RVC beta train new/desktop. ini) have not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some decoder which was not actually used for any stream

You can see that ffmpeg mistakenly treated audio files as lrc files. But I didn't find the desktop. ini file, it's a strange error.

Although I don't understand why there is this bug, creating a new folder and copying audio files to the new folder can solve this problem.

**Comment by hobolyra** [comment]
same error, moving file sometimes fixes it and sometimes doesn't. it's strange.

```
Traceback (most recent call last):
  File "L:\RCV_voiceclone\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "L:\RCV_voiceclone\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:\RCV_voiceclone\infer-web.py", line 161, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "L:\RCV_voiceclone\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "L:\RCV_voiceclone\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "L:\RCV_voiceclone\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "L:\RCV_voiceclone\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "L:\RCV_voiceclone\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "L:\RCV_voiceclone\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "L:\RCV_voiceclone\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "L:\RCV_voiceclone\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "L:\RCV_voiceclone\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:\RCV_voiceclone\infer-web.py", line 161, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "L:\RCV_voiceclone\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "L:\RCV_voiceclone\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "L:\RCV_voiceclone\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "L:\RCV_voiceclone\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "L:\RCV_voiceclone\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "L:\RCV_voiceclone\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "L:\RCV_voiceclone\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```

**Comment by ROBdk97** [comment]
I got a similar issue on the preprocess:

OS: Windows 11
CPU: AMD Ryzen7 5800X
Memory: 64GB
GPU: NVIDIA GeForce RTX 4090

```txt
start preprocess
['trainset_preprocess_pipeline_print.py', 'F:\\RVC-beta-v2-0618\\audio\\us', '40000', '16', 'F:\\RVC-beta-v2-0618/logs/us', 'False']
F:\RVC-beta-v2-0618\audio\us/test_us.wav->Traceback (most recent call last):
  File "F:\RVC-beta-v2-0618\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "F:\RVC-beta-v2-0618\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\RVC-beta-v2-0618\trainset_preprocess_pipeline_print.py", line 79, in pipeline
    audio = load_audio(path, self.sr)
  File "F:\RVC-beta-v2-0618\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)
```

**Comment by leaper-max** [comment]
I've trained my model with and without pitch guidance all in model v2 and v1. I Tried 0 protection 0.33 and 0.5, harvest crepe and pm give the same error.
The path is good no spaces no () only - _

Anyone had luck in solving this?

```
Traceback (most recent call last):
  File "V:\AI\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "V:\AI\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 178, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "V:\AI\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```

**Comment by TahaKCengiz** [comment]
Hello i have the same issue recently. I download ffmpeg building version on original website. After i add system path ffmpeg.exe location(in the bin folder). After my problem is gone.
