### ISSUE TITLE
Error in struct faiss how to fix it

### ISSUE THREAD

**Issue by zhuziying** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#392]
Traceback (most recent call last):
  File "E:\gitprojects\Retrieval-based-Voice-Conversion-WebUI\vc_infer_pipeline.py", line 284, in pipeline
    index = faiss.read_index(file_index)
  File "C:\Users\nbazz\.conda\envs\Voice\lib\site-packages\faiss\swigfaiss.py", line 9651, in read_index
    return _swigfaiss.read_index(*args)
RuntimeError: Error in struct faiss::Index *__cdecl faiss::read_index(struct faiss::IOReader *,int) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\index_read.cpp:1027: Index type 0x4d554e93 ("\x93NUM") not recognized

**Comment by fumiama** [comment]
Try to install another faiss version.

**Comment by zhuziying** [comment]
@fumiama 3q
