### ISSUE TITLE
[Colab] Error on Accompaniment and vocal separation

### ISSUE THREAD

**Issue by pasqualesimonetti** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#394]
When I try to process accompaniment and vocal accompaniment separation I get the following error message: 

> .ipynb_checkpoints.reformatted.wav->Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 164, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 195, in __soundfile_load
    context = sf.SoundFile(path)
  File "/usr/local/lib/python3.10/dist-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/lib/python3.10/dist-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening '/content/Retrieval-based-Voice-Conversion-WebUI/TEMP/.ipynb_checkpoints.reformatted.wav': System error.

The same happens if I select HP2 or HP5 model.

**Comment by lSevenLl** [comment]
Sometimes changing the file name or format before running UVR fix it. it works for me

**Comment by eugeborzone** [comment]
if the file have spaces it rises errors. delete it or change with _
