### ISSUE TITLE
Cannot find .index file even after separate Index training

### ISSUE THREAD

**Issue by NadineSensei** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#395]
I first used the one-click training and it was missing the .index file, so I followed the instructions on other Issues tabs and the wiki. But after training feature index saparately, this happens.
```Traceback (most recent call last):
  File "C:\Users\edenw\OneDrive\桌面\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\edenw\OneDrive\桌面\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\edenw\OneDrive\桌面\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\edenw\OneDrive\桌面\RVC-beta-v2-0528\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\edenw\OneDrive\桌面\RVC-beta-v2-0528\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\edenw\OneDrive\桌面\RVC-beta-v2-0528\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\edenw\OneDrive\桌面\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "C:\Users\edenw\OneDrive\桌面\RVC-beta-v2-0528\infer-web.py", line 804, in train_index
    faiss.write_index(
  File "C:\Users\edenw\OneDrive\桌面\RVC-beta-v2-0528\runtime\lib\site-packages\faiss\swigfaiss.py", line 8255, in write_index
    return _swigfaiss.write_index(*args)
RuntimeError: Error in __cdecl faiss::FileIOWriter::FileIOWriter(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:98: Error: 'f' failed: could not open C:\Users\edenw\OneDrive\桌面\RVC-beta-v2-0528/logs/my-voice/trained_IVF275_Flat_nprobe_1_my-voice_v2.index for writing: No such file or directory```

I might have missed a past Issue or two, but I genuinely couldn't figure out how to fix it.

**Comment by RVC-Boss** [comment]
试下不含中文的路径（桌面）

**Comment by niizam** [comment]
Nothing happens after Train Feature Index clicked?
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/c2f402d7d19dcb58f30d8eafeaf4551d4868d5ba/infer-web.py#L775-L776
Even though I've followed this tips
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/c2f402d7d19dcb58f30d8eafeaf4551d4868d5ba/docs/faq_en.md?plain=1#L6-L9

**Comment by Genteki** [comment]
I encountered the same problem as yours before. 

I solved it by downloading [`hubert_base.pt`](https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/hubert_base.pt) from [huggingface page](https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main), and add it to repository path.

**Comment by hcorn82** [comment]
I am getting the same problem after seeing "Training is done. The program is closed," there is no index file in the log folder. I've successful trained 5 other models but now I can't get it give me an index file. I tried clicking "train index" again like @niizam and the faq states but nothing happens.

**Comment by limonatam** [comment]
Do any of you found a way to solve this ?

**Comment by sonovac** [comment]
I'm facing the same problem.
Someone said it has to do with FFmpeg, 
but I don't know how to solve it specifically!

**Comment by SystemFaifure** [comment]
Получаются два файла индекса, причём они создаются автоматически, не важно нажали вы кнопку "создать индекс" или нет. Один файл лежит в папке log\eval и второй с похожим названием лежит в директории log - я не знаю какой из них "тот самый" но программа пишет "Success. Index: имя файла"на оба файла. Но если честно, я до конца не уверен, что это правильный индекс.

**Comment by SystemFaifure** [comment]
Объясняю по порядку... Индекс файл создаётся программой без проблем, если программа и все её компоненты были установлены правильно. Для nVidia видеокарт должны быть установлены CUDA - рекомендации к установке - requirements.txt. Но так как программа изначально не была заточена для пользователей AMD Radeon - она не задействует видеокарту, однако если установить программу и компоненты в режиме DML для пользователей AMD, то можно заставить программу создавать индекс файл и в этом случае. Но для этого нужно, чтобы установщик подхватил настройки из файла requirements-dml.txt.
Полный код установки для RVC из официального релиза для пользователей AMD на Windows:
  python.exe -m pip install --upgrade pip
  pip install torch torchvision torchaudio
  curl -sSL https://install.python-poetry.org | python3 -
  pip install poetry

::for Nvidia graphics cards
::pip install -r requirements.txt

::for AMD/Intel graphics cards on Windows (DirectML)：
  pip install -r requirements-dml.txt

::for Intel ARC graphics cards on Linux / WSL using Python 3.10: 
::pip install -r requirements-ipex.txt

::For AMD graphics cards on Linux (ROCm):
::pip install -r requirements-amd.txt
::pacman -S rocm-hip-sdk rocm-opencl-sdk
::export ROCM_PATH=/opt/rocm
::export HSA_OVERRIDE_GFX_VERSION=10.3.0
::sudo usermod -aG render $USERNAME
::sudo usermod -aG video $USERNAME
::sudo apt install ffmpeg

**Comment by daqqad** [comment]
> Объясняю по порядку... Индекс файл создаётся программой без проблем, если программа и все её компоненты были установлены правильно. Для nVidia видеокарт должны быть установлены CUDA - рекомендации к установке - requirements.txt. Но так как программа изначально не была заточена для пользователей AMD Radeon - она не задействует видеокарту, однако если установить программу и компоненты в режиме DML для пользователей AMD, то можно заставить программу создавать индекс файл и в этом случае. Но для этого нужно, чтобы установщик подхватил настройки из файла requirements-dml.txt. Полный код установки для RVC из официального релиза для пользователей AMD на Windows/Linux: python.exe -m pip install --upgrade pip pip install torch torchvision torchaudio curl -sSL https://install.python-poetry.org | python3 - pip install poetry
> 
> ::for Nvidia graphics cards ::pip install -r requirements.txt
> 
> ::for AMD/Intel graphics cards on Windows (DirectML)： pip install -r requirements-dml.txt
> 
> ::for Intel ARC graphics cards on Linux / WSL using Python 3.10: ::pip install -r requirements-ipex.txt
> 
> ::For AMD graphics cards on Linux (ROCm): ::pip install -r requirements-amd.txt ::pacman -S rocm-hip-sdk rocm-opencl-sdk ::export ROCM_PATH=/opt/rocm ::export HSA_OVERRIDE_GFX_VERSION=10.3.0 ::sudo usermod -aG render $USERNAME ::sudo usermod -aG video $USERNAME ::sudo apt install ffmpeg

Which of these steps are missing from Dockerfile?  This issue is also present when deploying via docker.

**Comment by raivisdejus** [comment]
For me the issue was empty feature directory  `3_feature768` in the `logs/YOUR-EXPERIMENT_NAME`. The directory was empty due to some error in loading the model as torch `2.6` changed how the models are loaded, so I downgraded 

```
torch<2.6
torchvision<2.6
torchaudio<2.6
```
