### ISSUE TITLE
点击开始音频转换时发生错误 Multiple input devices found for Microphone

### ISSUE THREAD

**Issue by 493Arceus** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#405]
<All keys matched successfully>
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "H:\AI\RVC-beta\gui.py", line 473, in soundinput
    with sd.Stream(
  File "C:\Users\super\AppData\Roaming\Python\Python39\site-packages\sounddevice.py", line 1794, in __init__
    _StreamBase.__init__(self, kind='duplex', wrap_callback='array',
  File "C:\Users\super\AppData\Roaming\Python\Python39\site-packages\sounddevice.py", line 794, in __init__
    iparameters, idtype, isize, isamplerate = _get_stream_parameters(
  File "C:\Users\super\AppData\Roaming\Python\Python39\site-packages\sounddevice.py", line 2653, in _get_stream_parameters
    device = _get_device_id(device, kind, raise_on_error=True)
  File "C:\Users\super\AppData\Roaming\Python\Python39\site-packages\sounddevice.py", line 2801, in _get_device_id
    raise ValueError('Multiple ' + kind + ' devices found for ' +
ValueError: Multiple input devices found for 'Microphone (Razer Seiren Mini)':
[1] Microphone (Razer Seiren Mini), MME
[13] Microphone (Razer Seiren Mini), Windows DirectSound
[33] Microphone (Razer Seiren Mini), Windows WASAPI

img:
![error](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17383497/d8597306-9929-4123-b336-57d8fc772247)

**Comment by 493Arceus** [comment]
根据#306 修改过gui.py的代码才运行起来的go-realtime-gui.bat

**Comment by frozenburst** [comment]
It appears that there may be a concern with ensuring input_devices_indices in the set_devices() function correctly contains the hostapi_name. If the hostapi_name is not present, adjustments might be necessary in the assignment logic within either the get_devices() (*This is in RVC1006Nvidia) or update_devices() (*Master branch) functions. This adjustment is crucial because sd.default.device requires an exact string match to function properly with sounddevice. Without the hostapi_name, it could be multiple matches.

If you've noticed that the gui_v1.py script differs from the one in the current master branch, this discrepancy could potentially impact functionality or compatibility. It might be beneficial to verify the versioning and ensure that any specific modifications are compatible with the current sounddevice requirements and your project's needs.

**Comment by 493Arceus** [comment]
This issue has been fixed in previous versions

**Comment by frozenburst** [comment]
It seems not updated to the latest release on 20231006.

**Comment by 493Arceus** [comment]
yes,but at 20231006,it's work for me.maybe you can try full update?
