### ISSUE TITLE
Weird ValueError and AttributeError

### ISSUE THREAD

**Issue by MineBorder10444** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#408]
Getting this whenever I try to train: 

ValueError: invalid literal for int() with base 10: 'sound'

**Comment by RVC-Boss** [comment]
There may be 2 reasons that caused the error:
1、Check if the path of exp_name and trainingset_dir contains space;
2、Check if there is a notice on the browser that shows that "Unfortunately, there is no compatible GPU available to support your training.". RVC doesn't support CPU training on windows platform.

**Comment by MineBorder10444** [comment]
> There may be 2 reasons that caused the error: 1、Check if the path of exp_name and trainingset_dir contains space; 2、Check if there is a notice on the browser that shows that "Unfortunately, there is no compatible GPU available to support your training.". RVC doesn't support CPU training on windows platform.

Thanks for the response. I somehow fixed this by restarting my computer and it worked like normal. Now I'm having a new issue. After training, I try to generate audio and get a new error:
AttributeError: 'NoneType' object has no attribute 'tobytes'

I looked at another issue that was closed and saw to install torchcrepe 0.0.18. I tried this and it did not fix my issue. This issue also occurs on any of the pitch extraction algorithms so it is not limited to only crepe.

**Comment by MineBorder10444** [comment]
I'm on windows 11 btw. Here is the full error message:

Traceback (most recent call last):
  File "D:\RVCUI\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\user\anaconda3\envs\rvc\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\RVCUI\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 161, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "D:\RVCUI\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\rvc\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\user\anaconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\user\anaconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\user\anaconda3\envs\rvc\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "C:\Users\user\anaconda3\envs\rvc\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

**Comment by MineBorder10444** [comment]
Thanks for the response. I somehow fixed this by restarting my computer and it worked like normal.
