### ISSUE TITLE
Model Inference : AssertionError

### ISSUE THREAD

**Issue by KelvinNgAU** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#422]
Hi,

I have successfully trained the voice and when try to do the model inference, I am having "AssertionError" , is there anything I can do to resolve this error?

Please help. 

G:\RVC-beta\RVC-beta-v2-0528>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Use Language: en_US
Running on local URL:  http://0.0.0.0:7897
loading weights/Train-BV1.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
Traceback (most recent call last):
  File "G:\RVC-beta\RVC-beta-v2-0528\infer-web.py", line 184, in vc_single
    audio_opt = vc.pipeline(
  File "G:\RVC-beta\RVC-beta-v2-0528\vc_infer_pipeline.py", line 382, in pipeline
    self.vc(
  File "G:\RVC-beta\RVC-beta-v2-0528\vc_infer_pipeline.py", line 201, in vc
    score, ix = index.search(npy, k=8)
  File "G:\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\faiss\__init__.py", line 341, in replacement_search
    assert d == self.d
AssertionError

Traceback (most recent call last):
  File "G:\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "G:\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "G:\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "G:\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "G:\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "G:\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by KelvinNgAU** [comment]
I used a new wav file with attribution, no Chinese character, and it work now.

**Comment by SilverAsh60** [comment]
i have the same issue, made new wav files but still error
