### ISSUE TITLE
read_index error

### ISSUE THREAD

**Issue by Soltus** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#425]
点击音频转换后报错，显卡是 1660s

```log
16系/10系显卡和P40强制单精度
input device:3:闪克PM461S (USB Condenser Microph (MME)
output device:7:入梦扬声器 (VB-Audio Cable A) (MME)
{'hubert_path': 'F:/白刀子进红刀子出高速下载中心/Motrix/RVC-beta/RVC-beta-v2-0528/RVC-beta-v2-0528/hubert_base.pt', 'pth_path': 'F:/白刀子进红刀子出高速下载中心/Motrix/RVC-beta/RVC/moxing/hanser/hanser/hanser.pth', 'index_path': 'F:/白刀子进红刀子出高速下载中心/Motrix/RVC-beta/RVC/moxing/hanser/hanser/added_IVF2379_Flat_nprobe_1.index', 'npy_path': 'F:/白刀子进红刀子出高速下载中心/Motrix/RVC-beta/RVC/moxing/hanser/hanser/total_fea.npy', 'pitch': 12.0, 'samplerate': 44100, 'block_time': 1.0, 'buffer_num': 1, 'threhold': -30.0, 'crossfade_time': 0.08, 'extra_time': 0.05, 'I_noise_reduce': False, 'O_noise_reduce': False, 'index_rate': 0.5}
using_cuda:True
Traceback (most recent call last):
  File "F:\白刀子进红刀子出高速下载中心\Motrix\RVC-beta\RVC-beta-v2-0528\RVC-beta-v2-0528\gui.py", line 60, in __init__
    self.index = faiss.read_index(index_path)
  File "F:\白刀子进红刀子出高速下载中心\Motrix\RVC-beta\RVC-beta-v2-0528\RVC-beta-v2-0528\runtime\lib\site-packages\faiss\swigfaiss.py", line 8261, in read_index
    return _swigfaiss.read_index(*args)
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open F:/白刀子进红刀子出高速下载中心/Motrix/RVC-beta/RVC/moxing/hanser/hanser/added_IVF2379_Flat_nprobe_1.index for reading: Illegal byte sequence
```

**Comment by Soltus** [comment]
换成纯英文路径解决了
