### ISSUE TITLE
Error while converting in Model Inference

### ISSUE THREAD

**Issue by DKTulio** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#430]
After training, I proceed to input the Inferencing voice and index file to convert but all of them gave the same error. How do I fix this problem?

"<All keys matched successfully>
Traceback (most recent call last):
  File "C:\Users\Asus\AI\RVC-beta\RVC-beta-v2-0528\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\Asus\AI\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Asus\AI\RVC-beta\RVC-beta-v2-0528\infer-web.py", line 161, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "C:\Users\Asus\AI\RVC-beta\RVC-beta-v2-0528\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "C:\Users\Asus\AI\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Asus\AI\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Asus\AI\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Asus\AI\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\Asus\AI\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\Asus\AI\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'"

**Comment by RVC-Boss** [comment]
What's the path of your input audio?

**Comment by DKTulio** [comment]
> What's the path of your input audio?

It inside the "weights" file inside the "RVC-beta-v2-0528" files
C:\Users\Asus\AI\RVC-beta\RVC-beta-v2-0528\weights

**Comment by ibaah21** [comment]
i have the same issue did you figure it out??

**Comment by Italia434** [comment]
Same problem
