### ISSUE TITLE
Got error when running go-web.bat

### ISSUE THREAD

**Issue by hysasuke** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#446]
Got **ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject** error. 

Seems like upgrading **numpy** will resolve the issue after some research. However, I'm not so familar with Python, so could anyone help me with that? Thanks a lot.

**Comment by FlashlightET** [comment]
same but different error
```Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\blah blah had to move these\X\RVC\RVC-beta-v2-0528\infer-web.py", line 84, in <module>
    from vc_infer_pipeline import VC
  File "H:\blah blah had to move these\X\RVC\RVC-beta-v2-0528\vc_infer_pipeline.py", line 5, in <module>
    import pyworld, os, traceback, faiss, librosa,torchcrepe
  File "H:\blah blah had to move these\X\RVC\RVC-beta-v2-0528\runtime\lib\site-packages\pyworld\__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld\pyworld.pyx", line 6, in init pyworld.pyworld
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import```

**Comment by RVC-Boss** [comment]
You can update the code to the latest main branch, where this version dependency issue has already been resolved.
