### ISSUE TITLE
我应该在这里放什么，因为它根本不起作用？Urgent help please as it is not working

### ISSUE THREAD

**Issue by Neblaa** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#449]
我应该在这里放什么，因为它根本不起作用？
What should I put here as it's not working at all
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/135685594/5878375a-31e2-41ea-83d5-405b2247ccd5)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/135685594/0d321582-7a71-417a-ab5d-a0b7366959b8)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/135685594/4b52bbf0-cdff-4167-81af-1559b8f53f66)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/135685594/3d43e3db-8622-4bc1-b4f4-cad06d4ead2e)

**Comment by Neblaa** [comment]
当我尝试分离音频时，我收到了这个错误。I get this error when I try to separate the audio
.
.
.

Amr Diab - Shokran Min Hina Le Bokra .mp3.reformatted.wav->Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 164, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 195, in __soundfile_load
    context = sf.SoundFile(path)
  File "/usr/local/lib/python3.10/dist-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/lib/python3.10/dist-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening '/content/Retrieval-based-Voice-Conversion-WebUI/TEMP/Amr Diab - Shokran Min Hina Le Bokra .mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 287, in uvr
    pre_fun._path_audio_(inp_path, save_root_ins, save_root_vocal)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer_uvr5.py", line 79, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "/usr/local/lib/python3.10/dist-packages/librosa/util/decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 170, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 226, in __audioread_load
    reader = audioread.audio_open(path)
  File "/usr/local/lib/python3.10/dist-packages/audioread/__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "/usr/local/lib/python3.10/dist-packages/audioread/rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/content/Retrieval-based-Voice-Conversion-WebUI/TEMP/Amr Diab - Shokran Min Hina Le Bokra .mp3.reformatted.wav'

.ipynb_checkpoints.reformatted.wav->Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 164, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 195, in __soundfile_load
    context = sf.SoundFile(path)
  File "/usr/local/lib/python3.10/dist-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/lib/python3.10/dist-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening '/content/Retrieval-based-Voice-Conversion-WebUI/TEMP/.ipynb_checkpoints.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 287, in uvr
    pre_fun._path_audio_(inp_path, save_root_ins, save_root_vocal)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer_uvr5.py", line 79, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "/usr/local/lib/python3.10/dist-packages/librosa/util/decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 170, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 226, in __audioread_load
    reader = audioread.audio_open(path)
  File "/usr/local/lib/python3.10/dist-packages/audioread/__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "/usr/local/lib/python3.10/dist-packages/audioread/rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/content/Retrieval-based-Voice-Conversion-WebUI/TEMP/.ipynb_checkpoints.reformatted.wav'

**Comment by RainaObi** [comment]
under DATASET introduce the path to your zip

**Comment by Neblaa** [comment]
@RainaObi I am sorry I am not an expert, would you please elaborate more regarding my zip that I need to introduce under the dataset?
