### ISSUE TITLE
FileNotFoundError  3_feature256

### ISSUE THREAD

**Issue by CiaShangLin** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#451]
按一鍵訓練後都會跑出這個錯誤
不管是在windons上或是mac上都會
windons上都讀取不到我的3060ti是因為太新嗎？
File "/Users/caishanglin/anaconda3/envs/py3_8_16/lib/python3.8/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "infer-web.py", line 933, in train1key
    & set([name.split(".")[0] for name in os.listdir(feature_dir)])
FileNotFoundError: [Errno 2] No such file or directory: '/Users/caishanglin/Downloads/RVC-beta-v2-0528/logs/Shang/3_feature256'

**Comment by RVC-Boss** [comment]
pytorch版本没装对，不支持cuda，嫌麻烦的话建议下完整包，否则去pytorch官网找支持cuda的pytorch的安装命令

**Comment by CiaShangLin** [comment]
裝好了結果跑python infer-web.py
結果跑出下面的錯誤頭痛
Traceback (most recent call last):
  File "C:\Users\User\Downloads\RVC-beta-v2-0528\infer-web.py", line 37, in <module>
    gpu_name = torch.cuda.get_device_name(i)
  File "C:\Users\User\anaconda3\envs\py3916\lib\site-packages\torch\cuda\__init__.py", line 365, in get_device_name
    return get_device_properties(device).name
  File "C:\Users\User\anaconda3\envs\py3916\lib\site-packages\torch\cuda\__init__.py", line 395, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "C:\Users\User\anaconda3\envs\py3916\lib\site-packages\torch\cuda\__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unrecognized CachingAllocator option: max_split_size_mb=4096

**Comment by 24bit192kHz** [comment]
(i'm using WSL)

i'm getting the same thing even tho i installed pytorch 
the 伴奏人声分离&去混响&去回声 works fine but when i try Train u i get this

ro0t@DESKTOP-JTUBJPS:/mnt/h/TCHT/RVC-beta-v2-0528$ python3 infer-web.py
Use Language: en_US
Running on local URL:  http://0.0.0.0:7865
/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

Traceback (most recent call last):
  File "/home/ro0t/.local/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ro0t/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/ro0t/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/ro0t/.local/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/home/ro0t/.local/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/ro0t/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ro0t/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/ro0t/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/ro0t/.local/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/mnt/h/TCHT/RVC-beta-v2-0528/infer-web.py", line 932, in train1key
    set([name.split(".")[0] for name in os.listdir(gt_wavs_dir)])
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/h/TCHT/RVC-beta-v2-0528/logs/mi-test/0_gt_wavs'

**Comment by CiaShangLin** [comment]
最後是安裝這個版本的cuda
# CUDA 11.1
pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
終於可以開得起來和偵測到顯卡了

**Comment by zhouhao27** [comment]
What to do in my Mac?
