### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tobytes'

### ISSUE THREAD

**Issue by baby11233** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#454]
训练过程/分离过程一切正常, 但是最后转换的时候就出错了

Traceback (most recent call last):
  File "E:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 184, in vc_single
    audio_opt = vc.pipeline(
  File "E:\RVC\Retrieval-based-Voice-Conversion-WebUI\vc_infer_pipeline.py", line 366, in pipeline
    self.vc(
  File "E:\RVC\Retrieval-based-Voice-Conversion-WebUI\vc_infer_pipeline.py", line 227, in vc
    pitchff = pitchf.clone()
AttributeError: 'NoneType' object has no attribute 'clone'

Traceback (most recent call last):
  File "E:\RVC\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\RVC\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\RVC\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "E:\RVC\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "E:\RVC\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

**Comment by RVC-Boss** [comment]
try protect=0.5

**Comment by RVC-Boss** [comment]
I will fix it. No f0 model doesn't support "protect".

**Comment by Bigwvevo** [comment]
im having the exact same issue and have tried alot of different things and it still isnt working. would it be the model i have?
