### ISSUE TITLE
Couldn't save model

### ISSUE THREAD

**Issue by Naozumi520** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#462]
```
INFO:ViceP:Training is done. The program is closed.
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/naozumi/Downloads/RVC-beta-v2-0528/train_nsf_sim_cache_sid_load_pretrain.py", line 219, in run
    train_and_evaluate(
  File "/Users/naozumi/Downloads/RVC-beta-v2-0528/train_nsf_sim_cache_sid_load_pretrain.py", line 578, in train_and_evaluate
    % (savee(ckpt, hps.sample_rate, hps.if_f0, hps.name, epoch, hps.version,hps))
TypeError: savee() takes 6 positional arguments but 7 were given
```

**Comment by Naozumi520** [comment]
My bad. It seems it's because I copied train_nsf_sim_cache_sid_load_pretrain.py from repo for latest mps support, but didn't also copy `train/process_ckpt.py` as there are 7 arg now.
