### ISSUE TITLE
RuntimeError: unmatched '}' in format string

### ISSUE THREAD

**Issue by soanhee** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#465]
After executing the training, I get the following error:
```
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\sohee\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\sohee\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "H:\RVC\Retrieval-based-Voice-Conversion-WebUI\train_nsf_sim_cache_sid_load_pretrain.py", line 100, in run
    dist.init_process_group(
  File "H:\RVC\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 900, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "H:\RVC\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\distributed\rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "H:\RVC\Retrieval-based-Voice-Conversion-WebUI\venv\lib\site-packages\torch\distributed\rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
RuntimeError: unmatched '}' in format string
```

Help! I have tried to reinstall many times and update according to the requirements, and the same error occurs. My system is WIN10, please help!

**Comment by Tps-F** [comment]
I found same error on
https://github.com/pytorch/pytorch/issues/100185
Maybe, but I don't think this is an RVC issue.
