### ISSUE TITLE
ffmpeg error during infer, audio file path seems fine

### ISSUE THREAD

**Issue by archangel012** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#491]
I get the following error when trying to infer
however my file path for the audio file is "C:\Users\lolfa\Downloads\scatman2", which seems fine to me, and the filename is vocalscatman.wav, which also seems fine 

Traceback (most recent call last):
  File "C:\Users\lolfa\Downloads\RVC-beta\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\lolfa\Downloads\RVC-beta\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lolfa\Downloads\RVC-beta\infer-web.py", line 160, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "C:\Users\lolfa\Downloads\RVC-beta\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "C:\Users\lolfa\Downloads\RVC-beta\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\lolfa\Downloads\RVC-beta\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\lolfa\Downloads\RVC-beta\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\lolfa\Downloads\RVC-beta\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\lolfa\Downloads\RVC-beta\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\lolfa\Downloads\RVC-beta\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by ody007gr** [comment]
im having this problem as well, can anyone help

**Comment by sethtallen** [comment]
Is it only this path and file giving you the error? Also try running it under the batch conversion by uploading only that audio file and see if it still spits out the error.

**Comment by krigrv** [comment]
try using batch conversion it works.

**Comment by Acrivec** [comment]
Make sure your path (folder names) do not contain any spaces, "_", "-", "()", "[]", "{}" etc. Just plain normal names.

**Comment by SeppeVE** [comment]
> try using batch conversion it works.

How would I do that?

**Comment by zimozimo000** [comment]
@archangel012 did u resolve this issue? I've same problem here
