### ISSUE TITLE
sounddevice.PortAudioError: Error opening Stream: Illegal combination of I/O devices [PaErrorCode -9993]

### ISSUE THREAD

**Issue by zhuziying** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#493]
Exception in thread Thread-8 (soundinput):
Traceback (most recent call last):
  File "C:\Users\nbazz\.conda\envs\Voice\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\nbazz\.conda\envs\Voice\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "E:\gitprojects\Retrieval-based-Voice-Conversion-WebUI\gui.py", line 535, in soundinput
    with sd.Stream(
  File "C:\Users\nbazz\.conda\envs\Voice\lib\site-packages\sounddevice.py", line 1800, in __init__
    _StreamBase.__init__(self, kind='duplex', wrap_callback='array',
  File "C:\Users\nbazz\.conda\envs\Voice\lib\site-packages\sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "C:\Users\nbazz\.conda\envs\Voice\lib\site-packages\sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening Stream: Illegal combination of I/O devices [PaErrorCode -9993]
why i get this problem?

**Comment by wwy6668219** [comment]
输出设备和输入设备的协议不一致

**Comment by ranranz-i** [comment]
> 输出设备和输入设备的协议不一致

请问怎么解决
