### ISSUE TITLE
geting an error message when i try to use models

### ISSUE THREAD

**Issue by CoolJNation** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#496]
this is what it gives me
Traceback (most recent call last):
  File "C:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by nonametao** [comment]
Same error, I think there is something wrong with the newest version webui when training models, I have tried v1 and v2 models, both have the same error when using them, I am pretty sure that I use the right 60M model.

**Comment by nonametao** [comment]
By the way, I use pip install -r requirements.txt to prepare the environment, is that the reason?

**Comment by ms903x1** [comment]
If it is a model no "f0", try turning off consonant protection (slider pulled to 0.5)

**Comment by nonametao** [comment]
It works! thanks a lot.

**Comment by Schmimms** [comment]
I have the same error, but I don't understand what u said to do for the solution.
