### ISSUE TITLE
cant run it on my pc. so much errors. im using the barebone python so im pretty much confused

### ISSUE THREAD

**Issue by HaloScripter** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#510]
C:\Users\(myusername)\Downloads\(RVC)>python.exe infer-web.py --pycmd python.exe --port 7897
Use Language: en_US
没有发现支持的N卡, 使用CPU进行推理
Running on local URL:  http://0.0.0.0:7897
loading weights/Dio_Brando_9800.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
Traceback (most recent call last):
  File "C:\Users\username\Downloads\RVCWebui\infer-web.py", line 168, in vc_single
    load_hubert()
  File "C:\Users\username\Downloads\RVCWebui\infer-web.py", line 111, in load_hubert
    models, _, _ = checkpoint_utils.load_model_ensemble_and_task(
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\fairseq\checkpoint_utils.py", line 423, in load_model_ensemble_and_task
    raise IOError("Model file not found: {}".format(filename))
OSError: Model file not found: hubert_base.pt

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

**Comment by Jdn4if** [comment]
الحل
