### ISSUE TITLE
Traceback error 

### ISSUE THREAD

**Issue by ctrlaltdle** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#521]
Traceback (most recent call last):
  File "C:\Users\ethan\anaconda3\envs\rvc\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\ethan\anaconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "C:\Users\ethan\anaconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 1090, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\ethan\anaconda3\envs\rvc\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\ethan\anaconda3\envs\rvc\lib\site-packages\gradio\utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\ethan\anaconda3\envs\rvc\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\ethan\anaconda3\envs\rvc\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\ethan\anaconda3\envs\rvc\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\ethan\anaconda3\envs\rvc\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "E:\voice ui\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 932, in train1key
    set([name.split(".")[0] for name in os.listdir(gt_wavs_dir)])
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\voice ui\\Retrieval-based-Voice-Conversion-WebUI/logs/femfaydan/0_gt_wavs'

**Comment by RVC-Boss** [comment]
"voice ui"no space
