### ISSUE TITLE
FileNotFoundError: [WinError 3]

### ISSUE THREAD

**Issue by AzzySama** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#548]
Hello there, I was trying to do the one-click training but every time I get this error:

```
...
f0ing,now-20,all-23,-C:\RVC/logs/dio/1_16k_wavs/0_65.wav
f0ing,now-20,all-23,-C:\RVC/logs/dio/1_16k_wavs/0_62.wav
f0ing,now-20,all-23,-C:\RVC/logs/dio/1_16k_wavs/0_59.wav
f0ing,now-20,all-23,-C:\RVC/logs/dio/1_16k_wavs/0_66.wav
f0ing,now-20,all-23,-C:\RVC/logs/dio/1_16k_wavs/0_64.wav
f0ing,now-20,all-23,-C:\RVC/logs/dio/1_16k_wavs/0_61.wav

Traceback (most recent call last):
  File "C:\RVC\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\RVC\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\RVC\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\RVC\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\RVC\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\RVC\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\RVC\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "C:\RVC\infer-web.py", line 933, in train1key
    & set([name.split(".")[0] for name in os.listdir(feature_dir)])
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\RVC/logs/dio/3_feature768'
``` 
Could you kindly help me figure this problem out? Thank you

**Comment by Smasanders** [comment]
I am also struggling with this issue

**Comment by Tps-F** [comment]
#347 

As you can see here, there is some kind of error in step1 and step2.

**Comment by Mugen-CC** [comment]
I got this error trying to do a one-click train as well.

**Comment by leonardobits** [comment]
I had the same issue, but it worked fine when I ran the server as admin. It could be some problem to create folders and files.

**Comment by leonardobits** [comment]
I had the same issue. I fixed it by creating two folders named 2a_f0 and 2b-f0nsf inside the logs folder that matches the model name I was training. It worked fine for me.

**Comment by boog-i** [comment]
Try downloading this:
https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/mute.zip
