### ISSUE TITLE
FileNotFoundError: [WinError 3] specifically file "0_gt_wavs"

### ISSUE THREAD

**Issue by RinnMel** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#557]
Tested multiple times but came out to the same issue 

['extract_f0_print.py', 'C:\TCHT\Retrieval-based-Voice-Conversion-WebUI/logs/suisei', '12', 'harvest']
['extract_feature_print.py', 'cuda:0', '1', '0', '0', 'C:\TCHT\Retrieval-based-Voice-Conversion-WebUI/logs/suisei', 'v1']
C:\TCHT\Retrieval-based-Voice-Conversion-WebUI/logs/suisei
load model(s) from hubert_base.pt
move model to cuda

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Python310\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\Python310\lib\site-packages\gradio\blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Python310\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.anext()
  File "C:\Python310\lib\site-packages\gradio\utils.py", line 334, in anext
    return await anyio.to_thread.run_sync(
  File "C:\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Python310\lib\site-packages\anyio_backends_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Python310\lib\site-packages\anyio_backends_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Python310\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 932, in train1key
    set([name.split(".")[0] for name in os.listdir(gt_wavs_dir)])
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\TCHT\Retrieval-based-Voice-Conversion-WebUI/logs/suisei/0_gt_wavs'

**Comment by RVC-Boss** [comment]
there is some other errors before this 
see preprocess.log

**Comment by pofudukpofi** [comment]
What should we do if we see this error?

**Comment by CallMeGuns** [comment]
preprocess.log won't inform you of anything useful, since this is a problem that occurs when training is about to start.

What solved it for me was running the bat from the location of the original directory used when installing everything. 
So if you initially set things up in `C:/SomeFolder`, it will then give the FileNotFoundError if you've moved the repository outside of that directory, say `C:/NewFolder/SomeFolder`. In my case, I just had to move it back to `C:/SomeFolder`. 

Not sure how to reconfigure it properly, but that was how I solved it in my case.

**Comment by DatDuckSaysQuack** [comment]
I am running into this issue as well, version RVC-beta-v2-0618...

**Comment by ddcharx** [comment]
I also have this problem....

C:\Users\Max Sun\Desktop\RVC-beta\RVC-beta-v2-0618>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Use Language: zh_CN
Running on local URL:  http://0.0.0.0:7897
Traceback (most recent call last):
  File "C:\Users\Max Sun\Desktop\RVC-beta\RVC-beta-v2-0618\trainset_preprocess_pipeline_print.py", line 20, in <module>
    f = open("%s/preprocess.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Max/preprocess.log'

Traceback (most recent call last):
  File "C:\Users\Max Sun\Desktop\RVC-beta\RVC-beta-v2-0618\extract_f0_print.py", line 14, in <module>
    f = open("%s/extract_f0_feature.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Max/extract_f0_feature.log'

Traceback (most recent call last):
  File "C:\Users\Max Sun\Desktop\RVC-beta\RVC-beta-v2-0618\extract_feature_print.py", line 29, in <module>
    f = open("%s/extract_f0_feature.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Max/extract_f0_feature.log'

Traceback (most recent call last):
  File "C:\Users\Max Sun\Desktop\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Max Sun\Desktop\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\Max Sun\Desktop\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Max Sun\Desktop\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Max Sun\Desktop\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Max Sun\Desktop\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Max Sun\Desktop\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "C:\Users\Max Sun\Desktop\RVC-beta\RVC-beta-v2-0618\infer-web.py", line 1072, in train1key
    set([name.split(".")[0] for name in os.listdir(gt_wavs_dir)])
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\Max Sun\\Desktop\\RVC-beta\\RVC-beta-v2-0618/logs/untest/0_gt_wavs'

**Comment by wf-chen** [comment]
Create a new folder within the project, place the materials in this folder, and specify the material path as the path of the newly created folder.

**Comment by wf-chen** [comment]
> Create a new folder within the project, place the materials in this folder, and specify the material path as the path of the newly created folder.

It solves my problem

**Comment by DatDuckSaysQuack** [comment]
> Create a new folder within the project, place the materials in this folder, and specify the material path as the path of the newly created folder.

With project, are you referring to where the original audio files are located, or where the unfinished training data is located? Apologies if my question is potentially stupid

**Comment by wf-chen** [comment]
> 

original audio files

**Comment by wf-chen** [comment]
> > Create a new folder within the project, place the materials in this folder, and specify the material path as the path of the newly created folder.
> 
> With project, are you referring to where the original audio files are located, or where the unfinished training data is located? Apologies if my question is potentially stupid

original audio files

**Comment by ddcharx** [comment]
At first, I tried creating a new folder within the project, placing the materials in this folder, and specifying the material path as the path of the newly created folder, but it didn't work. However, when I moved the entire 'rvc' folder with the materials to the root directory of the C drive, the program started running. I guess my initial path was too long for the program.

**Comment by DatDuckSaysQuack** [comment]
> > > Create a new folder within the project, place the materials in this folder, and specify the material path as the path of the newly created folder.
> > 
> > 
> > With project, are you referring to where the original audio files are located, or where the unfinished training data is located? Apologies if my question is potentially stupid
> 
> original audio files

I cannot say for certain as to how and why, but this actually worked. Huh.

**Comment by wf-chen** [comment]
> At first, I tried creating a new folder within the project, placing the materials in this folder, and specifying the material path as the path of the newly created folder, but it didn't work. However, when I moved the entire 'rvc' folder with the materials to the root directory of the C drive, the program started running. I guess my initial path was too long for the program.

I guess it might be caused by spaces in the folder names.

**Comment by DatDuckSaysQuack** [comment]
It actually does seem like that this RVC web UI hates spaces. Everything works for me now since I've removed any and all spaces from my paths, and this specific error only appears when I've specified a path that contains spaces.
That is very annoying, but at least now I know how to avert the error.

**Comment by boog-i** [comment]
Try downloading this:
https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/mute.zip

**Comment by abe546** [comment]
I was able to resolve this issue by moving the training set data folder to the root directory where the UI .bat file is launched.

**Comment by DatDuckSaysQuack** [comment]
I resolved this issue a while ago by just not having any spaces in the file path.

**Comment by qinglangee** [comment]
```
The reason of the issue for me is the input folder name, 
in windows system, if we copy path with the end slash '\', 
this will break the infer\modules\train\preprocess.py  script,  
so there is no 1_16k_wavs  and  0_gt_wavs folders created.
```
用资源管理器复制路径就不会踩这个坑了。。。
