### ISSUE TITLE
RuntimeError: mat1 and mat2 must have the same dtype

### ISSUE THREAD

**Issue by Mugen-CC** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#566]
```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\------\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "C:\Users\------\Documents\Programming\python\RVC\RVC-beta20230516\train_nsf_sim_cache_sid_load_pretrain.py", line 196, in run
    train_and_evaluate(
  File "C:\Users\------\Documents\Programming\python\RVC\RVC-beta20230516\train_nsf_sim_cache_sid_load_pretrain.py", line 364, in train_and_evaluate
    ) = net_g(phone, phone_lengths, pitch, pitchf, spec, spec_lengths, sid)
  File "C:\Users\------\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\------\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\parallel\distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "C:\Users\------\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\parallel\distributed.py", line 1113, in _run_ddp_forward
    return module_to_run(*inputs, **kwargs)
  File "C:\Users\------\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\------\Documents\Programming\python\RVC\RVC-beta20230516\infer_pack\models.py", line 737, in forward
    o = self.dec(z_slice, pitchf, g=g)
  File "C:\Users\------\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\------\Documents\Programming\python\RVC\RVC-beta20230516\infer_pack\models.py", line 492, in forward
    har_source, noi_source, uv = self.m_source(f0, self.upp)
  File "C:\Users\------\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\------\Documents\Programming\python\RVC\RVC-beta20230516\infer_pack\models.py", line 415, in forward
    sine_merge = self.l_tanh(self.l_linear(sine_wavs))
  File "C:\Users\------\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\------\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype
```
I got this error trying to train a model with Train Model. I'm using RVC-beta20230516 since the latest version won't train the model. I had to alter `extract_feature_print.py` so to get Feature extraction to work
```
if len(sys.argv) == 6:
    exp_dir = sys.argv[4]
    version = sys.argv[5]
else:
    i_gpu = sys.argv[4]
    exp_dir = sys.argv[5]
    os.environ["CUDA_VISIBLE_DEVICES"] = str(i_gpu)
    version = sys.argv[6]
```

**Comment by RVC-Boss** [comment]
File "C:\Users\------\Documents\Programming\python\RVC\RVC-beta20230516\infer_pack\models.py", line 415, in forward
    sine_merge = self.l_tanh(self.l_linear(sine_wavs))

you can change this line to

sine_merge = self.l_tanh(self.l_linear(sine_wavs.to(self.l_linear.weight.dtype)))

to fix it
