### ISSUE TITLE
Unable to use trained voice. Error. Somebody help?

### ISSUE THREAD

**Issue by AlejandroBlinky** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#580]
<All keys matched successfully>
Traceback (most recent call last):
  File "D:\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "D:\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 178, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "D:\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "D:\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "D:\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "D:\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'.
![imagen_2023-06-19_141531836](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/135030090/5c5e6295-b092-47ae-8cf9-255ec7a06167)

**Comment by AlejandroBlinky** [comment]
My vocal file was in .mp3 and not in .wav. That fixed it

**Comment by iamzhangyunlu** [comment]
> My vocal file was in .mp3 and not in .wav. That fixed it
@AlejandroBlinky I use mp3 file but that error still happen, do you know why?
