### ISSUE TITLE
error

### ISSUE THREAD

**Issue by muntasirmahdi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#581]
t2smidle_01 (enhanced) (2).wav.reformatted.wav->Traceback (most recent call last):
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\soundfile.py", line 1213, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'D:\\RVC-beta\\RVC-beta-v2-0618\\TEMP/t2smidle_01 (enhanced) (2).wav.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\RVC-beta\RVC-beta-v2-0618\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "D:\RVC-beta\RVC-beta-v2-0618\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\RVC-beta\\RVC-beta-v2-0618\\TEMP/t2smidle_01 (enhanced) (2).wav.reformatted.wav'

**Comment by RVC-Boss** [comment]
try delete space in "t2smidle_01 (enhanced) (2).wav"
