### ISSUE TITLE
PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by CGMikeG** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#585]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Programs\anaconda\envs\rvc\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Programs\anaconda\envs\rvc\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\Programs\anaconda\envs\rvc\lib\multiprocessing\connection.py", line 962, in rebuild_pipe_connection
    handle = dh.detach()
  File "D:\Programs\anaconda\envs\rvc\lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] Access is denied

**Comment by CGMikeG** [comment]
All good I just realize I put file path instead of just the folder path in the training folder
