### ISSUE TITLE
cant find path

### ISSUE THREAD

**Issue by adalimert** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#594]
Traceback (most recent call last):
  File "D:\rvcaudio\rvc\rvc\infer-web.py", line 178, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "D:\rvcaudio\rvc\rvc\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "D:\rvcaudio\rvc\rvc\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\rvcaudio\rvc\rvc\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\rvcaudio\rvc\rvc\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\rvcaudio\rvc\rvc\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "D:\rvcaudio\rvc\rvc\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "D:\rvcaudio\rvc\rvc\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

in model inference cant find the path ı write path vith song name but he cant find pls help

**Comment by protocolGITHUB** [comment]
fwiw, you get the same error if an audio file is not found, or if an audio file has more than 2 channels.

**Comment by Ma5onic** [comment]
If you are on windows make sure that your path has a `\` at the end.
