### ISSUE TITLE
Traceback FFMPEG or Gardio issues

### ISSUE THREAD

**Issue by Senaric** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#598]
Program used to work just fine, then started to get the following message when running locally. Any ideas?
```
Traceback (most recent call last):
  File "F:\AI\Voice\RVCbeta\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "F:\AI\Voice\RVCbeta\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\AI\Voice\RVCbeta\infer-web.py", line 181, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "F:\AI\Voice\RVCbeta\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "F:\AI\Voice\RVCbeta\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "F:\AI\Voice\RVCbeta\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\AI\Voice\RVCbeta\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "F:\AI\Voice\RVCbeta\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "F:\AI\Voice\RVCbeta\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "F:\AI\Voice\RVCbeta\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```

**Comment by Oscar1568** [comment]
Um, how did you fix that?

**Comment by PatrickSLU** [comment]
has this been resolved?

**Comment by Senaric** [comment]
> has this been resolved?



> Um, how did you fix that?

I've recently moved RVC's folder along with the audio files and mistakenly kept putting the wrong path since I changed the disk drive. If you're having that issue, check to make sure you have the correct path with no spaces in the names leading up to the audio file.

**Comment by PatrickSLU** [comment]
thank you for the input @Senaric i will try it out
