### ISSUE TITLE
File "traceback.py", line 105, in print_exceptionoSError: [WinError 6]

### ISSUE THREAD

**Issue by NaughtDZ** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#637]
Exception ignored from cffi callback function
_StreamBase._init_.<locals>.callback_ptr at Ox00000164FD1FDF70> :Traceback (most recent call last):
File "I:\RVC-beta\runtime\lib\site-packagesisounddevice.py", line 886,in callback_ptr
return _wrap_callback(
File "I:\RVc-betalruntime\libisite-packagesjsounddevice.py" , line2687, in _wrap_callback
callback(*args)
File "l:\RVC-beta\Rumeng.py", line 581, in audio_callback
self.rvc.infer(self.resampler1(torch.from_numpy(self.input_wav)))File "I:\RVC-betaRumeng.py", line 194, in infer
traceback.print_exco
File "traceback.py" , line 163, in print_exc
File "traceback.py", line 105, in print_exceptionoSError: [WinError 6]句柄无效。

**Comment by NaughtDZ** [comment]
MME show this errro,and wasapi or wdm cant out put any thing

**Comment by TripleKiller666** [comment]
My guess, you didn´t load in a .wav File and the File Format you supplied couldn´t be read.
Fixed most of my Problems by converting from .ogg/.flac/.mp3/etc  to  .wav first.
