### ISSUE TITLE
Having trouble with Training A Voice

### ISSUE THREAD

**Issue by CODEXX9** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#639]
I'm not a coder so I'm not 100% sure whats wrong, training ends and gives me this runtime error:

RuntimeError: The expanded size of the tensor (12800) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [1, 12800].  Tensor sizes: [0]

I successfully created 1 voice with it already, So I'm not sure what's wrong. Again, not a coder, so I don't know the in and outs of python or anything really. But any help is appreciated. I doubt this is it but I used audiosplitter on my .wav samples and it gives a .json file which I deleted. But yeah, big dummy here, need help.

**Comment by TripleKiller666** [comment]
You should post the entire CMD Log instead of just a single Line.
But I would roughly guess the your Card ran out of Memory from the Looks of it:
`The expanded size of the tensor (12800) must match the existing size (0) at non-singleton dimension 1. Target sizes: [1, 12800]. Tensor sizes: [0]`
Can you share a bit more about your Card and your Training Settings?

**Comment by novacrazy** [comment]
This seems to happen when the training data audio files change between training sessions. At least that's how I ran into it.

**Comment by Aarushb** [comment]
Can confirm, just ran into the same issue. I had trained a voice up to 200 epochs just to test it out as this was my very first experiment with this thing, but since it worked quite well wanted to train it further up to 1,000 max, so I added a bunch more files, selected epoch value from the web UI and the error occurred. Well, I tried with 1,000, and the error was roughly similar; only the values changed. This is with doing 800.
Using the NVIDIA GeForce RTX 3070 Ti with 8GB of dedicated VRAM.
I know this GPU is reasonablly powerful, but I don't know if this is too much for it to handle, or how much is "too much." 200 epochs worked just fine earlier, but this is also five times that. I can do it in chunks or something, like 200 first, then another 200, if I can find out how much it can handle at once.
Full error pasted below:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\train_nsf_sim_cache_sid_load_pretrain.py", line 228, in run
    train_and_evaluate(
  File "C:\Users\user\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\train_nsf_sim_cache_sid_load_pretrain.py", line 397, in train_and_evaluate
    ) = net_g(phone, phone_lengths, pitch, pitchf, spec, spec_lengths, sid)
  File "C:\Users\user\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\env\lib\site-packages\torch\nn\parallel\distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "C:\Users\user\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\env\lib\site-packages\torch\nn\parallel\distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "C:\Users\user\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\lib\infer_pack\models.py", line 741, in forward
    z_slice, ids_slice = commons.rand_slice_segments(
  File "C:\Users\user\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\lib\infer_pack\commons.py", line 68, in rand_slice_segments
    ret = slice_segments(x, ids_str, segment_size)
  File "C:\Users\user\Downloads\Retrieval-based-Voice-Conversion-WebUI-main\lib\infer_pack\commons.py", line 49, in slice_segments
    ret[i] = x[i, :, idx_str:idx_end]
RuntimeError: The expanded size of the tensor (36) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [192, 36].  Tensor sizes: [192, 0]

**Comment by volnas10** [comment]
I've had the same problem after changing the dataset or adding some files, here's how I fixed this error:
1.  Change experiment name to something different
2.  Enter the path for the new dataset and click 'Process data'. New folder will appear in the logs folder
3.  Extract the features
4.  Copy the latest D_******.pth and G_******.pth files (checkpoints) from the old to the new experiment folder
5.  And finally proceed with training as usual

**Comment by noobowned** [comment]
i had the same problem and a simple name fix to all the data audio fixed it for me. i also relocated the data set so a new folder so it could start fresh.

**Comment by d0mse** [comment]
@volnas10 thank you! It helped me ❤️👍

**Comment by ERETLY** [comment]
idk, I had a name.wav file and I changed it to another name.wav file and there was an error. I returned that file name.wav and inserted the second one as name1.wav and everything works. I don’t know how exactly to give him the opportunity to learn only from name1.wav. Because I use applio and it’s a little difficult to continue training.
