### ISSUE TITLE
[Help!} Error while converting in Model Inference #430 

### ISSUE THREAD

**Issue by ibaah21** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#640]
While in the model interface The _D and _G .pth files get immediate error codes and the .pth file without D or G doesn't get a error code until i hit convert. How do I fix this problem?

<img width="975" alt="Screenshot at Jun 26 20-21-54" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/116685119/5a2e8793-456e-4a4b-82ac-266171e5a2f6">
<img width="990" alt="Screenshot at Jun 26 20-21-07" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/116685119/3a4487f9-a8cf-46d6-bfcc-ce782a82cdea">

**Comment by TripleKiller666** [comment]
Are you properly loading in the Audio with ffmpeg?
Check your Path again, and make sure that your files are .wav
All other File Extensions gave me an error, so that might help.
You can also try to download the latest FFMPEG yourself, and then replace the one in your Folder.

**Comment by TripleKiller666** [comment]
For example, the below one didn´t work for me despite the path being right:
"X:\That's Life (Remastered 2008).flac"

When I converted it to .wav however, it worked without problem:
"X:\That's Life (Remastered 2008).wav"

Note, that both Times it´s the Vocal only Track and not the Full Song.

**Comment by leaper-max** [comment]
I've trained my model with and without pitch guidance all in model v2 and v1. I Tried 0 protection 0.33 and 0.5, harvest crepe and pm give the same error.
The path is good no spaces no () only - _

Anyone had luck in solving this?

```
Traceback (most recent call last):
  File "V:\AI\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "V:\AI\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 178, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "V:\AI\Retrieval-based-Voice-Conversion-WebUI\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\tools\miniconda3\envs\rvc\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```

**Comment by mferdem** [comment]
hey, im having the same error now. 
"AttributeError: 'NoneType' object has no attribute 'dtype'" 

How do I fix this problem?

**Comment by ibaah21** [comment]
> For example, the below one didn´t work for me despite the path being right: "X:\That's Life (Remastered 2008).flac"
> 
> When I converted it to .wav however, it worked without problem: "X:\That's Life (Remastered 2008).wav"
> 
> Note, that both Times it´s the Vocal only Track and not the Full Song.
Thanks! I did convert the song to .wav but I didn’t try it with latest FFMPEG. I’ll try that and see if it works.
