### ISSUE TITLE
ConnectionResetError: [WinError 10054]

### ISSUE THREAD

**Issue by ask0** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#651]
Getting this error in model inference. Produces mp3 file but no sound
```
<All keys matched successfully>
2023-06-29 16:07:06 | ERROR | root | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by leaper-max** [comment]
I have the same error in model inference. It produces an audio file with the same format as the audio file to be processed, it takes about 2 seconds to finish. the audio produced has sound but its kinda glitchy.

The output information says:
```
Success.
 Index not used.
Time:
 npy:0.04253196716308594s, f0:4.491180896759033s, infer:0.9832859039306641s
```

```
<All keys matched successfully>
2023-07-02 10:16:05 | ERROR | root | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by Digidr0** [comment]
I have the same error. **After one successful launch my server lost connection, and than future audio has the metal, glitchy sound.**

Console:
`ConnectionResetError: [WinError 10054] A remote host forcibly disconnected an existing connection
2023-07-06 13:34:00 | ERROR | asyncio | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] A remote host forcibly disconnected an existing connection`


I have to restart the server to make another attempt at audio conversion.

**Comment by Pashahlis** [comment]
I have the same issue and have yet to find a solution. It literally prevents me from doing inference. I have already tried the usual tricks with the firewall and such.

**Comment by Pashahlis** [comment]
After some more testing, turns out that error message just happens to some people but the audio is processed normally. The glitchy audio issues I was facing was because my dumb ass forgot to separate vocals and instruments for the input too.

**Comment by LGHung** [comment]
so there is no way to fix the issue but somehow it just fuction successfully? how do I know if it cause trouble elsewhere

**Comment by billy7097** [comment]
is it fixed now? I'm still having the trouble

**Comment by jasonmomos** [comment]
I am also facing the same issue, please anyone provide solution

**Comment by yang1010x** [comment]
把asyncio\windows_events.py里面的

DefaultEventLoopPolicy = WindowsProactorEventLoopPolicy
改成

DefaultEventLoopPolicy = WindowsSelectorEventLoopPolicy
