### ISSUE TITLE
ValueError: 48000 SR doesn't match target 40000 SR

### ISSUE THREAD

**Issue by Tomissugo** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#671]
```
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "F:\RVC-beta\RVC-beta-v2-0618\train_nsf_sim_cache_sid_load_pretrain.py", line 223, in run
    train_and_evaluate(
  File "F:\RVC-beta\RVC-beta-v2-0618\train_nsf_sim_cache_sid_load_pretrain.py", line 353, in train_and_evaluate
    for batch_idx, info in data_iterator:
  File "F:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "F:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "F:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "F:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "F:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "F:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\RVC-beta\RVC-beta-v2-0618\train\data_utils.py", line 136, in __getitem__
    return self.get_audio_text_pair(self.audiopaths_and_text[index])
  File "F:\RVC-beta\RVC-beta-v2-0618\train\data_utils.py", line 58, in get_audio_text_pair
    spec, wav = self.get_audio(file)
  File "F:\RVC-beta\RVC-beta-v2-0618\train\data_utils.py", line 96, in get_audio
    raise ValueError(
ValueError: 48000 SR doesn't match target 40000 SR
```

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/103772793/f17c9cb9-994a-417c-b30e-854e7934e2ed)

My GPU is an MSI RTX 2060 6GB

**Comment by RVC-Boss** [comment]
It's caused by you change the sample rate when you continue training.
If you want to change the sample_rate, you should start a new experiment.
