### ISSUE TITLE
RVC导出的onnx模型在VC（voice-changer）中无法使用，但pth可以

### ISSUE THREAD

**Issue by hpx502766238** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#672]
RVC导出的onnx模型在voice-changer(https://github.com/w-okada/voice-changer)中无法使用，报错，但VC直接使用pth又能够推理，但如果使用pth，又不能通过DirectML利用核显的算力了（测试用VC自带的onnx示例模型是可以使用核显推理的）。下面是VC报错内容：
[Voice Changer] VC PROCESSING EXCEPTION!!! Required inputs (['phone', 'phone_lengths', 'ds', 'rnd']) are missing from input feed (['feats', 'p_len', 'pitch', 'pitchf', 'sid']).
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 228, in on_request_sola
  File "voice_changer\RVC\RVC.py", line 157, in inference
  File "voice_changer\RVC\pipeline\Pipeline.py", line 209, in exec
  File "voice_changer\RVC\inferencer\OnnxRVCInferencer.py", line 57, in infer
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 213, in run
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 195, in _validate_input
ValueError: Required inputs (['phone', 'phone_lengths', 'ds', 'rnd']) are missing from input feed (['feats', 'p_len', 'pitch', 'pitchf', 'sid']).

**Comment by GamePP** [comment]
我现在ONNX能跑起来，shape也是对的，但是是杂音

**Comment by ykk648** [comment]
onnx转换的不一样
