### ISSUE TITLE
One-Click Training Error

### ISSUE THREAD

**Issue by enescelik0** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#674]
So i don't know anything about coding or ai things and it was so painful to install this on my computer. So i am assuming that i am missing some required files or programs (idk like ffmpeg thing?). I am just getting this error message when i try to train it 
Traceback (most recent call last):
My 
  File "C:\Users\ÇELİK\Desktop\Ses AI\Retrieval-based-Voice-Conversion-WebUI\trainset_preprocess_pipeline_print.py", line 8, in <module>
    sr = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'Eğitim'

Traceback (most recent call last):
  File "C:\Users\ÇELİK\Desktop\Ses AI\Retrieval-based-Voice-Conversion-WebUI\extract_f0_print.py", line 13, in <module>
    f = open("%s/extract_f0_feature.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ÇELİK\\Desktop\\Ses/extract_f0_feature.log'

Traceback (most recent call last):
  File "C:\Users\ÇELİK\Desktop\Ses AI\Retrieval-based-Voice-Conversion-WebUI\extract_feature_print.py", line 28, in <module>
    f = open("%s/extract_f0_feature.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ÇELİK\\Desktop\\Ses/extract_f0_feature.log'

Traceback (most recent call last):
  File "C:\Users\ÇELİK\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\ÇELİK\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\ÇELİK\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\ÇELİK\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\ÇELİK\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\ÇELİK\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\ÇELİK\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "C:\Users\ÇELİK\Desktop\Ses AI\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 1078, in train1key
    & set([name.split(".")[0] for name in os.listdir(f0_dir)])
FileNotFoundError: [WinError 3] The system cannot find the path specified : 'C:\\Users\\ÇELİK\\Desktop\\Ses AI\\Retrieval-based-Voice-Conversion-WebUI/logs/ümit özdağ/2a_f0'

**Comment by shbkukuk** [comment]
you should not use turkish letters as like 'Ğ,  İ , ü ' etc.

**Comment by AbeEstrada** [comment]
In my case, I was using `rvmpe_gpu`, selected `rvmpe` and it generated the `2a_f0` folder
