### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Sigarya** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#675]
1 (1).mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (1).mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (1).mp3.reformatted.wav'

1 (10).mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (10).mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (10).mp3.reformatted.wav'

1 (11).mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (11).mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (11).mp3.reformatted.wav'

1 (12).mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (12).mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (12).mp3.reformatted.wav'

1 (2).mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (2).mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (2).mp3.reformatted.wav'

1 (3).mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (3).mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (3).mp3.reformatted.wav'

1 (4).mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (4).mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (4).mp3.reformatted.wav'

1 (5).mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (5).mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (5).mp3.reformatted.wav'

1 (6).mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (6).mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (6).mp3.reformatted.wav'

1 (7).mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (7).mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (7).mp3.reformatted.wav'

1 (8).mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (8).mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (8).mp3.reformatted.wav'

1 (9).mp3.reformatted.wav->Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Python310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Python310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (9).mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Python310\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Python310\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/1 (9).mp3.reformatted.wav'

**Comment by RVC-Boss** [comment]
Maybe you need to rename the names and replace space to some other chars.
