### ISSUE TITLE
PyTorch prints a warning and the training automatically ends when continue to train a model

### ISSUE THREAD

**Issue by qing762** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#677]
I try to continue training my model and this happens.

```INFO:a:Loaded model weights
INFO:a:Loaded checkpoint './logs\a\D_3800.pth' (epoch 200)
INFO:a:loaded D
./logs\a\G_3800.pth
INFO:a:Loaded model weights
INFO:a:Loaded checkpoint './logs\a\G_3800.pth' (epoch 200)
D:\Downloads\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
D:\Downloads\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\autograd\__init__.py:200: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [64, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [64, 1, 4], strides() = [4, 4, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:337.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
INFO:a:Saving model and optimizer state at epoch 200 to ./logs\a\G_3800.pth
INFO:a:Saving model and optimizer state at epoch 200 to ./logs\a\D_3800.pth
INFO:a:====> Epoch: 200 [2023-07-03 19:12:50] | (0:00:40.886198)
INFO:a:Training is done. The program is closed.
INFO:a:saving final ckpt:Success

**Comment by RVC-Boss** [comment]
You trained a model named "a" with 200 epoch in the past time.
And you want to train a model named "a" with 200 epoch again.
The program finds an existing models named "a" and continue training from 200epoch to 200epoch. So 0 epoch will be trained.

**Comment by qing762** [comment]
> You trained a model named "a" with 200 epoch in the past time. And you want to train a model named "a" with 200 epoch again. The program finds an existing models named "a" and continue training from 200epoch to 200epoch. So 0 epoch will be trained.

Ahh I see. Thanks a lot!

**Comment by qing762** [comment]
I changed the total epoch value to 300
But I still getting an error
Here's the error code

```
INFO:a:{'train': {'log_interval': 200, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 6, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 12800, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 40000, 'filter_length': 2048, 'hop_length': 400, 'win_length': 2048, 'n_mel_channels': 125, 'mel_fmin': 0.0, 'mel_fmax': None, 'training_files': './logs\\a/filelist.txt'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 10, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'use_spectral_norm': False, 'gin_channels': 256, 'spk_embed_dim': 109}, 'model_dir': './logs\\a', 'experiment_dir': './logs\\a', 'save_every_epoch': 5, 'name': 'a', 'total_epoch': 300, 'pretrainG': 'pretrained_v2/f0G40k.pth', 'pretrainD': 'pretrained_v2/f0D40k.pth', 'version': 'v2', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 1, 'if_latest': 0, 'save_every_weights': '0', 'if_cache_data_in_gpu': 0}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
gin_channels: 256 self.spk_embed_dim: 109
./logs\a\D_3800.pth
INFO:a:Loaded model weights
INFO:a:Loaded checkpoint './logs\a\D_3800.pth' (epoch 200)
INFO:a:loaded D
./logs\a\G_3800.pth
INFO:a:Loaded model weights
INFO:a:Loaded checkpoint './logs\a\G_3800.pth' (epoch 200)
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "D:\Downloads\RVC-beta\RVC-beta-v2-0618\train_nsf_sim_cache_sid_load_pretrain.py", line 223, in run
    train_and_evaluate(
  File "D:\Downloads\RVC-beta\RVC-beta-v2-0618\train_nsf_sim_cache_sid_load_pretrain.py", line 353, in train_and_evaluate
    for batch_idx, info in data_iterator:
  File "D:\Downloads\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "D:\Downloads\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "D:\Downloads\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "D:\Downloads\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Downloads\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Downloads\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Downloads\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Downloads\RVC-beta\RVC-beta-v2-0618\train\data_utils.py", line 136, in __getitem__
    return self.get_audio_text_pair(self.audiopaths_and_text[index])
  File "D:\Downloads\RVC-beta\RVC-beta-v2-0618\train\data_utils.py", line 58, in get_audio_text_pair
    spec, wav = self.get_audio(file)
  File "D:\Downloads\RVC-beta\RVC-beta-v2-0618\train\data_utils.py", line 96, in get_audio
    raise ValueError(
ValueError: 48000 SR doesn't match target 40000 SR
