### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by PederHatlen** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#689]
I've been trying to set this up for a little while now, and have not managed to do it.
I got a trained model from a friend, (which works in the live-gui mode, and also performs excellent on his computer).

From what i have gathered is the `AttributeError: 'NoneType' object has no attribute 'dtype'` error, just there because it doesn't get the data it needs, so that's not the troublemaker.

I can't explain the error before it though:

```
Traceback (most recent call last):
  File "D:\RVC-beta-v2-0618\infer-web.py", line 201, in vc_single
    audio_opt = vc.pipeline(
  File "D:\RVC-beta-v2-0618\vc_infer_pipeline.py", line 349, in pipeline
    self.vc(
  File "D:\RVC-beta-v2-0618\vc_infer_pipeline.py", line 204, in vc
    npy = np.sum(big_npy[ix] * np.expand_dims(weight, axis=2), axis=1)
IndexError: index -1 is out of bounds for axis 0 with size 0
```

I have tried all the steps outlined in other issue-threads, but nothing seems to work.
If I'm missing something blatantly obvious, please tell me.

Thanks in advance

**Comment by RVC-Boss** [comment]
You used a wrong .index file. Don't use "trained_xxxx.index"

**Comment by PederHatlen** [comment]
I was using that one, like i said, it worked with the realtime gui client.
I downloaded it again, just to be shure i had the correct one, but that did not help. I tested the model on another machine running linux (the training machine), and that worked just fine (Made sure to put them in the same folders, and used the same audioclips aswell).
