### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: NEW

### ISSUE THREAD

**Issue by MrArabAi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#693]
I got this error during one click training

Traceback (most recent call last):
  File "D:\Ai tests\RVC-beta\RVC-beta-v2-0618\extract_f0_print.py", line 14, in <module>
    f = open("%s/extract_f0_feature.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Ai/extract_f0_feature.log'

Traceback (most recent call last):
  File "D:\Ai tests\RVC-beta\RVC-beta-v2-0618\extract_feature_print.py", line 29, in <module>
    f = open("%s/extract_f0_feature.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Ai/extract_f0_feature.log'

Traceback (most recent call last):
  File "D:\Ai tests\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\Ai tests\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "D:\Ai tests\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Ai tests\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Ai tests\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Ai tests\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Ai tests\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "D:\Ai tests\RVC-beta\RVC-beta-v2-0618\infer-web.py", line 1072, in train1key
    set([name.split(".")[0] for name in os.listdir(gt_wavs_dir)])
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\Ai tests\\RVC-beta\\RVC-beta-v2-0618/logs/mi-test/0_gt_wavs'

**Comment by RVC-Boss** [comment]
no space （"Ai tests"）

**Comment by fadi9696** [comment]
Its working ! Thanks
