### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by AyliasTheCoder** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#705]
When I try training it on a 1050, I get the following error, before it fails:

```
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\rvc\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\ProgramData\anaconda3\envs\rvc\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\train_nsf_sim_cache_sid_load_pretrain.py", line 223, in run
    train_and_evaluate(
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\train_nsf_sim_cache_sid_load_pretrain.py", line 430, in train_and_evaluate
    y_d_hat_r, y_d_hat_g, _, _ = net_d(wave, y_hat.detach())
  File "C:\ProgramData\anaconda3\envs\rvc\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\rvc\lib\site-packages\torch\nn\parallel\distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "C:\ProgramData\anaconda3\envs\rvc\lib\site-packages\torch\nn\parallel\distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "C:\ProgramData\anaconda3\envs\rvc\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_pack\models.py", line 1006, in forward
    y_d_r, fmap_r = d(y)
  File "C:\ProgramData\anaconda3\envs\rvc\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer_pack\models.py", line 1117, in forward
    x = l(x)
  File "C:\ProgramData\anaconda3\envs\rvc\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    result = hook(self, args)
  File "C:\ProgramData\anaconda3\envs\rvc\lib\site-packages\torch\nn\utils\weight_norm.py", line 65, in __call__
    setattr(module, self.name, self.compute_weight(module))
  File "C:\ProgramData\anaconda3\envs\rvc\lib\site-packages\torch\nn\utils\weight_norm.py", line 25, in compute_weight
    return _weight_norm(v, g, self.dim)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 1.69 GiB already allocated; 0 bytes free; 1.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by ahmaddarwesh** [comment]
The error is due to insufficient **GPU VRAM**, so you should lower the `Batch size per GPU` option. However, keep in mind that this will result in slower processing speeds.

**Comment by RVC-Boss** [comment]
2G GPU VRAM card is not supported for traning or inference.
