### ISSUE TITLE
RuntimeError: GlooDeviceFactory::makeUVDevice(): interface or hostname can't be empty

### ISSUE THREAD

**Issue by Accy587** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#724]
Traceback (most recent call last):
File "multiprocessing\process.py", line 315, in _bootstrap
File "multiprocessing\process.py", line 108, in run
File "C:\Users\me\Desktop\rvc\train_nsf_sim_cache_sid_load_pretrain.py", line 100, in run
dist.init_process_group(
File "C:\Users\me\Desktop\rvc\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 895, in init_process_group
default_pg = _new_process_group_helper(
File "C:\Users\me\Desktop\rvc\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 994, in _new_process_group_helper
backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: GlooDeviceFactory::makeUVDevice(): interface or hostname can't be empty

**Comment by Accy587** [comment]
i get this when training

**Comment by MarcoReckless** [comment]
Did you manage to fix this? I'm having the same issue.

**Comment by MarcoReckless** [comment]
I had the same issue since for whatever reason my PC's hostname was blank, I thought it was set and that this was just a random error.
I used the Rename-Computer option via PowerShell, maybe that can fix it for you?
