### ISSUE TITLE
运行完整包的go-realtime-gui程序出现的问题，请大家帮我看看怎么解决。

### ISSUE THREAD

**Issue by bf980818** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#733]
下载了完整包[updated0618v2]完整包 Complete package，在解压后运行里面的go-realtime-gui程序，出现命令窗口内容显示为：
C:\Users\aknokk\Desktop\RVC-beta-v2-0618>runtime\python.exe gui.py
Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
                 It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe
Traceback (most recent call last):
  File "C:\Users\aknokk\Desktop\RVC-beta-v2-0618\gui.py", line 19, in <module>
    from config import Config
  File "C:\Users\aknokk\Desktop\RVC-beta-v2-0618\config.py", line 2, in <module>
    import torch
  File "C:\Users\aknokk\Desktop\RVC-beta-v2-0618\runtime\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "C:\Users\aknokk\Desktop\RVC-beta-v2-0618\runtime\lib\site-packages\torch\lib\c10.dll" or one of its dependencies.

C:\Users\aknokk\Desktop\RVC-beta-v2-0618>pause
请按任意键继续. . .

导致go-realtime-gui程序无法正常运行。
我的电脑是Win10专业版（22H2 19045.3155），显卡1060Ti，驱动都更新到最新版本，尝试了很多方式，一直得不到解决，请大家帮我看看怎么解决，谢谢。

**Comment by Pijulin** [comment]
用DXRepair增强版 修复C++运行库
