### ISSUE TITLE
Filenotfound

### ISSUE THREAD

**Issue by Amrhajjaj** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#735]
todo-f0-79
f0ing,now-0,all-79,-D:\RVC-beta\RVC-beta-v2-0618/logs/o/1_16k_wavs/0_1.wav
todo-f0-79
f0ing,now-0,all-79,-D:\RVC-beta\RVC-beta-v2-0618/logs/o/1_16k_wavs/0_10.wav
f0ing,now-15,all-79,-D:\RVC-beta\RVC-beta-v2-0618/logs/o/1_16k_wavs/0_42.wav
f0ing,now-15,all-79,-D:\RVC-beta\RVC-beta-v2-0618/logs/o/1_16k_wavs/0_43.wav
f0ing,now-30,all-79,-D:\RVC-beta\RVC-beta-v2-0618/logs/o/1_16k_wavs/1_3.wav
f0ing,now-30,all-79,-D:\RVC-beta\RVC-beta-v2-0618/logs/o/1_16k_wavs/1_5.wav
f0ing,now-45,all-79,-D:\RVC-beta\RVC-beta-v2-0618/logs/o/1_16k_wavs/4_10.wav
f0ing,now-45,all-79,-D:\RVC-beta\RVC-beta-v2-0618/logs/o/1_16k_wavs/4_12.wav
f0ing,now-60,all-79,-D:\RVC-beta\RVC-beta-v2-0618/logs/o/1_16k_wavs/5_25.wav
f0ing,now-60,all-79,-D:\RVC-beta\RVC-beta-v2-0618/logs/o/1_16k_wavs/5_26.wav
f0ing,now-75,all-79,-D:\RVC-beta\RVC-beta-v2-0618/logs/o/1_16k_wavs/5_58.wav
f0ing,now-75,all-79,-D:\RVC-beta\RVC-beta-v2-0618/logs/o/1_16k_wavs/5_59.wav

Traceback (most recent call last):
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\RVC-beta\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "D:\RVC-beta\RVC-beta-v2-0618\infer-web.py", line 1073, in train1key
    & set([name.split(".")[0] for name in os.listdir(feature_dir)])
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\RVC-beta\\RVC-beta-v2-0618/logs/o/3_feature768'

**Comment by YahyaZekry** [comment]
Yep, I got the same issue

```
Traceback (most recent call last):
  File "F:\RVC\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "F:\RVC\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "F:\RVC\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\RVC\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\RVC\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\RVC\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\RVC\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "F:\RVC\infer-web.py", line 1073, in train1key
    & set([name.split(".")[0] for name in os.listdir(feature_dir)])
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\RVC/logs/mi-test/3_feature256'
```

**Comment by YahyaZekry** [comment]
Just replace the files with the new version, and you will bypass this bug
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI

**Comment by Nitch-dev** [comment]
> Just replace the files with the new version, and you will bypass this bug https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI

i have this error on mac:

.DS_Store->Traceback (most recent call last):
  File "/Users/albert/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ffmpeg/_run.py", line 313, in run
    process = run_async(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ffmpeg/_run.py", line 284, in run_async
    return subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infer-web.py", line 180, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "/Users/albert/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [Errno 2] No such file or directory: 'ffmpeg'

voice.wav->Traceback (most recent call last):
  File "/Users/albert/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ffmpeg/_run.py", line 313, in run
    process = run_async(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ffmpeg/_run.py", line 284, in run_async
    return subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infer-web.py", line 180, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "/Users/albert/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [Errno 2] No such file or directory: 'ffmpeg'
