### ISSUE TITLE
SystemError: initialization of _internal failed without raising an exception

### ISSUE THREAD

**Issue by micodev** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#752]
```
Traceback (most recent call last):
  File "infer-web.py", line 35, in <module>
    from infer_uvr5 import _audio_pre_, _audio_pre_new
  File "D:\v2v\infer_uvr5.py", line 8, in <module>
    import librosa
  File "D:\anaconda\envs\v2v\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "D:\anaconda\envs\v2v\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "D:\anaconda\envs\v2v\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "D:\anaconda\envs\v2v\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "D:\anaconda\envs\v2v\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "D:\anaconda\envs\v2v\lib\site-packages\librosa\util\utils.py", line 9, in <module>
    import numba
  File "D:\anaconda\envs\v2v\lib\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "D:\anaconda\envs\v2v\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "D:\anaconda\envs\v2v\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```

nvidia 3090
windows 10

**Comment by micodev** [comment]
fixed by using this:
https://github.com/openai/whisper/discussions/1103#discussioncomment-5371080
