### ISSUE TITLE
Can't train model due to GPU limit which is wrong

### ISSUE THREAD

**Issue by LordMilutin** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#754]
Hi, I have successfully ran this app in a Docker container, however, once I get to train model buttons, I am getting this error:

```
/usr/local/lib/python3.10/site-packages/torch/functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:862.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/train_nsf_sim_cache_sid_load_pretrain.py", line 223, in run
    train_and_evaluate(
  File "/app/train_nsf_sim_cache_sid_load_pretrain.py", line 436, in train_and_evaluate
    scaler.scale(loss_disc).backward()
  File "/usr/local/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

The strange thing is, that script is using only half of my GPU memory, there's 50% more available, but for some reason it breaks.

```
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      3718      C   /python3.10                               N/A      |
+---------------------------------------------------------------------------------------+
Fri Jul 14 23:43:45 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.06              Driver Version: 536.40       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050        On  | 00000000:01:00.0  On |                  N/A |
| 60%   45C    P8              16W / 130W |   2016MiB /  8192MiB |     36%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      3718      C   /python3.10                               N/A      |
+---------------------------------------------------------------------------------------+
Fri Jul 14 23:43:50 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.06              Driver Version: 536.40       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050        On  | 00000000:01:00.0  On |                  N/A |
| 60%   47C    P2              34W / 130W |   4002MiB /  8192MiB |     61%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      3718      C   /python3.10                               N/A      |
+---------------------------------------------------------------------------------------+
Fri Jul 14 23:43:55 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.06              Driver Version: 536.40       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050        On  | 00000000:01:00.0  On |                  N/A |
| 60%   45C    P5              18W / 130W |    692MiB /  8192MiB |     15%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

```

**Comment by Myst1ck** [comment]
If you are using wsl, it limits your GPU memory usage to 50% of your GPU's max. [Click here](https://www.aleksandrhovhannisyan.com/blog/limiting-memory-usage-in-wsl-2/) to see how to change it

**Comment by larangin** [comment]
Hi, I have same issue with Docker container but works fine without Docker. this is what I get with docker: 
`| INFO:mi-test:loaded pretrained assets/pretrained_v2/f0G40k.pth
rvc  | INFO:mi-test:<All keys matched successfully>
rvc  | INFO:mi-test:loaded pretrained assets/pretrained_v2/f0D40k.pth
rvc  | INFO:mi-test:<All keys matched successfully>
rvc  | Process Process-1:
rvc  | Traceback (most recent call last):
rvc  |   File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
rvc  |     self.run()
rvc  |   File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
rvc  |     self._target(*self._args, **self._kwargs)
rvc  |   File "/app/infer/modules/train/train.py", line 268, in run
rvc  |     train_and_evaluate(
rvc  |   File "/app/infer/modules/train/train.py", line 481, in train_and_evaluate
rvc  |     scaler.scale(loss_disc).backward()
rvc  |   File "/usr/local/lib/python3.9/dist-packages/torch/_tensor.py", line 522, in backward
rvc  |     torch.autograd.backward(
rvc  |   File "/usr/local/lib/python3.9/dist-packages/torch/autograd/__init__.py", line 266, in backward
rvc  |     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
rvc  | RuntimeError: CUDA error: out of memory
rvc  | CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
rvc  | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
rvc  | Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`
were you are able to train model using docker container? I dont think it is my graphic because I have RTX 4090 and works fine without docker. I would like to use it with docker, there must be some restriction on there.
