### ISSUE TITLE
Vocal separation 

### ISSUE THREAD

**Issue by kubis555** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#760]
I have a problem with this while trying to separate vocals 

Traceback (most recent call last):
  File "/home/kuba/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/infer-web.py", line 337, in uvr
    pre_fun = func(
  File "/home/kuba/Downloads/Retrieval-based-Voice-Conversion-WebUI-main/infer_uvr5.py", line 36, in __init__
    cpk = torch.load(model_path, map_location="cpu")
  File "/home/kuba/.local/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/kuba/.local/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by kubis555** [comment]
ok, i didn't download files from huggingface correctly
