### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by mardasancar** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#765]
I got this error while using CPU encoding:

Traceback (most recent call last):
  File "C:\Users\marda\Downloads\RVC-GUI-pkg-20220525-mp3fix\RVC-GUI-pkg\rvcgui.py", line 696, in <module>
    root.mainloop()
  File "C:\Users\marda\Downloads\RVC-GUI-pkg-20220525-mp3fix\RVC-GUI-pkg\runtime\lib\site-packages\customtkinter\windows\ctk_tk.py", line 163, in mainloop
    super().mainloop(*args, **kwargs)
  File "C:\Users\marda\Downloads\RVC-GUI-pkg-20220525-mp3fix\RVC-GUI-pkg\runtime\lib\site-packages\tkinter\__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)

Error!!! How would I solve this. Can you explain it understandablly.

**Comment by mardasancar** [comment]
And I also got this error while using GPU encoding:

Traceback (most recent call last):
  File "C:\Users\marda\Downloads\RVC-GUI-pkg-20220525-mp3fix\RVC-GUI-pkg\rvcgui.py", line 129, in vc_single
    audio_opt = vc.pipeline(
  File "C:\Users\marda\Downloads\RVC-GUI-pkg-20220525-mp3fix\RVC-GUI-pkg\vc_infer_pipeline.py", line 329, in pipeline
    pitch, pitchf = self.get_f0(audio_pad, p_len, f0_up_key, f0_method, crepe_hop_length, inp_f0)
  File "C:\Users\marda\Downloads\RVC-GUI-pkg-20220525-mp3fix\RVC-GUI-pkg\vc_infer_pipeline.py", line 141, in get_f0
    f0 = self.get_f0_crepe_computation(x, f0_min, f0_max, p_len, crepe_hop_length)
  File "C:\Users\marda\Downloads\RVC-GUI-pkg-20220525-mp3fix\RVC-GUI-pkg\vc_infer_pipeline.py", line 97, in get_f0_crepe_computation
    audio = torch.from_numpy(x).to(torch_device, copy=True)
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Can you please explain both error's causes and their solutions.

**Comment by acidrian07** [comment]
I have the same issue what does it mean?

**Comment by danablend** [comment]
@mardasancar Did you find a solution to this?

**Comment by prod-arkhamk** [comment]
@mardasancar @danablend @acidrian07  did you guys find a solution?

**Comment by danablend** [comment]
> @mardasancar @danablend @acidrian07 did you guys find a solution?

I can't recall specifically how I solved this, but I found a lot of help in the Discord [here](https://discord.gg/cCcrz4ry).

I believe I solved it by setting up the environment in a specific way using Docker. The Discord group is very helpful.
