### ISSUE TITLE
Windows issue Traceback (most recent call last):  import gradio as gr

### ISSUE THREAD

**Issue by tounstounsi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#768]
Hello i have this error when i launch go-web.bat

Traceback (most recent call last):
  File "C:\Users\Touns\Downloads\voicechanger\RVC-beta (1)\RVC-beta-v2-0618\infer-web.py", line 22, in <module>
    import gradio as gr
  File "C:\Users\Touns\Downloads\voicechanger\RVC-beta (1)\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\Touns\Downloads\voicechanger\RVC-beta (1)\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\components.py", line 34, in <module>
    from gradio import media_data, processing_utils, utils
  File "C:\Users\Touns\Downloads\voicechanger\RVC-beta (1)\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\processing_utils.py", line 22, in <module>
    from gradio import encryptor, utils
  File "C:\Users\Touns\Downloads\voicechanger\RVC-beta (1)\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\utils.py", line 46, in <module>
    from pydantic import BaseModel, Json, parse_obj_as
  File "pydantic\__init__.py", line 2, in init pydantic.__init__
  File "pydantic\dataclasses.py", line 52, in init pydantic.dataclasses
ImportError: cannot import name dataclass_transform

Can someone help me please?
Thanks

**Comment by Sayrix** [comment]
I have the same error

**Comment by RVC-Boss** [comment]
You can update the code to the latest main branch, where this version dependency issue has already been resolved.
