### ISSUE TITLE
Error when opening go-web.bat (AttributeError: module 'async_timeout' has no attribute 'Timeout')

### ISSUE THREAD

**Issue by LuhBlevins** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#781]
C:\Users\Owner\Downloads\RVC-beta-v2-0618>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Traceback (most recent call last):
  File "C:\Users\Owner\Downloads\RVC-beta-v2-0618\infer-web.py", line 22, in <module>
    import gradio as gr
  File "C:\Users\Owner\Downloads\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\Owner\Downloads\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\components.py", line 34, in <module>
    from gradio import media_data, processing_utils, utils
  File "C:\Users\Owner\Downloads\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\processing_utils.py", line 22, in <module>
    from gradio import encryptor, utils
  File "C:\Users\Owner\Downloads\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\utils.py", line 38, in <module>
    import aiohttp
  File "C:\Users\Owner\Downloads\RVC-beta-v2-0618\runtime\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\Owner\Downloads\RVC-beta-v2-0618\runtime\lib\site-packages\aiohttp\client.py", line 36, in <module>
    from . import hdrs, http, payload
  File "C:\Users\Owner\Downloads\RVC-beta-v2-0618\runtime\lib\site-packages\aiohttp\http.py", line 7, in <module>
    from .http_parser import (
  File "C:\Users\Owner\Downloads\RVC-beta-v2-0618\runtime\lib\site-packages\aiohttp\http_parser.py", line 29, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "C:\Users\Owner\Downloads\RVC-beta-v2-0618\runtime\lib\site-packages\aiohttp\helpers.py", line 731, in <module>
    def ceil_timeout(delay: Optional[float]) -> async_timeout.Timeout:
AttributeError: module 'async_timeout' has no attribute 'Timeout'

Don't know if I'm stupid or what but, please help

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this version dependency  issue has already been resolved.
