### ISSUE TITLE
i think they call this ffmpeg error or something like that

### ISSUE THREAD

**Issue by the3fe** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#790]
alright so i dont know a thing about coding, just looked at some tutorial and made a working auido, but when i tried it the second time, it wouldnt work and give me this error. i installed and uninstalled the entire rvc but the error is still here. please explain like you are explaining to a dummy,  i dont know a thing about coding lol (training works fine, the interface thing is the one with problems)

loading weights/TEST02.pth gin_channels: 256 self.spk_embed_dim: 109 Traceback (most recent call last): File "G:\RVC-beta-v2-
0618\my_utils.py", line 14, in load_audio ffmpeg.input(file, threads=0) File "G:\RVC-beta-v2-0618\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run raise Error('ffmpeg', out, err) ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "G:\RVC-beta-v2-0618\infer-web.py", line 178, in vc_single
audio = load_audio(input_audio_path, 16000)
File "G:\RVC-beta-v2-0618\my_utils.py", line 19, in load_audio
raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
File "G:\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
output = await app.blocks.process_api(
File "G:\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
data = self.postprocess_data(fn_index, result["prediction"], state)
File "G:\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
prediction_value = block.postprocess(prediction_value)
File "G:\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
processing_utils.audio_to_file(sample_rate, data, file.name)
File "G:\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
data = convert_to_16_bit_wav(data)
File "G:\RVC-beta-v2-0618\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

the error above isnt mine, its someones who had the same issue, i copied and pasted it here but its the same

**Comment by Lipooooo** [comment]
same issue
