### ISSUE TITLE
vc not defined and 'NoneType' object missing 'dtype' attribute

### ISSUE THREAD

**Issue by notkryptxc** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#793]
Traceback (most recent call last):
  File "RVC-beta0717\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "RVC-beta0717\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "RVC-beta0717\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "RVC-beta0717\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "RVC-beta0717\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "RVC-beta0717\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "RVC-beta0717\infer-web.py", line 203, in vc_single
    audio_opt = vc.pipeline(
NameError: name 'vc' is not defined

**Comment by alexledd** [comment]
Same here

**Comment by RVC-Boss** [comment]
The real problem is before this traceback

**Comment by VertofChest** [comment]
`if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'`
No fix for this issue? is it GPU relaxed?

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved.
