### ISSUE TITLE
m1 Mac can't pass python infer-web.py

### ISSUE THREAD

**Issue by bgomiss** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#804]
how can I fix this ?

python infer-web.py   
Traceback (most recent call last):
  File "/Users/asduskun/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 26, in <module>
    from fairseq import checkpoint_utils
  File "/Users/asduskun/Retrieval-based-Voice-Conversion-WebUI/rvcgui/lib/python3.10/site-packages/fairseq/__init__.py", line 40, in <module>
    import fairseq.scoring  # noqa
  File "/Users/asduskun/Retrieval-based-Voice-Conversion-WebUI/rvcgui/lib/python3.10/site-packages/fairseq/scoring/__init__.py", line 55, in <module>
    importlib.import_module("fairseq.scoring." + module)
  File "/Users/asduskun/miniconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/asduskun/Retrieval-based-Voice-Conversion-WebUI/rvcgui/lib/python3.10/site-packages/fairseq/scoring/bleu.py", line 14, in <module>
    from fairseq.scoring.tokenizer import EvaluationTokenizer
  File "/Users/asduskun/Retrieval-based-Voice-Conversion-WebUI/rvcgui/lib/python3.10/site-packages/fairseq/scoring/tokenizer.py", line 8, in <module>
    import sacrebleu as sb
  File "/Users/asduskun/Retrieval-based-Voice-Conversion-WebUI/rvcgui/lib/python3.10/site-packages/sacrebleu/__init__.py", line 21, in <module>
    from .utils import smart_open, SACREBLEU_DIR, download_test_set  # noqa: F401
  File "/Users/asduskun/Retrieval-based-Voice-Conversion-WebUI/rvcgui/lib/python3.10/site-packages/sacrebleu/utils.py", line 597, in <module>
    from .dataset import DATASETS, SUBSETS, DOMAINS, COUNTRIES
  File "/Users/asduskun/Retrieval-based-Voice-Conversion-WebUI/rvcgui/lib/python3.10/site-packages/sacrebleu/dataset/__init__.py", line 73, in <module>
    from .wmt_xml import WMTXMLDataset
  File "/Users/asduskun/Retrieval-based-Voice-Conversion-WebUI/rvcgui/lib/python3.10/site-packages/sacrebleu/dataset/wmt_xml.py", line 3, in <module>
    import lxml.etree as ET
ImportError: dlopen(/Users/asduskun/Retrieval-based-Voice-Conversion-WebUI/rvcgui/lib/python3.10/site-packages/lxml/etree.cpython-310-darwin.so, 0x0002): tried: '/Users/asduskun/Retrieval-based-Voice-Conversion-WebUI/rvcgui/lib/python3.10/site-packages/lxml/etree.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/asduskun/Retrieval-based-Voice-Conversion-WebUI/rvcgui/lib/python3.10/site-packages/lxml/etree.cpython-310-darwin.so' (no such file), '/Users/asduskun/Retrieval-based-Voice-Conversion-WebUI/rvcgui/lib/python3.10/site-packages/lxml/etree.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by cn-coderl** [comment]
The M2 Mac has the same issue.

**Comment by bgomiss** [comment]
So we can install this on Mac or not? Why there is not enough installation guide for us?

**Comment by cn-coderl** [comment]
@bgomiss 
I didn't have any issues with the Python 3.8 version. You can try.

**Comment by Naozumi520** [comment]
Uninstall all packages including cpython, then run "run.sh" which will install all packages you need and run automatically.

**Comment by bgomiss** [comment]
> Uninstall all packages including cpython, then run "run.sh" which will install all packages you need and run automatically.

yes it worked now. how can I reopen the program after I close? again run.sh ? by the way I get this error on MacBook Air m1 "Unfortunately, there is no compatible GPU available to support your training."

**Comment by Naozumi520** [comment]
> how can I reopen the program after I close?
Yep run.sh is the best way for now.

> "Unfortunately, there is no compatible GPU available to support your training."
You just need to ignore this. It eventually selects the GPU automatically. No need to input gpu index.

**Comment by dhruv1710** [comment]
> Uninstall all packages including cpython, then run "run.sh" which will install all packages you need and run automatically.

How do I uninstall all packages installed. Even I'm on Mac M1 and got this error
