### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '0_gt_wavs'

### ISSUE THREAD

**Issue by swut047** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#824]
Everytime I push model training button, I came out to this problem.
How can I solve this problem?

Traceback (most recent call last):
  File "/home/naoki/.local/share/virtualenvs/min_pipenv-XR_P2WaS/lib/python3.8/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/home/naoki/.local/share/virtualenvs/min_pipenv-XR_P2WaS/lib/python3.8/site-packages/gradio/blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "/home/naoki/.local/share/virtualenvs/min_pipenv-XR_P2WaS/lib/python3.8/site-packages/gradio/blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/naoki/.local/share/virtualenvs/min_pipenv-XR_P2WaS/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/naoki/.local/share/virtualenvs/min_pipenv-XR_P2WaS/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/naoki/.local/share/virtualenvs/min_pipenv-XR_P2WaS/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "infer-web.py", line 792, in click_train
    set([name.split(".")[0] for name in os.listdir(gt_wavs_dir)])
FileNotFoundError: [Errno 2] No such file or directory: '/home/naoki/Downloads/Retrieval-based-Voice-Conversion-WebUI/logs/test/0_gt_wavs'

**Comment by ms903x1** [comment]
Perhaps you should click on One click training

**Comment by RVC-Boss** [comment]
Does space exists on 
(1)Your rvc root folder path
(2)Your logs/exp_name folder path

**Comment by RVC-Boss** [comment]
I have supported space now.
You can update RVC from github and try again, or modify the path without space.

**Comment by ilyHapple** [comment]
@RVC-Boss Pls update colab
