### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by WhiteCodeC** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#853]
loading weights/cellbit.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
2023-07-24 19:34:12 | ERROR | asyncio | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\WhiteC\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\WhiteC\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by RVC-Boss** [comment]
I think you successfully get the audio after voice conversion.

**Comment by Mian06** [comment]
> I think you successfully get the audio after voice conversion.

Same issue, but I successfully get the audio. But why this error is showing? 

2024-05-29 11:58:48 | INFO | infer.modules.vc.modules | Get sid: keruanV1.pth
2024-05-29 11:58:48 | INFO | infer.modules.vc.modules | Loading: assets/weights/keruanV1.pth
2024-05-29 11:58:50 | INFO | infer.modules.vc.modules | Select index: logs\keruanV1.index
2024-05-29 12:00:35 | INFO | infer.modules.vc.pipeline | Loading rmvpe model,assets/rmvpe/rmvpe.pt
2024-05-29 12:01:01 | ERROR | root | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
