### ISSUE TITLE
Output error for voice training?

### ISSUE THREAD

**Issue by freezing-glitter** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#854]
Step 1: Processing data
C:\Python310\python.exe trainset_preprocess_pipeline_print.py C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\opt\my vocals 40000 6 C:\TCHT\Retrieval-based-Voice-Conversion-WebUI/logs/SEn test False
step2a:正在提取音高
C:\Python310\python.exe extract_f0_print.py C:\TCHT\Retrieval-based-Voice-Conversion-WebUI/logs/SEn test 6 harvest
Step 2b: Extracting features
C:\Python310\python.exe extract_feature_print.py cuda:0 1 0 0 C:\TCHT\Retrieval-based-Voice-Conversion-WebUI/logs/SEn test v2
Step 3a: Model training started

What do I need to fix this?^^

**Comment by RVC-Boss** [comment]
Can you copy more infomation?

**Comment by freezing-glitter** [comment]
Yes! I will send it in the morning!

**Comment by freezing-glitter** [comment]
Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\trainset_preprocess_pipeline_print.py", line 8, in <module>
    sr = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'HORROR\\Stories\\7-24-23'

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\extract_f0_print.py", line 13, in <module>
    f = open("%s/extract_f0_feature.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI/logs/my/extract_f0_feature.log'

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\extract_feature_print.py", line 29, in <module>
    f = open("%s/extract_f0_feature.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TCHT\\Retrieval-based-Voice-Conversion-WebUI/logs/my/extract_f0_feature.log'

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Python310\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Python310\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future

**Comment by freezing-glitter** [comment]
Traceback (most recent call last):
File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\trainset_preprocess_pipeline_print.py", line 8, in
sr = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: '(SENSITIVE PC STUFF)'

Traceback (most recent call last):
File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\extract_f0_print.py", line 13, in
f = open("%s/extract_f0_feature.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\TCHT\Retrieval-based-Voice-Conversion-WebUI/logs/my/extract_f0_feature.log'

Traceback (most recent call last):
File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\extract_feature_print.py", line 29, in
f = open("%s/extract_f0_feature.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\TCHT\Retrieval-based-Voice-Conversion-WebUI/logs/my/extract_f0_feature.log'

Traceback (most recent call last):
File "C:\Python310\lib\site-packages\gradio\routes.py", line 321, in run_predict
output = await app.blocks.process_api(
File "C:\Python310\lib\site-packages\gradio\blocks.py", line 1006, in process_api
result = await self.call_function(fn_index, inputs, iterator, request)
File "C:\Python310\lib\site-packages\gradio\blocks.py", line 859, in call_function
prediction = await anyio.to_thread.run_sync(
File "C:\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "C:\Python310\lib\site-packages\anyio_backends_asyncio.py", line 877, in run_sync_in_worker_thread
return await future

**Comment by RVC-Boss** [comment]
This issue is caused by there is space in your training set folder path.
I have supported space now.
You can update RVC from github and try again, or modify the path without space.

**Comment by freezing-glitter** [comment]
where would the space be? in the file path for the training folder?

**Comment by sethtallen** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\TCHT\Retrieval-based-Voice-Conversion-WebUI/logs/my/extract_f0_feature.log'`

Your slashes should be backslashes if you're using a windows machine. Note after Retrieval-based-Voice-Conversion-WebUI you're using forward slashes.

**Comment by freezing-glitter** [comment]
would I edit in the terminal/powershell? I didnt edit any code when installing

**Comment by ms903x1** [comment]
C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\opt\my vocals
C:\TCHT\Retrieval-based-Voice-Conversion-WebUI/logs/SEn test v2
The above paths contain spaces. Please ensure that all paths do not contain spaces and spaces other than '_' Other characters outside of.

**Comment by RVC-Boss** [comment]
Now RVC has supported paths containing space. You can try updating it from github.
