### ISSUE TITLE
ffmpg error 

### ISSUE THREAD

**Issue by Zxpwn05** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#870]
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "/usr/local/lib/python3.10/dist-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 139, in vc_single
    audio = load_audio(input_audio, 16000)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute  'tobytes'

**Comment by RVC-Boss** [comment]
The real problem is before this traceback, you may need to copy more traceback infomation before it.

**Comment by trashhead101** [comment]
As I embarked on my programming journey, I found myself facing a daunting challenge - an elusive error that seemed to thwart my progress at every turn. In my pursuit of using RVC I got the same error. pls help.

like really, pls help

**Comment by St33lMouse** [comment]
Yep, this one defeats me.

**Comment by PatrickAi01** [comment]
this is my error

loading weights/billie-eilish.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
Traceback (most recent call last):
  File "/Users/patrickdail/Downloads/RVC0813Nvidia/lib/audio.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "/opt/homebrew/lib/python3.8/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infer-web.py", line 188, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "/Users/patrickdail/Downloads/RVC0813Nvidia/lib/audio.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

is there any resolution on this issue yet?
thank you for the help

**Comment by fercook** [comment]
This is because the lbgl1 library is missing. In my Ubuntu system this is fixed by issuing

`sudo apt install libgl1`
