### ISSUE TITLE
cannot import name 'notf' from 'tensorboard.compat'

### ISSUE THREAD

**Issue by joker-404bug** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#881]
runtime\python.exe gui_v1.py
Traceback (most recent call last):
  File "E:\RVC-beta0717\runtime\lib\site-packages\tensorboard\compat\__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (E:\RVC-beta0717\runtime\lib\site-packages\tensorboard\compat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\RVC-beta0717\gui_v1.py", line 50, in <module>
    from rvc_for_realtime import RVC
  File "E:\RVC-beta0717\rvc_for_realtime.py", line 2, in <module>
    from fairseq import checkpoint_utils
  File "E:\RVC-beta0717\runtime\lib\site-packages\fairseq\__init__.py", line 21, in <module>
    from fairseq.logging import meters, metrics, progress_bar  # noqa
  File "E:\RVC-beta0717\runtime\lib\site-packages\fairseq\logging\progress_bar.py", line 407, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "E:\RVC-beta0717\runtime\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "E:\RVC-beta0717\runtime\lib\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>
    from ._embedding import (
  File "E:\RVC-beta0717\runtime\lib\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
  File "E:\RVC-beta0717\runtime\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "E:\RVC-beta0717\runtime\lib\site-packages\tensorboard\lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "E:\RVC-beta0717\runtime\lib\site-packages\tensorboard\lazy.py", line 50, in load_once
    module = load_fn()
  File "E:\RVC-beta0717\runtime\lib\site-packages\tensorboard\compat\__init__.py", line 45, in tf
    import tensorflow
  File "C:\Users\lin\AppData\Roaming\Python\Python39\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\lin\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\lin\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Users\lin\AppData\Roaming\Python\Python39\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\lin\AppData\Roaming\Python\Python39\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\Users\lin\AppData\Roaming\Python\Python39\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\lin\AppData\Roaming\Python\Python39\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\Users\lin\AppData\Roaming\Python\Python39\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "E:\RVC-beta0717\runtime\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**These are the issues I encountered while running go-realtime-gui.bat and go-web.bat. Has anyone else encountered these problems or knows how to handle them?**

**Comment by showkeyjar** [comment]
+1

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved.
