### ISSUE TITLE
Output error (need help)

### ISSUE THREAD

**Issue by Tobe2d** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#888]
I trained a model and I keep getting this error:

```
2023-07-27 21:21:23.826790
tts_text:
Dies ist eine Demo zur Umwandlung von Deutsch in Sprache.
tts_voice: de-DE-AmalaNeural-Female
Model name: e_99
F0: rmvpe, Key: 0.0, Index: 1, Protect: 0.33
Loading weights\e_99\f0D40k.pth
Traceback (most recent call last):
  File "E:\rvc-tts-webui\app.py", line 153, in tts
    tgt_sr, net_g, vc, version, index_file, if_f0 = model_data(model_name)
  File "E:\rvc-tts-webui\app.py", line 59, in model_data
    tgt_sr = cpt["config"][-1]
KeyError: 'config'
```
here is the model screenshot:
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/4099839/63bcc8f6-f496-4d64-935f-ca039bd6a824)

Can any one point to me what am I missing?

**Comment by ftk7810** [comment]
What was the solution?

**Comment by Tobe2d** [comment]
I was copying the wrong file ;-)
copy the one without nuber  .pth and it will work
