### ISSUE TITLE
Failed to load audio

### ISSUE THREAD

**Issue by collman87** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#893]
was trying to train, got this error. Got any idea ?

start preprocess
['trainset_preprocess_pipeline_print.py', 'C:\Users\mypc\IACHANT\RVC\training', '48000', '11', 'C:\Users\mypc\iachant\rvc/logs/poil', 'False']
C:\Users\mypc\IACHANT\RVC\training/faischier.wav->Traceback (most recent call last):
  File "C:\Users\mypc\iachant\rvc\lib\audio.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python38\lib\site-packages\ffmpeg_run.py", line 313, in run
    process = run_async(
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python38\lib\site-packages\ffmpeg_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 858, in init
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mypc\iachant\rvc\trainset_preprocess_pipeline_print.py", line 79, in pipeline
    audio = load_audio(path, self.sr)
  File "C:\Users\mypc\iachant\rvc\lib\audio.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 2] Le fichier spécifié est introuvable

end preprocess

**Comment by sethtallen** [comment]
Ran into this once with a Windows installation. Make sure ffmpeg is installed.

you can put the ffmpeg.exe within your installation folder from here, download the windows x64 and look in the bin folder
https://github.com/BtbN/FFmpeg-Builds/releases

**Comment by QuickLike** [comment]
> Ran into this once with a Windows installation. Make sure ffmpeg is installed.
> 
> you can put the ffmpeg.exe within your installation folder from here, download the windows x64 and look in the bin folder https://github.com/BtbN/FFmpeg-Builds/releases

Can you please explain where exactly should I put this executable file? Which folder?

**Comment by yangzi0210** [comment]
还有可能存在的一个问题是 fffmpeg & ffprobe 应该放在根目录而不是tools 下
