### ISSUE TITLE
no .index file generated after fusion of 2 pretrained v2 models (.pth cca 56MB size)

### ISSUE THREAD

**Issue by anty94** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#899]
Hi, I am having trouble infering the created model after using the _FUSION checktpoints tab_.
I get an error (see traceback lower) after fusing 2 v2 models, my humble guess would be that I am missing the .index file for the new created / fused model... and when using the index from one of the pretrained models, it obviously fails. 
Is it posible to use the fused model (.pth from weights, cca 56MB size) for inference with no corresponding .index file? Should I somehow fuse the .index files from 2 pretrained models?
Also 1 line in traceback ..... size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 768]) from checkpoint, the shape in current model is torch.Size([192, 256])..... seems to me that there is some troble with v2 models perhaps?
**Any help or advice appreciated!**

gin_channels: 256 self.spk_embed_dim: 109
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 345, in get_vc
    print(net_g.load_state_dict(cpt["weight"], strict=False))  # 不加这一行清不干净, 真奇葩
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
**RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid:
	size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 768]) from checkpoint, the shape in current model is torch.Size([192, 256]).**
2023-07-29 20:57:35 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 500 Internal Server Error"
2023-07-29 20:57:35 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
2023-07-29 20:58:36 | INFO | fairseq.tasks.hubert_pretraining | current directory is /content/Retrieval-based-Voice-Conversion-WebUI
2023-07-29 20:58:36 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-07-29 20:58:36 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 158, in vc_single
    audio_opt = vc.pipeline(
**NameError: name 'vc' is not defined**

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
**AttributeError: 'NoneType' object has no attribute 'dtype'**
2023-07-29 20:58:40 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 500 Internal Server Error"
2023-07-29 20:58:41 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"

**Comment by ms903x1** [comment]
This error is because you attempted to merge the v1 model with the v2 model. The program does not support this operation because the dimensions do not match. When fusing models, it is necessary to ensure that the version, sampling rate, and consistency of the model to be fused are maintained.

**Comment by anty94** [comment]
thanks but I think that all of the models that I have trained are the same version, sampling rate and consistency... 
and the error does not occur when fusing the model I might add... the error comes up when trying to infer the fused model.
Cant it be something different then?

**Comment by ms903x1** [comment]
You can view the model version and sampling rate through the View Model Information option under the CKPT Processing tab

**Comment by anty94** [comment]
**so I did a couple of experiments, trying out what you said, here are the results:**
**model_to_fuse_1**
模型信息:100epoch
采样率:40k
模型是否输入音高引导:1
**model_to_fuse_2**
模型信息:200epoch
采样率:40k
模型是否输入音高引导:1
**so the only thing that is different is number of epochs, which should not be a problem right? Next the fusion of the 2:**
模型信息:
采样率:40k
模型是否输入音高引导:0
**why the input pitch guided changed to 0 .... I dont know (I chose the YES), but here comes the interesting thing, after combining the model with itself, the result is still unsuble (I will get to why later):**
模型信息:
采样率:40k
模型是否输入音高引导:0

**And the most interesting thing is that after CHOOSING the model for inference of the 2 fused models, the same error occurs for both options, traceback:**
loading weights/art4voice_combo_5.pth
gin_channels: 256 self.spk_embed_dim: 109
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 345, in get_vc
    print(net_g.load_state_dict(cpt["weight"], strict=False))  # 不加这一行清不干净, 真奇葩
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid_nono:
	size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 768]) from checkpoint, the shape in current model is torch.Size([192, 256]).
2023-07-31 22:39:59 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 500 Internal Server Error"
2023-07-31 22:39:59 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"

**Funnily enough the same error with loading the weights for inference occurs right after CHOOSING the model from dropdown (not yet hitting the CONVERT button). The same situation occurs while trying to load ANY trained model (not only the fused ones). 
Is it because I am missing some file? Or am I trying to load the v2 models into v1? Or could it be that the Index is unloadable (after setting the slider to 0)?
Maybe it would help to know how to load the model checkpoint with torch.Size([192, 768]).**

**Comment by ms903x1** [comment]
merge-ckpt  not require an index file.
