### ISSUE TITLE
KeyError: 'config' when loading D or G models

### ISSUE THREAD

**Issue by Connum** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#921]
Whenever I try to load a _D_ or _G_ model, this results in an error in the console:
```
loading weights/sinatraRVC_G_51600.pth
Traceback (most recent call last):
  File "E:\AI\RVC-beta0717\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "E:\AI\RVC-beta0717\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "E:\AI\RVC-beta0717\runtime\lib\site-packages\gradio\blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\RVC-beta0717\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\RVC-beta0717\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\AI\RVC-beta0717\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AI\RVC-beta0717\infer-web.py", line 439, in get_vc
    tgt_sr = cpt["config"][-1]
KeyError: 'config'
```
The normal models work fine. I also couldn't find any information on those D and G models, what they are and what's the difference between them and between the normal models.

**Comment by ms903x1** [comment]
Regardless of whether you want to use the web UI or real-time GUI for inference, you should choose the small models located in the "weights" folder within the root directory of the RVC project. The "d" and "g" models are not intended for inference purposes.

**Comment by hexahigh** [comment]
> The webui's checkpoint processing tab can export the G model as a small model.

How do i do this?
