### ISSUE TITLE
Hard to start using RVC

### ISSUE THREAD

**Issue by Asyjjan** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#925]
Hi, 

I watched doc and some tutorials but I struggle using RVC, for now i have cloned the project and started the WebUI interface, I got a voice model which contains an index file and an pth file, I put the index file into /logs/rick/file.index and the pth file into weights/, when reloading data on the interface in Model inference I can now see the voice and the index file is detected but when I try to put my path to my audio file and push convert button, I always got an error, I tried to create a folder inside the project folder, on my desktop, it doesn't find the file and I got this issue : 

```
Traceback (most recent call last):
  File "/Users/Sylvio/Desktop/Retrieval-based-Voice-Conversion-WebUI/lib/audio.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ffmpeg/_run.py", line 313, in run
    process = run_async(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ffmpeg/_run.py", line 284, in run_async
    return subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infer-web.py", line 180, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "/Users/Sylvio/Desktop/Retrieval-based-Voice-Conversion-WebUI/lib/audio.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [Errno 2] No such file or directory: 'ffmpeg'

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```

anyone can help me understand and make it work ? I'm on a Mac

**Comment by ms903x1** [comment]
Your PATH is missing the ffmpeg component. You can find detailed installation instructions by searching on a search engine.

**Comment by Asyjjan** [comment]
There is not a lot of tutorials for MacOs

**Comment by ms903x1** [comment]
Mac users can install dependencies via run.sh:

sh ./run.sh

**Comment by Asyjjan** [comment]
I manage to install ffmpeg but know I'm missing a file

OSError: Model file not found: hubert_base.pt

I'm searching it in the git maybe I don't have it

**Comment by Asyjjan** [comment]
I've installed ffmpeg but know I got this issue

Traceback (most recent call last):
  File "infer-web.py", line 186, in vc_single
    load_hubert()
  File "infer-web.py", line 127, in load_hubert
    models, _, _ = checkpoint_utils.load_model_ensemble_and_task(
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "/opt/homebrew/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/homebrew/lib/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.8/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/opt/homebrew/lib/python3.8/site-packages/gradio/blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/opt/homebrew/lib/python3.8/site-packages/gradio/blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/opt/homebrew/lib/python3.8/site-packages/gradio/components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "/opt/homebrew/lib/python3.8/site-packages/gradio/processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "/opt/homebrew/lib/python3.8/site-packages/gradio/processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by Anonym0us33** [comment]
> Your PATH is missing the ffmpeg component. You can find detailed installation instructions by searching on a search engine.

which tutorial are you referring to?
 Running on wsl:
```
Retrieval-based-Voice-Conversion-WebUI$ pip list | grep "ffmpeg"
ffmpeg-python             0.2.0
```

**Comment by sukualam** [comment]
just download the complete package https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC-beta.7z and extract , and run on your mac, tested on me (macos ventura 13.4 with amd gpu)

**Comment by Anonym0us33** [comment]
What about windows and WSL?

**Comment by ReneBrandt** [comment]
I am having the same issue and error message as reported here. Running on fresh Ubuntu 20.04 through a HyperV VM.

**Comment by Anonym0us33** [comment]
It seems to be a folder conflict. I figured it out by scrutinizing the errors and working through about 3 layers until i realized among other things

1. the .pth files and folders from HF need to be in the root RVC folder. <--- not documented
2. a model must be paired with a index file. the tutorial suggests you can embedd the indel in the model, but this might be a mistranslation from chinese.
3. you can't use so-VITS models by default.
4. Some other path settings must be perfect like no spaces in the folder name
5. etc

**Comment by Blenderiste09** [comment]
> Hi,
> 
> I watched doc and some tutorials but I struggle using RVC, for now i have cloned the project and started the WebUI interface, I got a voice model which contains an index file and an pth file, I put the index file into /logs/rick/file.index and the pth file into weights/, when reloading data on the interface in Model inference I can now see the voice and the index file is detected but when I try to put my path to my audio file and push convert button, I always got an error, I tried to create a folder inside the project folder, on my desktop, it doesn't find the file and I got this issue :
> 
> ```
> Traceback (most recent call last):
>   File "/Users/Sylvio/Desktop/Retrieval-based-Voice-Conversion-WebUI/lib/audio.py", line 14, in load_audio
>     ffmpeg.input(file, threads=0)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ffmpeg/_run.py", line 313, in run
>     process = run_async(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ffmpeg/_run.py", line 284, in run_async
>     return subprocess.Popen(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "infer-web.py", line 180, in vc_single
>     audio = load_audio(input_audio_path, 16000)
>   File "/Users/Sylvio/Desktop/Retrieval-based-Voice-Conversion-WebUI/lib/audio.py", line 19, in load_audio
>     raise RuntimeError(f"Failed to load audio: {e}")
> RuntimeError: Failed to load audio: [Errno 2] No such file or directory: 'ffmpeg'
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/routes.py", line 321, in run_predict
>     output = await app.blocks.process_api(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/blocks.py", line 1007, in process_api
>     data = self.postprocess_data(fn_index, result["prediction"], state)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/blocks.py", line 953, in postprocess_data
>     prediction_value = block.postprocess(prediction_value)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/components.py", line 2076, in postprocess
>     processing_utils.audio_to_file(sample_rate, data, file.name)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/processing_utils.py", line 206, in audio_to_file
>     data = convert_to_16_bit_wav(data)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gradio/processing_utils.py", line 219, in convert_to_16_bit_wav
>     if data.dtype in [np.float64, np.float32, np.float16]:
> AttributeError: 'NoneType' object has no attribute 'dtype'
> ```
> 
> anyone can help me understand and make it work ? I'm on a Mac

Hi,
I had the same issue on Linux, so maybe it's the same on Mac.
Here's what I did :
sudo apt install ffmpeg
pip install ffmpeg-python
pip uninstall ffmpeg

The pip version of ffmpeg wasn't the good one.

Hope it helped you !

**Comment by tomasris** [comment]
> I almost got everything installed, but got stuck at this part: ImportError: cannot import name 'FFmpeg' from 'ffmpy' (/usr/local/lib/python3.8/site-packages/ffmpy/**init**.py) any help please?

pip install ffmpy==0.6.1
