### ISSUE TITLE
RuntimeError: CUDA error: out of memory after crash

### ISSUE THREAD

**Issue by Arashi0987** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#945]
I was working to train a new voice model, but something caused my system to completely crash at the 149th epoch, and ever since, when I start it up, I can't train any models because I get a "RuntimeError: CUDA error: out of memory" at the start when I try.

Here is the configuration that was working earlier today:
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/33102208/8eb95465-a63b-40ea-bbb8-3ca974a462a9)

I've tried setting my batch count to 1 and I was playing around with toggling pitch guidance, but I always get the same error. I've also updated my Nvidia driver, and restarted my computer:
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/33102208/91f53d98-5e5d-455f-945f-2cff6bbb943b)

Also here's the full error that I see:
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/arashi/git/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 228, in run
    train_and_evaluate(
  File "/home/arashi/git/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 441, in train_and_evaluate
    scaler.scale(loss_disc).backward()
  File "/home/arashi/.local/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/arashi/.local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Has anyone dealt with this issue before that has a solution? Considering that I've tried a batch size of 1 and still got the memory error, I think that my problem is something other than actually not having enough memory.

Thanks

**Comment by ms903x1** [comment]
The checkpoint saved right before the crash may be corrupted. It is recommended to try resuming training from the checkpoint before the last saved one, and consider reducing the batch size appropriately.

**Comment by smfreeze** [comment]
FAQ's:
Q8:Cuda error/Cuda out of memory.
There is a small chance that there is a problem with the CUDA configuration or the device is not supported; more likely, there is not enough memory (out of memory).

For training, reduce the batch size (if reducing to 1 is still not enough, you may need to change the graphics card); for inference, adjust the x_pad, x_query, x_center, and x_max settings in the [config.py](http://config.py/) file as needed. 4G or lower memory cards (e.g. 1060(3G) and various 2G cards) can be abandoned, while 4G memory cards still have a chance.

**Comment by KyleCe** [comment]
I fix it by reducing the train audio file or change to a better GPU computer

**Comment by 1430373671** [comment]
> 常见问题解答： Q8：库达错误/库达内存不足。 CUDA 配置出现问题或设备不受支持的可能性很小;更有可能的是，内存不足（内存不足）。
> 
> 对于训练，减少批量大小（如果减少到 1 仍然不够，可能需要更换显卡）;对于推理，请根据需要调整 [config.py](http://config.py/) 文件中的x_pad、x_query、x_center和x_max设置。4G或更低的存储卡（例如1060（3G）和各种2G卡）可以放弃，而4G存储卡仍然有机会。

config.pyq请问这个文件在哪?
