### ISSUE TITLE
Error in 2nd tab when loading song from C drive

### ISSUE THREAD

**Issue by gnjnshh** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#968]
Billie Eilish Male Cover - What Was I Made For_c103d7q3.mp3.reformatted.wav->Traceback (most recent call last):
  File "D:\RVC-beta\RVC-beta0717\runtime\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "D:\RVC-beta\RVC-beta0717\runtime\lib\site-packages\soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "D:\RVC-beta\RVC-beta0717\runtime\lib\site-packages\soundfile.py", line 1213, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'D:\\RVC-beta\\RVC-beta0717\\TEMP/Billie Eilish Male Cover - What Was I Made For_c103d7q3.mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\RVC-beta\RVC-beta0717\infer-web.py", line 374, in uvr
    pre_fun._path_audio_(
  File "D:\RVC-beta\RVC-beta0717\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "D:\RVC-beta\RVC-beta0717\runtime\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "D:\RVC-beta\RVC-beta0717\runtime\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "D:\RVC-beta\RVC-beta0717\runtime\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "D:\RVC-beta\RVC-beta0717\runtime\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "D:\RVC-beta\RVC-beta0717\runtime\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\RVC-beta\\RVC-beta0717\\TEMP/Billie Eilish Male Cover - What Was I Made For_c103d7q3.mp3.reformatted.wav'

C:\Users\gnjns\AppData\Local\Temp\Billie: No such file or directory
clean_empty_cache

Got above error

**Comment by RVC-Boss** [comment]
Would you mind upload this audio so that I can help you check the issue?

**Comment by gnjnshh** [comment]
https://rapidgator.net/file/b3fabd8407a99d883bc82494122b1ee9

Same error occurs with different audio files as well, but works sometimes! not sure what the issue is, does it require specific file type? thanks

**Comment by ed-bonnet** [comment]
I have the same issue on windows 11. Here is a workaround that worked for me:
- copy the file into TEMP 
- add ".reformatted.wav". 
Then the file has been processed successfully.

**Comment by KittoHub** [comment]
@gnjnshh 

I had the same issue error I have been getting. I found the reason why its not working.

You have to make sure the input file name and input folder name does not have space. I put underscore between the space of the input mp3 file and folder and voila sucess.

Example:
Current file name: Billie Eilish Male Cover - What Was I Made For.mp3
Change file name to: Billie_Eilish_Male_Cover_What_Was_I_Made_For.mp3 (put a underscore or remove spaces)

Do the same with the main input folder if you have space, you have to just remove it or add underscore then it works. Hope this helps.

**Comment by Frioo** [comment]
Getting the same error. Seems like the path is not being constructed properly on Windows?  
D:\RVC-beta\RVC-beta0717\TEMP/Billie Eilish Male Cover - What Was I Made For_c103d7q3.mp3.reformatted.wav':
After TEMP it uses a forward slash while the rest is backslashed. Experiencing the same output, with double backslashes and one forward slash at the end.
