### ISSUE TITLE
cannot open go-web.bat

### ISSUE THREAD

**Issue by trung6755** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#969]
I tried to open go-web.bat but an error occured.
it said:
C:\RVC-beta\RVC-beta0717>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Traceback (most recent call last):
  File "C:\RVC-beta\RVC-beta0717\infer-web.py", line 38, in <module>
    from vc_infer_pipeline import VC
  File "C:\RVC-beta\RVC-beta0717\vc_infer_pipeline.py", line 5, in <module>
    import pyworld, os, traceback, faiss, librosa, torchcrepe
  File "C:\RVC-beta\RVC-beta0717\runtime\lib\site-packages\pyworld__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld\pyworld.pyx", line 1, in init pyworld.pyworld
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

anyone know how to fix this?

**Comment by RVC-Boss** [comment]
Maybe you should make your built-in python environment can't find the python in your system.
A naive way is removing your system python.

**Comment by trung6755** [comment]
> Maybe you should make your built-in python environment can't find the python in your system. A naive way is removing your system python.

how can I make built-in python to not find my system python?

**Comment by gavytron** [comment]
Similar error here with Portable release RVC0813Nvidia.7z
Windows 10, NVIDIA 3080
running  go-web.bat   
"ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed."

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved. Pyworld is not imported now.
