### ISSUE TITLE
RuntimeError: mat1 and mat2 must have the same dtype

### ISSUE THREAD

**Issue by MQATAR** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#994]
warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Process Process-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.8/3.8.17_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.8/3.8.17_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/s-alkhaleej2/Desktop/RVC/train_nsf_sim_cache_sid_load_pretrain.py", line 223, in run
    train_and_evaluate(
  File "/Users/s-alkhaleej2/Desktop/RVC/train_nsf_sim_cache_sid_load_pretrain.py", line 392, in train_and_evaluate
    ) = net_g(phone, phone_lengths, pitch, pitchf, spec, spec_lengths, sid)
  File "/opt/homebrew/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/opt/homebrew/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1113, in _run_ddp_forward
    return module_to_run(*inputs, **kwargs)
  File "/opt/homebrew/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/s-alkhaleej2/Desktop/RVC/lib/infer_pack/models.py", line 747, in forward
    o = self.dec(z_slice, pitchf, g=g)
  File "/opt/homebrew/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/s-alkhaleej2/Desktop/RVC/lib/infer_pack/models.py", line 495, in forward
    har_source, noi_source, uv = self.m_source(f0, self.upp)
  File "/opt/homebrew/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/s-alkhaleej2/Desktop/RVC/lib/infer_pack/models.py", line 418, in forward
    sine_merge = self.l_tanh(self.l_linear(sine_wavs))
  File "/opt/homebrew/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype

**Comment by MQATAR** [comment]
i use RVC in macOS M1 ultra please how I can fix this issue ?

**Comment by RVC-Boss** [comment]
> i use RVC in macOS M1 ultra please how I can fix this issue ?

@MQATAR 
File "/Users/s-alkhaleej2/Desktop/RVC/lib/infer_pack/models.py", line 418, in forward
sine_merge = self.l_tanh(self.l_linear(sine_wavs))

try modifying this line to 
sine_merge = self.l_tanh(self.l_linear(sine_wavs.to(x)))

**Comment by MQATAR** [comment]
@RVC-Boss thanks it work
